DROP TABLE AMD_OWNER.AMD_REPAIR_COST_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.AMD_REPAIR_COST_DETAIL
(
  AOD                DATE,
  FISCAL_YEAR        NUMBER,
  CONTRACT_TYPE      VARCHAR2(4 BYTE),
  CAWP               VARCHAR2(35 BYTE),
  ACTIVITY_ID        VARCHAR2(10 BYTE),
  RELEASE_JOB_ORDER  VARCHAR2(40 BYTE),
  PURCHASE_REQUEST   VARCHAR2(20 BYTE),
  SOURCE_SYSTEM      VARCHAR2(10 BYTE),
  PC_RELEASE_DT      DATE,
  PURCHASE_CONTRACT  VARCHAR2(20 BYTE),
  PC_ITEM            VARCHAR2(5 BYTE),
  PCI_SCHED_DT       DATE,
  PART_NO            VARCHAR2(50 BYTE),
  PART_DESCRIPTION   VARCHAR2(512 BYTE),
  MFG_PART_NO        VARCHAR2(50 BYTE),
  PC_HEADING_TYPE    VARCHAR2(25 BYTE),
  QTY                NUMBER,
  UOM_CODE           VARCHAR2(2 BYTE),
  UNIT_PRICE         NUMBER,
  LAST_UPDATE_DT     DATE                       DEFAULT sysdate
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE BITMAP INDEX AMD_OWNER.AMD_REPAIR_COST_DETAILS_NK01 ON AMD_OWNER.AMD_REPAIR_COST_DETAIL
(FISCAL_YEAR)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.AMD_REPAIR_COST_DETAIL_NK02 ON AMD_OWNER.AMD_REPAIR_COST_DETAIL
(PART_NO)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.AMD_REPIAR_COST_DETAIL_NK03 ON AMD_OWNER.AMD_REPAIR_COST_DETAIL
(FISCAL_YEAR, PART_NO)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_REPAIR_COST_DETAIL TO AMD_DATALOAD;

GRANT SELECT ON AMD_OWNER.AMD_REPAIR_COST_DETAIL TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.AMD_REPAIR_COST_DETAIL TO AMD_USER;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_REPAIR_COST_DETAIL TO AMD_WRITER_ROLE;

