    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:02  $
     $Workfile:   amd_demands.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_demands.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:02   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_DEMANDS
(
  DOC_NO              VARCHAR2(20 BYTE)         NOT NULL,
  DOC_DATE            DATE,
  DOC_DATE_DEFAULTED  DATE,
  NSI_SID             NUMBER,
  LOC_SID             NUMBER,
  QUANTITY            NUMBER,
  ACTION_CODE         VARCHAR2(1 BYTE),
  LAST_UPDATE_DT      DATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_DEMANDS_PK ON AMD_DEMANDS
(DOC_NO)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_DEMANDS FOR AMD_DEMANDS;


ALTER TABLE AMD_DEMANDS ADD (
  CHECK ("NSI_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DEMANDS ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DEMANDS ADD (
  CHECK ("QUANTITY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DEMANDS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DEMANDS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DEMANDS ADD (
  CONSTRAINT AMD_DEMANDS_PK PRIMARY KEY (DOC_NO)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_DEMANDS ADD (
  CONSTRAINT AMD_DEMANDS_FK01 FOREIGN KEY (LOC_SID) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_DEMANDS ADD (
  CONSTRAINT AMD_DEMANDS_FK02 FOREIGN KEY (NSI_SID) 
    REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));


GRANT SELECT ON  AMD_DEMANDS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_DEMANDS TO AMD_WRITER_ROLE;


