DROP TABLE AMD_OWNER.TMP_AMD_DEMANDS CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.TMP_AMD_DEMANDS
(
  DOC_NO              VARCHAR2(20 BYTE),
  DOC_DATE            DATE,
  DOC_DATE_DEFAULTED  DATE,
  NSI_SID             NUMBER,
  LOC_SID             NUMBER,
  QUANTITY            NUMBER,
  ACTION_CODE         VARCHAR2(1 BYTE),
  LAST_UPDATE_DT      DATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          72K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX AMD_OWNER.TMP_AMD_DEMANDS_PK ON AMD_OWNER.TMP_AMD_DEMANDS
(DOC_NO, LOC_SID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM TMP_AMD_DEMANDS;

CREATE OR REPLACE PUBLIC SYNONYM TMP_AMD_DEMANDS FOR AMD_OWNER.TMP_AMD_DEMANDS;


GRANT SELECT ON AMD_OWNER.TMP_AMD_DEMANDS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.TMP_AMD_DEMANDS TO AMD_WRITER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.TMP_AMD_DEMANDS TO BSRM_LOADER;
