    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:58  $
     $Workfile:   tmp_amd_planner_parts.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\tmp_amd_planner_parts.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:58   c970183
/*   Initial revision.
*/

CREATE TABLE TMP_AMD_PLANNER_PARTS
(
  PLANNER_CODE  VARCHAR2(8 BYTE),
  MFGR          VARCHAR2(13 BYTE),
  PART_NO       VARCHAR2(20 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    5
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE INDEX TMPAMD_PLANNER_PARTS_I ON TMP_AMD_PLANNER_PARTS
(PART_NO, MFGR)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM TMP_AMD_PLANNER_PARTS FOR TMP_AMD_PLANNER_PARTS;


ALTER TABLE TMP_AMD_PLANNER_PARTS ADD (
  CHECK ("PLANNER_CODE" IS NOT NULL) DISABLE);

ALTER TABLE TMP_AMD_PLANNER_PARTS ADD (
  CHECK ("MFGR" IS NOT NULL) DISABLE);

ALTER TABLE TMP_AMD_PLANNER_PARTS ADD (
  CHECK ("PART_NO" IS NOT NULL) DISABLE);


GRANT DELETE, INSERT, SELECT, UPDATE ON  TMP_AMD_PLANNER_PARTS TO AMD_DATALOAD;

GRANT SELECT ON  TMP_AMD_PLANNER_PARTS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  TMP_AMD_PLANNER_PARTS TO AMD_WRITER_ROLE;


