DROP VIEW AMD_OWNER.PGOLD_ORDV_V;

/* Formatted on 7/9/2012 4:24:57 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.PGOLD_ORDV_V
(
   ORDER_NO,
   SITE_CODE,
   VENDOR_EST_COST,
   VENDOR_EST_RET_DATE
)
AS
   SELECT TRIM (order_no),
          site_code,
          vendor_est_cost,
          vendor_est_ret_date
     FROM ordv@amd_pgoldlb_link;


DROP PUBLIC SYNONYM PGOLD_ORDV_V;

CREATE OR REPLACE PUBLIC SYNONYM PGOLD_ORDV_V FOR AMD_OWNER.PGOLD_ORDV_V;


GRANT SELECT ON AMD_OWNER.PGOLD_ORDV_V TO AMD_READER_ROLE;
