SET DEFINE OFF;
ALTER TABLE AMD_OWNER.AMD_AIRCRAFTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_OWNER.AMD_AIRCRAFTS CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.AMD_AIRCRAFTS
(
  FUS                   NUMBER,
  P_NO                  VARCHAR2(5 BYTE),
  BUN                   VARCHAR2(6 BYTE),
  TAIL_NO               VARCHAR2(7 BYTE)        NOT NULL,
  FSN                   NUMBER,
  MASTER_ID             VARCHAR2(4 BYTE),
  PTD_FLIGHT_HRS        NUMBER,
  MODEL_ID              VARCHAR2(5 BYTE),
  AC_NO                 VARCHAR2(8 BYTE),
  DD250                 VARCHAR2(5 BYTE),
  CUR_DISTRIBS_UPDATED  VARCHAR2(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  ON_CONTRACT           VARCHAR2(1 BYTE)        DEFAULT 'Y'                   NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX AMD_OWNER.AMD_AIRCRAFTS_PK ON AMD_OWNER.AMD_AIRCRAFTS
(TAIL_NO)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AMD_OWNER.AMD_AIRCRAFTS_UC01 ON AMD_OWNER.AMD_AIRCRAFTS
(FUS)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AMD_OWNER.AMD_AIRCRAFTS_UC02 ON AMD_OWNER.AMD_AIRCRAFTS
(P_NO)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AMD_OWNER.AMD_AIRCRAFTS_UC03 ON AMD_OWNER.AMD_AIRCRAFTS
(BUN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AMD_OWNER.AMD_AIRCRAFTS_UC04 ON AMD_OWNER.AMD_AIRCRAFTS
(FSN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AMD_OWNER.AMD_AIRCRAFTS_UC05 ON AMD_OWNER.AMD_AIRCRAFTS
(MASTER_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM AMD_AIRCRAFTS;

CREATE PUBLIC SYNONYM AMD_AIRCRAFTS FOR AMD_OWNER.AMD_AIRCRAFTS;


DROP SYNONYM RMAD_OWNER.AMD_AIRCRAFTS;

CREATE SYNONYM RMAD_OWNER.AMD_AIRCRAFTS FOR AMD_OWNER.AMD_AIRCRAFTS;


ALTER TABLE AMD_OWNER.AMD_AIRCRAFTS ADD (
  CONSTRAINT YES_NO_INDICATOR
 CHECK (on_contract in ('Y','N')),
  CHECK ("AC_NO" IS NOT NULL) DISABLE,
  CHECK ("MODEL_ID" IS NOT NULL) DISABLE,
  CHECK ("FSN" IS NOT NULL) DISABLE,
  CHECK ("BUN" IS NOT NULL) DISABLE,
  CHECK ("P_NO" IS NOT NULL) DISABLE,
  CHECK ("FUS" IS NOT NULL) DISABLE,
  CONSTRAINT AMD_AIRCRAFTS_PK
 PRIMARY KEY
 (TAIL_NO)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ),
  CONSTRAINT AMD_AIRCRAFTS_UC01
 UNIQUE (FUS)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ),
  CONSTRAINT AMD_AIRCRAFTS_UC02
 UNIQUE (P_NO)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ),
  CONSTRAINT AMD_AIRCRAFTS_UC03
 UNIQUE (BUN)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ),
  CONSTRAINT AMD_AIRCRAFTS_UC04
 UNIQUE (FSN)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ),
  CONSTRAINT AMD_AIRCRAFTS_UC05
 UNIQUE (MASTER_ID)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE AMD_OWNER.AMD_AIRCRAFTS ADD (
  CONSTRAINT AMD_AIRCRAFTS_FK01 
 FOREIGN KEY (MODEL_ID) 
 REFERENCES AMD_OWNER.AMD_PRODUCT_MODELS (MODEL_ID));

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_AIRCRAFTS TO AMD_ASSET_MGT_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_AIRCRAFTS TO AMD_DATALOAD;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO AMD_SDSP_IF_ROLE;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO AMD_USER;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_AIRCRAFTS TO AMD_WRITER_ROLE;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO ASIS_ADMIN_ROLE;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO ASIS_DATALOAD_ROLE;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO ASIS_OWNER WITH GRANT OPTION;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO ASIS_READER_ROLE;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO ASIS_USER_ROLE;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO IF_USER;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO OPS_RMADADMN;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO OPS_RMADUSER;

GRANT SELECT ON AMD_OWNER.AMD_AIRCRAFTS TO RMAD_OWNER;


