prompt creating tmp_amd_demands table....
@create_tmp_amd_demands_tab.sql

prompt creating tmp_a2a_demands table....
@create_tmp_a2a_demands_tab.sql

prompt running amd_demand.pks....
@amd_demand.pks;

prompt running amd_demand.pkb....
@amd_demand.pkb;

prompt running alter_table_amd_demands_pk.sql....
@alter_table_amd_demands_pk.sql