    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 23 2005 12:32:58  $
     $Workfile:   constraints.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\Scripts\constraints.sql-arc  $
/*   
/*      Rev 1.0   May 23 2005 12:32:58   c970183
/*   Initial revision.
*/
--ACT_PERF__AMD_UOMS_FK
--ACT_PERF__FK
--AMD_ACMII_PK
--AMD_ACTUAL_AC_USAGES_FK01
--AMD_ACTUAL_AC_USAGES_FK02
--AMD_ACTUAL_AC_USAGES_PK
--AMD_ACTUAL_PERFORMANCES_PK
--AMD_AC_ASSIGNS_FK01
--AMD_AC_ASSIGNS_FK02
--AMD_AC_ASSIGNS_PK
--AMD_AIRCRAFTS_FK01
--AMD_AIRCRAFTS_PK
--AMD_AIRCRAFTS_UC01
--AMD_AIRCRAFTS_UC02
--AMD_AIRCRAFTS_UC03
--AMD_AIRCRAFTS_UC04
--AMD_AIRCRAFTS_UC05
--AMD_AIRPORTS_PK
--AMD_ARCHIVE_FLTOPS_PK
--AMD_ARCHIVE_PARTSFC_PK
--AMD_AWARD_FEES_PK
--AMD_BODS_FK01
--AMD_BODS_FK02
--AMD_BODS_PK
--AMD_CALENDARS_PK
--AMD_CALENDAR_EXCEPTIONS_FK01
--AMD_CALENDAR_EXCEPTIONS_PK
--AMD_CUR_NSI_LOC_DISTRIBS_FK01
--AMD_CUR_NSI_LOC_DISTRIBS_FK02
--AMD_CUR_NSI_LOC_DISTRIBS_PK
--AMD_CUR_NSI_LOC_DISTR_DERIV_CK
--AMD_DEMANDS_FK01
--AMD_DEMANDS_FK02
--AMD_DEMANDS_PK
--AMD_ESCALATION_FACTORS_PK
--AMD_FLEET_SIZES_PK
--AMD_FLEET_SIZES_PREDEFINED_CK
--AMD_FLEET_SIZES_SUBS_AC_CK
--AMD_FLEET_SIZE_MEMBER_PK
--AMD_FLIGHT_STATS_FK01
--AMD_FLIGHT_STATS_FK02
--AMD_FLIGHT_STATS_FK03
--AMD_FLIGHT_STATS_PK
--AMD_FORCASTED_AC_USAGES_FK01
--AMD_FORCASTED_AC_USAGES_FK02
--AMD_FORCASTED_AC_USAGES_PK
--AMD_FOR_AC_USAGES_PK
--AMD_FOR__AMD_UOM_FK01_FK
--AMD_FOR__FK
--AMD_ICAOS_FK01
--AMD_ICAOS_PK
--AMD_ICAO_REGIONS_FK01
--AMD_ICAO_REGIONS_PK
--AMD_ICAO_XREF_PK
--AMD_IN_REPAIR_FK01
--AMD_IN_REPAIR_FK02
--AMD_IN_REPAIR_PK
--AMD_IN_TRANSITS_PK
--AMD_ISGP_PK
--AMD_L67_SOURCE_PK
--AMD_LTD_FLEET_SIZE_MEMBER_FK01
--AMD_LTD_FLEET_SIZE_MEMBER_FK02
--AMD_MAINT_TASK_DISTRIBS_FK01
--AMD_MAINT_TASK_DISTRIBS_PK
--AMD_MISSION_FLIGHTS_FK1
--AMD_MISSION_FLIGHTS_FK2
--AMD_MISSION_FLIGHTS_FK3
--AMD_MISSION_FLIGHTS_FK4
--AMD_MISSION_FLIGHTS_PK
--AMD_MISSION_TYPES_PK
--AMD_NATIONAL_STOCK_ITEMS_CK01
--AMD_NATIONAL_STOCK_ITEMS_FK01
--AMD_NATIONAL_STOCK_ITEMS_FK02
--AMD_NATIONAL_STOCK_ITEMS_FK03
--AMD_NATIONAL_STOCK_ITEMS_FK04
--AMD_NATIONAL_STOCK_ITEMS_FK05
--AMD_NATIONAL_STOCK_ITEMS_FK06
--AMD_NATIONAL_STOCK_ITEMS_FK07
--AMD_NATIONAL_STOCK_ITEMS_FK09
--AMD_NATIONAL_STOCK_ITEMS_PK
--AMD_NATIONAL_STOCK_ITEMS_UC01
--AMD_NSIS_EFFECT_BY_CK
--AMD_NSIS_LATEST_CONFIG_CK
--AMD_NSI_EFFECTS_EFFECT_TYPE_CK
--AMD_NSI_EFFECTS_FK01
--AMD_NSI_EFFECTS_FK02
--AMD_NSI_EFFECTS_PK
--AMD_NSI_EFFECT_DERIVED_CK
--AMD_NSI_EFFECT_USER_DEFINED_CK
--AMD_NSI_GROUPS_FK01
--AMD_NSI_GROUPS_PK
--AMD_NSI_GROUPS_SPLIT_EFFECT_CK
--AMD_NSI_LOC_DISTRIBS_FK01
--AMD_NSI_LOC_DISTRIBS_FK02
--AMD_NSI_LOC_DISTRIBS_FK03
--AMD_NSI_LOC_DISTRIBS_PK
--AMD_NSI_PARTS_FK01
--AMD_NSI_PARTS_FK02
--AMD_NSI_PARTS_PK
--AMD_NSNS_FK01
--AMD_NSNS_PK
--AMD_ON_HAND_INVS_FK01
--AMD_ON_HAND_INVS_FK02
--AMD_ON_HAND_INVS_PK
--AMD_ON_ORDER_FK01
--AMD_ON_ORDER_FK02
--AMD_ON_ORDER_PK
--AMD_PARAMS_PK
--AMD_PARAM_CHANGES_FK01
--AMD_PARAM_CHANGES_PK
--AMD_PART_EFFECTIVITIES_FK01
--AMD_PART_EFFECTIVITIES_FK02
--AMD_PART_EFF_PK
--AMD_PART_LOCATIONS_FK02
--AMD_PART_LOCATIONS_PK
--AMD_PART_LOCS_FK01
--AMD_PART_LOCS_FK02
--AMD_PART_LOCS_PK
--AMD_PART_LOC_FORECASTS_FK01
--AMD_PART_LOC_FORECASTS_FK02
--AMD_PART_LOC_FORECASTS_PK
--AMD_PART_LOC_TIME_PERIODS_FK01
--AMD_PART_LOC_TIME_PERIODS_PK
--AMD_PART_NEXT_ASSEMBLIES_FK01
--AMD_PART_NEXT_ASSEMBLIES_PK2
--AMD_PART_NEXT_ASSM_PK
--AMD_PLANNERS_FK01
--AMD_PLANNERS_PK
--AMD_PLANNER_LOGONS_FK01
--AMD_PLANNER_LOGONS_PK
--AMD_PRODUCT_MODELS_PK
--AMD_PRODUCT_STRUCTURE_FK01
--AMD_PRODUCT_STRUCTURE_FK02
--AMD_PRODUCT_STRUCTURE_PK
--AMD_PROJECTED_AC_USAGES_FK01
--AMD_PROJECTED_AC_USAGES_FK02
--AMD_PROJ_AC_USAGES_PK
--AMD_RELATED_NSI_PAIRS_FK01
--AMD_RELATED_NSI_PAIRS_FK02
--AMD_RELATED_NSI_PAIRS_FK03
--AMD_RELATED_NSI_PAIRS_PK
--AMD_RELATED_NSI_UPGRADEABLE_CK
--AMD_RELATED_PAIRS_INTERCHG_CK
--AMD_REQS_FK01
--AMD_REQS_FK02
--AMD_REQS_PK
--AMD_RETROFIT_SCHEDULES_FK01
--AMD_RETROFIT_SCHEDULES_FK02
--AMD_RETROFIT_SCHEDULES_FK03
--AMD_RETROFIT_SCHEDULES_PK
--AMD_RETROFIT_SCHED_BLOCKS_PK
--AMD_RMADS_SOURCE_TMP_PK
--AMD_SHELF_LIFE_CODES_PK
--AMD_SPARE_NETWORKS_AK2
--AMD_SPARE_NETWORKS_FK01
--AMD_SPARE_NETWORKS_PK2
--AMD_SPARE_NET_PK
--AMD_SPARE_PARTS_FK01
--AMD_SPARE_PARTS_FK02
--AMD_SPARE_PARTS_FK03
--AMD_SPARE_PARTS_PK
--AMD_SPARE_PIPELINES_CK01
--AMD_SPARE_PIPELINES_FK01
--AMD_SPARE_PIPELINES_FK02
--AMD_SPARE_PIPELINES_FK03
--AMD_SPARE_PIPELINES_PK
--AMD_STORAGE_COSTS_FK01
--AMD_STORAGE_COSTS_PK
--AMD_TAV_LOCATIONS_PK
--AMD_TCTOS_PK
--AMD_TIME_PERIODS_PK
--AMD_TIME_PERIODS_UC01
--AMD_TRANSPORT_MODES_PK
--AMD_UOMS_PK
--AMD_UOMS_UC01
--AMD_USE1_PK
--AMD_USE1_UK01
--AWARD__FK
--CAT1P1
--FEDCP1
--FEESCHD_AWARD_FK
--FEESCHD_PK
--ITEMP1
--MILSP1
--MLITP1
--ORD1P1
--POI1P1
--PRC1P1
--RAMPP1
--SYS_C0025983
--SYS_C0025984
--SYS_C0025985
--SYS_C0025986
--SYS_C0025988
--SYS_C0025989
--SYS_C0025990
--SYS_C0025991
--SYS_C0025993
--SYS_C0025994
--SYS_C0025995
--SYS_C0025996
--SYS_C0025998
--SYS_C0025999
--SYS_C0026000
--SYS_C0026001
--SYS_C0026002
--SYS_C0026003
--SYS_C0026004
--SYS_C0026005
--SYS_C0026012
--SYS_C0026013
--SYS_C0026015
--SYS_C0026016
--SYS_C0026017
--SYS_C0026018
--SYS_C0026019
--SYS_C0026020
--SYS_C0026021
--SYS_C0026023
--SYS_C0026024
--SYS_C0026025
--SYS_C0026026
--SYS_C0026027
--SYS_C0026028
--SYS_C0026029
--SYS_C0026031
--SYS_C0026032
--SYS_C0026033
--SYS_C0026035
--SYS_C0026036
--SYS_C0026037
--SYS_C0026038
--SYS_C0026040
--SYS_C0026041
--SYS_C0026042
--SYS_C0026043
--SYS_C0026044
--SYS_C0026045
--SYS_C0026046
--SYS_C0026047
--SYS_C0026048
--SYS_C0026049
--SYS_C0026051
--SYS_C0026052
--SYS_C0026053
--SYS_C0026054
--SYS_C0026055
--SYS_C0026056
--SYS_C0026057
--SYS_C0026058
--SYS_C0026059
--SYS_C0026060
--SYS_C0026061
--SYS_C0026062
--SYS_C0026063
--SYS_C0026064
--SYS_C0026065
--SYS_C0026067
--SYS_C0026068
--SYS_C0026069
--SYS_C0026070
--SYS_C0026072
--SYS_C0026073
--SYS_C0026074
--SYS_C0026075
--SYS_C0026076
--SYS_C0026077
--SYS_C0026078
--SYS_C0026079
--SYS_C0026082
--SYS_C0026083
--SYS_C0026084
--SYS_C0026085
--SYS_C0026086
--SYS_C0026087
--SYS_C0026088
--SYS_C0026089
--SYS_C0026091
--SYS_C0026092
--SYS_C0026093
--SYS_C0026094
--SYS_C0026096
--SYS_C0026097
--SYS_C0026098
--SYS_C0026102
--SYS_C0026103
--SYS_C0026104
--SYS_C0026105
--SYS_C0026106
--SYS_C0026107
--SYS_C0026109
--SYS_C0026110
--SYS_C0026111
--SYS_C0026112
--SYS_C0026113
--SYS_C0026114
--SYS_C0026116
--SYS_C0026117
--SYS_C0026118
--SYS_C0026119
--SYS_C0026121
--SYS_C0026122
--SYS_C0026124
--SYS_C0026125
--SYS_C0026127
--SYS_C0026128
--SYS_C0026130
--SYS_C0026131
--SYS_C0026132
--SYS_C0026133
--SYS_C0026134
--SYS_C0026135
--SYS_C0026136
--SYS_C0026138
--SYS_C0026139
--SYS_C0026140
--SYS_C0026141
--SYS_C0026142
--SYS_C0026143
--SYS_C0026146
--SYS_C0026147
--SYS_C0026148
--SYS_C0026149
--SYS_C0026150
--SYS_C0026151
--SYS_C0026153
--SYS_C0026154
--SYS_C0026155
--SYS_C0026156
--SYS_C0026158
--SYS_C0026159
--SYS_C0026160
--SYS_C0026161
--SYS_C0026162
--SYS_C0026163
--SYS_C0026164
--SYS_C0026165
--SYS_C0026166
--SYS_C0026168
--SYS_C0026169
--SYS_C0026171
--SYS_C0026172
--SYS_C0026173
--SYS_C0026174
--SYS_C0026175
--SYS_C0026181
--SYS_C0026182
--SYS_C0026183
--SYS_C0026188
--SYS_C0026189
--SYS_C0026190
--SYS_C0026193
--SYS_C0026194
--SYS_C0026195
--SYS_C0026196
--SYS_C0026198
--SYS_C0026199
--SYS_C0026200
--SYS_C0026201
--SYS_C0026203
--SYS_C0026204
--SYS_C0026205
--SYS_C0026207
--SYS_C0026208
--SYS_C0026209
--SYS_C0026210
--SYS_C0026211
--SYS_C0026212
--SYS_C0026213
--SYS_C0026214
--SYS_C0026216
--SYS_C0026217
--SYS_C0026218
--SYS_C0026219
--SYS_C0026220
--SYS_C0026221
--SYS_C0026222
--SYS_C0026224
--SYS_C0026226
--SYS_C0026227
--SYS_C0026228
--SYS_C0026230
--SYS_C0026231
--SYS_C0026233
--SYS_C0026234
--SYS_C0026236
--SYS_C0026237
--SYS_C0026238
--SYS_C0026239
--SYS_C0026240
--SYS_C0026242
--SYS_C0026243
--SYS_C0026244
--SYS_C0026245
--SYS_C0026246
--SYS_C0026247
--SYS_C0026248
--SYS_C0026249
--SYS_C0026251
--SYS_C0026252
--SYS_C0026253
--SYS_C0026254
--SYS_C0026255
--SYS_C0026256
--SYS_C0026257
--SYS_C0026258
--SYS_C0026260
--SYS_C0026261
--SYS_C0026262
--SYS_C0026263
--SYS_C0026264
--SYS_C0026267
--SYS_C0026268
--SYS_C0026269
--SYS_C0026271
--SYS_C0026272
--SYS_C0026274
--SYS_C0026276
--SYS_C0026277
--SYS_C0026279
--SYS_C0026280
--SYS_C0026281
--SYS_C0026282
--SYS_C0026284
--SYS_C0026285
--SYS_C0026286
--SYS_C0026287
--SYS_C0026291
--SYS_C0026292
--SYS_C0026293
--SYS_C0026294
--SYS_C0026295
--SYS_C0026296
--SYS_C0026297
--SYS_C0026298
--SYS_C0026299
--SYS_C0026301
--SYS_C0026302
--SYS_C0026304
--SYS_C0026305
--SYS_C0026307
--SYS_C0026308
--SYS_C0026310
--SYS_C0026312
--SYS_C0026313
--SYS_C0026315
--SYS_C0026316
--SYS_C0026317
--SYS_C0026318
--SYS_C0026319
--SYS_C0026320
--SYS_C0026321
--SYS_C0026325
--SYS_C0026326
--SYS_C0026327
--SYS_C0026328
--SYS_C0026329
--SYS_C0026330
--SYS_C0026332
--SYS_C0026333
--SYS_C0026334
--SYS_C0026335
--SYS_C0026338
--SYS_C0026339
--SYS_C0026341
--SYS_C0026342
--SYS_C0026343
--SYS_C0026344
--SYS_C0026347
--SYS_C0026348
--SYS_C0026349
--SYS_C0026350
--SYS_C0026352
--SYS_C0026353
--SYS_C0026356
--SYS_C0026357
--SYS_C0026358
--SYS_C0026359
--SYS_C0026360
--SYS_C0026361
--SYS_C0026362
--SYS_C0026363
--SYS_C0026364
--SYS_C0026365
--SYS_C0026366
--SYS_C0026367
--SYS_C0026368
--SYS_C0026369
--SYS_C0026370
--SYS_C0026371
--SYS_C0026372
--SYS_C0026373
--SYS_C0026374
--SYS_C0026376
--SYS_C0026377
--SYS_C0026378
--SYS_C0026379
--SYS_C0026381
--SYS_C0026382
--SYS_C0026383
--SYS_C0026384
--SYS_C0026385
--SYS_C0026386
--SYS_C0026387
--SYS_C0026388
--SYS_C0026389
--SYS_C0026390
--SYS_C0026391
--SYS_C0026392
--SYS_C0026393
--SYS_C0026394
--SYS_C0026395
--SYS_C0026396
--SYS_C0026398
--SYS_C0026399
--SYS_C0026400
--SYS_C0026402
--SYS_C0026403
--SYS_C0026404
--SYS_C0026405
--SYS_C0026406
--SYS_C0026407
--SYS_C0026408
--SYS_C0026409
--SYS_C0026410
--SYS_C0026411
--SYS_C0026412
--SYS_C0026413
--SYS_C0026415
--SYS_C0026416
--SYS_C0026417
--SYS_C0026418
--SYS_C0026420
--SYS_C0026421
--SYS_C0026422
--SYS_C0026423
--SYS_C0026424
--SYS_C0026426
--SYS_C0026427
--SYS_C0026429
--SYS_C0026430
--SYS_C0026432
--SYS_C0026433
--SYS_C0026434
--SYS_C0026435
--SYS_C0026436
--SYS_C0026437
--SYS_C0026438
--SYS_C0026439
--SYS_C0026440
--SYS_C0026441
--SYS_C0026442
--SYS_C0026443
--SYS_C0026444
--SYS_C0026445
--SYS_C0026446
--SYS_C0026447
--SYS_C0026448
--SYS_C0026449
--SYS_C0026450
--SYS_C0026451
--SYS_C0026452
--SYS_C0026453
--SYS_C0026454
--SYS_C0026455
--SYS_C0026456
--SYS_C0026457
--SYS_C0026459
--SYS_C0026460
--SYS_C0033641
--SYS_C0033642
--SYS_C0033643
--SYS_C0033645
--SYS_C0033646
--SYS_C0033649
--SYS_C0033650
--SYS_C0033729
--VENCP1
--VENNP1
--
ALTER TABLE AMD_CUR_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_CUR_NSI_LOC_DISTR_DERIV_CK
 CHECK (
            DERIVED IN ('Y', 'N')));

ALTER TABLE AMD_CUR_NSI_LOC_DISTRIBS MODIFY 
  NSI_SID NOT NULL;

ALTER TABLE AMD_CUR_NSI_LOC_DISTRIBS MODIFY 
  LOC_SID NOT NULL;

ALTER TABLE AMD_CUR_NSI_LOC_DISTRIBS MODIFY 
  QUANTITY NOT NULL;

ALTER TABLE AMD_CUR_NSI_LOC_DISTRIBS MODIFY 
  USER_DEFINED NOT NULL;

ALTER TABLE AMD_CUR_NSI_LOC_DISTRIBS MODIFY 
  LAST_UPDATE_DT NOT NULL;

ALTER TABLE AMD_CUR_NSI_LOC_DISTRIBS MODIFY 
  LAST_UPDATE_ID NOT NULL;

ALTER TABLE AMD_CUR_NSI_LOC_DISTRIBS MODIFY 
  DERIVED NOT NULL;

ALTER TABLE AMD_CUR_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_CUR_NSI_LOC_DISTRIBS_PK
 PRIMARY KEY
 (NSI_SID, LOC_SID));


ALTER TABLE AMD_FLEET_SIZES ADD (
  CONSTRAINT AMD_FLEET_SIZES_PREDEFINED_CK
 CHECK (
         PREDEFINED IN ('Y', 'N')));

ALTER TABLE AMD_FLEET_SIZES ADD (
  CONSTRAINT AMD_FLEET_SIZES_SUBS_AC_CK
 CHECK (
			SUBS_AIRCRAFT IN ('Y', 'N') OR SUBS_AIRCRAFT IS NULL
		));

ALTER TABLE AMD_FLEET_SIZES MODIFY 
  FLEET_SIZE_NAME NOT NULL;

ALTER TABLE AMD_FLEET_SIZES MODIFY 
  FLEET_SIZE_DESC NOT NULL;

ALTER TABLE AMD_FLEET_SIZES MODIFY 
  PREDEFINED NOT NULL;

ALTER TABLE AMD_FLEET_SIZES ADD (
  CONSTRAINT AMD_FLEET_SIZES_PK
 PRIMARY KEY
 (FLEET_SIZE_NAME));


ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_CK01
 CHECK (
       NOT (ORDER_QUANTITY IS NULL
          AND ORDER_QUANTITY_DEFAULTED IS NULL)
       ));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NSIS_EFFECT_BY_CK
 CHECK (
            EFFECT_BY IN ('S', 'F')));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NSIS_LATEST_CONFIG_CK
 CHECK (
         LATEST_CONFIG IS NULL OR
         LATEST_CONFIG IN ('Y', 'N')
      ));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS MODIFY 
  NSI_SID NOT NULL;

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS MODIFY 
  TACTICAL NOT NULL;

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS MODIFY 
  ACTION_CODE NOT NULL;

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS MODIFY 
  LAST_UPDATE_DT NOT NULL;

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS MODIFY 
  FORECAST_IGNORE NOT NULL;

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_PK
 PRIMARY KEY
 (NSI_SID));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_UC01
 UNIQUE (NSN));


ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECTS_EFFECT_TYPE_CK
 CHECK (
         EFFECT_TYPE IN ('C', 'B')));

ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECT_DERIVED_CK
 CHECK (
            DERIVED IN ('Y', 'N')));

ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECT_USER_DEFINED_CK
 CHECK (
            USER_DEFINED IN ('Y', 'N', 'S')));

ALTER TABLE AMD_NSI_EFFECTS MODIFY 
  NSI_SID NOT NULL;

ALTER TABLE AMD_NSI_EFFECTS MODIFY 
  TAIL_NO NOT NULL;

ALTER TABLE AMD_NSI_EFFECTS MODIFY 
  EFFECT_TYPE NOT NULL;

ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECTS_PK
 PRIMARY KEY
 (NSI_SID, TAIL_NO));


ALTER TABLE AMD_NSI_GROUPS ADD (
  CONSTRAINT AMD_NSI_GROUPS_SPLIT_EFFECT_CK
 CHECK (SPLIT_EFFECT IN ('Y', 'N')));

ALTER TABLE AMD_NSI_GROUPS MODIFY 
  NSI_GROUP_SID NOT NULL;

ALTER TABLE AMD_NSI_GROUPS MODIFY 
  FLEET_SIZE_NAME NOT NULL;

ALTER TABLE AMD_NSI_GROUPS MODIFY 
  SPLIT_EFFECT NOT NULL;

ALTER TABLE AMD_NSI_GROUPS ADD (
  CONSTRAINT AMD_NSI_GROUPS_PK
 PRIMARY KEY
 (NSI_GROUP_SID));


ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_NSI_UPGRADEABLE_CK
 CHECK (
         UPGRADEABLE IN ('Y', 'N')));

ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_PAIRS_INTERCHG_CK
 CHECK (
			interchange_type in ('limited','Not','1-way','2-way')
		));

ALTER TABLE AMD_RELATED_NSI_PAIRS MODIFY 
  REPLACED_NSI_SID NOT NULL;

ALTER TABLE AMD_RELATED_NSI_PAIRS MODIFY 
  REPLACED_BY_NSI_SID NOT NULL;

ALTER TABLE AMD_RELATED_NSI_PAIRS MODIFY 
  UPGRADEABLE NOT NULL;

ALTER TABLE AMD_RELATED_NSI_PAIRS MODIFY 
  INTERCHANGE_TYPE NOT NULL;

ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_NSI_PAIRS_PK
 PRIMARY KEY
 (REPLACED_NSI_SID, REPLACED_BY_NSI_SID));


ALTER TABLE AMD_SPARE_PIPELINES ADD (
  CONSTRAINT AMD_SPARE_PIPELINES_CK01
 CHECK (FROM_LOC_SID <> TO_LOC_SID));

ALTER TABLE AMD_SPARE_PIPELINES MODIFY 
  FROM_LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_SPARE_PIPELINES MODIFY 
  TO_LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_SPARE_PIPELINES MODIFY 
  TRANSPORT_AGENT_ID NOT NULL DISABLE;

ALTER TABLE AMD_SPARE_PIPELINES MODIFY 
  TRANSPORT_MODE_ID NOT NULL DISABLE;

ALTER TABLE AMD_SPARE_PIPELINES ADD (
  CONSTRAINT AMD_SPARE_PIPELINES_PK
 PRIMARY KEY
 (FROM_LOC_SID, TO_LOC_SID, TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID));


ALTER TABLE AMD_ACTUAL_AC_USAGES MODIFY 
  EFFECTIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_ACTUAL_AC_USAGES ADD (
  CHECK ("USAGE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ACTUAL_AC_USAGES MODIFY 
  TAIL_NO NOT NULL DISABLE;

ALTER TABLE AMD_ACTUAL_AC_USAGES MODIFY 
  UOM_CODE NOT NULL DISABLE;

ALTER TABLE AMD_ACTUAL_AC_USAGES ADD (
  CONSTRAINT AMD_ACTUAL_AC_USAGES_PK
 PRIMARY KEY
 (EFFECTIVE_DATE, TAIL_NO, UOM_CODE));


ALTER TABLE AMD_ACTUAL_PERFORMANCES MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_ACTUAL_PERFORMANCES MODIFY 
  UOM_CODE NOT NULL DISABLE;

ALTER TABLE AMD_ACTUAL_PERFORMANCES MODIFY 
  EFFECTIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_ACTUAL_PERFORMANCES ADD (
  CHECK ("VALUE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ACTUAL_PERFORMANCES ADD (
  CONSTRAINT AMD_ACTUAL_PERFORMANCES_PK
 PRIMARY KEY
 (EFFECTIVE_DATE, LOC_SID, UOM_CODE));


ALTER TABLE AMD_AC_ASSIGNS MODIFY 
  ASSIGNMENT_START NOT NULL DISABLE;

ALTER TABLE AMD_AC_ASSIGNS MODIFY 
  TAIL_NO NOT NULL DISABLE;

ALTER TABLE AMD_AC_ASSIGNS ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AC_ASSIGNS MODIFY 
  LAST_UPDATE_DATE NOT NULL;

ALTER TABLE AMD_AC_ASSIGNS ADD (
  CONSTRAINT AMD_AC_ASSIGNS_PK
 PRIMARY KEY
 (ASSIGNMENT_START, TAIL_NO));


ALTER TABLE AMD_AIRCRAFTS ADD (
  CHECK ("FUS" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AIRCRAFTS ADD (
  CHECK ("P_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AIRCRAFTS ADD (
  CHECK ("BUN" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AIRCRAFTS MODIFY 
  TAIL_NO NOT NULL DISABLE;

ALTER TABLE AMD_AIRCRAFTS ADD (
  CHECK ("FSN" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AIRCRAFTS ADD (
  CHECK ("MODEL_ID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AIRCRAFTS ADD (
  CHECK ("AC_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AIRCRAFTS MODIFY 
  CUR_DISTRIBS_UPDATED NOT NULL;

ALTER TABLE AMD_AIRCRAFTS ADD (
  CONSTRAINT AMD_AIRCRAFTS_PK
 PRIMARY KEY
 (TAIL_NO));

ALTER TABLE AMD_AIRCRAFTS ADD (
  CONSTRAINT AMD_AIRCRAFTS_UC01
 UNIQUE (FUS));

ALTER TABLE AMD_AIRCRAFTS ADD (
  CONSTRAINT AMD_AIRCRAFTS_UC02
 UNIQUE (P_NO));

ALTER TABLE AMD_AIRCRAFTS ADD (
  CONSTRAINT AMD_AIRCRAFTS_UC03
 UNIQUE (BUN));

ALTER TABLE AMD_AIRCRAFTS ADD (
  CONSTRAINT AMD_AIRCRAFTS_UC04
 UNIQUE (FSN));

ALTER TABLE AMD_AIRCRAFTS ADD (
  CONSTRAINT AMD_AIRCRAFTS_UC05
 UNIQUE (MASTER_ID));


ALTER TABLE AMD_AIRPORTS MODIFY 
  ICAO NOT NULL DISABLE;

ALTER TABLE AMD_AIRPORTS ADD (
  CHECK ("AIRPORT_NAME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AIRPORTS ADD (
  CONSTRAINT AMD_AIRPORTS_PK
 PRIMARY KEY
 (ICAO));


ALTER TABLE AMD_ARCHIVE_FLTOPS MODIFY 
  ARCHIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_ARCHIVE_FLTOPS MODIFY 
  FORECAST_NAME NOT NULL DISABLE;

ALTER TABLE AMD_ARCHIVE_FLTOPS MODIFY 
  LOC_ID NOT NULL DISABLE;

ALTER TABLE AMD_ARCHIVE_FLTOPS MODIFY 
  UOM_CODE NOT NULL DISABLE;

ALTER TABLE AMD_ARCHIVE_FLTOPS MODIFY 
  TIME_PERIOD_START NOT NULL DISABLE;

ALTER TABLE AMD_ARCHIVE_FLTOPS ADD (
  CHECK ("TIME_PERIOD_END" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ARCHIVE_FLTOPS ADD (
  CHECK ("USAGE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ARCHIVE_FLTOPS ADD (
  CONSTRAINT AMD_ARCHIVE_FLTOPS_PK
 PRIMARY KEY
 (ARCHIVE_DATE, FORECAST_NAME, LOC_ID, UOM_CODE, TIME_PERIOD_START));


ALTER TABLE AMD_ARCHIVE_PARTSFC MODIFY 
  ARCHIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_ARCHIVE_PARTSFC MODIFY 
  FORECAST_NAME NOT NULL DISABLE;

ALTER TABLE AMD_ARCHIVE_PARTSFC MODIFY 
  NSN NOT NULL DISABLE;

ALTER TABLE AMD_ARCHIVE_PARTSFC MODIFY 
  LOC_ID NOT NULL DISABLE;

ALTER TABLE AMD_ARCHIVE_PARTSFC MODIFY 
  TIME_PERIOD_START NOT NULL DISABLE;

ALTER TABLE AMD_ARCHIVE_PARTSFC ADD (
  CHECK ("TIME_PERIOD_END" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ARCHIVE_PARTSFC ADD (
  CHECK ("QUANTITY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ARCHIVE_PARTSFC ADD (
  CONSTRAINT AMD_ARCHIVE_PARTSFC_PK
 PRIMARY KEY
 (ARCHIVE_DATE, FORECAST_NAME, NSN, LOC_ID, TIME_PERIOD_START));


ALTER TABLE AMD_AWARD_FEES MODIFY 
  UOM_CODE NOT NULL DISABLE;

ALTER TABLE AMD_AWARD_FEES MODIFY 
  EFFECTIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_AWARD_FEES ADD (
  CHECK ("AWARD_BASE_AMT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AWARD_FEES ADD (
  CONSTRAINT AMD_AWARD_FEES_PK
 PRIMARY KEY
 (UOM_CODE, EFFECTIVE_DATE));


ALTER TABLE AMD_AWARD_FEE_SCHDS MODIFY 
  EFFECTIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_AWARD_FEE_SCHDS MODIFY 
  UOM_CODE NOT NULL DISABLE;

ALTER TABLE AMD_AWARD_FEE_SCHDS MODIFY 
  PERF_VALUE NOT NULL DISABLE;

ALTER TABLE AMD_AWARD_FEE_SCHDS ADD (
  CHECK ("AWARD_FEE_PCT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AWARD_FEE_SCHDS ADD (
  CONSTRAINT FEESCHD_PK
 PRIMARY KEY
 (EFFECTIVE_DATE, UOM_CODE, PERF_VALUE));


ALTER TABLE AMD_BODS MODIFY 
  FROM_LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_BODS MODIFY 
  TO_LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_BODS MODIFY 
  TRANSPORT_AGENT_ID NOT NULL DISABLE;

ALTER TABLE AMD_BODS MODIFY 
  TRANSPORT_MODE_ID NOT NULL DISABLE;

ALTER TABLE AMD_BODS MODIFY 
  BOD_SUBJECT NOT NULL DISABLE;

ALTER TABLE AMD_BODS ADD (
  CHECK ("BOD_SUBJECT_TYPE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BODS ADD (
  CHECK ("BOD_TIME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BODS ADD (
  CHECK ("SOURCING_PRIORITY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BODS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BODS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BODS ADD (
  CONSTRAINT AMD_BODS_PK
 PRIMARY KEY
 (FROM_LOC_SID, TO_LOC_SID, TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID, BOD_SUBJECT));


ALTER TABLE AMD_BSSM_SOURCE ADD (
  CHECK ("REQUISITION_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BSSM_SOURCE ADD (
  CHECK ("REQUISITION_DATE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BSSM_SOURCE ADD (
  CHECK ("QUANTITY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BSSM_SOURCE ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BSSM_SOURCE ADD (
  CHECK ("NSN" IS NOT NULL) DISABLE);


ALTER TABLE AMD_CALENDARS MODIFY 
  CALENDAR_NAME NOT NULL DISABLE;

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_SUNDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_MONDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_TUESDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_WEDNESDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_THURSDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_FRIDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_SATURDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CONSTRAINT AMD_CALENDARS_PK
 PRIMARY KEY
 (CALENDAR_NAME));


ALTER TABLE AMD_CALENDAR_EXCEPTIONS MODIFY 
  CALENDAR_NAME NOT NULL DISABLE;

ALTER TABLE AMD_CALENDAR_EXCEPTIONS MODIFY 
  EXCEPTION_DATE NOT NULL DISABLE;

ALTER TABLE AMD_CALENDAR_EXCEPTIONS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDAR_EXCEPTIONS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDAR_EXCEPTIONS ADD (
  CONSTRAINT AMD_CALENDAR_EXCEPTIONS_PK
 PRIMARY KEY
 (CALENDAR_NAME, EXCEPTION_DATE));


ALTER TABLE AMD_CCN_PREFIX ADD (
  CHECK ("CCN_PREFIX" IS NOT NULL) DISABLE);


ALTER TABLE AMD_DATA_OWNERS ADD (
  CHECK ("SOURCE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DATA_OWNERS ADD (
  CHECK ("DATA_OWNER" IS NOT NULL) DISABLE);


ALTER TABLE AMD_DEMANDS MODIFY 
  DOC_NO NOT NULL DISABLE;

ALTER TABLE AMD_DEMANDS ADD (
  CHECK ("NSI_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DEMANDS ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DEMANDS ADD (
  CHECK ("QUANTITY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DEMANDS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DEMANDS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DEMANDS ADD (
  CONSTRAINT AMD_DEMANDS_PK
 PRIMARY KEY
 (DOC_NO));


ALTER TABLE AMD_ESCALATION_FACTORS MODIFY 
  EFFECTIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_ESCALATION_FACTORS MODIFY 
  TIME_PERIOD NOT NULL DISABLE;

ALTER TABLE AMD_ESCALATION_FACTORS ADD (
  CHECK ("ESCALATION_FACTOR" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ESCALATION_FACTORS MODIFY 
  INDEX_TYPE NOT NULL DISABLE;

ALTER TABLE AMD_ESCALATION_FACTORS ADD (
  CONSTRAINT AMD_ESCALATION_FACTORS_PK
 PRIMARY KEY
 (EFFECTIVE_DATE, TIME_PERIOD, INDEX_TYPE));


ALTER TABLE AMD_FLIGHT_STATS MODIFY 
  BASE NOT NULL DISABLE;

ALTER TABLE AMD_FLIGHT_STATS MODIFY 
  FSL NOT NULL DISABLE;

ALTER TABLE AMD_FLIGHT_STATS MODIFY 
  TAIL_NO NOT NULL DISABLE;

ALTER TABLE AMD_FLIGHT_STATS MODIFY 
  TIME_PERIOD NOT NULL DISABLE;

ALTER TABLE AMD_FLIGHT_STATS MODIFY 
  UOM NOT NULL DISABLE;

ALTER TABLE AMD_FLIGHT_STATS ADD (
  CHECK ("UOM_VALUE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_FLIGHT_STATS ADD (
  CONSTRAINT AMD_FLIGHT_STATS_PK
 PRIMARY KEY
 (UOM, BASE, FSL, TAIL_NO, TIME_PERIOD));


ALTER TABLE AMD_FORCASTED_AC_USAGES MODIFY 
  FORECAST_NAME NOT NULL DISABLE;

ALTER TABLE AMD_FORCASTED_AC_USAGES MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_FORCASTED_AC_USAGES MODIFY 
  UOM_CODE NOT NULL DISABLE;

ALTER TABLE AMD_FORCASTED_AC_USAGES MODIFY 
  TIME_PERIOD_START NOT NULL DISABLE;

ALTER TABLE AMD_FORCASTED_AC_USAGES ADD (
  CHECK ("TIME_PERIOD_END" IS NOT NULL) DISABLE);

ALTER TABLE AMD_FORCASTED_AC_USAGES ADD (
  CHECK ("FORECAST_QTY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_FORCASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FORCASTED_AC_USAGES_PK
 PRIMARY KEY
 (FORECAST_NAME, LOC_SID, UOM_CODE, TIME_PERIOD_START));


ALTER TABLE AMD_FORECASTED_AC_USAGES MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_FORECASTED_AC_USAGES MODIFY 
  EFFECTIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_FORECASTED_AC_USAGES ADD (
  CHECK ("USAGE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_FORECASTED_AC_USAGES MODIFY 
  UOM_CODE NOT NULL DISABLE;

ALTER TABLE AMD_FORECASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FOR_AC_USAGES_PK
 PRIMARY KEY
 (LOC_SID, EFFECTIVE_DATE, UOM_CODE));


ALTER TABLE AMD_ICAOS MODIFY 
  ICAO NOT NULL DISABLE;

ALTER TABLE AMD_ICAOS MODIFY 
  LOCATION NOT NULL DISABLE;

ALTER TABLE AMD_ICAOS ADD (
  CONSTRAINT AMD_ICAOS_PK
 PRIMARY KEY
 (ICAO, LOCATION));


ALTER TABLE AMD_ICAO_REGIONS MODIFY 
  ICAO_REGION_ID NOT NULL DISABLE;

ALTER TABLE AMD_ICAO_REGIONS ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ICAO_REGIONS ADD (
  CONSTRAINT AMD_ICAO_REGIONS_PK
 PRIMARY KEY
 (ICAO_REGION_ID));


ALTER TABLE AMD_ICAO_XREF MODIFY 
  ICAO NOT NULL DISABLE;

ALTER TABLE AMD_ICAO_XREF ADD (
  CHECK ("LOCATION_NAME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ICAO_XREF ADD (
  CONSTRAINT AMD_ICAO_XREF_PK
 PRIMARY KEY
 (ICAO));


ALTER TABLE AMD_IN_REPAIR MODIFY 
  PART_NO NOT NULL DISABLE;

ALTER TABLE AMD_IN_REPAIR MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_IN_REPAIR MODIFY 
  REPAIR_DATE NOT NULL DISABLE;

ALTER TABLE AMD_IN_REPAIR MODIFY 
  REPAIR_TYPE NOT NULL DISABLE;

ALTER TABLE AMD_IN_REPAIR ADD (
  CHECK ("REPAIR_QTY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_IN_REPAIR ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_IN_REPAIR ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_IN_REPAIR ADD (
  CONSTRAINT AMD_IN_REPAIR_PK
 PRIMARY KEY
 (PART_NO, LOC_SID, REPAIR_DATE, REPAIR_TYPE));


ALTER TABLE AMD_IN_TRANSITS ADD (
  CHECK ("TO_LOC_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_IN_TRANSITS ADD (
  CHECK ("QUANTITY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_IN_TRANSITS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_IN_TRANSITS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_IN_TRANSITS MODIFY 
  DOCUMENT_ID NOT NULL;

ALTER TABLE AMD_IN_TRANSITS MODIFY 
  PART_NO NOT NULL;

ALTER TABLE AMD_IN_TRANSITS ADD (
  CONSTRAINT AMD_IN_TRANSITS_PK
 PRIMARY KEY
 (DOCUMENT_ID));


ALTER TABLE AMD_LOAD_DETAILS ADD (
  CHECK ("LOAD_NO" IS NOT NULL) DISABLE);


ALTER TABLE AMD_LOAD_STATUS ADD (
  CHECK ("LOAD_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_LOAD_STATUS ADD (
  CHECK ("SOURCE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_LOAD_STATUS ADD (
  CHECK ("LOAD_DATE" IS NOT NULL) DISABLE);


ALTER TABLE AMD_LTD_FLEET_SIZE_MEMBER MODIFY 
  FLEET_SIZE_NAME NOT NULL;

ALTER TABLE AMD_LTD_FLEET_SIZE_MEMBER MODIFY 
  TAIL_NO NOT NULL;

ALTER TABLE AMD_LTD_FLEET_SIZE_MEMBER ADD (
  CONSTRAINT AMD_FLEET_SIZE_MEMBER_PK
 PRIMARY KEY
 (FLEET_SIZE_NAME, TAIL_NO));


ALTER TABLE AMD_MAINT_TASK_DISTRIBS MODIFY 
  NSI_SID NOT NULL DISABLE;

ALTER TABLE AMD_MAINT_TASK_DISTRIBS MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_MAINT_TASK_DISTRIBS MODIFY 
  EFFECTIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_MAINT_TASK_DISTRIBS MODIFY 
  ACT_PROJ_IND NOT NULL DISABLE;

ALTER TABLE AMD_MAINT_TASK_DISTRIBS ADD (
  CONSTRAINT AMD_MAINT_TASK_DISTRIBS_PK
 PRIMARY KEY
 (NSI_SID, LOC_SID, EFFECTIVE_DATE, ACT_PROJ_IND));


ALTER TABLE AMD_MISSION_FLIGHTS MODIFY 
  MISSION_LEG NOT NULL DISABLE;

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("SCHED_DEPART_TIME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("ACTUAL_DEPART_TIME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("ACTUAL_ARRIVE_TIME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("TAIL_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("DEPARTURE_ICAO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("ARRIVAL_ICAO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("MISSION_TYPE_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS MODIFY 
  MISSION_ID NOT NULL DISABLE;

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CONSTRAINT AMD_MISSION_FLIGHTS_PK
 PRIMARY KEY
 (MISSION_LEG, MISSION_ID));


ALTER TABLE AMD_MISSION_TYPES MODIFY 
  MISSION_TYPE_CODE NOT NULL DISABLE;

ALTER TABLE AMD_MISSION_TYPES ADD (
  CHECK ("MISSION_TYPE_DESC" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_TYPES ADD (
  CONSTRAINT AMD_MISSION_TYPES_PK
 PRIMARY KEY
 (MISSION_TYPE_CODE));


ALTER TABLE AMD_NSI_LOC_DISTRIBS MODIFY 
  NSI_SID NOT NULL;

ALTER TABLE AMD_NSI_LOC_DISTRIBS MODIFY 
  LOC_SID NOT NULL;

ALTER TABLE AMD_NSI_LOC_DISTRIBS MODIFY 
  TIME_PERIOD_START NOT NULL;

ALTER TABLE AMD_NSI_LOC_DISTRIBS MODIFY 
  TIME_PERIOD_END NOT NULL;

ALTER TABLE AMD_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_NSI_LOC_DISTRIBS_PK
 PRIMARY KEY
 (NSI_SID, LOC_SID, TIME_PERIOD_START, TIME_PERIOD_END));


ALTER TABLE AMD_NSI_PARTS MODIFY 
  NSI_SID NOT NULL DISABLE;

ALTER TABLE AMD_NSI_PARTS MODIFY 
  ASSIGNMENT_DATE NOT NULL DISABLE;

ALTER TABLE AMD_NSI_PARTS MODIFY 
  PART_NO NOT NULL DISABLE;

ALTER TABLE AMD_NSI_PARTS ADD (
  CHECK ("PRIME_IND" IS NOT NULL) DISABLE);

ALTER TABLE AMD_NSI_PARTS ADD (
  CONSTRAINT AMD_NSI_PARTS_PK
 PRIMARY KEY
 (NSI_SID, ASSIGNMENT_DATE, PART_NO));


ALTER TABLE AMD_NSNS MODIFY 
  NSN NOT NULL DISABLE;

ALTER TABLE AMD_NSNS ADD (
  CHECK ("NSN_TYPE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_NSNS ADD (
  CHECK ("CREATION_DATE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_NSNS ADD (
  CONSTRAINT AMD_NSNS_PK
 PRIMARY KEY
 (NSN));


ALTER TABLE AMD_ON_BASE_REPAIR_COSTS ADD (
  CHECK ("PART_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ON_BASE_REPAIR_COSTS ADD (
  CHECK ("ON_BASE_REPAIR_COST" IS NOT NULL) DISABLE);


ALTER TABLE AMD_ON_HAND_INVS MODIFY 
  PART_NO NOT NULL DISABLE;

ALTER TABLE AMD_ON_HAND_INVS MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_ON_HAND_INVS MODIFY 
  INV_DATE NOT NULL DISABLE;

ALTER TABLE AMD_ON_HAND_INVS ADD (
  CHECK ("INV_QTY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ON_HAND_INVS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ON_HAND_INVS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ON_HAND_INVS ADD (
  CONSTRAINT AMD_ON_HAND_INVS_PK
 PRIMARY KEY
 (PART_NO, LOC_SID, INV_DATE));


ALTER TABLE AMD_ON_ORDER MODIFY 
  GOLD_ORDER_NUMBER NOT NULL DISABLE;

ALTER TABLE AMD_ON_ORDER ADD (
  CHECK ("PART_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ON_ORDER ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ON_ORDER ADD (
  CHECK ("SCHED_RECEIPT_DATE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ON_ORDER ADD (
  CHECK ("ORDER_QTY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ON_ORDER ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ON_ORDER ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ON_ORDER ADD (
  CONSTRAINT AMD_ON_ORDER_PK
 PRIMARY KEY
 (GOLD_ORDER_NUMBER));


ALTER TABLE AMD_PARAMS MODIFY 
  PARAM_KEY NOT NULL DISABLE;

ALTER TABLE AMD_PARAMS ADD (
  CONSTRAINT AMD_PARAMS_PK
 PRIMARY KEY
 (PARAM_KEY));


ALTER TABLE AMD_PARAM_CHANGES MODIFY 
  PARAM_KEY NOT NULL DISABLE;

ALTER TABLE AMD_PARAM_CHANGES MODIFY 
  EFFECTIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_PARAM_CHANGES ADD (
  CHECK ("USER_ID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PARAM_CHANGES ADD (
  CONSTRAINT AMD_PARAM_CHANGES_PK
 PRIMARY KEY
 (PARAM_KEY, EFFECTIVE_DATE));


ALTER TABLE AMD_PART_EFFECTIVITIES MODIFY 
  PN_NA_SID NOT NULL DISABLE;

ALTER TABLE AMD_PART_EFFECTIVITIES MODIFY 
  TAIL_NO NOT NULL DISABLE;

ALTER TABLE AMD_PART_EFFECTIVITIES ADD (
  CONSTRAINT AMD_PART_EFF_PK
 PRIMARY KEY
 (PN_NA_SID, TAIL_NO));


ALTER TABLE AMD_PART_LOCATIONS MODIFY 
  NSN NOT NULL DISABLE;

ALTER TABLE AMD_PART_LOCATIONS MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_PART_LOCATIONS ADD (
  CONSTRAINT AMD_PART_LOCATIONS_PK
 PRIMARY KEY
 (NSN, LOC_SID));


ALTER TABLE AMD_PART_LOCS MODIFY 
  NSI_SID NOT NULL DISABLE;

ALTER TABLE AMD_PART_LOCS MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_PART_LOCS ADD (
  CHECK ("TACTICAL" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOCS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOCS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOCS ADD (
  CONSTRAINT AMD_PART_LOCS_PK
 PRIMARY KEY
 (NSI_SID, LOC_SID));


ALTER TABLE AMD_PART_LOC_FORECASTS MODIFY 
  FORECAST_NAME NOT NULL DISABLE;

ALTER TABLE AMD_PART_LOC_FORECASTS MODIFY 
  NSI_SID NOT NULL DISABLE;

ALTER TABLE AMD_PART_LOC_FORECASTS MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_PART_LOC_FORECASTS MODIFY 
  TIME_PERIOD_START NOT NULL DISABLE;

ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CHECK ("TIME_PERIOD_END" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CHECK ("FORECAST_QTY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CONSTRAINT AMD_PART_LOC_FORECASTS_PK
 PRIMARY KEY
 (FORECAST_NAME, NSI_SID, LOC_SID, TIME_PERIOD_START));


ALTER TABLE AMD_PART_LOC_TIME_PERIODS MODIFY 
  NSI_SID NOT NULL DISABLE;

ALTER TABLE AMD_PART_LOC_TIME_PERIODS MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_PART_LOC_TIME_PERIODS MODIFY 
  TIME_PERIOD_START NOT NULL DISABLE;

ALTER TABLE AMD_PART_LOC_TIME_PERIODS ADD (
  CHECK ("TIME_PERIOD_END" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_TIME_PERIODS ADD (
  CHECK ("REORDER_POINT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_TIME_PERIODS ADD (
  CHECK ("REORDER_QUANTITY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_TIME_PERIODS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_TIME_PERIODS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_TIME_PERIODS ADD (
  CONSTRAINT AMD_PART_LOC_TIME_PERIODS_PK
 PRIMARY KEY
 (NSI_SID, LOC_SID, TIME_PERIOD_START));


ALTER TABLE AMD_PART_NEXT_ASSEMBLIES MODIFY 
  PN_NA_SID NOT NULL DISABLE;

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CHECK ("NEXT_ASSEMBLY_PART_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CHECK ("NEXT_ASSEMBLY_CAGE_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CHECK ("COMPONENT_PART_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CHECK ("COMPONENT_MFGR" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CONSTRAINT AMD_PART_NEXT_ASSM_PK
 PRIMARY KEY
 (PN_NA_SID));

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CONSTRAINT AMD_PART_NEXT_ASSEMBLIES_PK2
 UNIQUE (COMPONENT_PART_NO, COMPONENT_MFGR, NEXT_ASSEMBLY_PART_NO, NEXT_ASSEMBLY_CAGE_CODE));


ALTER TABLE AMD_PLANNERS MODIFY 
  PLANNER_CODE NOT NULL DISABLE;

ALTER TABLE AMD_PLANNERS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PLANNERS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PLANNERS ADD (
  CONSTRAINT AMD_PLANNERS_PK
 PRIMARY KEY
 (PLANNER_CODE));


ALTER TABLE AMD_PLANNER_LOGONS MODIFY 
  PLANNER_CODE NOT NULL DISABLE;

ALTER TABLE AMD_PLANNER_LOGONS MODIFY 
  LOGON_ID NOT NULL DISABLE;

ALTER TABLE AMD_PLANNER_LOGONS ADD (
  CONSTRAINT AMD_PLANNER_LOGONS_PK
 PRIMARY KEY
 (PLANNER_CODE, LOGON_ID));


ALTER TABLE AMD_PRODUCT_MODELS MODIFY 
  MODEL_ID NOT NULL DISABLE;

ALTER TABLE AMD_PRODUCT_MODELS ADD (
  CONSTRAINT AMD_PRODUCT_MODELS_PK
 PRIMARY KEY
 (MODEL_ID));


ALTER TABLE AMD_PRODUCT_STRUCTURE MODIFY 
  ASSY_NSI_SID NOT NULL;

ALTER TABLE AMD_PRODUCT_STRUCTURE MODIFY 
  COMP_NSI_SID NOT NULL;

ALTER TABLE AMD_PRODUCT_STRUCTURE ADD (
  CONSTRAINT AMD_PRODUCT_STRUCTURE_PK
 PRIMARY KEY
 (ASSY_NSI_SID, COMP_NSI_SID));


ALTER TABLE AMD_PROJECTED_AC_USAGES MODIFY 
  EFFECTIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_PROJECTED_AC_USAGES ADD (
  CHECK ("USAGE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PROJECTED_AC_USAGES MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_PROJECTED_AC_USAGES MODIFY 
  UOM_CODE NOT NULL DISABLE;

ALTER TABLE AMD_PROJECTED_AC_USAGES ADD (
  CONSTRAINT AMD_PROJ_AC_USAGES_PK
 PRIMARY KEY
 (LOC_SID, EFFECTIVE_DATE, UOM_CODE));


ALTER TABLE AMD_REQS MODIFY 
  REQ_ID NOT NULL DISABLE;

ALTER TABLE AMD_REQS ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("NSI_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("QUANTITY_ORDERED" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("QUANTITY_DUE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("NEED_DATE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("PRIORITY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CONSTRAINT AMD_REQS_PK
 PRIMARY KEY
 (REQ_ID));


ALTER TABLE AMD_RETROFIT_SCHEDULES MODIFY 
  TCTO_NUMBER NOT NULL;

ALTER TABLE AMD_RETROFIT_SCHEDULES MODIFY 
  TAIL_NO NOT NULL;

ALTER TABLE AMD_RETROFIT_SCHEDULES ADD (
  CONSTRAINT AMD_RETROFIT_SCHEDULES_PK
 PRIMARY KEY
 (TCTO_NUMBER, TAIL_NO));


ALTER TABLE AMD_RETROFIT_SCHED_BLOCKS MODIFY 
  BLOCK_NAME NOT NULL;

ALTER TABLE AMD_RETROFIT_SCHED_BLOCKS MODIFY 
  BLOCK_DESC NOT NULL;

ALTER TABLE AMD_RETROFIT_SCHED_BLOCKS ADD (
  CONSTRAINT AMD_RETROFIT_SCHED_BLOCKS_PK
 PRIMARY KEY
 (BLOCK_NAME));


ALTER TABLE AMD_RETROFIT_TCTOS MODIFY 
  TCTO_NUMBER NOT NULL;

ALTER TABLE AMD_RETROFIT_TCTOS MODIFY 
  TCTO_DESC NOT NULL;

ALTER TABLE AMD_RETROFIT_TCTOS ADD (
  CONSTRAINT AMD_TCTOS_PK
 PRIMARY KEY
 (TCTO_NUMBER));


ALTER TABLE AMD_RMADS_SOURCE_TMP MODIFY 
  PART_NO NOT NULL;

ALTER TABLE AMD_RMADS_SOURCE_TMP ADD (
  CONSTRAINT AMD_RMADS_SOURCE_TMP_PK
 PRIMARY KEY
 (PART_NO));


ALTER TABLE AMD_SHELF_LIFE_CODES MODIFY 
  SL_CODE NOT NULL DISABLE;

ALTER TABLE AMD_SHELF_LIFE_CODES ADD (
  CHECK ("STORAGE_DAYS" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SHELF_LIFE_CODES ADD (
  CONSTRAINT AMD_SHELF_LIFE_CODES_PK
 PRIMARY KEY
 (SL_CODE));


ALTER TABLE AMD_SPARE_NETWORKS ADD (
  CHECK ("LOCATION_NAME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_NETWORKS MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_SPARE_NETWORKS ADD (
  CHECK ("LOC_ID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_NETWORKS ADD (
  CHECK ("LOC_TYPE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_NETWORKS ADD (
  CHECK ("TACTICAL" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_NETWORKS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_NETWORKS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_NETWORKS ADD (
  CONSTRAINT AMD_SPARE_NET_PK
 PRIMARY KEY
 (LOC_SID));

ALTER TABLE AMD_SPARE_NETWORKS ADD (
  CONSTRAINT AMD_SPARE_NETWORKS_AK2
 UNIQUE (ICAO));

ALTER TABLE AMD_SPARE_NETWORKS ADD (
  CONSTRAINT AMD_SPARE_NETWORKS_PK2
 UNIQUE (LOC_ID, LOC_TYPE));


ALTER TABLE AMD_SPARE_PARTS MODIFY 
  PART_NO NOT NULL DISABLE;

ALTER TABLE AMD_SPARE_PARTS ADD (
  CHECK ("ICP_IND" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_PARTS ADD (
  CHECK ("NOMENCLATURE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_PARTS ADD (
  CHECK ("TACTICAL" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_PARTS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_PARTS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_PARTS ADD (
  CONSTRAINT AMD_SPARE_PARTS_PK
 PRIMARY KEY
 (PART_NO));


ALTER TABLE AMD_STORAGE_COSTS MODIFY 
  EFFECTIVE_DATE NOT NULL DISABLE;

ALTER TABLE AMD_STORAGE_COSTS MODIFY 
  LOC_SID NOT NULL DISABLE;

ALTER TABLE AMD_STORAGE_COSTS ADD (
  CONSTRAINT AMD_STORAGE_COSTS_PK
 PRIMARY KEY
 (LOC_SID, EFFECTIVE_DATE));


ALTER TABLE AMD_TIME_PERIODS MODIFY 
  TIME_PERIOD_START NOT NULL DISABLE;

ALTER TABLE AMD_TIME_PERIODS MODIFY 
  TIME_PERIOD_END NOT NULL DISABLE;

ALTER TABLE AMD_TIME_PERIODS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_TIME_PERIODS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_TIME_PERIODS ADD (
  CONSTRAINT AMD_TIME_PERIODS_PK
 PRIMARY KEY
 (TIME_PERIOD_START, TIME_PERIOD_END));

ALTER TABLE AMD_TIME_PERIODS ADD (
  CONSTRAINT AMD_TIME_PERIODS_UC01
 UNIQUE (TACTICAL_BUCKET_NAME, TACTICAL_BUCKET_ID));


ALTER TABLE AMD_TRANSPORT_MODES MODIFY 
  TRANSPORT_AGENT_ID NOT NULL DISABLE;

ALTER TABLE AMD_TRANSPORT_MODES MODIFY 
  TRANSPORT_MODE_ID NOT NULL DISABLE;

ALTER TABLE AMD_TRANSPORT_MODES ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_TRANSPORT_MODES ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_TRANSPORT_MODES ADD (
  CONSTRAINT AMD_TRANSPORT_MODES_PK
 PRIMARY KEY
 (TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID));


ALTER TABLE AMD_UOMS MODIFY 
  UOM_CODE NOT NULL DISABLE;

ALTER TABLE AMD_UOMS ADD (
  CHECK ("UOM_TERM" IS NOT NULL) DISABLE);

ALTER TABLE AMD_UOMS ADD (
  CONSTRAINT AMD_UOMS_PK
 PRIMARY KEY
 (UOM_CODE));

ALTER TABLE AMD_UOMS ADD (
  CONSTRAINT AMD_UOMS_UC01
 UNIQUE (UOM_TERM));


ALTER TABLE CAT1 MODIFY 
  PART NOT NULL DISABLE;

ALTER TABLE CAT1 ADD (
  CHECK ("NSN" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("NOUN" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("PRIME" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("UM_SHOW_CODE" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("UM_ISSUE_CODE" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("UM_TURN_CODE" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("UM_DISP_CODE" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("UM_CAP_CODE" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("UM_MIL_CODE" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("ASSET_REQ_ON_RECEIPT" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("RECORD_CHANGED1_YN" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("RECORD_CHANGED2_YN" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("RECORD_CHANGED3_YN" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("RECORD_CHANGED4_YN" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("RECORD_CHANGED5_YN" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("RECORD_CHANGED6_YN" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("RECORD_CHANGED7_YN" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CHECK ("RECORD_CHANGED8_YN" IS NOT NULL) DISABLE);

ALTER TABLE CAT1 ADD (
  CONSTRAINT CAT1P1
 PRIMARY KEY
 (PART));


ALTER TABLE CHGH ADD (
  CHECK ("CHGH_ID" IS NOT NULL) DISABLE);


ALTER TABLE FEDC MODIFY 
  PART_NUMBER NOT NULL DISABLE;

ALTER TABLE FEDC MODIFY 
  VENDOR_CODE NOT NULL DISABLE;

ALTER TABLE FEDC MODIFY 
  SEQ_NUMBER NOT NULL DISABLE;

ALTER TABLE FEDC ADD (
  CONSTRAINT FEDCP1
 PRIMARY KEY
 (PART_NUMBER, VENDOR_CODE, SEQ_NUMBER));


ALTER TABLE ITEM MODIFY 
  ITEM_ID NOT NULL DISABLE;

ALTER TABLE ITEM ADD (
  CHECK ("RECEIVED_ITEM_ID" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("SC" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("PART" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("PRIME" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("CONDITION" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("STATUS_DEL_WHEN_GONE" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("STATUS_SERVICABLE" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("STATUS_NEW_ORDER" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("STATUS_ACCOUNTABLE" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("STATUS_AVAIL" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("STATUS_FROZEN" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("STATUS_ACTIVE" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("STATUS_MAI" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("STATUS_2" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CHECK ("STATUS_3" IS NOT NULL) DISABLE);

ALTER TABLE ITEM ADD (
  CONSTRAINT ITEMP1
 PRIMARY KEY
 (ITEM_ID));


ALTER TABLE MILS MODIFY 
  MILS_ID NOT NULL DISABLE;

ALTER TABLE MILS ADD (
  CHECK ("REC_TYPES" IS NOT NULL) DISABLE);

ALTER TABLE MILS ADD (
  CHECK ("CREATED_DATETIME" IS NOT NULL) DISABLE);

ALTER TABLE MILS ADD (
  CONSTRAINT MILSP1
 PRIMARY KEY
 (MILS_ID));


ALTER TABLE MLIT MODIFY 
  DOCUMENT_ID NOT NULL;

ALTER TABLE MLIT MODIFY 
  CUSTOMER NOT NULL;

ALTER TABLE MLIT MODIFY 
  MILS_ACTIVITY NOT NULL;

ALTER TABLE MLIT MODIFY 
  MILS_OWNERSHIP_CODE NOT NULL;

ALTER TABLE MLIT MODIFY 
  MILS_PROFILE NOT NULL;

ALTER TABLE MLIT MODIFY 
  IN_TRAN_FROM NOT NULL;

ALTER TABLE MLIT MODIFY 
  IN_TRAN_TO NOT NULL;

ALTER TABLE MLIT MODIFY 
  IN_TRAN_TYPE NOT NULL;

ALTER TABLE MLIT MODIFY 
  PART NOT NULL;

ALTER TABLE MLIT MODIFY 
  CREATE_DATE NOT NULL;

ALTER TABLE MLIT MODIFY 
  MILS_CONDITION NOT NULL;

ALTER TABLE MLIT MODIFY 
  STATUS_IND NOT NULL;

ALTER TABLE MLIT ADD (
  CONSTRAINT MLITP1
 PRIMARY KEY
 (DOCUMENT_ID));


ALTER TABLE ORD1 MODIFY 
  ORDER_NO NOT NULL DISABLE;

ALTER TABLE ORD1 ADD (
  CHECK ("ORDER_TYPE" IS NOT NULL) DISABLE);

ALTER TABLE ORD1 ADD (
  CHECK ("SC" IS NOT NULL) DISABLE);

ALTER TABLE ORD1 ADD (
  CHECK ("PART" IS NOT NULL) DISABLE);

ALTER TABLE ORD1 ADD (
  CONSTRAINT ORD1P1
 PRIMARY KEY
 (ORDER_NO));


ALTER TABLE POI1 MODIFY 
  ORDER_NO NOT NULL DISABLE;

ALTER TABLE POI1 MODIFY 
  SEQ NOT NULL DISABLE;

ALTER TABLE POI1 MODIFY 
  ITEM NOT NULL DISABLE;

ALTER TABLE POI1 ADD (
  CHECK ("QTY" IS NOT NULL) DISABLE);

ALTER TABLE POI1 ADD (
  CHECK ("ITEM_LINE" IS NOT NULL) DISABLE);

ALTER TABLE POI1 ADD (
  CONSTRAINT POI1P1
 PRIMARY KEY
 (ORDER_NO, SEQ, ITEM));


ALTER TABLE PRC1 MODIFY 
  SC NOT NULL;

ALTER TABLE PRC1 MODIFY 
  PART NOT NULL;

ALTER TABLE PRC1 ADD (
  CONSTRAINT PRC1P1
 PRIMARY KEY
 (SC, PART));


ALTER TABLE RAMP MODIFY 
  NSN NOT NULL DISABLE;

ALTER TABLE RAMP MODIFY 
  SC NOT NULL DISABLE;

ALTER TABLE RAMP ADD (
  CONSTRAINT RAMPP1
 PRIMARY KEY
 (NSN, SC));


ALTER TABLE REQ1 ADD (
  CHECK ("REQUEST_ID" IS NOT NULL) DISABLE);

ALTER TABLE REQ1 ADD (
  CHECK ("STATUS" IS NOT NULL) DISABLE);

ALTER TABLE REQ1 ADD (
  CHECK ("ALLOW_ALTS_YN" IS NOT NULL) DISABLE);


ALTER TABLE RSV1 ADD (
  CHECK ("RESERVE_ID" IS NOT NULL) DISABLE);

ALTER TABLE RSV1 ADD (
  CHECK ("FORM_REQUIRED_YN" IS NOT NULL) DISABLE);

ALTER TABLE RSV1 ADD (
  CHECK ("REMARK_MOVE_ONLY_YN" IS NOT NULL) DISABLE);


ALTER TABLE TEMP_AMD_BASE_PART_SES ADD (
  CHECK ("NSN" IS NOT NULL) DISABLE);

ALTER TABLE TEMP_AMD_BASE_PART_SES ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);


ALTER TABLE TEMP_AMD_PART_USAGES ADD (
  CHECK ("COMPONENT_PART_NO" IS NOT NULL) DISABLE);

ALTER TABLE TEMP_AMD_PART_USAGES ADD (
  CHECK ("COMPONENT_MFGR" IS NOT NULL) DISABLE);

ALTER TABLE TEMP_AMD_PART_USAGES ADD (
  CHECK ("NEXT_ASSEMBLY_PART_NO" IS NOT NULL) DISABLE);

ALTER TABLE TEMP_AMD_PART_USAGES ADD (
  CHECK ("NEXT_ASSEMBLY_CAGE_CODE" IS NOT NULL) DISABLE);

ALTER TABLE TEMP_AMD_PART_USAGES ADD (
  CHECK ("WUC" IS NOT NULL) DISABLE);


ALTER TABLE TMP1 ADD (
  CHECK ("TEMP_OUT_ID" IS NOT NULL) DISABLE);


ALTER TABLE TMP_AMD_NSN_WUC_XREFS ADD (
  CHECK ("NSN" IS NOT NULL) DISABLE);

ALTER TABLE TMP_AMD_NSN_WUC_XREFS ADD (
  CHECK ("WUC" IS NOT NULL) DISABLE);


ALTER TABLE TMP_AMD_PLANNER_PARTS ADD (
  CHECK ("PLANNER_CODE" IS NOT NULL) DISABLE);

ALTER TABLE TMP_AMD_PLANNER_PARTS ADD (
  CHECK ("MFGR" IS NOT NULL) DISABLE);

ALTER TABLE TMP_AMD_PLANNER_PARTS ADD (
  CHECK ("PART_NO" IS NOT NULL) DISABLE);


ALTER TABLE TMP_AMD_SPARE_PARTS MODIFY 
  PART_NO NOT NULL;

ALTER TABLE TMP_AMD_SPARE_PARTS MODIFY 
  ICP_IND NOT NULL;

ALTER TABLE TMP_AMD_SPARE_PARTS MODIFY 
  NOMENCLATURE NOT NULL;

ALTER TABLE TMP_AMD_SPARE_PARTS MODIFY 
  LAST_UPDATE_DT NOT NULL;


ALTER TABLE VENC MODIFY 
  PART NOT NULL DISABLE;

ALTER TABLE VENC MODIFY 
  SEQ NOT NULL DISABLE;

ALTER TABLE VENC ADD (
  CHECK ("VENDOR_CODE" IS NOT NULL) DISABLE);

ALTER TABLE VENC ADD (
  CONSTRAINT VENCP1
 PRIMARY KEY
 (PART, SEQ));


ALTER TABLE VENN MODIFY 
  VENDOR_CODE NOT NULL DISABLE;

ALTER TABLE VENN ADD (
  CHECK ("VENDOR_NAME" IS NOT NULL) DISABLE);

ALTER TABLE VENN ADD (
  CONSTRAINT VENNP1
 PRIMARY KEY
 (VENDOR_CODE));


ALTER TABLE AMD_ISGP MODIFY 
  SC NOT NULL;

ALTER TABLE AMD_ISGP MODIFY 
  PART NOT NULL;

ALTER TABLE AMD_ISGP MODIFY 
  GROUP_NO NOT NULL;

ALTER TABLE AMD_ISGP ADD (
  CONSTRAINT AMD_ISGP_PK
 PRIMARY KEY
 (SC, PART, GROUP_NO));


ALTER TABLE AMD_USE1 MODIFY 
  USERID NOT NULL;

ALTER TABLE AMD_USE1 MODIFY 
  USER_NAME NOT NULL;

ALTER TABLE AMD_USE1 ADD (
  CONSTRAINT AMD_USE1_PK
 PRIMARY KEY
 (USERID));

ALTER TABLE AMD_USE1 ADD (
  CONSTRAINT AMD_USE1_UK01
 UNIQUE (EMPLOYEE_NO));


ALTER TABLE AMD_ACMII MODIFY 
  NSN NOT NULL;

ALTER TABLE AMD_ACMII MODIFY 
  SRAN NOT NULL;

ALTER TABLE AMD_ACMII ADD (
  CONSTRAINT AMD_ACMII_PK
 PRIMARY KEY
 (NSN, SRAN));


ALTER TABLE NSN1 MODIFY 
  NSN NOT NULL;


ALTER TABLE AMD_L67_SOURCE ADD (
  CONSTRAINT AMD_L67_SOURCE_PK
 PRIMARY KEY
 (NSN, DOC_NO, TRANS_DATE, TRANS_SER, SRAN));


ALTER TABLE AMD_TAV_LOCATIONS ADD (
  CONSTRAINT AMD_TAV_LOCATIONS_PK
 PRIMARY KEY
 (SRAN));


ALTER TABLE AMD_CUR_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_CUR_NSI_LOC_DISTRIBS_FK01 
 FOREIGN KEY (NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));

ALTER TABLE AMD_CUR_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_CUR_NSI_LOC_DISTRIBS_FK02 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK01 
 FOREIGN KEY (NSN) 
 REFERENCES AMD_NSNS (NSN));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK02 
 FOREIGN KEY (PRIME_PART_NO) 
 REFERENCES AMD_SPARE_PARTS (PART_NO));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK03 
 FOREIGN KEY (PLANNER_CODE) 
 REFERENCES AMD_PLANNERS (PLANNER_CODE));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK04 
 FOREIGN KEY (PLANNER_CODE_CLEANED) 
 REFERENCES AMD_PLANNERS (PLANNER_CODE));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK05 
 FOREIGN KEY (DISTRIB_UOM) 
 REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK06 
 FOREIGN KEY (DISTRIB_UOM_DEFAULTED) 
 REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK07 
 FOREIGN KEY (ORDER_UOM_CLEANED) 
 REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK09 
 FOREIGN KEY (NSI_GROUP_SID) 
 REFERENCES AMD_NSI_GROUPS (NSI_GROUP_SID));


ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECTS_FK01 
 FOREIGN KEY (NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));

ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECTS_FK02 
 FOREIGN KEY (TAIL_NO) 
 REFERENCES AMD_AIRCRAFTS (TAIL_NO));


ALTER TABLE AMD_NSI_GROUPS ADD (
  CONSTRAINT AMD_NSI_GROUPS_FK01 
 FOREIGN KEY (FLEET_SIZE_NAME) 
 REFERENCES AMD_FLEET_SIZES (FLEET_SIZE_NAME));


ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_NSI_PAIRS_FK01 
 FOREIGN KEY (REPLACED_NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));

ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_NSI_PAIRS_FK02 
 FOREIGN KEY (REPLACED_BY_NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));

ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_NSI_PAIRS_FK03 
 FOREIGN KEY (TCTO_NUMBER) 
 REFERENCES AMD_RETROFIT_TCTOS (TCTO_NUMBER));


ALTER TABLE AMD_SPARE_PIPELINES ADD (
  CONSTRAINT AMD_SPARE_PIPELINES_FK01 
 FOREIGN KEY (FROM_LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID)
    ON DELETE CASCADE);

ALTER TABLE AMD_SPARE_PIPELINES ADD (
  CONSTRAINT AMD_SPARE_PIPELINES_FK02 
 FOREIGN KEY (TO_LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID)
    ON DELETE CASCADE);

ALTER TABLE AMD_SPARE_PIPELINES ADD (
  CONSTRAINT AMD_SPARE_PIPELINES_FK03 
 FOREIGN KEY (TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID) 
 REFERENCES AMD_TRANSPORT_MODES (TRANSPORT_AGENT_ID,TRANSPORT_MODE_ID));


ALTER TABLE AMD_ACTUAL_AC_USAGES ADD (
  CONSTRAINT AMD_ACTUAL_AC_USAGES_FK01 
 FOREIGN KEY (TAIL_NO) 
 REFERENCES AMD_AIRCRAFTS (TAIL_NO));

ALTER TABLE AMD_ACTUAL_AC_USAGES ADD (
  CONSTRAINT AMD_ACTUAL_AC_USAGES_FK02 
 FOREIGN KEY (UOM_CODE) 
 REFERENCES AMD_UOMS (UOM_CODE));


ALTER TABLE AMD_ACTUAL_PERFORMANCES ADD (
  CONSTRAINT ACT_PERF__AMD_UOMS_FK 
 FOREIGN KEY (UOM_CODE) 
 REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_ACTUAL_PERFORMANCES ADD (
  CONSTRAINT ACT_PERF__FK 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


ALTER TABLE AMD_AC_ASSIGNS ADD (
  CONSTRAINT AMD_AC_ASSIGNS_FK01 
 FOREIGN KEY (TAIL_NO) 
 REFERENCES AMD_AIRCRAFTS (TAIL_NO));

ALTER TABLE AMD_AC_ASSIGNS ADD (
  CONSTRAINT AMD_AC_ASSIGNS_FK02 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


ALTER TABLE AMD_AIRCRAFTS ADD (
  CONSTRAINT AMD_AIRCRAFTS_FK01 
 FOREIGN KEY (MODEL_ID) 
 REFERENCES AMD_PRODUCT_MODELS (MODEL_ID));


ALTER TABLE AMD_AWARD_FEES ADD (
  CONSTRAINT AWARD__FK 
 FOREIGN KEY (UOM_CODE) 
 REFERENCES AMD_UOMS (UOM_CODE));


ALTER TABLE AMD_AWARD_FEE_SCHDS ADD (
  CONSTRAINT FEESCHD_AWARD_FK 
 FOREIGN KEY (UOM_CODE, EFFECTIVE_DATE) 
 REFERENCES AMD_AWARD_FEES (UOM_CODE,EFFECTIVE_DATE));


ALTER TABLE AMD_BODS ADD (
  CONSTRAINT AMD_BODS_FK01 
 FOREIGN KEY (FROM_LOC_SID, TO_LOC_SID, TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID) 
 REFERENCES AMD_SPARE_PIPELINES (FROM_LOC_SID,TO_LOC_SID,TRANSPORT_AGENT_ID,TRANSPORT_MODE_ID)
    ON DELETE CASCADE);

ALTER TABLE AMD_BODS ADD (
  CONSTRAINT AMD_BODS_FK02 
 FOREIGN KEY (NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID)
    ON DELETE CASCADE);


ALTER TABLE AMD_CALENDAR_EXCEPTIONS ADD (
  CONSTRAINT AMD_CALENDAR_EXCEPTIONS_FK01 
 FOREIGN KEY (CALENDAR_NAME) 
 REFERENCES AMD_CALENDARS (CALENDAR_NAME)
    ON DELETE CASCADE);


ALTER TABLE AMD_DEMANDS ADD (
  CONSTRAINT AMD_DEMANDS_FK01 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_DEMANDS ADD (
  CONSTRAINT AMD_DEMANDS_FK02 
 FOREIGN KEY (NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));


ALTER TABLE AMD_FLIGHT_STATS ADD (
  CONSTRAINT AMD_FLIGHT_STATS_FK01 
 FOREIGN KEY (TAIL_NO) 
 REFERENCES AMD_AIRCRAFTS (TAIL_NO));

ALTER TABLE AMD_FLIGHT_STATS ADD (
  CONSTRAINT AMD_FLIGHT_STATS_FK02 
 FOREIGN KEY (BASE) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_FLIGHT_STATS ADD (
  CONSTRAINT AMD_FLIGHT_STATS_FK03 
 FOREIGN KEY (FSL) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


ALTER TABLE AMD_FORCASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FORCASTED_AC_USAGES_FK01 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_FORCASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FORCASTED_AC_USAGES_FK02 
 FOREIGN KEY (UOM_CODE) 
 REFERENCES AMD_UOMS (UOM_CODE));


ALTER TABLE AMD_FORECASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FOR__AMD_UOM_FK01_FK 
 FOREIGN KEY (UOM_CODE) 
 REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_FORECASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FOR__FK 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


ALTER TABLE AMD_ICAOS ADD (
  CONSTRAINT AMD_ICAOS_FK01 
 FOREIGN KEY (ICAO) 
 REFERENCES AMD_ICAO_XREF (ICAO) DISABLE);


ALTER TABLE AMD_ICAO_REGIONS ADD (
  CONSTRAINT AMD_ICAO_REGIONS_FK01 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


ALTER TABLE AMD_IN_REPAIR ADD (
  CONSTRAINT AMD_IN_REPAIR_FK01 
 FOREIGN KEY (PART_NO) 
 REFERENCES AMD_SPARE_PARTS (PART_NO));

ALTER TABLE AMD_IN_REPAIR ADD (
  CONSTRAINT AMD_IN_REPAIR_FK02 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


ALTER TABLE AMD_LTD_FLEET_SIZE_MEMBER ADD (
  CONSTRAINT AMD_LTD_FLEET_SIZE_MEMBER_FK01 
 FOREIGN KEY (FLEET_SIZE_NAME) 
 REFERENCES AMD_FLEET_SIZES (FLEET_SIZE_NAME));

ALTER TABLE AMD_LTD_FLEET_SIZE_MEMBER ADD (
  CONSTRAINT AMD_LTD_FLEET_SIZE_MEMBER_FK02 
 FOREIGN KEY (TAIL_NO) 
 REFERENCES AMD_AIRCRAFTS (TAIL_NO));


ALTER TABLE AMD_MAINT_TASK_DISTRIBS ADD (
  CONSTRAINT AMD_MAINT_TASK_DISTRIBS_FK01 
 FOREIGN KEY (NSI_SID, LOC_SID) 
 REFERENCES AMD_PART_LOCS (NSI_SID,LOC_SID));


ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CONSTRAINT AMD_MISSION_FLIGHTS_FK1 
 FOREIGN KEY (MISSION_TYPE_CODE) 
 REFERENCES AMD_MISSION_TYPES (MISSION_TYPE_CODE));

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CONSTRAINT AMD_MISSION_FLIGHTS_FK2 
 FOREIGN KEY (TAIL_NO) 
 REFERENCES AMD_AIRCRAFTS (TAIL_NO) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CONSTRAINT AMD_MISSION_FLIGHTS_FK3 
 FOREIGN KEY (DEPARTURE_ICAO) 
 REFERENCES AMD_AIRPORTS (ICAO));

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CONSTRAINT AMD_MISSION_FLIGHTS_FK4 
 FOREIGN KEY (ARRIVAL_ICAO) 
 REFERENCES AMD_AIRPORTS (ICAO));


ALTER TABLE AMD_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_NSI_LOC_DISTRIBS_FK01 
 FOREIGN KEY (NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));

ALTER TABLE AMD_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_NSI_LOC_DISTRIBS_FK02 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_NSI_LOC_DISTRIBS_FK03 
 FOREIGN KEY (TIME_PERIOD_START, TIME_PERIOD_END) 
 REFERENCES AMD_TIME_PERIODS (TIME_PERIOD_START,TIME_PERIOD_END));


ALTER TABLE AMD_NSI_PARTS ADD (
  CONSTRAINT AMD_NSI_PARTS_FK01 
 FOREIGN KEY (NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID)
    ON DELETE CASCADE);

ALTER TABLE AMD_NSI_PARTS ADD (
  CONSTRAINT AMD_NSI_PARTS_FK02 
 FOREIGN KEY (PART_NO) 
 REFERENCES AMD_SPARE_PARTS (PART_NO));


ALTER TABLE AMD_NSNS ADD (
  CONSTRAINT AMD_NSNS_FK01 
 FOREIGN KEY (NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));


ALTER TABLE AMD_ON_HAND_INVS ADD (
  CONSTRAINT AMD_ON_HAND_INVS_FK01 
 FOREIGN KEY (PART_NO) 
 REFERENCES AMD_SPARE_PARTS (PART_NO));

ALTER TABLE AMD_ON_HAND_INVS ADD (
  CONSTRAINT AMD_ON_HAND_INVS_FK02 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


ALTER TABLE AMD_ON_ORDER ADD (
  CONSTRAINT AMD_ON_ORDER_FK01 
 FOREIGN KEY (PART_NO) 
 REFERENCES AMD_SPARE_PARTS (PART_NO));

ALTER TABLE AMD_ON_ORDER ADD (
  CONSTRAINT AMD_ON_ORDER_FK02 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


ALTER TABLE AMD_PARAM_CHANGES ADD (
  CONSTRAINT AMD_PARAM_CHANGES_FK01 
 FOREIGN KEY (PARAM_KEY) 
 REFERENCES AMD_PARAMS (PARAM_KEY));


ALTER TABLE AMD_PART_EFFECTIVITIES ADD (
  CONSTRAINT AMD_PART_EFFECTIVITIES_FK01 
 FOREIGN KEY (PN_NA_SID) 
 REFERENCES AMD_PART_NEXT_ASSEMBLIES (PN_NA_SID));

ALTER TABLE AMD_PART_EFFECTIVITIES ADD (
  CONSTRAINT AMD_PART_EFFECTIVITIES_FK02 
 FOREIGN KEY (TAIL_NO) 
 REFERENCES AMD_AIRCRAFTS (TAIL_NO));


ALTER TABLE AMD_PART_LOCATIONS ADD (
  CONSTRAINT AMD_PART_LOCATIONS_FK02 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


ALTER TABLE AMD_PART_LOCS ADD (
  CONSTRAINT AMD_PART_LOCS_FK01 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_PART_LOCS ADD (
  CONSTRAINT AMD_PART_LOCS_FK02 
 FOREIGN KEY (NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));


ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CONSTRAINT AMD_PART_LOC_FORECASTS_FK01 
 FOREIGN KEY (NSI_SID, LOC_SID) 
 REFERENCES AMD_PART_LOCS (NSI_SID,LOC_SID));

ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CONSTRAINT AMD_PART_LOC_FORECASTS_FK02 
 FOREIGN KEY (TIME_PERIOD_START, TIME_PERIOD_END) 
 REFERENCES AMD_TIME_PERIODS (TIME_PERIOD_START,TIME_PERIOD_END));


ALTER TABLE AMD_PART_LOC_TIME_PERIODS ADD (
  CONSTRAINT AMD_PART_LOC_TIME_PERIODS_FK01 
 FOREIGN KEY (NSI_SID, LOC_SID) 
 REFERENCES AMD_PART_LOCS (NSI_SID,LOC_SID));


ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CONSTRAINT AMD_PART_NEXT_ASSEMBLIES_FK01 
 FOREIGN KEY (COMPONENT_PART_NO) 
 REFERENCES AMD_SPARE_PARTS (PART_NO));


ALTER TABLE AMD_PLANNERS ADD (
  CONSTRAINT AMD_PLANNERS_FK01 
 FOREIGN KEY (SUPERVISOR_CODE) 
 REFERENCES AMD_PLANNERS (PLANNER_CODE));


ALTER TABLE AMD_PLANNER_LOGONS ADD (
  CONSTRAINT AMD_PLANNER_LOGONS_FK01 
 FOREIGN KEY (PLANNER_CODE) 
 REFERENCES AMD_PLANNERS (PLANNER_CODE)
    ON DELETE CASCADE);


ALTER TABLE AMD_PRODUCT_STRUCTURE ADD (
  CONSTRAINT AMD_PRODUCT_STRUCTURE_FK01 
 FOREIGN KEY (ASSY_NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));

ALTER TABLE AMD_PRODUCT_STRUCTURE ADD (
  CONSTRAINT AMD_PRODUCT_STRUCTURE_FK02 
 FOREIGN KEY (COMP_NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));


ALTER TABLE AMD_PROJECTED_AC_USAGES ADD (
  CONSTRAINT AMD_PROJECTED_AC_USAGES_FK01 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_PROJECTED_AC_USAGES ADD (
  CONSTRAINT AMD_PROJECTED_AC_USAGES_FK02 
 FOREIGN KEY (UOM_CODE) 
 REFERENCES AMD_UOMS (UOM_CODE));


ALTER TABLE AMD_REQS ADD (
  CONSTRAINT AMD_REQS_FK01 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_REQS ADD (
  CONSTRAINT AMD_REQS_FK02 
 FOREIGN KEY (NSI_SID) 
 REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));


ALTER TABLE AMD_RETROFIT_SCHEDULES ADD (
  CONSTRAINT AMD_RETROFIT_SCHEDULES_FK01 
 FOREIGN KEY (TCTO_NUMBER) 
 REFERENCES AMD_RETROFIT_TCTOS (TCTO_NUMBER));

ALTER TABLE AMD_RETROFIT_SCHEDULES ADD (
  CONSTRAINT AMD_RETROFIT_SCHEDULES_FK02 
 FOREIGN KEY (TAIL_NO) 
 REFERENCES AMD_AIRCRAFTS (TAIL_NO));

ALTER TABLE AMD_RETROFIT_SCHEDULES ADD (
  CONSTRAINT AMD_RETROFIT_SCHEDULES_FK03 
 FOREIGN KEY (BLOCK_NAME) 
 REFERENCES AMD_RETROFIT_SCHED_BLOCKS (BLOCK_NAME));


ALTER TABLE AMD_SPARE_NETWORKS ADD (
  CONSTRAINT AMD_SPARE_NETWORKS_FK01 
 FOREIGN KEY (CALENDAR_NAME) 
 REFERENCES AMD_CALENDARS (CALENDAR_NAME));


ALTER TABLE AMD_SPARE_PARTS ADD (
  CONSTRAINT AMD_SPARE_PARTS_FK01 
 FOREIGN KEY (NSN) 
 REFERENCES AMD_NSNS (NSN));

ALTER TABLE AMD_SPARE_PARTS ADD (
  CONSTRAINT AMD_SPARE_PARTS_FK02 
 FOREIGN KEY (ORDER_UOM) 
 REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_SPARE_PARTS ADD (
  CONSTRAINT AMD_SPARE_PARTS_FK03 
 FOREIGN KEY (ORDER_UOM_DEFAULTED) 
 REFERENCES AMD_UOMS (UOM_CODE));


ALTER TABLE AMD_STORAGE_COSTS ADD (
  CONSTRAINT AMD_STORAGE_COSTS_FK01 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_SPARE_NETWORKS (LOC_SID));




