CREATE TABLE C17DEVLPR.SPO_LOAD_STATUS
(
  LOAD_NO             NUMBER,
  SOURCE              VARCHAR2(20 BYTE),
  LOAD_DATE           DATE,
  TABLE_NAME          VARCHAR2(30 BYTE),
  DATA_FILE_NAME      VARCHAR2(100 BYTE),
  DATA_LINE_LOADED    NUMBER,
  DATA_LINE_REJECTED  NUMBER
)
TABLESPACE USERS
PCTUSED    40
PCTFREE    5
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE INDEX C17DEVLPR.SPO_LOAD_STATUS_LOAD_DATE_I ON C17DEVLPR.SPO_LOAD_STATUS
(LOAD_DATE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE C17DEVLPR.SPO_LOAD_STATUS ADD (
  CHECK ("LOAD_NO" IS NOT NULL) DISABLE,
  CHECK ("SOURCE" IS NOT NULL) DISABLE,
  CHECK ("LOAD_DATE" IS NOT NULL) DISABLE);
  

DROP PUBLIC SYNONYM SPO_LOAD_STATUS;

CREATE PUBLIC SYNONYM SPO_LOAD_STATUS FOR C17DEVLPR.SPO_LOAD_STATUS;

GRANT DELETE, INSERT, SELECT, UPDATE ON C17DEVLPR.SPO_LOAD_STATUS TO C17V2_DEVELOPER;

GRANT DELETE, INSERT, SELECT, UPDATE ON C17DEVLPR.SPO_LOAD_STATUS TO SPOC17V2_DEVELOPER;
        


