/*
      $Author:   zf297a  $
    $Revision:   1.1  $
        $Date:   26 Jan 2007 14:31:30  $
    $Workfile:   createStlEscmLinkPlusViews.sql  $
         $Log:   I:\Program Files\Merant\vm\win32\bin\pds\archives\SDS-AMD\Database\Scripts\createStlEscmLinkPlusViews.sql.-arc  $
/*   
/*      Rev 1.1   26 Jan 2007 14:31:30   zf297a
/*   added sqlplus "set define off" command
/*   
/*      Rev 1.0   26 Jan 2007 11:46:32   zf297a
/*   Initial revision.
*/   

set define off

-- create St Louis Link

--STL_ESCM_LINK.LGB.AMS.BOEING.COM 

/*
# file = c17names.ora
STLS_ESCMDEV=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=dbmsdv01.stl.mo.boeing.com)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=escmdev)))
*/

CREATE DATABASE LINK "STL_ESCM_LINK.LGB.AMS.BOEING.COM"
 CONNECT TO C17DEVLPR
 IDENTIFIED BY "hthurston"
 USING 'STLS_ESCMDEV';


CREATE OR REPLACE VIEW SPO_CONFIRMED_REQUEST_LINE_V
(CONFIRMED_REQUEST, LINE, LOCATION, PART, REQUEST_DATE, 
 DUE_DATE, REQUEST_STATUS, SUPPLIER_LOCATION, PROPOSED_REQUEST, ATTRIBUTE_1, 
 ATTRIBUTE_2, ATTRIBUTE_3, ATTRIBUTE_4, ATTRIBUTE_5, ATTRIBUTE_6, 
 ATTRIBUTE_7, ATTRIBUTE_8, TIMESTAMP, QUANTITY_ORDERED, QUANTITY_RECEIVED)
AS 
SELECT "CONFIRMED_REQUEST","LINE","LOCATION","PART","REQUEST_DATE","DUE_DATE","REQUEST_STATUS","SUPPLIER_LOCATION","PROPOSED_REQUEST","ATTRIBUTE_1","ATTRIBUTE_2","ATTRIBUTE_3","ATTRIBUTE_4","ATTRIBUTE_5","ATTRIBUTE_6","ATTRIBUTE_7","ATTRIBUTE_8","TIMESTAMP","QUANTITY_ORDERED","QUANTITY_RECEIVED"  FROM spoc17v2.confirmed_request_line@STL_ESCM_LINK
/


CREATE OR REPLACE VIEW SPO_CONFIRMED_REQUEST_V
(ID, NAME, REQUEST_TYPE, TIMESTAMP)
AS 
SELECT "ID","NAME","REQUEST_TYPE","TIMESTAMP"  FROM spoc17v2.confirmed_request@STL_ESCM_LINK
/


CREATE OR REPLACE VIEW SPO_LP_DEMAND_V
(ID, TRANSACTION_ID, LOCATION, PART, CONTRACT, 
 DEMAND_TYPE, DEMAND_DATE, CUSTOMER_LOCATION, PRODUCT_SERIAL_NUMBER, QUANTITY, 
 TIMESTAMP)
AS 
SELECT "ID","TRANSACTION_ID","LOCATION","PART","CONTRACT","DEMAND_TYPE","DEMAND_DATE","CUSTOMER_LOCATION","PRODUCT_SERIAL_NUMBER","QUANTITY","TIMESTAMP"  FROM spoc17v2.lp_demand@STL_ESCM_LINK
/


CREATE OR REPLACE VIEW SPO_LP_IN_TRANSIT_V
(LOCATION, PART, IN_TRANSIT_TYPE, TIMESTAMP, QUANTITY)
AS 
SELECT "LOCATION","PART","IN_TRANSIT_TYPE","TIMESTAMP","QUANTITY"  FROM spoc17v2.lp_in_transit@STL_ESCM_LINK
/


CREATE OR REPLACE VIEW SPO_LP_ON_HAND_V
(LOCATION, PART, ON_HAND_TYPE, TIMESTAMP, QUANTITY)
AS 
SELECT "LOCATION","PART","ON_HAND_TYPE","TIMESTAMP","QUANTITY"  FROM spoc17v2.lp_on_hand@STL_ESCM_LINK
/


CREATE OR REPLACE VIEW SPO_LP_OVERRIDE_V
(LOCATION, PART, OVERRIDE_TYPE, QUANTITY, OVERRIDE_REASON, 
 OVERRIDE_USER, BEGIN_DATE, END_DATE, TIMESTAMP)
AS 
SELECT "LOCATION","PART","OVERRIDE_TYPE","QUANTITY","OVERRIDE_REASON","OVERRIDE_USER","BEGIN_DATE","END_DATE","TIMESTAMP"  FROM spoc17v2.lp_override@STL_ESCM_LINK
/


CREATE OR REPLACE VIEW SPO_PART_PLANNED_PART_V
(PART, PLANNED_PART, BEGIN_DATE, END_DATE, SUPERSESSION_TYPE, 
 TIMESTAMP, SPO_USER)
AS 
SELECT "PART","PLANNED_PART","BEGIN_DATE","END_DATE","SUPERSESSION_TYPE","TIMESTAMP","SPO_USER"  FROM spoc17v2.part_planned_part@STL_ESCM_LINK
/


CREATE OR REPLACE VIEW SPO_PART_V
(ID, NAME, PART_TYPE, DESCRIPTION, COST, 
 BEGIN_DATE, END_DATE, TIMESTAMP, HOLDING_COST_RATE, FIXED_ORDER_COST, 
 IS_ORDER_POLICY_ROQ_BASED, IS_REPARABLE, REPAIR_COST, DECAY_RATE, GENERATE_NEW_BUY, 
 GENERATE_REPAIR, GENERATE_ALLOCATION, GENERATE_TRANSSHIPMENT, MAX_QTY_ALLOWANCE, IS_PLANNED, 
 ATTRIBUTE_1, ATTRIBUTE_2, ATTRIBUTE_3, ATTRIBUTE_4, ATTRIBUTE_5, 
 ATTRIBUTE_6, ATTRIBUTE_7, ATTRIBUTE_8, ATTRIBUTE_9, ATTRIBUTE_10, 
 ATTRIBUTE_11, ATTRIBUTE_12, ATTRIBUTE_13, ATTRIBUTE_14, ATTRIBUTE_15, 
 ATTRIBUTE_16, ATTRIBUTE_17, ATTRIBUTE_18, ATTRIBUTE_19, ATTRIBUTE_20, 
 ATTRIBUTE_21, ATTRIBUTE_22, ATTRIBUTE_23, ATTRIBUTE_24, ATTRIBUTE_25, 
 ATTRIBUTE_26, ATTRIBUTE_27, ATTRIBUTE_28, ATTRIBUTE_29, ATTRIBUTE_30, 
 ATTRIBUTE_31, ATTRIBUTE_32, MATERIAL_CLASS, WEIGHT, VOLUME, 
 IS_EXEMPT, IGNORE_WEIGHT_AND_VOLUME, IS_SEASONAL, MAX_TOTAL_TSL)
AS 
SELECT "ID","NAME","PART_TYPE","DESCRIPTION","COST","BEGIN_DATE","END_DATE","TIMESTAMP","HOLDING_COST_RATE","FIXED_ORDER_COST","IS_ORDER_POLICY_ROQ_BASED","IS_REPARABLE","REPAIR_COST","DECAY_RATE","GENERATE_NEW_BUY","GENERATE_REPAIR","GENERATE_ALLOCATION","GENERATE_TRANSSHIPMENT","MAX_QTY_ALLOWANCE","IS_PLANNED","ATTRIBUTE_1","ATTRIBUTE_2","ATTRIBUTE_3","ATTRIBUTE_4","ATTRIBUTE_5","ATTRIBUTE_6","ATTRIBUTE_7","ATTRIBUTE_8","ATTRIBUTE_9","ATTRIBUTE_10","ATTRIBUTE_11","ATTRIBUTE_12","ATTRIBUTE_13","ATTRIBUTE_14","ATTRIBUTE_15","ATTRIBUTE_16","ATTRIBUTE_17","ATTRIBUTE_18","ATTRIBUTE_19","ATTRIBUTE_20","ATTRIBUTE_21","ATTRIBUTE_22","ATTRIBUTE_23","ATTRIBUTE_24","ATTRIBUTE_25","ATTRIBUTE_26","ATTRIBUTE_27","ATTRIBUTE_28","ATTRIBUTE_29","ATTRIBUTE_30","ATTRIBUTE_31","ATTRIBUTE_32","MATERIAL_CLASS","WEIGHT","VOLUME","IS_EXEMPT","IGNORE_WEIGHT_AND_VOLUME","IS_SEASONAL","MAX_TOTAL_TSL" FROM spoc17v2.part@STL_ESCM_LINK
/


GRANT SELECT ON  SPO_PART_V TO AMD_READER_ROLE
/

GRANT SELECT ON  SPO_PART_PLANNED_PART_V TO AMD_READER_ROLE
/

GRANT SELECT ON  SPO_LP_OVERRIDE_V TO AMD_READER_ROLE
/

GRANT SELECT ON  SPO_LP_ON_HAND_V TO AMD_READER_ROLE
/

GRANT SELECT ON  SPO_LP_IN_TRANSIT_V TO AMD_READER_ROLE
/

GRANT SELECT ON  SPO_LP_DEMAND_V TO AMD_READER_ROLE
/

GRANT SELECT ON  SPO_CONFIRMED_REQUEST_V TO AMD_READER_ROLE
/

GRANT SELECT ON  SPO_CONFIRMED_REQUEST_LINE_V TO AMD_READER_ROLE
/

show errors

