DROP TABLE C17DEVLPR.SPO_LOAD_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE C17DEVLPR.SPO_LOAD_DETAILS
(
  LOAD_NO       NUMBER,
  DATA_LINE_NO  NUMBER,
  DATA_LINE     VARCHAR2(2000 BYTE),
  KEY_1         VARCHAR2(50 BYTE),
  KEY_2         VARCHAR2(50 BYTE),
  KEY_3         VARCHAR2(50 BYTE),
  KEY_4         VARCHAR2(50 BYTE),
  KEY_5         VARCHAR2(50 BYTE),
  COMMENTS      VARCHAR2(2000 BYTE)
)
TABLESPACE USERS
PCTUSED    40
PCTFREE    5
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE INDEX C17DEVLPR.SPO_LOAD_DETAILS_LOAD_NO_I ON C17DEVLPR.SPO_LOAD_DETAILS
(LOAD_NO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX C17DEVLPR.SPO_LOAD_DETAILS_KEY_1_I ON C17DEVLPR.SPO_LOAD_DETAILS
(KEY_1)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM SPO_LOAD_DETAILS;

CREATE PUBLIC SYNONYM SPO_LOAD_DETAILS FOR C17DEVLPR.SPO_LOAD_DETAILS;


ALTER TABLE C17DEVLPR.SPO_LOAD_DETAILS ADD (
  CHECK ("LOAD_NO" IS NOT NULL) DISABLE);

GRANT DELETE, INSERT, SELECT, UPDATE ON C17DEVLPR.SPO_LOAD_DETAILS TO C17V2_DEVELOPER;

GRANT DELETE, INSERT, SELECT, UPDATE ON C17DEVLPR.SPO_LOAD_DETAILS TO SPOC17V2_DEVELOPER;
