    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 23 2005 12:33:00  $
     $Workfile:   sequences.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\Scripts\sequences.sql-arc  $
/*   
/*      Rev 1.0   May 23 2005 12:33:00   c970183
/*   Initial revision.
*/

DROP SEQUENCE AMD_OWNER.TEMP_HAM_SEQ;

CREATE SEQUENCE AMD_OWNER.TEMP_HAM_SEQ
  START WITH 1
  MAXVALUE 999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


DROP SEQUENCE AMD_OWNER.SCENARIO_ID_SEQ;

CREATE SEQUENCE AMD_OWNER.SCENARIO_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 100
  ORDER;


DROP SEQUENCE AMD_OWNER.MSG_SEQ;

CREATE SEQUENCE AMD_OWNER.MSG_SEQ
  START WITH 1
  MAXVALUE 999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


DROP SEQUENCE AMD_OWNER.AMD_SPARE_NETWORKS_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_SPARE_NETWORKS_SEQ
  START WITH 788
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


DROP SEQUENCE AMD_OWNER.AMD_RETROFITS_RETROFIT_SID_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_RETROFITS_RETROFIT_SID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE AMD_OWNER.AMD_PART_NEXT_ASSEMBLIES_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_PART_NEXT_ASSEMBLIES_SEQ
  START WITH 9063642
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 100
  ORDER;


DROP SEQUENCE AMD_OWNER.AMD_ORDER_SID_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_ORDER_SID_SEQ
  START WITH 859901
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE AMD_OWNER.AMD_NSN_SEQ_NO;

CREATE SEQUENCE AMD_OWNER.AMD_NSN_SEQ_NO
  START WITH 159961
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE AMD_OWNER.AMD_NSI_SID_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_NSI_SID_SEQ
  START WITH 902561
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE AMD_OWNER.AMD_NSI_GROUP_SID_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_NSI_GROUP_SID_SEQ
  START WITH 306581
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE AMD_OWNER.AMD_LOAD_STATUS_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_LOAD_STATUS_SEQ
  START WITH 1536175
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


DROP SEQUENCE AMD_OWNER.AMD_IN_TRANSITS_SID_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_IN_TRANSITS_SID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE AMD_OWNER.AMD_IN_REPAIR_ORDER_SID_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_IN_REPAIR_ORDER_SID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP SEQUENCE AMD_OWNER.AMD_FLEET_SIZES_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_FLEET_SIZES_SEQ
  START WITH 21
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP PUBLIC SYNONYM AMD_FLEET_SIZES_SEQ;

CREATE PUBLIC SYNONYM AMD_FLEET_SIZES_SEQ FOR AMD_OWNER.AMD_FLEET_SIZES_SEQ;


DROP PUBLIC SYNONYM AMD_LOAD_STATUS_SEQ;

CREATE PUBLIC SYNONYM AMD_LOAD_STATUS_SEQ FOR AMD_OWNER.AMD_LOAD_STATUS_SEQ;


DROP PUBLIC SYNONYM AMD_NSI_GROUP_SID_SEQ;

CREATE PUBLIC SYNONYM AMD_NSI_GROUP_SID_SEQ FOR AMD_OWNER.AMD_NSI_GROUP_SID_SEQ;


DROP PUBLIC SYNONYM AMD_NSN_SEQ_NO;

CREATE PUBLIC SYNONYM AMD_NSN_SEQ_NO FOR AMD_OWNER.AMD_NSN_SEQ_NO;


DROP PUBLIC SYNONYM AMD_PART_NEXT_ASSEMBLIES_SEQ;

CREATE PUBLIC SYNONYM AMD_PART_NEXT_ASSEMBLIES_SEQ FOR AMD_OWNER.AMD_PART_NEXT_ASSEMBLIES_SEQ;


DROP PUBLIC SYNONYM AMD_SPARE_NETWORKS_SEQ;

CREATE PUBLIC SYNONYM AMD_SPARE_NETWORKS_SEQ FOR AMD_OWNER.AMD_SPARE_NETWORKS_SEQ;


DROP PUBLIC SYNONYM MSG_SEQ;

CREATE PUBLIC SYNONYM MSG_SEQ FOR AMD_OWNER.MSG_SEQ;


DROP PUBLIC SYNONYM SCENARIO_ID_SEQ;

CREATE PUBLIC SYNONYM SCENARIO_ID_SEQ FOR AMD_OWNER.SCENARIO_ID_SEQ;


DROP PUBLIC SYNONYM TEMP_HAM_SEQ;

CREATE PUBLIC SYNONYM TEMP_HAM_SEQ FOR AMD_OWNER.TEMP_HAM_SEQ;


GRANT SELECT ON  AMD_OWNER.TEMP_HAM_SEQ TO AMD_COSMIC_SUPERUSER;

GRANT SELECT ON  AMD_OWNER.TEMP_HAM_SEQ TO AMD_DATALOAD;

GRANT SELECT ON  AMD_OWNER.TEMP_HAM_SEQ TO AMD_USER;

GRANT SELECT ON  AMD_OWNER.SCENARIO_ID_SEQ TO AMD_COSMIC_SUPERUSER;

GRANT SELECT ON  AMD_OWNER.SCENARIO_ID_SEQ TO AMD_DATALOAD;

GRANT SELECT ON  AMD_OWNER.SCENARIO_ID_SEQ TO AMD_USER;

GRANT SELECT ON  AMD_OWNER.SCENARIO_ID_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.SCENARIO_ID_SEQ TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.MSG_SEQ TO AMD_COSMIC_SUPERUSER;

GRANT SELECT ON  AMD_OWNER.MSG_SEQ TO AMD_DATALOAD;

GRANT SELECT ON  AMD_OWNER.MSG_SEQ TO AMD_USER;

GRANT SELECT ON  AMD_OWNER.MSG_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.MSG_SEQ TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_SPARE_NETWORKS_SEQ TO AMD_DATALOAD;

GRANT SELECT ON  AMD_OWNER.AMD_SPARE_NETWORKS_SEQ TO AMD_MAINT;

GRANT SELECT ON  AMD_OWNER.AMD_SPARE_NETWORKS_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_SPARE_NETWORKS_SEQ TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_RETROFITS_RETROFIT_SID_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_RETROFITS_RETROFIT_SID_SEQ TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_PART_NEXT_ASSEMBLIES_SEQ TO AMD_DATALOAD;

GRANT SELECT ON  AMD_OWNER.AMD_PART_NEXT_ASSEMBLIES_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_PART_NEXT_ASSEMBLIES_SEQ TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_ORDER_SID_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_ORDER_SID_SEQ TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_NSN_SEQ_NO TO AMD_DATALOAD;

GRANT SELECT ON  AMD_OWNER.AMD_NSN_SEQ_NO TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_NSN_SEQ_NO TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_NSI_SID_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_NSI_SID_SEQ TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_NSI_GROUP_SID_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_NSI_GROUP_SID_SEQ TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_LOAD_STATUS_SEQ TO AMD_DATALOAD;

GRANT SELECT ON  AMD_OWNER.AMD_LOAD_STATUS_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_LOAD_STATUS_SEQ TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_IN_TRANSITS_SID_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_IN_TRANSITS_SID_SEQ TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_IN_REPAIR_ORDER_SID_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_IN_REPAIR_ORDER_SID_SEQ TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_FLEET_SIZES_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.AMD_FLEET_SIZES_SEQ TO AMD_WRITER_ROLE;


