    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:26  $
     $Workfile:   amd_reqs.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_reqs.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:26   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_REQS
(
  REQ_ID            VARCHAR2(40 BYTE)           NOT NULL,
  LOC_SID           NUMBER,
  NSI_SID           NUMBER,
  QUANTITY_ORDERED  NUMBER,
  QUANTITY_DUE      NUMBER,
  NEED_DATE         DATE,
  PRIORITY          NUMBER,
  ACTION_CODE       VARCHAR2(1 BYTE),
  LAST_UPDATE_DT    DATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_REQS_PK ON AMD_REQS
(REQ_ID)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_REQS FOR AMD_REQS;


ALTER TABLE AMD_REQS ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("NSI_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("QUANTITY_ORDERED" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("QUANTITY_DUE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("NEED_DATE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("PRIORITY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_REQS ADD (
  CONSTRAINT AMD_REQS_PK PRIMARY KEY (REQ_ID)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_REQS ADD (
  CONSTRAINT AMD_REQS_FK01 FOREIGN KEY (LOC_SID) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_REQS ADD (
  CONSTRAINT AMD_REQS_FK02 FOREIGN KEY (NSI_SID) 
    REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));


GRANT SELECT ON  AMD_REQS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_REQS TO AMD_WRITER_ROLE;


