    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:32  $
     $Workfile:   amd_storage_costs.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_storage_costs.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:32   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_STORAGE_COSTS
(
  EFFECTIVE_DATE           DATE                 NOT NULL,
  HOLDING_COSTS            NUMBER,
  LOC_SID                  NUMBER               NOT NULL,
  HOLDING_COSTS_DEFAULTED  NUMBER
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_STORAGE_COSTS_PK ON AMD_STORAGE_COSTS
(LOC_SID, EFFECTIVE_DATE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_STORAGE_COSTS FOR AMD_STORAGE_COSTS;


ALTER TABLE AMD_STORAGE_COSTS ADD (
  CONSTRAINT AMD_STORAGE_COSTS_PK PRIMARY KEY (LOC_SID, EFFECTIVE_DATE)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_STORAGE_COSTS ADD (
  CONSTRAINT AMD_STORAGE_COSTS_FK01 FOREIGN KEY (LOC_SID) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_STORAGE_COSTS TO AMD_DATALOAD;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_STORAGE_COSTS TO AMD_MAINT;

GRANT SELECT ON  AMD_STORAGE_COSTS TO AMD_USER;

GRANT SELECT ON  AMD_STORAGE_COSTS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_STORAGE_COSTS TO AMD_WRITER_ROLE;


