DROP TABLE AMD_OWNER.AMD_SC_INCLUSIONS CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.AMD_SC_INCLUSIONS
(
  INCLUDE_SC  VARCHAR2(20 BYTE)
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE BITMAP INDEX AMD_OWNER.AMD_SC_INCLUSIONS_I01 ON AMD_OWNER.AMD_SC_INCLUSIONS
(SUBSTR("INCLUDE_SC",8,7))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM AMD_SC_INCLUSIONS;

CREATE OR REPLACE PUBLIC SYNONYM AMD_SC_INCLUSIONS FOR AMD_OWNER.AMD_SC_INCLUSIONS;


GRANT SELECT ON AMD_OWNER.AMD_SC_INCLUSIONS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_SC_INCLUSIONS TO AMD_WRITER_ROLE;

