SET DEFINE OFF;
ALTER TABLE AMD_OWNER.AMD_BACKORDER_SUM
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_OWNER.AMD_BACKORDER_SUM CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.AMD_BACKORDER_SUM
(
  SPO_PRIME_PART_NO  VARCHAR2(40 BYTE)          NOT NULL,
  SPO_LOCATION       VARCHAR2(20 BYTE)          NOT NULL,
  QTY                NUMBER,
  ACTION_CODE        VARCHAR2(1 BYTE)           DEFAULT 'A'                   NOT NULL,
  LAST_UPDATE_DT     DATE                       DEFAULT sysdate               NOT NULL
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX AMD_OWNER.AMD_BACKORDER_SUM_PK ON AMD_OWNER.AMD_BACKORDER_SUM
(SPO_PRIME_PART_NO, SPO_LOCATION)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM AMD_BACKORDER_SUM;

CREATE PUBLIC SYNONYM AMD_BACKORDER_SUM FOR AMD_OWNER.AMD_BACKORDER_SUM;


ALTER TABLE AMD_OWNER.AMD_BACKORDER_SUM ADD (
  CONSTRAINT CHECK_ACTION_CODE
 CHECK (ACTION_CODE = 'A' or ACTION_CODE = 'D' or ACTION_CODE = 'C'),
  CONSTRAINT AMD_BACKORDER_SUM_PK
 PRIMARY KEY
 (SPO_PRIME_PART_NO, SPO_LOCATION)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE AMD_OWNER.AMD_BACKORDER_SUM ADD (
  CONSTRAINT AMD_BACKORDER_SUM_FK01 
 FOREIGN KEY (SPO_PRIME_PART_NO) 
 REFERENCES AMD_OWNER.AMD_SPARE_PARTS (PART_NO));

GRANT SELECT ON AMD_OWNER.AMD_BACKORDER_SUM TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_BACKORDER_SUM TO AMD_WRITER_ROLE;


