begin
amd_owner.mta_disable_constraint('amd_sent_to_a2a_history','amd_sent_to_a2a_history_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_backorder_info','tmp_a2a_backorder_info_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_bom_detail','tmp_a2a_bom_detail_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_demands','tmp_a2a_demands_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_ext_forecast','tmp_a2a_ext_forecase_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_inv_info','tmp_a2a_inv_info_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_in_transits','tmp_a2a_in_transits_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_loc_part_lead_time','tmp_a2a_loc_part_lead_tim_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_loc_part_override','tmp_a2a_loc_part_override_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_order_info','tmp_a2a_order_info_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_order_info_line','tmp_a2a_order_info_line_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_parts','tmp_a2a_parts_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_part_alt_rel_delete','tmp_a2a_part_alt_rel_dlet_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_part_effectivity','tmp_a2a_part_effectivity_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_part_factors','tmp_a2a_part_factors_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_part_lead_time','tmp_a2a_part_lead_time_fk02');
amd_owner.mta_disable_constraint('tmp_a2a_part_pricing','tmp_a2a_part_pricing_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_repair_info','tmp_a2a_repair_info_fk01');
amd_owner.mta_disable_constraint('tmp_a2a_repair_inv_info','tmp_a2a_repair_inv_info_fk01');
amd_owner.mta_disable_constraint('amd_sent_to_a2a','amd_sent_to_a2a_fk01');
amd_owner.mta_disable_constraint('amd_sent_to_a2a','amd_sent_to_a2a_fk02');
amd_owner.mta_truncate_table('amd_in_transits','reuse storage');
amd_owner.mta_truncate_table('amd_in_transits_sum','reuse storage');
amd_owner.mta_truncate_table('amd_on_hand_invs','reuse storage');
amd_owner.mta_truncate_table('amd_on_hand_invs_sum','reuse storage');
amd_owner.mta_truncate_table('amd_on_order','reuse storage');
amd_owner.mta_truncate_table('amd_reqs','reuse storage');
amd_owner.mta_truncate_table('amd_backorder_sum','reuse storage');
amd_owner.mta_truncate_table('amd_rsp','reuse storage');
amd_owner.mta_truncate_table('amd_rsp_sum','reuse storage');
amd_owner.mta_truncate_table('amd_location_part_leadtime','reuse storage');
amd_owner.mta_truncate_table('amd_location_part_override','reuse storage');
amd_owner.mta_truncate_table('amd_part_loc_forecasts','reuse storage');
amd_owner.mta_truncate_table('amd_part_factors','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_backorder_info','reuse storage') ;
amd_owner.mta_truncate_table('tmp_a2a_bom_detail','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_demands','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_ext_forecast','reuse storage') ;
amd_owner.mta_truncate_table('tmp_a2a_inv_info','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_in_transits','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_loc_part_lead_time','reuse storage') ;
amd_owner.mta_truncate_table('tmp_a2a_loc_part_override','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_order_info','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_order_info_line','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_parts','reuse storage') ;
amd_owner.mta_truncate_table('tmp_a2a_part_alt_rel_delete','reuse storage') ;
amd_owner.mta_truncate_table('tmp_a2a_part_effectivity','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_part_factors','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_part_info','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_part_lead_time','reuse storage') ;
amd_owner.mta_truncate_table('tmp_a2a_part_pricing','reuse storage') ;
amd_owner.mta_truncate_table('tmp_a2a_repair_info','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_repair_inv_info','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_site_resp_asset_mgr','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_spo_users','reuse storage');
amd_owner.mta_truncate_table('amd_sent_to_a2a_history','reuse storage');
amd_owner.mta_truncate_table('tmp_a2a_part_pricing','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_demands','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_equivalent_parts','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_escalation_factors','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_icp_sbss_intersect','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_in_repair','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_in_transits','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_location_part_leadtime','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_location_part_override','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_on_base_repair_costs','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_on_hand_invs','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_on_order','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_part_cost_scheds','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_part_factors','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_part_loc_forecasts','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_planner_parts','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_reqs','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_rsp','reuse storage');
amd_owner.mta_truncate_table('tmp_amd_spare_parts','reuse storage');
amd_owner.mta_truncate_table('amd_sent_to_a2a','reuse storage');
amd_owner.mta_enable_constraint('tmp_a2a_repair_info','tmp_a2a_repair_info_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_repair_inv_info','tmp_a2a_repair_inv_info_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_inv_info','tmp_a2a_inv_info_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_loc_part_override','tmp_a2a_loc_part_override_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_order_info','tmp_a2a_order_info_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_order_info_line','tmp_a2a_order_info_line_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_part_factors','tmp_a2a_part_factors_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_ext_forecast','tmp_a2a_ext_forecase_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_loc_part_lead_time','tmp_a2a_loc_part_lead_tim_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_part_effectivity','tmp_a2a_part_effectivity_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_bom_detail','tmp_a2a_bom_detail_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_backorder_info','tmp_a2a_backorder_info_fk01');
amd_owner.mta_enable_constraint('amd_sent_to_a2a','amd_sent_to_a2a_fk01');
amd_owner.mta_enable_constraint('amd_sent_to_a2a','amd_sent_to_a2a_fk02');
amd_owner.mta_enable_constraint('amd_sent_to_a2a_history','amd_sent_to_a2a_history_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_demands','tmp_a2a_demands_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_parts','tmp_a2a_parts_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_part_alt_rel_delete','tmp_a2a_part_alt_rel_dlet_fk01');
amd_owner.mta_enable_constraint('tmp_a2a_part_lead_time','tmp_a2a_part_lead_time_fk02');
amd_owner.mta_enable_constraint('tmp_a2a_in_transits','tmp_a2a_in_transits_fk01');
end ;
/
