DROP TABLE AMD_OWNER.AMD_PRICING_FACTORS CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.AMD_PRICING_FACTORS
(
  FISCAL_YEAR     NUMBER,
  PRICING_FACTOR  NUMBER
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX AMD_OWNER.AMD_PRICING_FACTORS_PK ON AMD_OWNER.AMD_PRICING_FACTORS
(FISCAL_YEAR)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_PRICING_FACTORS TO AMD_DATALOAD;

GRANT SELECT ON AMD_OWNER.AMD_PRICING_FACTORS TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.AMD_PRICING_FACTORS TO AMD_USER;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_PRICING_FACTORS TO AMD_WRITER_ROLE;

