DROP VIEW AMD_OWNER.FLIP_ICAP_VIEW_V;

/* Formatted on 6/10/2011 12:14:33 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.FLIP_ICAP_VIEW_V
(
   REFDES,
   PARTNUM,
   IPB,
   SSSN,
   IPBFIGURE,
   IPBINDEX,
   DESCRIP
)
AS
   SELECT REFDES,
          PARTNUM,
          IPB,
          SSSN,
          IPBFIGURE,
          IPBINDEX,
          DESCRIP
     FROM flip_owner.FLIP_icap_view@amd_flip_link;


DROP PUBLIC SYNONYM FLIP_ICAP_VIEW_V;

CREATE OR REPLACE PUBLIC SYNONYM FLIP_ICAP_VIEW_V FOR AMD_OWNER.FLIP_ICAP_VIEW_V;


GRANT SELECT ON AMD_OWNER.FLIP_ICAP_VIEW_V TO AMD_READER_ROLE;
