
CREATE TABLE TMP_A2A_SITE_RESP_ASSET_MGR
(
  SITE_RESP_ASSET_MGR  VARCHAR2(20 BYTE)        NOT NULL,
  TOOL_LOGON_ID        VARCHAR2(20 BYTE)        NOT NULL,
  ACTION_CODE          VARCHAR2(1 BYTE),
  LAST_UPDATE_DT       DATE                     DEFAULT sysdate
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX TMP_A2A_SITE_RESP_ASSET_MGR_PK ON TMP_A2A_SITE_RESP_ASSET_MGR
(SITE_RESP_ASSET_MGR, TOOL_LOGON_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM TMP_A2A_SITE_RESP_ASSET_MGR FOR TMP_A2A_SITE_RESP_ASSET_MGR;


GRANT DELETE, INSERT, SELECT, UPDATE ON  TMP_A2A_SITE_RESP_ASSET_MGR TO AMD_WRITER_ROLE;



