    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:18  $
     $Workfile:   amd_part_effectivities.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_part_effectivities.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:18   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_PART_EFFECTIVITIES
(
  QPA                     NUMBER,
  ORDER_PREFER_PART_NO    VARCHAR2(20 BYTE),
  ORDER_PREFER_CAGE_CODE  VARCHAR2(5 BYTE),
  USE_PREFER_PART_NO      VARCHAR2(20 BYTE),
  USE_PREFER_CAGE_CODE    VARCHAR2(5 BYTE),
  PN_NA_SID               NUMBER                NOT NULL,
  TAIL_NO                 VARCHAR2(7 BYTE)      NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_PART_EFF_PK ON AMD_PART_EFFECTIVITIES
(PN_NA_SID, TAIL_NO)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_PART_EFFECTIVITIES FOR AMD_PART_EFFECTIVITIES;


ALTER TABLE AMD_PART_EFFECTIVITIES ADD (
  CONSTRAINT AMD_PART_EFF_PK PRIMARY KEY (PN_NA_SID, TAIL_NO)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_PART_EFFECTIVITIES ADD (
  CONSTRAINT AMD_PART_EFFECTIVITIES_FK01 FOREIGN KEY (PN_NA_SID) 
    REFERENCES AMD_PART_NEXT_ASSEMBLIES (PN_NA_SID));

ALTER TABLE AMD_PART_EFFECTIVITIES ADD (
  CONSTRAINT AMD_PART_EFFECTIVITIES_FK02 FOREIGN KEY (TAIL_NO) 
    REFERENCES AMD_AIRCRAFTS (TAIL_NO));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_PART_EFFECTIVITIES TO AMD_DATALOAD;

GRANT SELECT ON  AMD_PART_EFFECTIVITIES TO AMD_USER;

GRANT SELECT ON  AMD_PART_EFFECTIVITIES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_PART_EFFECTIVITIES TO AMD_WRITER_ROLE;


