    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:12  $
     $Workfile:   amd_nsi_effects.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_nsi_effects.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:12   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_NSI_EFFECTS
(
  NSI_SID       NUMBER                          NOT NULL,
  TAIL_NO       VARCHAR2(7 BYTE)                NOT NULL,
  EFFECT_TYPE   VARCHAR2(1 BYTE)                NOT NULL,
  USER_DEFINED  VARCHAR2(1 BYTE),
  DERIVED       VARCHAR2(1 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_NSI_EFFECTS_PK ON AMD_NSI_EFFECTS
(NSI_SID, TAIL_NO)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_NSI_EFFECTS FOR AMD_NSI_EFFECTS;


ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECTS_EFFECT_TYPE_CK CHECK (
         EFFECT_TYPE IN ('C', 'B')));

ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECT_DERIVED_CK CHECK (
            DERIVED IN ('Y', 'N')));

ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECT_USER_DEFINED_CK CHECK (
            USER_DEFINED IN ('Y', 'N', 'S')));

ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECTS_PK PRIMARY KEY (NSI_SID, TAIL_NO)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECTS_FK01 FOREIGN KEY (NSI_SID) 
    REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));

ALTER TABLE AMD_NSI_EFFECTS ADD (
  CONSTRAINT AMD_NSI_EFFECTS_FK02 FOREIGN KEY (TAIL_NO) 
    REFERENCES AMD_AIRCRAFTS (TAIL_NO));


GRANT SELECT ON  AMD_NSI_EFFECTS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_NSI_EFFECTS TO AMD_WRITER_ROLE;


