    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:12  $
     $Workfile:   amd_mission_types.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_mission_types.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:12   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_MISSION_TYPES
(
  MISSION_TYPE_CODE  VARCHAR2(8 BYTE)           NOT NULL,
  MISSION_TYPE_DESC  VARCHAR2(25 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_MISSION_TYPES_PK ON AMD_MISSION_TYPES
(MISSION_TYPE_CODE)
LOGGING
TABLESPACE AMD_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_MISSION_TYPES FOR AMD_MISSION_TYPES;


ALTER TABLE AMD_MISSION_TYPES ADD (
  CHECK ("MISSION_TYPE_DESC" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_TYPES ADD (
  CONSTRAINT AMD_MISSION_TYPES_PK PRIMARY KEY (MISSION_TYPE_CODE)
    USING INDEX 
    TABLESPACE AMD_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_MISSION_TYPES TO AMD_COSMIC_SUPERUSER;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_MISSION_TYPES TO AMD_DATALOAD;

GRANT SELECT ON  AMD_MISSION_TYPES TO AMD_USER;

GRANT SELECT ON  AMD_MISSION_TYPES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_MISSION_TYPES TO AMD_WRITER_ROLE;


