/*
	$Author:   zf297a  $
      $Revision:   1.1  $
          $Date:   30 Oct 2007 14:11:56  $
      $Workfile:   tmp_a2a_part_alt.sql  $
	   $Log:   I:\Program Files\Merant\vm\win32\bin\pds\archives\SDS-AMD\Database\ddl\tmp_a2a_part_alt.sql.-arc  $
/*   
/*      Rev 1.1   30 Oct 2007 14:11:56   zf297a
/*   Changed primary key to part, tran_action, and last_update_dt
*/

set define off

ALTER TABLE AMD_OWNER.TMP_A2A_PART_ALT
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_OWNER.TMP_A2A_PART_ALT CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.TMP_A2A_PART_ALT
(
  PART_NO         VARCHAR2(50 BYTE)             NOT NULL,
  PRIME_PART      VARCHAR2(50 BYTE)             NOT NULL,
  TRAN_ACTION     VARCHAR2(1 BYTE),
  LAST_UPDATE_DT  DATE                          DEFAULT SYSDATE
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX AMD_OWNER.TMP_A2A_PART_ALT_PK ON AMD_OWNER.TMP_A2A_PART_ALT
(PART_NO, TRAN_ACTION, LAST_UPDATE_DT)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM TMP_A2A_PART_ALT;

CREATE PUBLIC SYNONYM TMP_A2A_PART_ALT FOR AMD_OWNER.TMP_A2A_PART_ALT;


ALTER TABLE AMD_OWNER.TMP_A2A_PART_ALT ADD (
  CONSTRAINT TMP_A2A_PART_ALT_PK
 PRIMARY KEY
 (PART_NO, TRAN_ACTION, LAST_UPDATE_DT)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE AMD_OWNER.TMP_A2A_PART_ALT ADD (
  CONSTRAINT TMP_A2A_PART_ALT_FK01 
 FOREIGN KEY (PART_NO) 
 REFERENCES AMD_OWNER.AMD_SENT_TO_A2A (PART_NO));

GRANT SELECT ON AMD_OWNER.TMP_A2A_PART_ALT TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.TMP_A2A_PART_ALT TO AMD_WRITER_ROLE;


