    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:26  $
     $Workfile:   amd_retrofit_schedules.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_retrofit_schedules.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:26   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_RETROFIT_SCHEDULES
(
  TCTO_NUMBER              VARCHAR2(13 BYTE)    NOT NULL,
  TAIL_NO                  VARCHAR2(7 BYTE)     NOT NULL,
  BLOCK_NAME               VARCHAR2(20 BYTE),
  SCHEDULED_COMPLETE_DATE  DATE,
  ACTUAL_COMPLETE_DATE     DATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_RETROFIT_SCHEDULES_PK ON AMD_RETROFIT_SCHEDULES
(TCTO_NUMBER, TAIL_NO)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_RETROFIT_SCHEDULES FOR AMD_RETROFIT_SCHEDULES;


ALTER TABLE AMD_RETROFIT_SCHEDULES ADD (
  CONSTRAINT AMD_RETROFIT_SCHEDULES_PK PRIMARY KEY (TCTO_NUMBER, TAIL_NO)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_RETROFIT_SCHEDULES ADD (
  CONSTRAINT AMD_RETROFIT_SCHEDULES_FK01 FOREIGN KEY (TCTO_NUMBER) 
    REFERENCES AMD_RETROFIT_TCTOS (TCTO_NUMBER));

ALTER TABLE AMD_RETROFIT_SCHEDULES ADD (
  CONSTRAINT AMD_RETROFIT_SCHEDULES_FK02 FOREIGN KEY (TAIL_NO) 
    REFERENCES AMD_AIRCRAFTS (TAIL_NO));

ALTER TABLE AMD_RETROFIT_SCHEDULES ADD (
  CONSTRAINT AMD_RETROFIT_SCHEDULES_FK03 FOREIGN KEY (BLOCK_NAME) 
    REFERENCES AMD_RETROFIT_SCHED_BLOCKS (BLOCK_NAME));


GRANT SELECT ON  AMD_RETROFIT_SCHEDULES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_RETROFIT_SCHEDULES TO AMD_WRITER_ROLE;


