DROP TABLE C17PGM.LP_DEMAND_FORECAST CASCADE CONSTRAINTS;

CREATE TABLE C17PGM.LP_DEMAND_FORECAST
(
  LOCATION              VARCHAR2(32 BYTE)       NOT NULL,
  PART                  VARCHAR2(64 BYTE)       NOT NULL,
  DEMAND_FORECAST_TYPE  VARCHAR2(16 BYTE)       NOT NULL,
  PERIOD                DATE                    NOT NULL,
  QUANTITY              NUMBER                  NOT NULL,
  BATCH                 NUMBER                  NOT NULL,
  ACTION                VARCHAR2(3 BYTE)        NOT NULL,
  EXCEPTION             NUMBER,
  INTERFACE_SEQUENCE    NUMBER                  NOT NULL,
  TIMESTAMP             DATE                    DEFAULT SYSDATE               NOT NULL
)
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX C17PGM.LP_DEM_FORE_ACTN ON C17PGM.LP_DEMAND_FORECAST
(ACTION)
NOLOGGING
NOPARALLEL;


CREATE INDEX C17PGM.LP_DEM_FORE_BATCH_IDX ON C17PGM.LP_DEMAND_FORECAST
(BATCH)
NOLOGGING
NOPARALLEL;


CREATE INDEX C17PGM.LP_DEM_FORE_EXCP ON C17PGM.LP_DEMAND_FORECAST
(EXCEPTION)
NOLOGGING
NOPARALLEL;


CREATE INDEX C17PGM.LP_DEM_FORE_KEY_IDX ON C17PGM.LP_DEMAND_FORECAST
(LOCATION, PART, DEMAND_FORECAST_TYPE, PERIOD)
NOLOGGING
NOPARALLEL;


CREATE INDEX C17PGM.LP_DEM_FORE_SEQ_IDX ON C17PGM.LP_DEMAND_FORECAST
(INTERFACE_SEQUENCE)
NOLOGGING
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON C17PGM.LP_DEMAND_FORECAST TO C17PGM_ROLE;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON C17PGM.LP_DEMAND_FORECAST TO SPOC17V2_DEVELOPER;

