ALTER TABLE C17DEVLPR.QUEUED_REQUEST_SNAPSHOT
 DROP PRIMARY KEY CASCADE;
DROP TABLE C17DEVLPR.QUEUED_REQUEST_SNAPSHOT CASCADE CONSTRAINTS;

CREATE TABLE C17DEVLPR.QUEUED_REQUEST_SNAPSHOT
(
  PART                  NUMBER                  NOT NULL,
  SOURCE_LOCATION       NUMBER                  NOT NULL,
  DESTINATION_LOCATION  NUMBER                  NOT NULL,
  DGI_LOCATION          NUMBER,
  DGI_PART              NUMBER,
  REQUEST_DATE          DATE,
  DUE_DATE              DATE,
  REQUEST_TYPE          NUMBER                  NOT NULL,
  REQUEST_STATUS        NUMBER                  NOT NULL,
  QUANTITY              NUMBER                  NOT NULL,
  QUEUED_TIMESTAMP      DATE,
  SPO_USER              NUMBER                  NOT NULL,
  EXCEPTION_RULE        NUMBER                  NOT NULL,
  QUEUE_STATUS          NUMBER                  NOT NULL,
  RELEASE_DATE          DATE                    NOT NULL,
  SNAPSHOT_TIMESTAMP    DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX C17DEVLPR.QUEUED_REQUEST_SNAPSHOT_PK ON C17DEVLPR.QUEUED_REQUEST_SNAPSHOT
(PART, SOURCE_LOCATION, DESTINATION_LOCATION)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE C17DEVLPR.QUEUED_REQUEST_SNAPSHOT ADD (
  CONSTRAINT QUEUED_REQUEST_SNAPSHOT_PK
 PRIMARY KEY
 (PART, SOURCE_LOCATION, DESTINATION_LOCATION)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

