 /*
      $Author:   zf297a  $
    $Revision:   1.0  $
        $Date:   23 Aug 2007 10:41:26  $
    $Workfile:   tmp_locpart_overid_consumables.sql  $
         $Log:   I:\Program Files\Merant\vm\win32\bin\pds\archives\SDS-AMD\Database\Scripts\AMD 2.0 Implementation\tmp_locpart_overid_consumables.sql.-arc  $
/*   
/*      Rev 1.0   23 Aug 2007 10:41:26   zf297a
/*   Initial revision.
*/

set define off

ALTER TABLE AMD_OWNER.TMP_LOCPART_OVERID_CONSUMABLES
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_OWNER.TMP_LOCPART_OVERID_CONSUMABLES CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.TMP_LOCPART_OVERID_CONSUMABLES
(
  PART_NO              VARCHAR2(50 BYTE)        NOT NULL,
  SPO_LOCATION         VARCHAR2(20 BYTE)        NOT NULL,
  TSL_OVERRIDE_TYPE    VARCHAR2(32 BYTE),
  TSL_OVERRIDE_QTY     NUMBER,
  TSL_OVERRIDE_USER    VARCHAR2(8 BYTE),
  TSL_OVERRIDE_SOURCE  VARCHAR2(32 BYTE),
  LOC_SID              NUMBER,
  ACTION_CODE          VARCHAR2(1 BYTE)         DEFAULT 'A'                   NOT NULL,
  LAST_UPDATE_DT       DATE                     DEFAULT sysdate               NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX AMD_OWNER.TMPLOCPARTOVERIDCONSUMABLES_PK ON AMD_OWNER.TMP_LOCPART_OVERID_CONSUMABLES
(PART_NO, SPO_LOCATION, TSL_OVERRIDE_TYPE)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM TMP_LOCPART_OVERID_CONSUMABLES;

CREATE PUBLIC SYNONYM TMP_LOCPART_OVERID_CONSUMABLES FOR AMD_OWNER.TMP_LOCPART_OVERID_CONSUMABLES;


ALTER TABLE AMD_OWNER.TMP_LOCPART_OVERID_CONSUMABLES ADD (
  CONSTRAINT TMPLOCPARTOVERIDCONSUMABLES_PK
 PRIMARY KEY
 (PART_NO, SPO_LOCATION, TSL_OVERRIDE_TYPE)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE AMD_OWNER.TMP_LOCPART_OVERID_CONSUMABLES ADD (
  CONSTRAINT TMP_LOCPARTOVERRID_CONSUM_FK01 
 FOREIGN KEY (LOC_SID) 
 REFERENCES AMD_OWNER.AMD_SPARE_NETWORKS (LOC_SID),
  CONSTRAINT TMP_LOCPARTOVERRID_CONSUM_FK02 
 FOREIGN KEY (PART_NO) 
 REFERENCES AMD_OWNER.AMD_SPARE_PARTS (PART_NO));

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.TMP_LOCPART_OVERID_CONSUMABLES TO AMD_DATALOAD;

GRANT SELECT ON AMD_OWNER.TMP_LOCPART_OVERID_CONSUMABLES TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.TMP_LOCPART_OVERID_CONSUMABLES TO AMD_USER;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.TMP_LOCPART_OVERID_CONSUMABLES TO AMD_WRITER_ROLE;


