DROP VIEW AMD_OWNER.SLIC_XI_V;

/* Formatted on 7/9/2012 4:35:08 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SLIC_XI_V
(
   DBKEY,
   UPDTCNT,
   BCKP,
   CAN_INT,
   UPDTCD,
   TMCODEXI,
   TMNUMBXI
)
AS
   SELECT DBKEY,
          UPDTCNT,
          BCKP,
          CAN_INT,
          UPDTCD,
          TMCODEXI,
          TMNUMBXI
     FROM pslms_xi@amd_pslms_link.boeingdb;


DROP PUBLIC SYNONYM SLIC_XI_V;

CREATE OR REPLACE PUBLIC SYNONYM SLIC_XI_V FOR AMD_OWNER.SLIC_XI_V;


GRANT SELECT ON AMD_OWNER.SLIC_XI_V TO AMD_READER_ROLE;
