DROP VIEW AMD_OWNER.SLIC_XC_V;

/* Formatted on 7/9/2012 4:35:04 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SLIC_XC_V
(
   DBKEY,
   UPDTCNT,
   BCKP,
   CAN_INT,
   UPDTCD,
   EIACODXA,
   LSACONXB,
   ALTLCNXB,
   LCNTYPXB,
   UOCSEIXC,
   PCCNUMXC,
   ITMDESXC,
   PLISNOXC,
   TOCCODXC,
   QTYASYXC,
   QTYPEIXC,
   TRASEIXC,
   QTY_PER_EI_CALC_OPT_CODE
)
AS
   SELECT DBKEY,
          UPDTCNT,
          BCKP,
          CAN_INT,
          UPDTCD,
          EIACODXA,
          LSACONXB,
          ALTLCNXB,
          LCNTYPXB,
          UOCSEIXC,
          PCCNUMXC,
          ITMDESXC,
          PLISNOXC,
          TOCCODXC,
          QTYASYXC,
          QTYPEIXC,
          TRASEIXC,
          QTY_PER_EI_CALC_OPT_CODE
     FROM pslms_xc@amd_pslms_link.boeingdb;


DROP PUBLIC SYNONYM SLIC_XC_V;

CREATE OR REPLACE PUBLIC SYNONYM SLIC_XC_V FOR AMD_OWNER.SLIC_XC_V;


GRANT SELECT ON AMD_OWNER.SLIC_XC_V TO AMD_READER_ROLE;
