DROP VIEW AMD_OWNER.SLIC_HG_V;

/* Formatted on 7/9/2012 4:34:54 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SLIC_HG_V
(
   DBKEY,
   UPDTCNT,
   BCKP,
   CAN_INT,
   UPDTCD,
   CAGECDXH,
   REFNUMHA,
   EIACODXA,
   LSACONXB,
   ALTLCNXB,
   LCNTYPXB,
   PLISNOHG,
   QTYASYHG,
   SUPINDHG,
   DATASCHG,
   PROSICHG,
   LLIPTDHG,
   PPLPTDHG,
   SFPPTDHG,
   CBLPTDHG,
   RILPTDHG,
   ISLPTDHG,
   PCLPTDHG,
   TTLPTDHG,
   SCPPTDHG,
   ARAPTDHG,
   ARBPTDHG,
   TOCCODHG,
   INDCODHG,
   QTYPEIHG,
   PIPLISHG,
   SAPLISHG,
   HARDCIHG,
   REMIPIHG,
   LRUNITHG,
   ITMCATHG,
   ESSCODHG,
   SMRCODHG,
   MRRONEHG,
   MRRTWOHG,
   MRRMODHG,
   ORTDOOHG,
   FRTDFFHG,
   HRTDHHHG,
   LRTDLLHG,
   DRTDDDHG,
   MINREUHG,
   MAOTIMHG,
   MAIACTHG,
   RISSBUHG,
   RMSSLIHG,
   RTLLQTHG,
   TOTQTYHG,
   OMTDOOHG,
   FMTDFFHG,
   HMTDHHHG,
   LMTDLLHG,
   DMTDDDHG,
   CBDMTDHG,
   CADMTDHG,
   ORCTOOHG,
   FRCTFFHG,
   HRCTHHHG,
   LRCTLLHG,
   DRCTDDHG,
   CONRCTHG,
   NORETSHG,
   REPSURHG,
   DRPONEHG,
   DRPTWOHG,
   WRKUCDHG,
   ALLOWCHG,
   ALIQTYHG,
   IDENTIFICATION_NUMBER_HG,
   PCCNUMXC,
   EXT_PARTAPPL_ID
)
AS
   SELECT "DBKEY",
          "UPDTCNT",
          "BCKP",
          "CAN_INT",
          "UPDTCD",
          "CAGECDXH",
          TRIM (REFNUMHA),
          "EIACODXA",
          TRIM (LSACONXB),
          "ALTLCNXB",
          "LCNTYPXB",
          TRIM (PLISNOHG),
          TO_NUMBER (TRIM (QTYASYHG)),
          "SUPINDHG",
          "DATASCHG",
          "PROSICHG",
          "LLIPTDHG",
          "PPLPTDHG",
          "SFPPTDHG",
          "CBLPTDHG",
          "RILPTDHG",
          "ISLPTDHG",
          "PCLPTDHG",
          "TTLPTDHG",
          "SCPPTDHG",
          "ARAPTDHG",
          "ARBPTDHG",
          TRIM (TOCCODHG),
          TRIM (INDCODHG),
          "QTYPEIHG",
          "PIPLISHG",
          "SAPLISHG",
          "HARDCIHG",
          "REMIPIHG",
          "LRUNITHG",
          "ITMCATHG",
          "ESSCODHG",
          TRIM (SMRCODHG),
          "MRRONEHG",
          "MRRTWOHG",
          "MRRMODHG",
          "ORTDOOHG",
          "FRTDFFHG",
          "HRTDHHHG",
          "LRTDLLHG",
          "DRTDDDHG",
          "MINREUHG",
          "MAOTIMHG",
          "MAIACTHG",
          "RISSBUHG",
          "RMSSLIHG",
          "RTLLQTHG",
          "TOTQTYHG",
          "OMTDOOHG",
          "FMTDFFHG",
          "HMTDHHHG",
          "LMTDLLHG",
          "DMTDDDHG",
          "CBDMTDHG",
          "CADMTDHG",
          "ORCTOOHG",
          "FRCTFFHG",
          "HRCTHHHG",
          "LRCTLLHG",
          "DRCTDDHG",
          "CONRCTHG",
          "NORETSHG",
          "REPSURHG",
          "DRPONEHG",
          "DRPTWOHG",
          TRIM (WRKUCDHG),
          "ALLOWCHG",
          "ALIQTYHG",
          "IDENTIFICATION_NUMBER_HG",
          TRIM (PCCNUMXC),
          "EXT_PARTAPPL_ID"
     FROM pslms_hg@amd_pslms_link.boeingdb;


DROP PUBLIC SYNONYM SLIC_HG_V;

CREATE OR REPLACE PUBLIC SYNONYM SLIC_HG_V FOR AMD_OWNER.SLIC_HG_V;


GRANT SELECT ON AMD_OWNER.SLIC_HG_V TO AMD_READER_ROLE;
