DROP VIEW AMD_OWNER.SLIC_HF_V;

/* Formatted on 7/9/2012 4:34:47 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SLIC_HF_V
(
   DBKEY,
   UPDTCNT,
   BCKP,
   CAN_INT,
   UPDTCD,
   CAGECDXH,
   REFNUMHA,
   DEGPROHF,
   UNICONHF,
   UCLEVLHF,
   PKGCODHF,
   PACCATHF,
   MEPRESHF,
   CDPROCHF,
   PRSMATHF,
   WRAPMTHF,
   CUSHMAHF,
   CUSTHIHF,
   QTYUPKHF,
   INTCONHF,
   INCQTYHF,
   SPEMRKHF,
   UNPKWTHF,
   LENUPKHF,
   WIDUPKHF,
   DEPUPKHF,
   UNPKCUHF,
   OPTPRIHF,
   SPINUMHF,
   SPIREVHF,
   SPDATEHF,
   CONNSNHF,
   SUPPKDHF,
   PKCAGEHF
)
AS
   SELECT DBKEY,
          UPDTCNT,
          BCKP,
          CAN_INT,
          UPDTCD,
          CAGECDXH,
          REFNUMHA,
          DEGPROHF,
          UNICONHF,
          UCLEVLHF,
          PKGCODHF,
          PACCATHF,
          MEPRESHF,
          CDPROCHF,
          PRSMATHF,
          WRAPMTHF,
          CUSHMAHF,
          CUSTHIHF,
          QTYUPKHF,
          INTCONHF,
          INCQTYHF,
          SPEMRKHF,
          UNPKWTHF,
          LENUPKHF,
          WIDUPKHF,
          DEPUPKHF,
          UNPKCUHF,
          OPTPRIHF,
          SPINUMHF,
          SPIREVHF,
          SPDATEHF,
          CONNSNHF,
          SUPPKDHF,
          PKCAGEHF
     FROM PSLMS_Hf@AMD_PSLMS_LINK.BOEINGDB;


DROP PUBLIC SYNONYM SLIC_HF_V;

CREATE OR REPLACE PUBLIC SYNONYM SLIC_HF_V FOR AMD_OWNER.SLIC_HF_V;


GRANT SELECT ON AMD_OWNER.SLIC_HF_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SLIC_HF_V TO BSRM_LOADER;
