@spo_bom_detail_v.sql
@spo_bom_location_contract_v.sql
@spo_confirmed_request_line_v.sql
@spo_confirmed_request_v.sql
@spo_contract_causal_forecast_v.sql
@spo_contract_causal_v.sql
@spo_fixed_current_period_v.sql
@spo_flag_v.sql
@spo_fx_lp_demand_forecast_v.sql
@spo_in_transit_v.sql
@spo_interface_batch_v.sql
@spo_location_v.sql
@spo_lp_attribute_v.sql
@spo_lp_backorder_v.sql
@spo_lp_demand_forecast_v.sql
@spo_lp_demand_v.sql
@spo_lp_in_transit_v.sql
@spo_lp_on_hand_v.sql
@spo_lp_override_v.sql
@spo_network_part_v.sql
@spo_on_hand_v.sql
@spo_parameter_v.sql
@spo_part_causal_type_v.sql
@spo_part_mtbf_v.sql
@spo_part_planned_part_v.sql
@spo_part_upgraded_part_v.sql
@spo_part_v.sql
@spo_period_v.sql
@spo_supersession_v.sql
@spo_user_part_v.sql
@spo_user_type_v.sql
@spo_user_user_type_v.sql
@spo_user_user_v.sql
@spo_user_v.sql
@spo_x_imp_interface_batch_v.sql
@x_bom_detail_v.sql
@x_bom_location_contract_v.sql
@x_lp_attribute_v.sql
@x_network_part_v.sql
@x_part_v.sql
@x_user_part_v.sql
@x_user_user_type_v.sql
@x_user_v.sql
