    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:04  $
     $Workfile:   amd_forcasted_ac_usages.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_forcasted_ac_usages.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:04   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_FORCASTED_AC_USAGES
(
  FORECAST_NAME      VARCHAR2(40 BYTE)          NOT NULL,
  LOC_SID            NUMBER                     NOT NULL,
  UOM_CODE           VARCHAR2(2 BYTE)           NOT NULL,
  TIME_PERIOD_START  DATE                       NOT NULL,
  TIME_PERIOD_END    DATE,
  FORECAST_QTY       NUMBER
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_FORCASTED_AC_USAGES_PK ON AMD_FORCASTED_AC_USAGES
(FORECAST_NAME, LOC_SID, UOM_CODE, TIME_PERIOD_START)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_FORCASTED_AC_USAGES FOR AMD_FORCASTED_AC_USAGES;


ALTER TABLE AMD_FORCASTED_AC_USAGES ADD (
  CHECK ("TIME_PERIOD_END" IS NOT NULL) DISABLE);

ALTER TABLE AMD_FORCASTED_AC_USAGES ADD (
  CHECK ("FORECAST_QTY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_FORCASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FORCASTED_AC_USAGES_PK PRIMARY KEY (FORECAST_NAME, LOC_SID, UOM_CODE, TIME_PERIOD_START)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_FORCASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FORCASTED_AC_USAGES_FK01 FOREIGN KEY (LOC_SID) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_FORCASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FORCASTED_AC_USAGES_FK02 FOREIGN KEY (UOM_CODE) 
    REFERENCES AMD_UOMS (UOM_CODE));


GRANT SELECT ON  AMD_FORCASTED_AC_USAGES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_FORCASTED_AC_USAGES TO AMD_WRITER_ROLE;


