DROP VIEW AMD_OWNER.SLIC_XB_V;

/* Formatted on 7/9/2012 4:35:01 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SLIC_XB_V
(
   DBKEY,
   UPDTCNT,
   BCKP,
   CAN_INT,
   UPDTCD,
   EIACODXA,
   LSACONXB,
   ALTLCNXB,
   LCNTYPXB,
   LCNINDXB,
   LCNAMEXB,
   TMFGCDXB,
   SYSIDNXB,
   SECITMXB,
   RAMINDXB,
   DOCUMENT_CODE_XB,
   WORK_AREA_CODE_ZONE_XB,
   EXT_LCN_ID
)
AS
   SELECT DBKEY,
          UPDTCNT,
          BCKP,
          CAN_INT,
          TRIM (UPDTCD),
          TRIM (EIACODXA),
          TRIM (LSACONXB),
          ALTLCNXB,
          LCNTYPXB,
          TRIM (LCNINDXB),
          TRIM (LCNAMEXB),
          TRIM (TMFGCDXB),
          TRIM (SYSIDNXB),
          TRIM (SECITMXB),
          TRIM (RAMINDXB),
          TRIM (DOCUMENT_CODE_XB),
          TRIM (WORK_AREA_CODE_ZONE_XB),
          EXT_LCN_ID
     FROM pslms_xb@amd_pslms_link.boeingdb;


DROP PUBLIC SYNONYM SLIC_XB_V;

CREATE OR REPLACE PUBLIC SYNONYM SLIC_XB_V FOR AMD_OWNER.SLIC_XB_V;


GRANT SELECT ON AMD_OWNER.SLIC_XB_V TO AMD_READER_ROLE;
