SET DEFINE OFF;
ALTER TABLE AMD_OWNER.AMD_SPO_PARTS_HISTORY
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_OWNER.AMD_SPO_PARTS_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.AMD_SPO_PARTS_HISTORY
(
  PART_NO                VARCHAR2(50 BYTE)      NOT NULL,
  LAST_UPDATE_DT         DATE                   DEFAULT sysdate,
  IS_SPO_PART            VARCHAR2(1 BYTE),
  IS_SPO_PART_CHG        VARCHAR2(1 BYTE),
  IS_REPAIRABLE          VARCHAR2(1 BYTE),
  IS_REPAIRABLE_CHG      VARCHAR2(1 BYTE),
  IS_CONSUMABLE          VARCHAR2(1 BYTE),
  IS_CONSUMABLE_CHG      VARCHAR2(1 BYTE),
  SPO_PRIME_PART_NO      VARCHAR2(50 BYTE),
  SPO_PRIME_PART_NO_CHG  VARCHAR2(1 BYTE),
  UNIT_COST              NUMBER,
  UNIT_COST_CHG          VARCHAR2(1 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX AMD_OWNER.AMD_SPO_PARTS_HISTORY_PK ON AMD_OWNER.AMD_SPO_PARTS_HISTORY
(PART_NO, LAST_UPDATE_DT)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.AMD_SPO_PARTS_HISTORY_NK01 ON AMD_OWNER.AMD_SPO_PARTS_HISTORY
(PART_NO)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
REVERSE;


CREATE INDEX AMD_OWNER.AMD_SPO_PARTS_HISTORY_NK02 ON AMD_OWNER.AMD_SPO_PARTS_HISTORY
(LAST_UPDATE_DT)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM AMD_SPO_PARTS_HISTORY;

CREATE PUBLIC SYNONYM AMD_SPO_PARTS_HISTORY FOR AMD_OWNER.AMD_SPO_PARTS_HISTORY;


ALTER TABLE AMD_OWNER.AMD_SPO_PARTS_HISTORY ADD (
  CONSTRAINT AMD_SPO_PARTS_HISTORY_PK
 PRIMARY KEY
 (PART_NO, LAST_UPDATE_DT)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE AMD_OWNER.AMD_SPO_PARTS_HISTORY ADD (
  CONSTRAINT AMD_SPO_PARTS_HISTORY_FK01 
 FOREIGN KEY (PART_NO) 
 REFERENCES AMD_OWNER.AMD_SPARE_PARTS (PART_NO));

GRANT SELECT ON AMD_OWNER.AMD_SPO_PARTS_HISTORY TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_SPO_PARTS_HISTORY TO AMD_WRITER_ROLE;


