DROP TABLE AMD_OWNER.LRU_BREAKDOWN CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.LRU_BREAKDOWN
(
  PART_NO         VARCHAR2(32 BYTE),
  MASTER_LCN      VARCHAR2(18 BYTE),
  LCN             VARCHAR2(18 BYTE),
  PCCN            VARCHAR2(6 BYTE),
  PLISN           VARCHAR2(5 BYTE),
  QPA             NUMBER,
  INDENTURE       VARCHAR2(1 BYTE),
  SLIC_SMR        VARCHAR2(6 BYTE),
  SLIC_WUC        VARCHAR2(7 BYTE),
  TOCC            VARCHAR2(1 BYTE),
  SLIC_CAGE       CHAR(5 BYTE),
  SLIC_NOUN       VARCHAR2(19 BYTE),
  GOLD_NOUN       VARCHAR2(40 BYTE),
  USABLE_FROM     VARCHAR2(20 BYTE),
  USABLE_TO       VARCHAR2(20 BYTE),
  IMS             VARCHAR2(20 BYTE),
  AAC             VARCHAR2(1 BYTE),
  SOS             VARCHAR2(3 BYTE),
  NSN             VARCHAR2(16 BYTE),
  LAST_UPDATE_DT  DATE                          DEFAULT sysdate
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX AMD_OWNER.LRU_BREAKDOWN_NK01 ON AMD_OWNER.LRU_BREAKDOWN
(PART_NO)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.LRU_BREAKDOWN_NK02 ON AMD_OWNER.LRU_BREAKDOWN
(LCN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.LRU_BREAKDOWN_NK03 ON AMD_OWNER.LRU_BREAKDOWN
(PCCN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.LRU_BREAKDOWN_NK04 ON AMD_OWNER.LRU_BREAKDOWN
(PLISN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.LRU_BREAKDOWN_NK05 ON AMD_OWNER.LRU_BREAKDOWN
(SLIC_WUC)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.LRU_BREAKDOWN_NK06 ON AMD_OWNER.LRU_BREAKDOWN
(MASTER_LCN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AMD_OWNER.LRU_BREAKDOWN_NK07 ON AMD_OWNER.LRU_BREAKDOWN
(SUBSTR("SLIC_SMR",1,3))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AMD_OWNER.LRU_BREAKDOWN_NK08 ON AMD_OWNER.LRU_BREAKDOWN
(SUBSTR("SLIC_SMR",4,1))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AMD_OWNER.LRU_BREAKDOWN_NK09 ON AMD_OWNER.LRU_BREAKDOWN
(SUBSTR("SLIC_SMR",5,1))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AMD_OWNER.LRU_BREAKDOWN_NK10 ON AMD_OWNER.LRU_BREAKDOWN
(SUBSTR("SLIC_SMR",6,1))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.LRU_BREAKDOWN_NK11 ON AMD_OWNER.LRU_BREAKDOWN
(LCN, MASTER_LCN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.LRU_BREAKDOWN_NK12 ON AMD_OWNER.LRU_BREAKDOWN
(NSN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM LRU_BREAKDOWN;

GRANT SELECT ON AMD_OWNER.LRU_BREAKDOWN TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.LRU_BREAKDOWN TO AMD_WRITER_ROLE;

