LOAD DATA
INFILE '/data/escm_lb/LpOverride.dat'
BADFILE './loadXImpLpOverride.bad'
DISCARDFILE './loadXImpLpOverride.dsc'
Append INTO TABLE SPOV22ICSV2.X_IMP_LP_OVERRIDE
FIELDS TERMINATED BY "|"
(LOCATION,
 PART,
 OVERRIDE_TYPE,
 QUANTITY,
 OVERRIDE_REASON,
 OVERRIDE_USER,
 BEGIN_DATE,
 END_DATE,
 ACTION,
 BATCH,
 INTERFACE_SEQUENCE	             
)