DROP VIEW AMD_OWNER.PGOLD_ISGP_V;

/* Formatted on 7/9/2012 4:24:30 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.PGOLD_ISGP_V
(
   SC,
   PART,
   GROUP_NO,
   RELATIONSHIP_TYPE,
   GROUP_PRIORITY,
   JUMP_TO,
   INCOMPATIBILITY_CODE,
   DISABLED_B,
   SEQUENCE_NO
)
AS
   SELECT TRIM (SC),
          TRIM (PART),
          TRIM (GROUP_NO),
          RELATIONSHIP_TYPE,
          TRIM (GROUP_PRIORITY),
          JUMP_TO,
          INCOMPATIBILITY_CODE,
          DISABLED_B,
          SEQUENCE_NO
     FROM isgp@amd_pgoldlb_link;


DROP PUBLIC SYNONYM PGOLD_ISGP_V;

CREATE OR REPLACE PUBLIC SYNONYM PGOLD_ISGP_V FOR AMD_OWNER.PGOLD_ISGP_V;


GRANT SELECT ON AMD_OWNER.PGOLD_ISGP_V TO AMD_READER_ROLE;
