DROP VIEW AMD_OWNER.PGOLD_VENN_V;

/* Formatted on 7/9/2012 4:25:39 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.PGOLD_VENN_V
(
   VENDOR_CODE,
   VENDOR_NAME,
   CAGE_CODE,
   USER_REF1
)
AS
   SELECT TRIM (vendor_code),
          TRIM (vendor_name),
          TRIM (cage_code),
          TRIM (user_ref1)
     FROM venn@amd_pgoldlb_link
    WHERE cage_code IS NOT NULL;


DROP PUBLIC SYNONYM PGOLD_VENN_V;

CREATE OR REPLACE PUBLIC SYNONYM PGOLD_VENN_V FOR AMD_OWNER.PGOLD_VENN_V;


GRANT SELECT ON AMD_OWNER.PGOLD_VENN_V TO AMD_READER_ROLE;
