DROP VIEW AMD_OWNER.PGOLD_NSN1_V;

/* Formatted on 7/9/2012 4:24:50 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.PGOLD_NSN1_V
(
   NSN,
   NSN_SMIC
)
AS
   SELECT TRIM (nsn), TRIM (nsn_smic) FROM nsn1@amd_pgoldlb_link;


DROP PUBLIC SYNONYM PGOLD_NSN1_V;

CREATE OR REPLACE PUBLIC SYNONYM PGOLD_NSN1_V FOR AMD_OWNER.PGOLD_NSN1_V;


GRANT SELECT ON AMD_OWNER.PGOLD_NSN1_V TO AMD_READER_ROLE;
