/*
	$Author:   zf297a  $
      $Revision:   1.7  $
	  $Date:   Sep 15 2006 10:01:08  $
       $Modtime:   Sep 15 2006 09:58:04  $
        $Header:   I:\Program Files\Merant\vm\win32\bin\pds\archives\SDS-AMD\Database\Scripts\tables_1_8_05.sql.-arc   1.7   Sep 15 2006 10:01:08   zf297a  $
      $Workfile:   tables_1_8_05.sql  $
       $Archive:   I:\Program Files\Merant\vm\win32\bin\pds\archives\SDS-AMD\Database\Scripts\tables_1_8_05.sql.-arc  $
           $Log:   I:\Program Files\Merant\vm\win32\bin\pds\archives\SDS-AMD\Database\Scripts\tables_1_8_05.sql.-arc  $
/*   
/*      Rev 1.7   Sep 15 2006 10:01:08   zf297a
/*   Added new column data_source to tmp_a2a_site_resp_asset_mgr.
/*   
/*      Rev 1.4   Jun 08 2006 08:22:22   zf297a
/*   Added amd_on_order_filter_names and amd_on_order_date_filters + associated triggers
/*   
/*      Rev 1.3   Jun 02 2006 10:59:28   zf297a
/*   dropped table tmp_a2a_demand_info
/*   
/*      Rev 1.2   May 11 2006 14:16:12   zf297a
/*   added last_update_dt to amd_bssm_s_base_part_periods.
/*   
/*      Rev 1.1   May 04 2006 10:41:10   zf297a
/*   Added alter table tmp_a2a_ext_forecast add column duplicate
*/

drop table tmp_a2a_demand_info ;

Alter table tmp_a2a_ext_forecast add (   DUPLICATE NUMBER DEFAULT NULL) ;

Alter table amd_bssm_s_base_part_periods Add last_update_dt date default sysdate ;

CREATE TABLE AMD_RSP
(
  PART_NO         VARCHAR2(50 BYTE)             NOT NULL,
  LOC_SID         NUMBER                        NOT NULL,
  RSP_INV         NUMBER,
  RSP_LEVEL       NUMBER,
  ACTION_CODE     VARCHAR2(1 BYTE),
  LAST_UPDATE_DT  DATE
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

show errors

CREATE TABLE AMD_RSP_SUM
(
  PART_NO         VARCHAR2(50 BYTE)             NOT NULL,
  RSP_LOCATION    VARCHAR2(20 BYTE)             NOT NULL,
  QTY_ON_HAND     NUMBER,
  RSP_LEVEL       NUMBER,
  ACTION_CODE     VARCHAR2(1 BYTE)              NOT NULL,
  LAST_UPDATE_DT  DATE
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

show errors

CREATE TABLE TMP_AMD_RSP
(
  PART_NO         VARCHAR2(50 BYTE)             NOT NULL,
  LOC_SID         NUMBER                        NOT NULL,
  RSP_INV         NUMBER,
  RSP_LEVEL       NUMBER,
  ACTION_CODE     VARCHAR2(1 BYTE),
  LAST_UPDATE_DT  DATE
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

show errors

CREATE UNIQUE INDEX AMD_RSP_PK ON AMD_RSP
(PART_NO, LOC_SID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

show errors

CREATE UNIQUE INDEX AMD_RSP_SUM_PK ON AMD_RSP_SUM
(PART_NO, RSP_LOCATION)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

show errors

CREATE PUBLIC SYNONYM AMD_RSP FOR AMD_RSP;


CREATE PUBLIC SYNONYM TMP_AMD_RSP FOR TMP_AMD_RSP;


CREATE PUBLIC SYNONYM AMD_RSP_SUM FOR AMD_RSP_SUM;


ALTER TABLE AMD_RSP ADD (
  CONSTRAINT AMD_RSP_PK
 PRIMARY KEY
 (PART_NO, LOC_SID)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

show errors

ALTER TABLE AMD_RSP_SUM ADD (
  CONSTRAINT AMD_RSP_SUM_PK
 PRIMARY KEY
 (PART_NO, RSP_LOCATION)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

show errors

ALTER TABLE TMP_AMD_RSP ADD (
  CONSTRAINT TMP_AMD_RSP_PK
 PRIMARY KEY
 (PART_NO, LOC_SID) DISABLE);

show errors

GRANT DELETE, INSERT ON  AMD_RSP_SUM TO AMD_READER_ROLE;

GRANT SELECT ON  TMP_AMD_RSP TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_RSP_SUM TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_RSP TO AMD_READER_ROLE;

GRANT UPDATE ON  AMD_RSP_SUM TO AMD_READER_ROLE;

GRANT DELETE ON  TMP_AMD_RSP TO AMD_WRITER_ROLE;

GRANT DELETE ON  AMD_RSP_SUM TO AMD_WRITER_ROLE;

GRANT DELETE ON  AMD_RSP TO AMD_WRITER_ROLE;

GRANT INSERT ON  TMP_AMD_RSP TO AMD_WRITER_ROLE;

GRANT INSERT ON  AMD_RSP TO AMD_WRITER_ROLE;

GRANT INSERT ON  AMD_RSP_SUM TO AMD_WRITER_ROLE;

GRANT SELECT ON  TMP_AMD_RSP TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_RSP TO AMD_WRITER_ROLE;

GRANT SELECT ON  AMD_RSP_SUM TO AMD_WRITER_ROLE;

GRANT UPDATE ON  TMP_AMD_RSP TO AMD_WRITER_ROLE;

GRANT UPDATE ON  AMD_RSP TO AMD_WRITER_ROLE;

GRANT UPDATE ON  AMD_RSP_SUM TO AMD_WRITER_ROLE;


CREATE TABLE AMD_ON_ORDER_DATE_FILTERS
(
  FILTER_NAME                  VARCHAR2(50 BYTE) NOT NULL,
  VOUCHER_PREFIX               VARCHAR2(2 BYTE) NOT NULL,
  ORDER_CREATE_DATE            DATE,
  SCHEDULED_RECEIPT_DATE_FROM  DATE,
  SCHEDULED_RECEIPT_DATE_TO    DATE,
  CALENDAR_DAYS                NUMBER,
  LAST_UPDATE_DT               DATE             DEFAULT sysdate,
  ORACLE_USERID                VARCHAR2(30 BYTE) DEFAULT user
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE TABLE AMD_ON_ORDER_FILTER_NAMES
(
  FILTER_NAME     VARCHAR2(50 BYTE)             NOT NULL,
  LAST_UPDATE_DT  DATE                          DEFAULT sysdate,
  ORACLE_USERID   VARCHAR2(30 BYTE)             DEFAULT user
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX AMD_ON_ORDER_DATE_FILTER_PK ON AMD_ON_ORDER_DATE_FILTERS
(FILTER_NAME, VOUCHER_PREFIX)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AMD_ON_ORDER_FILTER_NAMES_PK ON AMD_ON_ORDER_FILTER_NAMES
(FILTER_NAME)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER AMD_ON_ORDER_DATE_FILTERS_TRG1
BEFORE INSERT OR UPDATE
ON AMD_OWNER.AMD_ON_ORDER_DATE_FILTERS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
voucher varchar2(2) ;
/******************************************************************************
      $Author:   zf297a  $
    $Revision:   1.7  $
	    $Date:   Sep 15 2006 10:01:08  $
    $Workfile:   tables_1_8_05.sql  $
         $Log:   I:\Program Files\Merant\vm\win32\bin\pds\archives\SDS-AMD\Database\Triggers\AMD_ON_ORDER_DATE_FILTERS_TRG1.trg.-arc  $
/*   
/*      Rev 1.1   May 17 2006 14:51:36   zf297a
/*   removed start_date - column is not needed
/*   
/*      Rev 1.0   May 17 2006 12:00:34   zf297a
/*   Initial revision.

******************************************************************************/
BEGIN
   if inserting then
   	  begin
   	  	   select distinct substr(gold_order_number,1,2) into voucher from amd_on_order where substr(gold_order_number,1,2) = :new.voucher_prefix ;
	  exception when standard.no_data_found then
		   RAISE_APPLICATION_ERROR(-20000, 'The voucher prefix does not exist in amd_on_order.');
	  end ;	 
   else
   	   :new.last_update_dt := sysdate ;
	   :new.oracle_userid := user ; 
   end if ;
   if :new.calendar_days is not null then
   	  if :new.calendar_days < 0 then
	  	 RAISE_APPLICATION_ERROR(-20001, 'calendar_days must be positive.');
	  end if ;
   	  if :new.scheduled_receipt_date_from is not null then
	  	 RAISE_APPLICATION_ERROR(-20002, 'Cannot have scheduled_receipt_date_from with calendar_days.');
	  elsif :new.scheduled_receipt_date_to is not null then
	  	 RAISE_APPLICATION_ERROR(-20003, 'Cannot have scheduled_receipt_date_to with calendar_days.');
	  end if ;
   else
   	   if :new.scheduled_receipt_date_from is not null then
	   	  if :new.scheduled_receipt_date_to is null then
		  	 RAISE_APPLICATION_ERROR(-20004, 'You must enter scheduled_receipt_date_to.');
		  end if ;
	   else
	   	   if :new.scheduled_receipt_date_to is not null then
		  	 RAISE_APPLICATION_ERROR(-20005, 'You must enter scheduled_receipt_date_from.');
		   end if ;
	   end if ;
	   if :new.scheduled_receipt_date_from > :new.scheduled_receipt_date_to then
		  	 RAISE_APPLICATION_ERROR(-20006, 'scheduled_receipt_date_from must be <= scheduled_receipt_date_to.');
	   else
	   	   :new.calendar_days := null ; -- the calendar days are no longer needed
	   end if ;
   end if ;
   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END AMD_ON_ORDER_DATE_FILTERS_TRG1;
/

SHOW ERRORS;



CREATE PUBLIC SYNONYM AMD_ON_ORDER_DATE_FILTERS FOR AMD_ON_ORDER_DATE_FILTERS;


CREATE PUBLIC SYNONYM AMD_ON_ORDER_FILTER_NAMES FOR AMD_ON_ORDER_FILTER_NAMES;


ALTER TABLE AMD_ON_ORDER_DATE_FILTERS ADD (
  CONSTRAINT AMD_ON_ORDER_DATE_FILTER_PK
 PRIMARY KEY
 (FILTER_NAME, VOUCHER_PREFIX)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

show errors

ALTER TABLE AMD_ON_ORDER_FILTER_NAMES ADD (
  CONSTRAINT AMD_ON_ORDER_FILTER_NAMES_PK
 PRIMARY KEY
 (FILTER_NAME)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_ON_ORDER_DATE_FILTERS ADD (
  CONSTRAINT AMD_ON_ORDER_DATE_FILTERS_FK01 
 FOREIGN KEY (FILTER_NAME) 
 REFERENCES AMD_ON_ORDER_FILTER_NAMES (FILTER_NAME));

show errors

GRANT SELECT ON  AMD_ON_ORDER_FILTER_NAMES TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_ON_ORDER_DATE_FILTERS TO AMD_READER_ROLE;

GRANT DELETE ON  AMD_ON_ORDER_FILTER_NAMES TO AMD_WRITER_ROLE;

GRANT DELETE ON  AMD_ON_ORDER_DATE_FILTERS TO AMD_WRITER_ROLE;

GRANT INSERT ON  AMD_ON_ORDER_FILTER_NAMES TO AMD_WRITER_ROLE;

GRANT INSERT ON  AMD_ON_ORDER_DATE_FILTERS TO AMD_WRITER_ROLE;

GRANT UPDATE ON  AMD_ON_ORDER_FILTER_NAMES TO AMD_WRITER_ROLE;

GRANT UPDATE ON  AMD_ON_ORDER_DATE_FILTERS TO AMD_WRITER_ROLE;


ALTER TABLE AMD_PLANNER_LOGONS
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_PLANNER_LOGONS CASCADE CONSTRAINTS;

CREATE TABLE AMD_PLANNER_LOGONS
(
  PLANNER_CODE    VARCHAR2(8 BYTE)              NOT NULL,
  LOGON_ID        VARCHAR2(8 BYTE)              NOT NULL,
  DATA_SOURCE     VARCHAR2(1 BYTE)              NOT NULL,
  DEFAULT_IND     VARCHAR2(1 BYTE),
  ACTION_CODE     VARCHAR2(1 BYTE)              DEFAULT 'A',
  LAST_UPDATE_DT  DATE                          DEFAULT SYSDATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX AMD_PLANNER_LOGONS_PK ON AMD_PLANNER_LOGONS
(PLANNER_CODE, LOGON_ID, DATA_SOURCE)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


show errors

DROP PUBLIC SYNONYM AMD_PLANNER_LOGONS;

CREATE PUBLIC SYNONYM AMD_PLANNER_LOGONS FOR AMD_PLANNER_LOGONS;


ALTER TABLE AMD_PLANNER_LOGONS ADD (
  CONSTRAINT AMD_PLANNER_LOGONS_PK
 PRIMARY KEY
 (PLANNER_CODE, LOGON_ID, DATA_SOURCE)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

show errors

GRANT SELECT ON  AMD_PLANNER_LOGONS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_PLANNER_LOGONS TO AMD_WRITER_ROLE;


INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AFA', '0230637', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AFA', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AFB', '0299644', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AFB', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AFC', '0248814', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AFC', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AFD', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AFD', '1059280', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AFM', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASA', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASA', '1127180', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASC', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASC', '0343644', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASD', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASD', '0400996', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASE', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASE', '1585760', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASF', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASF', '0337502', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASG', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'ASG', '0341972', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVA', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVA', '1621393', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVB', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVB', '0339037', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVC', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVC', '0342807', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVD', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVD', '1003465', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVE', '0289881', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVE', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVF', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVF', '0323505', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVF', '0342807', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVG', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'AVG', '1621764', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE1', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE2', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE2', '0808867', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE3', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE3', '0332931', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE4', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE4', '0323910', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE5', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE5', '0326958', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE6', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE6', '0325675', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE7', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE7', '0343216', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE8', '0287843', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE8', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'KE9', '0784072', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'NSA', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'NSA', '1561546', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'NSB', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'NSB', '0330563', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'NSD', '0235143', '1', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO AMD_PLANNER_LOGONS ( PLANNER_CODE, LOGON_ID, DATA_SOURCE, DEFAULT_IND, ACTION_CODE,
LAST_UPDATE_DT ) VALUES ( 
'NSD', '0302805', '2', NULL, 'A',  TO_Date( '06/04/2006 12:55:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
COMMIT;

show errors

ALTER TABLE AMD_BACKORDER_SPO_SUM
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_BACKORDER_SPO_SUM CASCADE CONSTRAINTS;

CREATE TABLE AMD_BACKORDER_SPO_SUM
(
  SPO_PRIME_PART_NO  VARCHAR2(40 BYTE)          NOT NULL,
  QTY                NUMBER,
  ACTION_CODE        VARCHAR2(1 BYTE)           NOT NULL,
  LAST_UPDATE_DT     DATE                       DEFAULT sysdate               NOT NULL
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX AMD_BACKORDER_SPO_SUM_PK ON AMD_BACKORDER_SPO_SUM
(SPO_PRIME_PART_NO)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM AMD_BACKORDER_SPO_SUM;

CREATE PUBLIC SYNONYM AMD_BACKORDER_SPO_SUM FOR AMD_BACKORDER_SPO_SUM;


ALTER TABLE AMD_BACKORDER_SPO_SUM ADD (
  CONSTRAINT AMD_BACKORDER_SPO_SUM_PK
 PRIMARY KEY
 (SPO_PRIME_PART_NO)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


GRANT SELECT ON  AMD_BACKORDER_SPO_SUM TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_BACKORDER_SPO_SUM TO AMD_WRITER_ROLE;


show errors 



DROP TABLE TMP_A2A_SITE_RESP_ASSET_MGR CASCADE CONSTRAINTS;

CREATE TABLE TMP_A2A_SITE_RESP_ASSET_MGR
(
  SITE_RESP_ASSET_MGR  VARCHAR2(20 BYTE)        NOT NULL,
  TOOL_LOGON_ID        VARCHAR2(20 BYTE)        NOT NULL,
  DATA_SOURCE          VARCHAR2(1 BYTE)         NOT NULL,
  ACTION_CODE          VARCHAR2(1 BYTE),
  LAST_UPDATE_DT       DATE                     DEFAULT sysdate
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX TMP_A2A_SITE_RESP_ASSET_MGR_PK ON TMP_A2A_SITE_RESP_ASSET_MGR
(SITE_RESP_ASSET_MGR, TOOL_LOGON_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM TMP_A2A_SITE_RESP_ASSET_MGR;

CREATE PUBLIC SYNONYM TMP_A2A_SITE_RESP_ASSET_MGR FOR TMP_A2A_SITE_RESP_ASSET_MGR;


GRANT SELECT ON  TMP_A2A_SITE_RESP_ASSET_MGR TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  TMP_A2A_SITE_RESP_ASSET_MGR TO AMD_WRITER_ROLE;



show errors


