    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:30  $
     $Workfile:   amd_spare_pipelines.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_spare_pipelines.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:30   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_SPARE_PIPELINES
(
  FROM_LOC_SID        NUMBER                    NOT NULL,
  TO_LOC_SID          NUMBER                    NOT NULL,
  TRANSPORT_AGENT_ID  VARCHAR2(40 BYTE)         NOT NULL,
  TRANSPORT_MODE_ID   VARCHAR2(40 BYTE)         NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_SPARE_PIPELINES_PK ON AMD_SPARE_PIPELINES
(FROM_LOC_SID, TO_LOC_SID, TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_SPARE_PIPELINES FOR AMD_SPARE_PIPELINES;


ALTER TABLE AMD_SPARE_PIPELINES ADD (
  CONSTRAINT AMD_SPARE_PIPELINES_CK01 CHECK (FROM_LOC_SID <> TO_LOC_SID));

ALTER TABLE AMD_SPARE_PIPELINES ADD (
  CONSTRAINT AMD_SPARE_PIPELINES_PK PRIMARY KEY (FROM_LOC_SID, TO_LOC_SID, TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_SPARE_PIPELINES ADD (
  CONSTRAINT AMD_SPARE_PIPELINES_FK01 FOREIGN KEY (FROM_LOC_SID) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID)
    ON DELETE CASCADE);

ALTER TABLE AMD_SPARE_PIPELINES ADD (
  CONSTRAINT AMD_SPARE_PIPELINES_FK02 FOREIGN KEY (TO_LOC_SID) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID)
    ON DELETE CASCADE);

ALTER TABLE AMD_SPARE_PIPELINES ADD (
  CONSTRAINT AMD_SPARE_PIPELINES_FK03 FOREIGN KEY (TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID) 
    REFERENCES AMD_TRANSPORT_MODES (TRANSPORT_AGENT_ID,TRANSPORT_MODE_ID));


GRANT SELECT ON  AMD_SPARE_PIPELINES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_SPARE_PIPELINES TO AMD_WRITER_ROLE;


