AMD_LOCATION_PART_OVERRIDE_PKG.sql                                              
AMD_CURRENT_PERIOD_V.sql                                                        
SPO_BACKORDER_TYPE_V.sql                                                        
SPO_BOM_DETAIL_V.sql                                                            
SPO_BOM_LOCATION_CONTRACT_V.sql                                                 
SPO_CAUSAL_TYPE_V.sql                                                           
SPO_CONFIRMED_REQUEST_LINE_V.sql                                                
SPO_CONFIRMED_REQUEST_V.sql                                                     
SPO_CONTRACT_CAUSAL_FORECAST_V.sql                                              
SPO_DEMAND_FORECAST_TYPE_V.sql                                                  
SPO_CONTRACT_CAUSAL_V.sql                                                       
SPO_FIXED_CURRENT_PERIOD_V.sql                                                  
SPO_DEMAND_TYPE_V.sql                                                           
SPO_FLAG_V.sql                                                                  
SPO_FX_LP_DEMAND_FORECAST_V.sql                                                 
SPO_IN_TRANSIT_TYPE_V.sql                                                       
SPO_INTERFACE_BATCH_V.sql                                                       
SPO_LEAD_TIME_TYPE_V.sql                                                        
SPO_LOCATION_V.sql                                                              
SPO_LP_ATTRIBUTE_V.sql                                                          
SPO_LP_BACKORDER_V.sql                                                          
SPO_LP_DEMAND_FORECAST_V.sql                                                    
SPO_LP_DEMAND_V.sql                                                             
SPO_LP_IN_TRANSIT_V.sql                                                         
SPO_LP_LEAD_TIME_V.sql                                                          
SPO_LP_ON_HAND_V.sql                                                            
SPO_LP_OVERRIDE_V.sql                                                           
SPO_MTBF_TYPE_V.sql                                                             
SPO_NETWORK_PART_V.sql                                                          
SPO_ON_HAND_TYPE_V.sql                                                          
SPO_OVERRIDE_TYPE_V.sql                                                         
SPO_PARAMETER_V.sql                                                             
SPO_PART_CAUSAL_TYPE_V.sql                                                      
SPO_PART_LEAD_TIME_V.sql                                                        
SPO_PART_MTBF_V.sql                                                             
SPO_PART_PLANNED_PART_V.sql                                                     
SPO_PART_UPGRADED_PART_V.sql                                                    
SPO_PART_V.sql                                                                  
SPO_PERIOD_V.sql                                                                
SPO_REQUEST_TYPE_V.sql                                                          
SPO_SUPERSESSION_TYPE_V.sql                                                     
SPO_USER_PART_V.sql                                                             
SPO_USER_TYPE_V.sql                                                             
SPO_USER_USER_TYPE_V.sql                                                        
SPO_USER_V.sql                                                                  
SPO_X_IMP_INTERFACE_BATCH_V.sql                                                 
AMD_SPO_TYPES_V.sql                                                             
X_CONFIRMED_REQUEST_LINE_V.sql                                                  
X_USER_PART_V.sql                                                               
X_BOM_DETAIL_V.sql                                                              
X_CONFIRMED_REQUEST_V.sql                                                       
X_LP_ATTRIBUTE_V.sql                                                            
X_LP_BACKORDER_V.sql                                                            
X_LP_DEMAND_FORECAST_V.sql                                                      
X_LP_DEMAND_V.sql                                                               
X_LP_IN_TRANSIT_V.sql                                                           
X_LP_LEAD_TIME_V.sql                                                            
X_LP_ON_HAND_V.sql                                                              
X_LP_OVERRIDE_V.sql                                                             
X_NETWORK_PART_V.sql                                                            
X_PART_CAUSAL_TYPE_V.sql                                                        
X_PART_LEAD_TIME_V.sql                                                          
X_PART_MTBF_V.sql                                                               
X_PART_PLANNED_PART_V.sql                                                       
X_PART_V.sql                                                                    
X_USER_USER_TYPE_V.sql                                                          
X_USER_V.sql                                                                    
