DROP VIEW AMD_OWNER.PGOLD_FEDC_V;

/* Formatted on 7/9/2012 4:24:26 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.PGOLD_FEDC_V
(
   PART_NUMBER,
   VENDOR_CODE,
   SEQ_NUMBER,
   VENDOR_PART,
   VENDOR_NAME,
   NIIN,
   NOUN,
   UNIT_OF_ISSUE,
   SOURCE_CODE,
   COGNIZANCE_CODE,
   PMI_CODE,
   DEMILITARIZATION_CODE,
   NSN,
   NSN_SMIC,
   SMRC,
   ERRC_CODE,
   ERRC_DESIGNATOR,
   IMS_DESIGNATOR_CODE,
   HAZARDOUS_MATERIAL_CODE,
   CRITICAL_ITEM_CODE,
   ISGP_GROUP_NO,
   BUDGET_CODE,
   SECURITY_CODE,
   GFP_PRICE,
   PRICE1,
   ACTIVITY_CODE,
   WRITE_FLAG
)
AS
   SELECT PART_NUMBER,
          VENDOR_CODE,
          SEQ_NUMBER,
          VENDOR_PART,
          VENDOR_NAME,
          NIIN,
          NOUN,
          UNIT_OF_ISSUE,
          SOURCE_CODE,
          COGNIZANCE_CODE,
          PMI_CODE,
          DEMILITARIZATION_CODE,
          NSN,
          NSN_SMIC,
          SMRC,
          ERRC_CODE,
          ERRC_DESIGNATOR,
          IMS_DESIGNATOR_CODE,
          HAZARDOUS_MATERIAL_CODE,
          CRITICAL_ITEM_CODE,
          ISGP_GROUP_NO,
          BUDGET_CODE,
          SECURITY_CODE,
          GFP_PRICE,
          PRICE1,
          ACTIVITY_CODE,
          WRITE_FLAG
     FROM fedc@amd_pgoldlb_link;


DROP PUBLIC SYNONYM PGOLD_FEDC_V;

CREATE OR REPLACE PUBLIC SYNONYM PGOLD_FEDC_V FOR AMD_OWNER.PGOLD_FEDC_V;


GRANT SELECT ON AMD_OWNER.PGOLD_FEDC_V TO AMD_READER_ROLE;
