    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:02  $
     $Workfile:   amd_data_owners.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_data_owners.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:02   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_DATA_OWNERS
(
  SOURCE      VARCHAR2(20 BYTE),
  DATA_OWNER  VARCHAR2(50 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE INDEX AMD_DATA_OWNERS_PK ON AMD_DATA_OWNERS
(SOURCE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_DATA_OWNERS FOR AMD_DATA_OWNERS;


ALTER TABLE AMD_DATA_OWNERS ADD (
  CHECK ("SOURCE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_DATA_OWNERS ADD (
  CHECK ("DATA_OWNER" IS NOT NULL) DISABLE);


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_DATA_OWNERS TO AMD_DATALOAD;

GRANT SELECT ON  AMD_DATA_OWNERS TO AMD_MAINT;

GRANT SELECT ON  AMD_DATA_OWNERS TO AMD_USER;

GRANT SELECT ON  AMD_DATA_OWNERS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_DATA_OWNERS TO AMD_WRITER_ROLE;


