set define off

ALTER TABLE AMD_OWNER.ACTIVE_NIINS
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_OWNER.ACTIVE_NIINS CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.ACTIVE_NIINS
(
  NIIN  VARCHAR2(9 BYTE)                        NOT NULL
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX AMD_OWNER.ACTIVE_NIINS_PK01 ON AMD_OWNER.ACTIVE_NIINS
(NIIN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM ACTIVE_NIINS;

CREATE PUBLIC SYNONYM ACTIVE_NIINS FOR AMD_OWNER.ACTIVE_NIINS;


ALTER TABLE AMD_OWNER.ACTIVE_NIINS ADD (
  CONSTRAINT ACTIVE_NIINS_PK01
 PRIMARY KEY
 (NIIN)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT SELECT ON AMD_OWNER.ACTIVE_NIINS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.ACTIVE_NIINS TO AMD_WRITER_ROLE;


