    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:34  $
     $Workfile:   amd_transport_modes.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_transport_modes.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:34   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_TRANSPORT_MODES
(
  TRANSPORT_AGENT_ID   VARCHAR2(40 BYTE)        NOT NULL,
  TRANSPORT_MODE_ID    VARCHAR2(40 BYTE)        NOT NULL,
  TRANSPORT_MODE_DESC  VARCHAR2(200 BYTE),
  ACTION_CODE          VARCHAR2(1 BYTE),
  LAST_UPDATE_DT       DATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_TRANSPORT_MODES_PK ON AMD_TRANSPORT_MODES
(TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_TRANSPORT_MODES FOR AMD_TRANSPORT_MODES;


ALTER TABLE AMD_TRANSPORT_MODES ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_TRANSPORT_MODES ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_TRANSPORT_MODES ADD (
  CONSTRAINT AMD_TRANSPORT_MODES_PK PRIMARY KEY (TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


GRANT SELECT ON  AMD_TRANSPORT_MODES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_TRANSPORT_MODES TO AMD_WRITER_ROLE;


