    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:10  $
     $Workfile:   amd_load_status.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_load_status.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:10   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_LOAD_STATUS
(
  LOAD_NO             NUMBER,
  SOURCE              VARCHAR2(20 BYTE),
  LOAD_DATE           DATE,
  TABLE_NAME          VARCHAR2(30 BYTE),
  DATA_FILE_NAME      VARCHAR2(100 BYTE),
  DATA_LINE_LOADED    NUMBER,
  DATA_LINE_REJECTED  NUMBER
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    5
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE INDEX AMD_LOAD_STATUS_LOAD_DATE_I ON AMD_LOAD_STATUS
(LOAD_DATE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_LOAD_STATUS FOR AMD_LOAD_STATUS;


ALTER TABLE AMD_LOAD_STATUS ADD (
  CHECK ("LOAD_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_LOAD_STATUS ADD (
  CHECK ("SOURCE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_LOAD_STATUS ADD (
  CHECK ("LOAD_DATE" IS NOT NULL) DISABLE);


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_LOAD_STATUS TO AMD_DATALOAD;

GRANT SELECT ON  AMD_LOAD_STATUS TO AMD_USER;

GRANT SELECT ON  AMD_LOAD_STATUS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_LOAD_STATUS TO AMD_WRITER_ROLE;


