    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:18  $
     $Workfile:   amd_part_loc_forecasts.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_part_loc_forecasts.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:18   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_PART_LOC_FORECASTS
(
  FORECAST_NAME      VARCHAR2(40 BYTE)          NOT NULL,
  NSI_SID            NUMBER                     NOT NULL,
  LOC_SID            NUMBER                     NOT NULL,
  TIME_PERIOD_START  DATE                       NOT NULL,
  TIME_PERIOD_END    DATE,
  FORECAST_QTY       NUMBER,
  ACTION_CODE        VARCHAR2(1 BYTE),
  LAST_UPDATE_DT     DATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_PART_LOC_FORECASTS_PK ON AMD_PART_LOC_FORECASTS
(FORECAST_NAME, NSI_SID, LOC_SID, TIME_PERIOD_START)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_PART_LOC_FORECASTS FOR AMD_PART_LOC_FORECASTS;


ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CHECK ("TIME_PERIOD_END" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CHECK ("FORECAST_QTY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CONSTRAINT AMD_PART_LOC_FORECASTS_PK PRIMARY KEY (FORECAST_NAME, NSI_SID, LOC_SID, TIME_PERIOD_START)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CONSTRAINT AMD_PART_LOC_FORECASTS_FK01 FOREIGN KEY (NSI_SID, LOC_SID) 
    REFERENCES AMD_PART_LOCS (NSI_SID,LOC_SID));

ALTER TABLE AMD_PART_LOC_FORECASTS ADD (
  CONSTRAINT AMD_PART_LOC_FORECASTS_FK02 FOREIGN KEY (TIME_PERIOD_START, TIME_PERIOD_END) 
    REFERENCES AMD_TIME_PERIODS (TIME_PERIOD_START,TIME_PERIOD_END));


GRANT SELECT ON  AMD_PART_LOC_FORECASTS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_PART_LOC_FORECASTS TO AMD_WRITER_ROLE;


