
CREATE TABLE AMD_AC_ASSIGNS
(
  ASSIGNMENT_START  DATE                        NOT NULL,
  ASSIGNMENT_END    DATE,
  TAIL_NO           VARCHAR2(7 BYTE)            NOT NULL,
  LOC_SID           NUMBER,
  LAST_UPDATE_DATE  DATE                        DEFAULT SYSDATE               NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_AC_ASSIGNS_PK ON AMD_AC_ASSIGNS
(ASSIGNMENT_START, TAIL_NO)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_AC_ASSIGNS FOR AMD_AC_ASSIGNS;


ALTER TABLE AMD_AC_ASSIGNS ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AC_ASSIGNS ADD (
  CONSTRAINT AMD_AC_ASSIGNS_PK PRIMARY KEY (ASSIGNMENT_START, TAIL_NO)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_AC_ASSIGNS ADD (
  CONSTRAINT AMD_AC_ASSIGNS_FK01 FOREIGN KEY (TAIL_NO) 
    REFERENCES AMD_AIRCRAFTS (TAIL_NO));

ALTER TABLE AMD_AC_ASSIGNS ADD (
  CONSTRAINT AMD_AC_ASSIGNS_FK02 FOREIGN KEY (LOC_SID) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


GRANT SELECT ON  AMD_AC_ASSIGNS TO ASIS_DATALOAD_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_AC_ASSIGNS TO AMD_DATALOAD;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_AC_ASSIGNS TO AMD_MAINT;

GRANT SELECT ON  AMD_AC_ASSIGNS TO AMD_USER;

GRANT SELECT ON  AMD_AC_ASSIGNS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_AC_ASSIGNS TO AMD_WRITER_ROLE;


