    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:52:58  $
     $Workfile:   amd_calendar_exceptions.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_calendar_exceptions.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:52:58   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_CALENDAR_EXCEPTIONS
(
  CALENDAR_NAME   VARCHAR2(40 BYTE)             NOT NULL,
  EXCEPTION_DATE  DATE                          NOT NULL,
  ACTION_CODE     VARCHAR2(1 BYTE),
  LAST_UPDATE_DT  DATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_CALENDAR_EXCEPTIONS_PK ON AMD_CALENDAR_EXCEPTIONS
(CALENDAR_NAME, EXCEPTION_DATE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_CALENDAR_EXCEPTIONS FOR AMD_CALENDAR_EXCEPTIONS;


ALTER TABLE AMD_CALENDAR_EXCEPTIONS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDAR_EXCEPTIONS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDAR_EXCEPTIONS ADD (
  CONSTRAINT AMD_CALENDAR_EXCEPTIONS_PK PRIMARY KEY (CALENDAR_NAME, EXCEPTION_DATE)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_CALENDAR_EXCEPTIONS ADD (
  CONSTRAINT AMD_CALENDAR_EXCEPTIONS_FK01 FOREIGN KEY (CALENDAR_NAME) 
    REFERENCES AMD_CALENDARS (CALENDAR_NAME)
    ON DELETE CASCADE);


GRANT SELECT ON  AMD_CALENDAR_EXCEPTIONS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_CALENDAR_EXCEPTIONS TO AMD_WRITER_ROLE;


