    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:02  $
     $Workfile:   amd_escalation_factors.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_escalation_factors.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:02   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_ESCALATION_FACTORS
(
  EFFECTIVE_DATE     DATE                       NOT NULL,
  TIME_PERIOD        DATE                       NOT NULL,
  ESCALATION_FACTOR  NUMBER,
  INDEX_TYPE         VARCHAR2(6 BYTE)           NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_ESCALATION_FACTORS_PK ON AMD_ESCALATION_FACTORS
(EFFECTIVE_DATE, TIME_PERIOD, INDEX_TYPE)
LOGGING
TABLESPACE AMD_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_ESCALATION_FACTORS FOR AMD_ESCALATION_FACTORS;


ALTER TABLE AMD_ESCALATION_FACTORS ADD (
  CHECK ("ESCALATION_FACTOR" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ESCALATION_FACTORS ADD (
  CONSTRAINT AMD_ESCALATION_FACTORS_PK PRIMARY KEY (EFFECTIVE_DATE, TIME_PERIOD, INDEX_TYPE)
    USING INDEX 
    TABLESPACE AMD_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_ESCALATION_FACTORS TO AMD_COSMIC_SUPERUSER;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_ESCALATION_FACTORS TO AMD_DATALOAD;

GRANT SELECT ON  AMD_ESCALATION_FACTORS TO AMD_USER;

GRANT SELECT ON  AMD_ESCALATION_FACTORS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_ESCALATION_FACTORS TO AMD_WRITER_ROLE;


