    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:30  $
     $Workfile:   amd_spare_parts.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_spare_parts.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:30   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_SPARE_PARTS
(
  PART_NO                    VARCHAR2(50 BYTE)  NOT NULL,
  MFGR                       VARCHAR2(13 BYTE),
  DATE_ICP                   DATE,
  DISPOSAL_COST              NUMBER,
  DISPOSAL_COST_DEFAULTED    NUMBER,
  ERC                        VARCHAR2(1 BYTE),
  ICP_IND                    VARCHAR2(3 BYTE),
  NOMENCLATURE               VARCHAR2(512 BYTE),
  ORDER_LEAD_TIME            NUMBER,
  ORDER_LEAD_TIME_DEFAULTED  NUMBER,
  ORDER_UOM                  VARCHAR2(2 BYTE),
  ORDER_UOM_DEFAULTED        VARCHAR2(2 BYTE),
  SCRAP_VALUE                NUMBER,
  SCRAP_VALUE_DEFAULTED      NUMBER,
  SERIAL_FLAG                VARCHAR2(1 BYTE),
  SHELF_LIFE                 NUMBER,
  SHELF_LIFE_DEFAULTED       NUMBER,
  UNIT_COST                  NUMBER,
  UNIT_COST_DEFAULTED        NUMBER,
  UNIT_VOLUME                NUMBER,
  UNIT_VOLUME_DEFAULTED      NUMBER,
  NSN                        VARCHAR2(15 BYTE),
  TACTICAL                   VARCHAR2(1 BYTE),
  ACTION_CODE                VARCHAR2(1 BYTE),
  LAST_UPDATE_DT             DATE,
  PROCESS_BYPASS             VARCHAR2(40 BYTE),
  ACQUISITION_ADVICE_CODE    VARCHAR2(1 BYTE),
  UNIT_OF_ISSUE              VARCHAR2(2 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_SPARE_PARTS_PK ON AMD_SPARE_PARTS
(PART_NO)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_SPARE_PARTS FOR AMD_SPARE_PARTS;


ALTER TABLE AMD_SPARE_PARTS ADD (
  CHECK ("ICP_IND" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_PARTS ADD (
  CHECK ("NOMENCLATURE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_PARTS ADD (
  CHECK ("TACTICAL" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_PARTS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_PARTS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_SPARE_PARTS ADD (
  CONSTRAINT AMD_SPARE_PARTS_PK PRIMARY KEY (PART_NO)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_SPARE_PARTS ADD (
  CONSTRAINT AMD_SPARE_PARTS_FK01 FOREIGN KEY (NSN) 
    REFERENCES AMD_NSNS (NSN));

ALTER TABLE AMD_SPARE_PARTS ADD (
  CONSTRAINT AMD_SPARE_PARTS_FK02 FOREIGN KEY (ORDER_UOM) 
    REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_SPARE_PARTS ADD (
  CONSTRAINT AMD_SPARE_PARTS_FK03 FOREIGN KEY (ORDER_UOM_DEFAULTED) 
    REFERENCES AMD_UOMS (UOM_CODE));


GRANT SELECT ON  AMD_SPARE_PARTS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_SPARE_PARTS TO AMD_WRITER_ROLE;


