    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:24  $
     $Workfile:   amd_product_structure.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_product_structure.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:24   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_PRODUCT_STRUCTURE
(
  ASSY_NSI_SID  NUMBER                          NOT NULL,
  COMP_NSI_SID  NUMBER                          NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_PRODUCT_STRUCTURE_PK ON AMD_PRODUCT_STRUCTURE
(ASSY_NSI_SID, COMP_NSI_SID)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_PRODUCT_STRUCTURE FOR AMD_PRODUCT_STRUCTURE;


ALTER TABLE AMD_PRODUCT_STRUCTURE ADD (
  CONSTRAINT AMD_PRODUCT_STRUCTURE_PK PRIMARY KEY (ASSY_NSI_SID, COMP_NSI_SID)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_PRODUCT_STRUCTURE ADD (
  CONSTRAINT AMD_PRODUCT_STRUCTURE_FK01 FOREIGN KEY (ASSY_NSI_SID) 
    REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));

ALTER TABLE AMD_PRODUCT_STRUCTURE ADD (
  CONSTRAINT AMD_PRODUCT_STRUCTURE_FK02 FOREIGN KEY (COMP_NSI_SID) 
    REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));


GRANT SELECT ON  AMD_PRODUCT_STRUCTURE TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_PRODUCT_STRUCTURE TO AMD_WRITER_ROLE;


