    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:04  $
     $Workfile:   amd_forecasted_ac_usages.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_forecasted_ac_usages.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:04   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_FORECASTED_AC_USAGES
(
  LOC_SID         NUMBER                        NOT NULL,
  EFFECTIVE_DATE  DATE                          NOT NULL,
  USAGE           NUMBER,
  UOM_CODE        VARCHAR2(2 BYTE)              NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE INDEX AMD_FOR__AMD_UOM_FK01_FK_I ON AMD_FORECASTED_AC_USAGES
(UOM_CODE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_FOR__FK_I ON AMD_FORECASTED_AC_USAGES
(LOC_SID)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AMD_FOR_AC_USAGES_PK ON AMD_FORECASTED_AC_USAGES
(LOC_SID, EFFECTIVE_DATE, UOM_CODE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_FORECASTED_AC_USAGES FOR AMD_FORECASTED_AC_USAGES;


ALTER TABLE AMD_FORECASTED_AC_USAGES ADD (
  CHECK ("USAGE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_FORECASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FOR_AC_USAGES_PK PRIMARY KEY (LOC_SID, EFFECTIVE_DATE, UOM_CODE)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_FORECASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FOR__AMD_UOM_FK01_FK FOREIGN KEY (UOM_CODE) 
    REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_FORECASTED_AC_USAGES ADD (
  CONSTRAINT AMD_FOR__FK FOREIGN KEY (LOC_SID) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_FORECASTED_AC_USAGES TO AMD_DATALOAD;

GRANT SELECT ON  AMD_FORECASTED_AC_USAGES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_FORECASTED_AC_USAGES TO AMD_WRITER_ROLE;


