    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:22  $
     $Workfile:   amd_part_next_assemblies.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_part_next_assemblies.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:22   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_PART_NEXT_ASSEMBLIES
(
  PN_NA_SID                NUMBER               NOT NULL,
  NEXT_ASSEMBLY_PART_NO    VARCHAR2(20 BYTE),
  NEXT_ASSEMBLY_CAGE_CODE  VARCHAR2(5 BYTE),
  REWORK_PART_NO           VARCHAR2(20 BYTE),
  REWORK_CAGE_CODE         VARCHAR2(5 BYTE),
  SCRAP_FLAG               VARCHAR2(1 BYTE),
  COMPONENT_PART_NO        VARCHAR2(20 BYTE),
  COMPONENT_MFGR           VARCHAR2(13 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    5
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_PART_NEXT_ASSM_PK ON AMD_PART_NEXT_ASSEMBLIES
(PN_NA_SID)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AMD_PART_NEXT_ASSEMBLIES_PK2 ON AMD_PART_NEXT_ASSEMBLIES
(COMPONENT_PART_NO, COMPONENT_MFGR, NEXT_ASSEMBLY_PART_NO, NEXT_ASSEMBLY_CAGE_CODE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_PART_NEXT_ASSEMBLIES FOR AMD_PART_NEXT_ASSEMBLIES;


ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CHECK ("NEXT_ASSEMBLY_PART_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CHECK ("NEXT_ASSEMBLY_CAGE_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CHECK ("COMPONENT_PART_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CHECK ("COMPONENT_MFGR" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CONSTRAINT AMD_PART_NEXT_ASSM_PK PRIMARY KEY (PN_NA_SID)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CONSTRAINT AMD_PART_NEXT_ASSEMBLIES_PK2 UNIQUE (COMPONENT_PART_NO, COMPONENT_MFGR, NEXT_ASSEMBLY_PART_NO, NEXT_ASSEMBLY_CAGE_CODE)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_PART_NEXT_ASSEMBLIES ADD (
  CONSTRAINT AMD_PART_NEXT_ASSEMBLIES_FK01 FOREIGN KEY (COMPONENT_PART_NO) 
    REFERENCES AMD_SPARE_PARTS (PART_NO));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_PART_NEXT_ASSEMBLIES TO AMD_DATALOAD;

GRANT SELECT ON  AMD_PART_NEXT_ASSEMBLIES TO AMD_USER;

GRANT SELECT ON  AMD_PART_NEXT_ASSEMBLIES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_PART_NEXT_ASSEMBLIES TO AMD_WRITER_ROLE;


