DROP TABLE AMD_OWNER.AMD_WARNER_ROBINS_FILES CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.AMD_WARNER_ROBINS_FILES
(
  EXCEL_ROW               NUMBER                NOT NULL,
  SOURCE_CODE             VARCHAR2(3 BYTE)      NOT NULL,
  TRANSACTION_DATE        DATE                  NOT NULL,
  NSN                     VARCHAR2(15 BYTE)     NOT NULL,
  DOC_NO                  VARCHAR2(20 BYTE),
  DEMAND_QUANTITY         NUMBER                NOT NULL,
  FILENAME                VARCHAR2(100 BYTE)    NOT NULL,
  LAST_UPDATE_DT          DATE                  DEFAULT sysdate,
  DATE_LOADED_TO_DEMANDS  DATE,
  BAD_NSN                 CHAR(1 BYTE),
  ACTION_CODE             VARCHAR2(1 BYTE)
)
TABLESPACE AMD_INDEX
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON AMD_OWNER.AMD_WARNER_ROBINS_FILES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_WARNER_ROBINS_FILES TO AMD_WRITER_ROLE;
