    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:26  $
     $Workfile:   amd_related_nsi_pairs.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_related_nsi_pairs.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:26   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_RELATED_NSI_PAIRS
(
  REPLACED_NSI_SID     NUMBER                   NOT NULL,
  REPLACED_BY_NSI_SID  NUMBER                   NOT NULL,
  UPGRADEABLE          VARCHAR2(1 BYTE)         NOT NULL,
  INTERCHANGE_TYPE     VARCHAR2(15 BYTE)        NOT NULL,
  TCTO_NUMBER          VARCHAR2(13 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_RELATED_NSI_PAIRS_PK ON AMD_RELATED_NSI_PAIRS
(REPLACED_NSI_SID, REPLACED_BY_NSI_SID)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_RELATED_NSI_PAIRS FOR AMD_RELATED_NSI_PAIRS;


ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_NSI_UPGRADEABLE_CK CHECK (
         UPGRADEABLE IN ('Y', 'N')));

ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_PAIRS_INTERCHG_CK CHECK (
			interchange_type in ('limited','Not','1-way','2-way')
		));

ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_NSI_PAIRS_PK PRIMARY KEY (REPLACED_NSI_SID, REPLACED_BY_NSI_SID)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_NSI_PAIRS_FK01 FOREIGN KEY (REPLACED_NSI_SID) 
    REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));

ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_NSI_PAIRS_FK02 FOREIGN KEY (REPLACED_BY_NSI_SID) 
    REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));

ALTER TABLE AMD_RELATED_NSI_PAIRS ADD (
  CONSTRAINT AMD_RELATED_NSI_PAIRS_FK03 FOREIGN KEY (TCTO_NUMBER) 
    REFERENCES AMD_RETROFIT_TCTOS (TCTO_NUMBER));


GRANT SELECT ON  AMD_RELATED_NSI_PAIRS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_RELATED_NSI_PAIRS TO AMD_WRITER_ROLE;


