    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:22  $
     $Workfile:   amd_planners.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_planners.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:22   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_PLANNERS
(
  PLANNER_CODE         VARCHAR2(8 BYTE)         NOT NULL,
  PLANNER_DESCRIPTION  VARCHAR2(30 BYTE),
  SUPERVISOR_CODE      VARCHAR2(7 BYTE),
  ACTION_CODE          VARCHAR2(1 BYTE)         DEFAULT 'A',
  LAST_UPDATE_DT       DATE                     DEFAULT SYSDATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_PLANNERS_PK ON AMD_PLANNERS
(PLANNER_CODE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_PLANNERS FOR AMD_PLANNERS;


ALTER TABLE AMD_PLANNERS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PLANNERS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PLANNERS ADD (
  CONSTRAINT AMD_PLANNERS_PK PRIMARY KEY (PLANNER_CODE)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_PLANNERS ADD (
  CONSTRAINT AMD_PLANNERS_FK01 FOREIGN KEY (SUPERVISOR_CODE) 
    REFERENCES AMD_PLANNERS (PLANNER_CODE));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_PLANNERS TO AMD_DATALOAD;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_PLANNERS TO AMD_MAINT;

GRANT SELECT ON  AMD_PLANNERS TO AMD_USER;

GRANT SELECT ON  AMD_PLANNERS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_PLANNERS TO AMD_WRITER_ROLE;


