    /*   				
       $Author:   c970183  $
     $Revision:   1.1  $
         $Date:   May 20 2005 09:23:58  $
     $Workfile:   amd_national_stock_items.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_national_stock_items.sql-arc  $
/*   
/*      Rev 1.1   May 20 2005 09:23:58   c970183
/*   changed dla_warehouse_stock and dla_warehouse_stock_cleaned to current_backorder and current_backorder_cleaned.
/*   Added changed indicators.
/*   
/*      Rev 1.0   May 20 2005 09:18:32   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_NATIONAL_STOCK_ITEMS
(
  NSI_SID                         NUMBER        NOT NULL,
  NSN                             VARCHAR2(15 BYTE),
  ADD_INCREMENT                   NUMBER,
  ADD_INCREMENT_CLEANED           NUMBER,
  AMC_BASE_STOCK                  NUMBER,
  AMC_BASE_STOCK_CLEANED          NUMBER,
  AMC_DAYS_EXPERIENCE             NUMBER,
  AMC_DAYS_EXPERIENCE_CLEANED     NUMBER,
  AMC_DEMAND                      NUMBER,
  AMC_DEMAND_CLEANED              NUMBER,
  CAPABILITY_REQUIREMENT          VARCHAR2(1 BYTE),
  CAPABILITY_REQUIREMENT_CLEANED  VARCHAR2(1 BYTE),
  CRITICALITY                     NUMBER,
  CRITICALITY_CLEANED             NUMBER,
  DISTRIB_UOM                     VARCHAR2(2 BYTE),
  DISTRIB_UOM_DEFAULTED           VARCHAR2(2 BYTE),
  DLA_DEMAND                      NUMBER,
  DLA_DEMAND_CLEANED              NUMBER,
  CURRENT_BACKORDER               NUMBER,
  CURRENT_BACKORDER_CLEANED       NUMBER,
  FEDC_COST                       NUMBER,
  FEDC_COST_CLEANED               NUMBER,
  ITEM_TYPE                       VARCHAR2(1 BYTE),
  ITEM_TYPE_CLEANED               VARCHAR2(1 BYTE),
  MIC_CODE_LOWEST                 VARCHAR2(1 BYTE),
  MIC_CODE_LOWEST_CLEANED         VARCHAR2(1 BYTE),
  MTBDR                           NUMBER,
  MTBDR_CLEANED                   NUMBER,
  NOMENCLATURE_CLEANED            VARCHAR2(512 BYTE),
  ORDER_LEAD_TIME_CLEANED         NUMBER,
  ORDER_QUANTITY                  NUMBER,
  ORDER_QUANTITY_DEFAULTED        NUMBER,
  ORDER_UOM_CLEANED               VARCHAR2(2 BYTE),
  PLANNER_CODE                    VARCHAR2(8 BYTE),
  PLANNER_CODE_CLEANED            VARCHAR2(8 BYTE),
  PRIME_PART_NO                   VARCHAR2(50 BYTE),
  QPEI_WEIGHTED                   NUMBER,
  QPEI_WEIGHTED_DEFAULTED         NUMBER,
  RU_IND                          VARCHAR2(1 BYTE),
  RU_IND_CLEANED                  VARCHAR2(1 BYTE),
  SMR_CODE                        VARCHAR2(6 BYTE),
  SMR_CODE_DEFAULTED              VARCHAR2(6 BYTE),
  SMR_CODE_CLEANED                VARCHAR2(6 BYTE),
  UNIT_COST_CLEANED               NUMBER,
  USER_COMMENT                    VARCHAR2(512 BYTE),
  CONDEMN_AVG                     NUMBER,
  CONDEMN_AVG_DEFAULTED           NUMBER,
  CONDEMN_AVG_CLEANED             NUMBER,
  NRTS_AVG                        NUMBER,
  NRTS_AVG_DEFAULTED              NUMBER,
  NRTS_AVG_CLEANED                NUMBER,
  RTS_AVG                         NUMBER,
  RTS_AVG_DEFAULTED               NUMBER,
  RTS_AVG_CLEANED                 NUMBER,
  COST_TO_REPAIR_OFF_BASE_CLEAND  NUMBER,
  TIME_TO_REPAIR_OFF_BASE_CLEAND  NUMBER,
  TIME_TO_REPAIR_ON_BASE_AVG      NUMBER,
  TIME_TO_REPAIR_ON_BASE_AVG_DF   NUMBER,
  TIME_TO_REPAIR_ON_BASE_AVG_CL   NUMBER,
  MIN_PURCHASE_QUANTITY           NUMBER,
  DEMAND_VARIANCE                 NUMBER,
  TACTICAL                        VARCHAR2(1 BYTE) NOT NULL,
  ACTION_CODE                     VARCHAR2(1 BYTE) NOT NULL,
  LAST_UPDATE_DT                  DATE          NOT NULL,
  TACTICAL_REPLAN                 VARCHAR2(1 BYTE),
  CONDEMN_COST                    NUMBER,
  FORECAST_IGNORE                 VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
  DEPLETION_START_DATE            DATE,
  EFFECT_LAST_UPDATE_ID           VARCHAR2(8 BYTE),
  EFFECT_LAST_UPDATE_DT           DATE,
  EFFECT_BY                       VARCHAR2(1 BYTE),
  ASSET_MGMT_STATUS               VARCHAR2(15 BYTE),
  LATEST_CONFIG                   VARCHAR2(1 BYTE),
  SPARE_START_DATE                DATE,
  NSI_GROUP_SID                   NUMBER,
  MMAC                            VARCHAR2(2 BYTE),
  CRITICALITY_CHANGED             VARCHAR2(1 BYTE) DEFAULT 'N',
  NRTS_AVG_CHANGED                VARCHAR2(1 BYTE) DEFAULT 'N',
  RTS_AVG_CHANGED                 VARCHAR2(1 BYTE) DEFAULT 'N',
  CONDEMN_AVG_CHANGED             VARCHAR2(1 BYTE) DEFAULT 'N',
  SPO_TOTAL_INVENTORY             NUMBER,
  COST_TO_REPAIR_OFF_BASE         NUMBER,
  TIME_TO_REPAIR_OFF_BASE         NUMBER,
  COST_TO_REPAIR_OFF_BASE_CHGED   VARCHAR2(1 BYTE) DEFAULT 'N',
  TIME_TO_REPAIR_OFF_BASE_CHGED   VARCHAR2(1 BYTE) DEFAULT 'N'
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON COLUMN AMD_NATIONAL_STOCK_ITEMS.SPO_TOTAL_INVENTORY IS 'value does not represent total if part is prime as determined by bssm_rbl_pairs';


CREATE UNIQUE INDEX AMD_NATIONAL_STOCK_ITEMS_PK ON AMD_NATIONAL_STOCK_ITEMS
(NSI_SID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AMD_NATIONAL_STOCK_ITEMS_UC01 ON AMD_NATIONAL_STOCK_ITEMS
(NSN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER amd_national_stock_items_trig1
before insert
on amd_national_stock_items
for each row
--
-- SCCSID:  %M%   %I%   Modified: %G%  %U%
--
--   $Author:   c970183  $
-- $Revision:   1.1  $
--     $Date:   May 20 2005 09:23:58  $
-- $Workfile:   amd_national_stock_items.sql  $
--
-- 02/13/03  FF     Added check to allow user-specific nsi_sids.
--                  Useful when copying data from one db to another.
declare
begin
	if (:new.nsi_sid is null) then
		select amd_nsi_sid_seq.nextval into :new.nsi_sid from dual;
	end if;
end;
/
SHOW ERRORS;



CREATE PUBLIC SYNONYM AMD_NATIONAL_STOCK_ITEMS FOR AMD_NATIONAL_STOCK_ITEMS;


ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_CK01 CHECK (
       NOT (ORDER_QUANTITY IS NULL
          AND ORDER_QUANTITY_DEFAULTED IS NULL)
       ));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NSIS_EFFECT_BY_CK CHECK (
            EFFECT_BY IN ('S', 'F')));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NSIS_LATEST_CONFIG_CK CHECK (
         LATEST_CONFIG IS NULL OR
         LATEST_CONFIG IN ('Y', 'N')
      ));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_PK PRIMARY KEY (NSI_SID)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_UC01 UNIQUE (NSN)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK01 FOREIGN KEY (NSN) 
    REFERENCES AMD_NSNS (NSN));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK02 FOREIGN KEY (PRIME_PART_NO) 
    REFERENCES AMD_SPARE_PARTS (PART_NO));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK03 FOREIGN KEY (PLANNER_CODE) 
    REFERENCES AMD_PLANNERS (PLANNER_CODE));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK04 FOREIGN KEY (PLANNER_CODE_CLEANED) 
    REFERENCES AMD_PLANNERS (PLANNER_CODE));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK05 FOREIGN KEY (DISTRIB_UOM) 
    REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK06 FOREIGN KEY (DISTRIB_UOM_DEFAULTED) 
    REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK07 FOREIGN KEY (ORDER_UOM_CLEANED) 
    REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS ADD (
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK09 FOREIGN KEY (NSI_GROUP_SID) 
    REFERENCES AMD_NSI_GROUPS (NSI_GROUP_SID));


GRANT SELECT ON  AMD_NATIONAL_STOCK_ITEMS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_NATIONAL_STOCK_ITEMS TO AMD_WRITER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_NATIONAL_STOCK_ITEMS TO BSSM_OWNER WITH GRANT OPTION;


