
CREATE TABLE AMD_ICAO_XREF
(
  ICAO           VARCHAR2(4 BYTE)               NOT NULL,
  LOCATION_NAME  VARCHAR2(25 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    0
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_ICAO_XREF_PK ON AMD_ICAO_XREF
(ICAO)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_ICAO_XREF FOR AMD_ICAO_XREF;


ALTER TABLE AMD_ICAO_XREF ADD (
  CHECK ("LOCATION_NAME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ICAO_XREF ADD (
  CONSTRAINT AMD_ICAO_XREF_PK PRIMARY KEY (ICAO)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_ICAO_XREF TO AMD_DATALOAD;

GRANT SELECT ON  AMD_ICAO_XREF TO AMD_USER;

GRANT SELECT ON  AMD_ICAO_XREF TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_ICAO_XREF TO AMD_WRITER_ROLE;


