    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:10  $
     $Workfile:   amd_ltd_fleet_size_member.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_ltd_fleet_size_member.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:10   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_LTD_FLEET_SIZE_MEMBER
(
  FLEET_SIZE_NAME  VARCHAR2(15 BYTE)            NOT NULL,
  TAIL_NO          VARCHAR2(7 BYTE)             NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_FLEET_SIZE_MEMBER_PK ON AMD_LTD_FLEET_SIZE_MEMBER
(FLEET_SIZE_NAME, TAIL_NO)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_LTD_FLEET_SIZE_MEMBER FOR AMD_LTD_FLEET_SIZE_MEMBER;


ALTER TABLE AMD_LTD_FLEET_SIZE_MEMBER ADD (
  CONSTRAINT AMD_FLEET_SIZE_MEMBER_PK PRIMARY KEY (FLEET_SIZE_NAME, TAIL_NO)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_LTD_FLEET_SIZE_MEMBER ADD (
  CONSTRAINT AMD_LTD_FLEET_SIZE_MEMBER_FK01 FOREIGN KEY (FLEET_SIZE_NAME) 
    REFERENCES AMD_FLEET_SIZES (FLEET_SIZE_NAME));

ALTER TABLE AMD_LTD_FLEET_SIZE_MEMBER ADD (
  CONSTRAINT AMD_LTD_FLEET_SIZE_MEMBER_FK02 FOREIGN KEY (TAIL_NO) 
    REFERENCES AMD_AIRCRAFTS (TAIL_NO));


GRANT SELECT ON  AMD_LTD_FLEET_SIZE_MEMBER TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_LTD_FLEET_SIZE_MEMBER TO AMD_WRITER_ROLE;


