    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:52:58  $
     $Workfile:   amd_bods.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_bods.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:52:58   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_BODS
(
  FROM_LOC_SID        NUMBER                    NOT NULL,
  TO_LOC_SID          NUMBER                    NOT NULL,
  TRANSPORT_AGENT_ID  VARCHAR2(40 BYTE)         NOT NULL,
  TRANSPORT_MODE_ID   VARCHAR2(40 BYTE)         NOT NULL,
  BOD_SUBJECT         VARCHAR2(40 BYTE)         NOT NULL,
  BOD_SUBJECT_TYPE    VARCHAR2(1 BYTE),
  NSI_SID             NUMBER,
  BOD_TIME            NUMBER,
  SOURCING_PRIORITY   NUMBER,
  ACTION_CODE         VARCHAR2(1 BYTE),
  LAST_UPDATE_DT      DATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_BODS_PK ON AMD_BODS
(FROM_LOC_SID, TO_LOC_SID, TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID, BOD_SUBJECT)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_BODS FOR AMD_BODS;


ALTER TABLE AMD_BODS ADD (
  CHECK ("BOD_SUBJECT_TYPE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BODS ADD (
  CHECK ("BOD_TIME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BODS ADD (
  CHECK ("SOURCING_PRIORITY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BODS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BODS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BODS ADD (
  CONSTRAINT AMD_BODS_PK PRIMARY KEY (FROM_LOC_SID, TO_LOC_SID, TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID, BOD_SUBJECT)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_BODS ADD (
  CONSTRAINT AMD_BODS_FK01 FOREIGN KEY (FROM_LOC_SID, TO_LOC_SID, TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID) 
    REFERENCES AMD_SPARE_PIPELINES (FROM_LOC_SID,TO_LOC_SID,TRANSPORT_AGENT_ID,TRANSPORT_MODE_ID)
    ON DELETE CASCADE);

ALTER TABLE AMD_BODS ADD (
  CONSTRAINT AMD_BODS_FK02 FOREIGN KEY (NSI_SID) 
    REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID)
    ON DELETE CASCADE);


GRANT SELECT ON  AMD_BODS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_BODS TO AMD_WRITER_ROLE;


