    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:52:56  $
     $Workfile:   amd_award_fee_schds.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_award_fee_schds.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:52:56   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_AWARD_FEE_SCHDS
(
  EFFECTIVE_DATE   DATE                         NOT NULL,
  UOM_CODE         VARCHAR2(2 BYTE)             NOT NULL,
  PERF_VALUE       NUMBER                       NOT NULL,
  AWARD_FEE_PCT    NUMBER,
  AWARD_FEE_LEVEL  VARCHAR2(20 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE INDEX FEESCHD_AWARD_FK_I ON AMD_AWARD_FEE_SCHDS
(UOM_CODE, EFFECTIVE_DATE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FEESCHD_PK ON AMD_AWARD_FEE_SCHDS
(EFFECTIVE_DATE, UOM_CODE, PERF_VALUE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_AWARD_FEE_SCHDS FOR AMD_AWARD_FEE_SCHDS;


ALTER TABLE AMD_AWARD_FEE_SCHDS ADD (
  CHECK ("AWARD_FEE_PCT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_AWARD_FEE_SCHDS ADD (
  CONSTRAINT FEESCHD_PK PRIMARY KEY (EFFECTIVE_DATE, UOM_CODE, PERF_VALUE)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_AWARD_FEE_SCHDS ADD (
  CONSTRAINT FEESCHD_AWARD_FK FOREIGN KEY (UOM_CODE, EFFECTIVE_DATE) 
    REFERENCES AMD_AWARD_FEES (UOM_CODE,EFFECTIVE_DATE));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_AWARD_FEE_SCHDS TO AMD_DATALOAD;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_AWARD_FEE_SCHDS TO AMD_MAINT;

GRANT SELECT ON  AMD_AWARD_FEE_SCHDS TO AMD_USER;

GRANT SELECT ON  AMD_AWARD_FEE_SCHDS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_AWARD_FEE_SCHDS TO AMD_WRITER_ROLE;


