    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:52:52  $
     $Workfile:   amd_actual_performances.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_actual_performances.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:52:52   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_ACTUAL_PERFORMANCES
(
  LOC_SID         NUMBER                        NOT NULL,
  UOM_CODE        VARCHAR2(2 BYTE)              NOT NULL,
  EFFECTIVE_DATE  DATE                          NOT NULL,
  VALUE           NUMBER
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE INDEX ACT_PERF__AMD_UOMS_FK_I ON AMD_ACTUAL_PERFORMANCES
(UOM_CODE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AMD_ACTUAL_PERFORMANCES_PK ON AMD_ACTUAL_PERFORMANCES
(EFFECTIVE_DATE, LOC_SID, UOM_CODE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_ACTUAL_PERFORMANCES FOR AMD_ACTUAL_PERFORMANCES;


ALTER TABLE AMD_ACTUAL_PERFORMANCES ADD (
  CHECK ("VALUE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ACTUAL_PERFORMANCES ADD (
  CONSTRAINT AMD_ACTUAL_PERFORMANCES_PK PRIMARY KEY (EFFECTIVE_DATE, LOC_SID, UOM_CODE)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_ACTUAL_PERFORMANCES ADD (
  CONSTRAINT ACT_PERF__AMD_UOMS_FK FOREIGN KEY (UOM_CODE) 
    REFERENCES AMD_UOMS (UOM_CODE));

ALTER TABLE AMD_ACTUAL_PERFORMANCES ADD (
  CONSTRAINT ACT_PERF__FK FOREIGN KEY (LOC_SID) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_ACTUAL_PERFORMANCES TO AMD_DATALOAD;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_ACTUAL_PERFORMANCES TO AMD_MAINT;

GRANT SELECT ON  AMD_ACTUAL_PERFORMANCES TO AMD_USER;

GRANT SELECT ON  AMD_ACTUAL_PERFORMANCES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_ACTUAL_PERFORMANCES TO AMD_WRITER_ROLE;


