/*+========================================================================+*/
/*| FILE: AMDv1_2.sql                                                      |*/
/*|------------------------------------------------------------------------|*/
/*| Who | Date       | Description                                         |*/
/*|------------------------------------------------------------------------|*/
/*| PAB | Sep 24, 01 | Initial complete DDL generation for AMDv1.2         |*/
/*+========================================================================+*/
/* ks this version was used for implementation 9/26/01 into amdd */
/* ks changed all AMD_NDX to AMD_INDEX */
/* ks changed all drops to drop TABLE */
/* Drop "deadwood" */

drop TABLE AMD_ALTERNATE_PARTS cascade constraints;
drop TABLE AMD_AWARD_FEE_SNAPSHOTS cascade constraints;
drop TABLE AMD_BASE_FORECASTS cascade constraints;
drop TABLE AMD_BASE_PART_FORECASTS cascade constraints;
drop TABLE AMD_BASE_PART_SNAPSHOTS cascade constraints;
drop TABLE AMD_BASE_SNAPSHOTS cascade constraints;
drop TABLE AMD_CAUSAL_FACTORS cascade constraints;
drop TABLE AMD_CAUSAL_FCTR_SNAPSHOTS cascade constraints;
drop TABLE AMD_COSMIC_SYSTEM_VERS cascade constraints;
drop TABLE AMD_EFFECTIVITIES cascade constraints;
drop TABLE AMD_ESCALATION_SNAPSHOTS cascade constraints;
drop TABLE AMD_FEE_SCHED_SNAPSHOTS cascade constraints;
drop TABLE AMD_FLEET_FORECASTS cascade constraints;
drop TABLE AMD_FLT_CURVE_FORECASTS cascade constraints;
drop TABLE AMD_MISSION_FLIGHTS cascade constraints;
drop TABLE AMD_MISSION_TYPES cascade constraints;
drop TABLE AMD_NSN_WUC_XREFS cascade constraints;
drop TABLE AMD_ON_BASE_REPAIR_COSTS cascade constraints;
drop TABLE AMD_ON_LOAN_INVS cascade constraints;
drop TABLE AMD_PART_SNAPSHOTS cascade constraints;
drop TABLE AMD_PART_USAGES cascade constraints;
drop TABLE AMD_PART_WUCS cascade constraints;
drop TABLE AMD_SCENARIO_BASE_PT_CHGS cascade constraints;
drop TABLE AMD_SCENARIO_BASE_USAGES cascade constraints;
drop TABLE AMD_SCENARIO_BASES cascade constraints;
drop TABLE AMD_SCENARIO_FORECAST_REPORTS cascade constraints;
drop TABLE AMD_SCENARIO_PART_CHGS cascade constraints;
drop TABLE AMD_SCENARIO_RUN_MESSAGES cascade constraints;
drop TABLE AMD_SCENARIO_RUNS cascade constraints;
drop TABLE AMD_SCENARIO_SNAPSHOTS cascade constraints;
drop TABLE AMD_SCENARIO_TIME_PERIODS cascade constraints;
drop TABLE AMD_SPARE_SCENARIOS cascade constraints;
drop TABLE AMD_SPECIAL_LEVEL_ITEMS cascade constraints;
drop TABLE AMD_SPECIAL_LEVEL_JUSTIFS cascade constraints;
drop TABLE AMD_STRAT_PLANNERS cascade constraints;
drop TABLE AMD_TABLE_TITLE_XREF cascade constraints;
drop TABLE AMD_TARGET_PERFORMANCES cascade constraints;
drop TABLE AMD_WORK_UNITS cascade constraints;
drop TABLE AMD_WUC_EFFECTIVITIES cascade constraints;
drop TABLE AMD_WUCS cascade constraints;
drop TABLE SBSS_AMD_MAINT_TASK_DISTRIBS cascade constraints;
drop TABLE SBSS_AMD_SPARE_PARTS cascade constraints;

/* Dropping of "deadwood" complete */

/* Create AMD_CALENDARS */

CREATE TABLE AMD_CALENDARS (
   CALENDAR_NAME  VARCHAR2(40)  NOT NULL,
   WORKING_SUNDAY  NUMBER  NOT NULL,
   WORKING_MONDAY  NUMBER  NOT NULL,
   WORKING_TUESDAY  NUMBER  NOT NULL,
   WORKING_WEDNESDAY  NUMBER  NOT NULL,
   WORKING_THURSDAY  NUMBER  NOT NULL,
   WORKING_FRIDAY  NUMBER  NOT NULL,
   WORKING_SATURDAY  NUMBER  NOT NULL,
   ACTION_CODE  VARCHAR2(1)  NOT NULL,
   LAST_UPDATE_DT  DATE  NOT NULL,
   CONSTRAINT AMD_CALENDARS_PK PRIMARY KEY (CALENDAR_NAME)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Creation of AMD_CALENDARS complete */

/* Create AMD_CALENDAR_EXCEPTIONS */

CREATE TABLE AMD_CALENDAR_EXCEPTIONS (
   CALENDAR_NAME  VARCHAR2(40)  NOT NULL,
   EXCEPTION_DATE  DATE  NOT NULL,
   ACTION_CODE  VARCHAR2(1)  NOT NULL,
   LAST_UPDATE_DT  DATE  NOT NULL,
   CONSTRAINT AMD_CALENDAR_EXCEPTIONS_FK01
      FOREIGN KEY (CALENDAR_NAME)
      REFERENCES AMD_CALENDARS (CALENDAR_NAME) 
      ON DELETE CASCADE,
   CONSTRAINT AMD_CALENDAR_EXCEPTIONS_PK
      PRIMARY KEY (CALENDAR_NAME, EXCEPTION_DATE)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Creation of AMD_CALENDAR_EXCEPTIONS complete */

/* Modify AMD_SPARE_NETWORKS */

ALTER TABLE AMD_SPARE_NETWORKS add (
   CALENDAR_NAME  VARCHAR2(40),
   TACTICAL  VARCHAR2(1)  DEFAULT 'Y'  NOT NULL,
   ACTION_CODE  VARCHAR2(1)  DEFAULT 'A'  NOT NULL,
   LAST_UPDATE_DT  DATE  DEFAULT SYSDATE  NOT NULL,
   CONSTRAINT AMD_SPARE_NETWORKS_FK01
      FOREIGN KEY (CALENDAR_NAME)
      REFERENCES AMD_CALENDARS (CALENDAR_NAME)
);

/* Modification to AMD_SPARE_NETWORKS complete */

/* Replace AMD_NATIONAL_STOCK_ITEMS et al */

drop TABLE AMD_PLANNER_PARTS;
drop TABLE AMD_PART_COST_SCHEDS;
/* ks add cascade constraints */
drop TABLE AMD_NATIONAL_STOCK_ITEMS cascade constraints;

CREATE SEQUENCE AMD_NSI_SID_SEQ;

CREATE TABLE AMD_NATIONAL_STOCK_ITEMS ( 
  NSI_SID  NUMBER  NOT NULL,
  NSN VARCHAR2(15),
  ADD_INCREMENT NUMBER,
  ADD_INCREMENT_CLEANED NUMBER,
  AMC_BASE_STOCK NUMBER,
  AMC_BASE_STOCK_CLEANED NUMBER,
  AMC_DAYS_EXPERIENCE NUMBER,
  AMC_DAYS_EXPERIENCE_CLEANED NUMBER,
  AMC_DEMAND NUMBER,
  AMC_DEMAND_CLEANED NUMBER,
  CAPABILITY_REQUIREMENT VARCHAR2(1),
  CAPABILITY_REQUIREMENT_CLEANED VARCHAR2(1),
  CRITICALITY VARCHAR2(1),
  CRITICALITY_CLEANED VARCHAR2(1),
  DISTRIB_UOM VARCHAR2(2),
  DISTRIB_UOM_DEFAULTED VARCHAR2(2),
  DLA_DEMAND NUMBER,
  DLA_DEMAND_CLEANED NUMBER,
  DLA_WAREHOUSE_STOCK NUMBER,
  DLA_WAREHOUSE_STOCK_CLEANED NUMBER,
  FEDC_COST NUMBER,
  FEDC_COST_CLEANED NUMBER,
  ITEM_TYPE VARCHAR2(1),
  ITEM_TYPE_CLEANED VARCHAR2(1),
  MIC_CODE_LOWEST VARCHAR2(1),
  MIC_CODE_LOWEST_CLEANED VARCHAR2(1),
  MTBDR NUMBER,
  MTBDR_CLEANED NUMBER,
  NOMENCLATURE_CLEANED VARCHAR2(512),
  ORDER_QUANTITY NUMBER,
  ORDER_QUANTITY_DEFAULTED  NUMBER,
     CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_CK01 CHECK (
       NOT (ORDER_QUANTITY IS NULL
          AND ORDER_QUANTITY_DEFAULTED IS NULL)
       ),
  PLANNER_CODE VARCHAR2(7),
  PLANNER_CODE_CLEANED VARCHAR2(7),
  PRIME_MFGR  VARCHAR2(13),
  PRIME_PART_NO  VARCHAR2(50),
  QPEI_WEIGHTED NUMBER,
  QPEI_WEIGHTED_DEFAULTED NUMBER,
  RU_IND VARCHAR2(1),
  RU_IND_CLEANED VARCHAR2(1),
  SMR_CODE VARCHAR2(6),
  SMR_CODE_DEFAULTED VARCHAR2(6),
  SMR_CODE_CLEANED VARCHAR2(6),
  UNIT_COST_CLEANED  NUMBER,
  USER_COMMENT VARCHAR2(512),
  CONDEMN_AVG  NUMBER,
  CONDEMN_AVG_DEFAULTED  NUMBER,
  CONDEMN_AVG_CLEANED  NUMBER,
  NRTS_AVG  NUMBER,
  NRTS_AVG_DEFAULTED  NUMBER,
  NRTS_AVG_CLEANED  NUMBER,
  RTS_AVG  NUMBER,
  RTS_AVG_DEFAULTED  NUMBER,
  RTS_AVG_CLEANED  NUMBER,
  COST_TO_REPAIR_OFF_BASE_CLEAND NUMBER,
  TIME_TO_REPAIR_OFF_BASE_CLEAND NUMBER,
  TIME_TO_REPAIR_ON_BASE_AVG NUMBER,
  TIME_TO_REPAIR_ON_BASE_AVG_DF NUMBER,
  TIME_TO_REPAIR_ON_BASE_AVG_CL NUMBER,
  TACTICAL  VARCHAR2(1) NOT NULL,
  ACTION_CODE  VARCHAR2(1)  NOT NULL,
  LAST_UPDATE_DT  DATE  NOT NULL,
  TACTICAL_REPLAN VARCHAR2(1),
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK03
      FOREIGN KEY (PLANNER_CODE)
      REFERENCES AMD_PLANNERS (PLANNER_CODE),
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK04
      FOREIGN KEY (PLANNER_CODE_CLEANED)
      REFERENCES AMD_PLANNERS (PLANNER_CODE),
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK05
      FOREIGN KEY (DISTRIB_UOM)
	REFERENCES AMD_UOMS (UOM_CODE),
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK06
      FOREIGN KEY (DISTRIB_UOM_DEFAULTED)
	REFERENCES AMD_UOMS (UOM_CODE),
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_PK
      PRIMARY KEY (NSI_SID)
      USING INDEX TABLESPACE AMD_INDEX,
  CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_UC01
      UNIQUE (NSN)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Replacement of AMD_NATIONAL_STOCK_ITEMS complete */

/* ks change following constraints to separate steps - nsi_sid does not exist yet at this point
not sure what 	CONSTRAINT AMD_NSNS_FK01 FOREIGN KEY (NSI_SID)
     		REFERENCES AMD_SPARE_PARTS (NSI_SID),
is since no nsi_sid in amd_spare_parts and if should be nsn, then going wrong way.
assume it is amd_national_stock_items instead of amd_spare_parts.
*/
CREATE TABLE AMD_NSNS ( 
  NSN VARCHAR2(15) NOT NULL,
  NSN_TYPE VARCHAR2(1) NOT NULL,
  NSI_SID  NUMBER,
  CONSTRAINT AMD_NSNS_FK01 FOREIGN KEY (NSI_SID)
     REFERENCES AMD_SPARE_PARTS (NSI_SID),
  CONSTRAINT AMD_NSNS_PK PRIMARY KEY (NSN)
     USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;
*/
CREATE TABLE AMD_NSNS ( 
  NSN VARCHAR2(15) NOT NULL,
  NSN_TYPE VARCHAR2(1) NOT NULL,
  NSI_SID  NUMBER
) TABLESPACE AMD_DATA;

ALTER TABLE AMD_NSNS add (
    CONSTRAINT AMD_NSNS_PK PRIMARY KEY (NSN)
     USING INDEX TABLESPACE AMD_INDEX
);

ALTER TABLE AMD_NSNS add (
    CONSTRAINT AMD_NSNS_FK01 FOREIGN KEY (NSI_SID)
     REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID)
);
	
	

ALTER TABLE AMD_NATIONAL_STOCK_ITEMS add (
   CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK01
      FOREIGN KEY (NSN)
      REFERENCES AMD_NSNS (NSN)
);


/* Replace AMD_SPARE_PARTS et al */

drop TABLE AMD_SPARE_PARTS CASCADE CONSTRAINTS;
drop TABLE AMD_EQUIVALENT_PARTS;

/* ks change AMD_NATIONAL_STOCK_NUMBERS to AMD_NSNS
   change gold_mfgr_code to gold_mfgr_cage */
create table AMD_SPARE_PARTS (
	PART_NO  VARCHAR2(50)  NOT NULL,
	MFGR  VARCHAR2(13)  NOT NULL,
	DATE_ICP  DATE,
	DISPOSAL_COST  NUMBER,
	DISPOSAL_COST_DEFAULTED  NUMBER,
	ERC  VARCHAR2(1),
	GOLD_MFGR_CAGE  VARCHAR2(13),
	ICP_IND  VARCHAR2(3)  NOT NULL,
	NOMENCLATURE  VARCHAR2(512)  NOT NULL,
	ORDER_LEAD_TIME  NUMBER,
	ORDER_LEAD_TIME_DEFAULTED  NUMBER,
	ORDER_LEAD_TIME_CLEANED  NUMBER,
	ORDER_UOM  VARCHAR2(2),
	ORDER_UOM_DEFAULTED  VARCHAR2(2),
	ORDER_UOM_CLEANED  VARCHAR2(2),
	SCRAP_VALUE  NUMBER,
	SCRAP_VALUE_DEFAULTED  NUMBER,
	SERIAL_FLAG  VARCHAR2(1),
	SHELF_LIFE  NUMBER,
	SHELF_LIFE_DEFAULTED  NUMBER,
	UNIT_COST NUMBER,
	UNIT_COST_DEFAULTED NUMBER,
      UNIT_VOLUME  NUMBER,
      UNIT_VOLUME_DEFAULTED  NUMBER,
      NSN  VARCHAR2(15),
      TACTICAL  VARCHAR2(1) NOT NULL,
      ACTION_CODE  VARCHAR2(1)  NOT NULL,
      LAST_UPDATE_DT  DATE  NOT NULL,
	CONSTRAINT AMD_SPARE_PARTS_FK01 FOREIGN KEY (NSN)
	   REFERENCES AMD_NSNS (NSN),
	CONSTRAINT AMD_SPARE_PARTS_FK02 FOREIGN KEY (ORDER_UOM)
	   REFERENCES AMD_UOMS (UOM_CODE),
	CONSTRAINT AMD_SPARE_PARTS_FK03 FOREIGN KEY (ORDER_UOM_DEFAULTED)
	   REFERENCES AMD_UOMS (UOM_CODE),
	CONSTRAINT AMD_SPARE_PARTS_FK04 FOREIGN KEY (ORDER_UOM_CLEANED)
	   REFERENCES AMD_UOMS (UOM_CODE),
	CONSTRAINT AMD_SPARE_PARTS_PK PRIMARY KEY (PART_NO, MFGR)
         USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;


ALTER TABLE AMD_NATIONAL_STOCK_ITEMS add (
   CONSTRAINT AMD_NATIONAL_STOCK_ITEMS_FK02
      FOREIGN KEY (PRIME_PART_NO, PRIME_MFGR)
      REFERENCES AMD_SPARE_PARTS (PART_NO, MFGR)
);

/* Re-instate cascade dropped RI */

ALTER TABLE AMD_SPARE_INVS add (
   CONSTRAINT AMD_SPARE_INVS_FK01
      FOREIGN KEY (PART_NO, MFGR)
      REFERENCES AMD_SPARE_PARTS (PART_NO, MFGR)
);

ALTER TABLE AMD_PART_NEXT_ASSEMBLIES add (
   CONSTRAINT AMD_PART_NEXT_ASSEMBLIES_FK01
      FOREIGN KEY (COMPONENT_PART_NO, COMPONENT_MFGR)
      REFERENCES AMD_SPARE_PARTS (PART_NO, MFGR)
);
/* ks omit, already exists
ALTER TABLE AMD_RSP_CONTENTS add (
   CONSTRAINT AMD_RSP_CONTENTS_FK02
      FOREIGN KEY (PART_NO, MFGR)
      REFERENCES AMD_SPARE_PARTS (PART_NO, MFGR)
);
*/
/* Replacement of AMD_SPARE_PARTS complete */

/* Create AMD_NSI_PARTS */

CREATE TABLE AMD_NSI_PARTS (
   NSI_SID  NUMBER  NOT NULL,
   ASSIGNMENT_DATE  DATE  NOT NULL,
   UNASSIGNMENT_DATE  DATE,
   PART_NO  VARCHAR2(50)  NOT NULL,
   MFGR  VARCHAR2(13)  NOT NULL,
   PRIME_IND  VARCHAR2(1)  NOT NULL,
   PRIME_IND_CLEANED  VARCHAR2(1),
   CONSTRAINT AMD_NSI_PARTS_FK01
      FOREIGN KEY (NSI_SID)
      REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID) 
      ON DELETE CASCADE,
   CONSTRAINT AMD_NSI_PARTS_FK02
      FOREIGN KEY (PART_NO, MFGR)
      REFERENCES AMD_SPARE_PARTS (PART_NO, MFGR),
   CONSTRAINT AMD_NSI_PARTS_PK
      PRIMARY KEY (NSI_SID, ASSIGNMENT_DATE)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Creation of AMD_NSI_PARTS complete */

/* Create AMD_TIME_PERIODS */
/* ks add comma after 1st constraint */
CREATE TABLE AMD_TIME_PERIODS (
   TIME_PERIOD_START  DATE  NOT NULL,
   TIME_PERIOD_END  DATE  NOT NULL,
   TACTICAL_BUCKET_NAME  VARCHAR2(40),
   TACTICAL_BUCKET_ID  VARCHAR2(40),
   ACTION_CODE  VARCHAR2(1)  NOT NULL,
   LAST_UPDATE_DT  DATE  NOT NULL,
   CONSTRAINT AMD_TIME_PERIODS_PK
      PRIMARY KEY (TIME_PERIOD_START, TIME_PERIOD_END)
      USING INDEX TABLESPACE AMD_INDEX,
   CONSTRAINT AMD_TIME_PERIODS_UC01
      UNIQUE (TACTICAL_BUCKET_NAME, TACTICAL_BUCKET_ID)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Creation of AMD_TIME_PERIODS complete */

/* Modify AMD_PLANNERS */

ALTER TABLE AMD_PLANNERS add (
   SUPERVISOR_CODE  VARCHAR2(7),
   ACTION_CODE  VARCHAR2(1)  DEFAULT 'A'  NOT NULL,
   LAST_UPDATE_DT  DATE  DEFAULT SYSDATE  NOT NULL,
   CONSTRAINT AMD_PLANNERS_FK01
      FOREIGN KEY (SUPERVISOR_CODE)
      REFERENCES AMD_PLANNERS (PLANNER_CODE)
);

/* Modification to AMD_PLANNERS complete */

/* Create AMD_TRANSPORT_MODES */

CREATE TABLE AMD_TRANSPORT_MODES (
   TRANSPORT_AGENT_ID  VARCHAR2(40)  NOT NULL,
   TRANSPORT_MODE_ID  VARCHAR2(40)  NOT NULL,
   TRANSPORT_MODE_DESC VARCHAR2(200),
   ACTION_CODE  VARCHAR2(1)  NOT NULL,
   LAST_UPDATE_DT  DATE  NOT NULL,
   CONSTRAINT AMD_TRANSPORT_MODES_PK
      PRIMARY KEY (TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Creation of AMD_TRANSPORT_MODES complete */

/* Create AMD_DEMANDS */

drop TABLE AMD_AF_REQS;
/* ks delete comma after last constraint */
CREATE TABLE AMD_DEMANDS ( 
   DOC_NO  VARCHAR2(14)  NOT NULL,
   DOC_DATE  DATE,
   DOC_DATE_DEFAULTED  DATE,
   NSI_SID  NUMBER  NOT NULL,
   LOC_SID  NUMBER  NOT NULL,
   QUANTITY  NUMBER  NOT NULL, 
   ACTION_CODE  VARCHAR2(1)  NOT NULL,
   LAST_UPDATE_DT  DATE  NOT NULL,
   CONSTRAINT AMD_DEMANDS_FK01
      FOREIGN KEY (LOC_SID)
      REFERENCES AMD_SPARE_NETWORKS (LOC_SID),
   CONSTRAINT AMD_DEMANDS_FK02
      FOREIGN KEY (NSI_SID)
      REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID),
   CONSTRAINT AMD_DEMANDS_PK
      PRIMARY KEY (DOC_NO)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Creation of AMD_DEMANDS complete */

/* Replace AMD_PART_LOCS */
/* ks add cascade constraints */
drop TABLE AMD_REPAIR_LEVELS cascade constraints;

/* ks mod part loc not exist for amdd 
drop TABLE AMD_PART_LOCS;
*/


/* ks delete of comma after last constraint */
CREATE TABLE AMD_PART_LOCS ( 
   NSI_SID  NUMBER  NOT NULL,
   LOC_SID  NUMBER  NOT NULL,
   AWT  NUMBER,
   AWT_DEFAULTED  NUMBER,
   COST_TO_REPAIR  NUMBER,
   COST_TO_REPAIR_DEFAULTED  NUMBER,
   MIC  NUMBER,
   MIC_DEFAULTED  NUMBER,
   REMOVAL_IND  VARCHAR2(1),
   REMOVAL_IND_DEFAULTED  VARCHAR2(1),
   REMOVAL_IND_CLEANED  VARCHAR2(1),
   REPAIR_LEVEL_CODE  VARCHAR2(1),
   REPAIR_LEVEL_CODE_DEFAULTED  VARCHAR2(1),
   REPAIR_LEVEL_CODE_CLEANED  VARCHAR2(1),
   TIME_TO_REPAIR NUMBER,
   TIME_TO_REPAIR_DEFAULTED NUMBER,
   TACTICAL  VARCHAR2(1)  NOT NULL,
   ACTION_CODE  VARCHAR2(1)  NOT NULL,
   LAST_UPDATE_DT  DATE  NOT NULL,
   CONSTRAINT AMD_PART_LOCS_FK01
      FOREIGN KEY (LOC_SID)
      REFERENCES AMD_SPARE_NETWORKS (LOC_SID),
   CONSTRAINT AMD_PART_LOCS_FK02
      FOREIGN KEY (NSI_SID)
      REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID),
   CONSTRAINT AMD_PART_LOCS_PK
      PRIMARY KEY (NSI_SID, LOC_SID)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Replacement of AMD_PART_LOCS complete */

/* Replace AMD_MAINT_TASK_DISTRIBS */

drop TABLE AMD_MAINT_TASK_DISTRIBS;
/* ks change CONTRAINT to CONSTRAINT and delete comma after last constraint */
CREATE TABLE AMD_MAINT_TASK_DISTRIBS ( 
   NSI_SID  NUMBER  NOT NULL,
   LOC_SID  NUMBER  NOT NULL,
   EFFECTIVE_DATE  DATE  NOT NULL,
   ACT_PROJ_IND  VARCHAR2(1)  NOT NULL,
   COND  NUMBER,
   COND_DEFAULTED  NUMBER,
   NRTS  NUMBER,
   NRTS_DEFAULTED  NUMBER,
   RTS  NUMBER,
   RTS_DEFAULTED  NUMBER,
   CONTRAINT AMD_MAINT_TASK_DISTRIBS_FK01
      FOREIGN KEY (NSI_SID, LOC_SID)
      REFERENCES AMD_PART_LOCS (NSI_SID, LOC_SID),
   CONSTRAINT AMD_MAINT_TASK_DISTRIBS_PK
      PRIMARY KEY (NSI_SID, LOC_SID, EFFECTIVE_DATE, ACT_PROJ_IND)
      USING INDEX TABLESPACE AMD_INDEX,
) TABLESPACE AMD_DATA ;

/* Replacement of AMD_MAINT_TASK_DISTRIBS complete */

/* Replace AMD_SPARE_PIPELINES */

drop TABLE AMD_SPARE_PIPELINES;

/* ks delete comma after last constraint */
CREATE TABLE AMD_SPARE_PIPELINES ( 
   FROM_LOC_SID  NUMBER  NOT NULL,
   TO_LOC_SID  NUMBER  NOT NULL,
   TRANSPORT_AGENT_ID  VARCHAR2(40)  NOT NULL,
   TRANSPORT_MODE_ID  VARCHAR2(40)  NOT NULL,
   CONSTRAINT AMD_SPARE_PIPELINES_FK01
      FOREIGN KEY (FROM_LOC_SID)
      REFERENCES AMD_SPARE_NETWORKS (LOC_SID) 
      ON DELETE CASCADE,
   CONSTRAINT AMD_SPARE_PIPELINES_FK02
      FOREIGN KEY (TO_LOC_SID)
      REFERENCES AMD_SPARE_NETWORKS (LOC_SID) 
      ON DELETE CASCADE,
   CONSTRAINT AMD_SPARE_PIPELINES_FK03
      FOREIGN KEY (TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID)
      REFERENCES AMD_TRANSPORT_MODES (TRANSPORT_AGENT_ID, TRANSPORT_MODE_ID),
   CONSTRAINT AMD_SPARE_PIPELINES_CK01
      CHECK (FROM_LOC_SID <> TO_LOC_SID),
   CONSTRAINT AMD_SPARE_PIPELINES_PK
      PRIMARY KEY (
         FROM_LOC_SID,
         TO_LOC_SID,
         TRANSPORT_AGENT_ID,
         TRANSPORT_MODE_ID)
      USING INDEX TABLESPACE AMD_INDEX,
) TABLESPACE AMD_DATA ;

/* Replacement of AMD_SPARE_PIPELINES complete */

/* Create AMD_BODS */
/* ks delete comma after last constraint */
CREATE TABLE AMD_BODS ( 
   FROM_LOC_SID  NUMBER  NOT NULL,
   TO_LOC_SID  NUMBER  NOT NULL,
   TRANSPORT_AGENT_ID  VARCHAR2(40)  NOT NULL,
   TRANSPORT_MODE_ID  VARCHAR2(40)  NOT NULL,
   BOD_SUBJECT  VARCHAR2(40)  NOT NULL,
   BOD_SUBJECT_TYPE  VARCHAR2(1)  NOT NULL,
   NSI_SID  NUMBER,
   BOD_TIME  NUMBER  NOT NULL,
   SOURCING_PRIORITY  NUMBER  NOT NULL,
   ACTION_CODE  VARCHAR2(1)  NOT NULL,
   LAST_UPDATE_DT  DATE  NOT NULL,
   CONSTRAINT AMD_BODS_FK01
      FOREIGN KEY (
         FROM_LOC_SID,
         TO_LOC_SID,
         TRANSPORT_AGENT_ID,
         TRANSPORT_MODE_ID)
      REFERENCES AMD_SPARE_PIPELINES (
         FROM_LOC_SID,
         TO_LOC_SID,
         TRANSPORT_AGENT_ID,
         TRANSPORT_MODE_ID) 
      ON DELETE CASCADE,
   CONSTRAINT AMD_BODS_FK02
      FOREIGN KEY (NSI_SID)
      REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID) 
      ON DELETE CASCADE,
   CONSTRAINT AMD_BODS_PK
      PRIMARY KEY (
         FROM_LOC_SID,
         TO_LOC_SID,
         TRANSPORT_AGENT_ID,
         TRANSPORT_MODE_ID,
         BOD_SUBJECT)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Creation of AMD_BODS complete */

/* Create AMD_PART_LOC_TIME_PERIODS */

CREATE TABLE AMD_PART_LOC_TIME_PERIODS (
   NSI_SID  NUMBER  NOT NULL,
   LOC_SID  NUMBER  NOT NULL,
   TIME_PERIOD_START  DATE  NOT NULL,
   TIME_PERIOD_END  DATE  NOT NULL,
   REORDER_POINT  NUMBER  NOT NULL,
   REORDER_QUANTITY  NUMBER  NOT NULL,
   ACTION_CODE  VARCHAR2(1)  NOT NULL,
   LAST_UPDATE_DT  DATE  NOT NULL,
   CONSTRAINT AMD_PART_LOC_TIME_PERIODS_FK01
      FOREIGN KEY (NSI_SID, LOC_SID)
      REFERENCES AMD_PART_LOCS (NSI_SID, LOC_SID),
   CONSTRAINT AMD_PART_LOC_TIME_PERIODS_PK
      PRIMARY KEY (NSI_SID, LOC_SID, TIME_PERIOD_START)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Creation of AMD_PART_LOC_TIME_PERIODS complete */

/* Create AMD_PART_LOC_FORECASTS */

CREATE TABLE AMD_PART_LOC_FORECASTS (
   NSI_SID  NUMBER  NOT NULL,
   LOC_SID  NUMBER  NOT NULL,
   TIME_PERIOD_START  DATE  NOT NULL,
   TIME_PERIOD_END  DATE  NOT NULL,
   FORECAST_NAME  VARCHAR2(40)  NOT NULL,
   FORECAST_QTY  NUMBER  NOT NULL,
   ACTION_CODE  VARCHAR2(1)  NOT NULL,
   LAST_UPDATE_DT  DATE  NOT NULL,
   CONSTRAINT AMD_PART_LOC_FORECASTS_FK01
      FOREIGN KEY (NSI_SID, LOC_SID)
      REFERENCES AMD_PART_LOCS (NSI_SID, LOC_SID),
   CONSTRAINT AMD_PART_LOC_FORECASTS_FK02
      FOREIGN KEY (TIME_PERIOD_START, TIME_PERIOD_END)
      REFERENCES AMD_TIME_PERIODS (TIME_PERIOD_START, TIME_PERIOD_END),
   CONSTRAINT AMD_PART_LOC_FORECASTS_PK
      PRIMARY KEY (NSI_SID, LOC_SID, TIME_PERIOD_START, TIME_PERIOD_END, FORECAST_NAME)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Creation of AMD_PART_LOC_FORECASTS complete */

/* Modify AMD_SPARE_INVS */

CREATE SEQUENCE AMD_SPARE_INVS_ORDER_SID_SEQ;

ALTER TABLE AMD_SPARE_INVS add (
   GOLD_ORDER_NUMBER  VARCHAR2(20),
   ORDER_SID  NUMBER,
   ACTION_CODE  VARCHAR2(1)  DEFAULT 'A'  NOT NULL,
   LAST_UPDATE_DT  DATE  DEFAULT SYSDATE  NOT NULL,
   CONSTRAINT AMD_SPARE_INVS_CK01
      CHECK (
         (INV_TYPE = '3' AND GOLD_ORDER_NUMBER IS NOT NULL)
         OR GOLD_ORDER_NUMBER IS NULL),
   CONSTRAINT AMD_SPARE_INVS_CK02
      CHECK (
         (INV_TYPE IN ('2' ,'4') AND ORDER_SID IS NOT NULL)
         OR ORDER_SID IS NULL)
);

/* Modification to AMD_SPARE_INVS complete */

/* Modify AMD_STORAGE_COSTS */

ALTER TABLE AMD_STORAGE_COSTS modify (
   HOLDING_COSTS  NULL
);

ALTER TABLE AMD_STORAGE_COSTS add (
   HOLDING_COSTS_DEFAULTED  NUMBER
);

/* Modification to AMD_STORAGE_COSTS complete */

/* Create AMD_PLANNER_LOGONS */

CREATE TABLE AMD_PLANNER_LOGONS (
   PLANNER_CODE  VARCHAR2(7)  NOT NULL,
   LOGON_ID  VARCHAR2(8)  NOT NULL,
   CONSTRAINT AMD_PLANNER_LOGONS_FK01
      FOREIGN KEY (PLANNER_CODE)
      REFERENCES AMD_PLANNERS (PLANNER_CODE)
      ON DELETE CASCADE,
   CONSTRAINT AMD_PLANNER_LOGONS_PK
      PRIMARY KEY (PLANNER_CODE, LOGON_ID)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;


/* Creation of AMD_PLANNER_LOGONS complete */

/* Create AMD_FORCASTED_AC_USAGES */

CREATE TABLE AMD_FORCASTED_AC_USAGES (
   FORECAST_NAME  VARCHAR2(40)  NOT NULL,
   LOC_SID  NUMBER  NOT NULL,
   UOM_CODE  VARCHAR2(2)  NOT NULL,
   TIME_PERIOD_START  DATE  NOT NULL,
   TIME_PERIOD_END  DATE  NOT NULL,
   FORECAST_QTY  NUMBER  NOT NULL,
   CONSTRAINT AMD_FORCASTED_AC_USAGES_FK01
      FOREIGN KEY (LOC_SID)
      REFERENCES AMD_SPARE_NETWORKS (LOC_SID),
   CONSTRAINT AMD_FORCASTED_AC_USAGES_FK02
      FOREIGN KEY (UOM_CODE)
      REFERENCES AMD_UOMS (UOM_CODE),
   CONSTRAINT AMD_FORCASTED_AC_USAGES_PK
      PRIMARY KEY (FORECAST_NAME, LOC_SID, UOM_CODE, TIME_PERIOD_START)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Creation of AMD_FORCASTED_AC_USAGES complete */

/* Replace AMD_RSP_CONTENTS */

drop TABLE AMD_RSP_CONTENTS;

CREATE TABLE AMD_RSP_CONTENTS (
   KIT_TYPE  VARCHAR2(4)  NOT NULL,
   NSI_SID  NUMBER  NOT NULL,
   RSP_QUANTITY  NUMBER  NOT NULL,
   CONSTRAINT AMD_RSP_CONTENTS_FK01
      FOREIGN KEY (KIT_TYPE)
      REFERENCES AMD_RSPS (KIT_TYPE) 
      ON DELETE CASCADE,
   CONSTRAINT AMD_RSP_CONTENTS_FK02
      FOREIGN KEY (NSI_SID)
      REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID),
   CONSTRAINT AMD_RSP_CONTENTS_PK
      PRIMARY KEY (KIT_TYPE, NSI_SID)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Replacement of AMD_RSP_CONTENTS complete */

/* Create AMD_ICAO_REGIONS */

drop TABLE AMD_ICAO_XREF;

CREATE TABLE AMD_ICAO_REGIONS (
   ICAO_REGION_ID  VARCHAR2(1)  NOT NULL,
   LOC_SID  NUMBER  NOT NULL,
   CONSTRAINT AMD_ICAO_REGIONS_FK01
      FOREIGN KEY (LOC_SID)
      REFERENCES AMD_SPARE_NETWORKS (LOC_SID),
   CONSTRAINT AMD_ICAO_REGIONS_PK
      PRIMARY KEY (ICAO_REGION_ID)
      USING INDEX TABLESPACE AMD_INDEX
) TABLESPACE AMD_DATA ;

/* Creation of AMD_ICAO_REGIONS complete */

/* Create AMD_IN_TRANSITS */

CREATE SEQUENCE AMD_IN_TRANSITS_ORDER_SID_SEQ;
/* ks delete comma after last constraints */
CREATE TABLE AMD_IN_TRANSITS ( 
   ORDER_SID  NUMBER  NOT NULL,
   FROM_LOC_SID  NUMBER  NOT NULL,
   TO_LOC_SID  NUMBER  NOT NULL,
   TRANSPORT_AGENT_ID  VARCHAR2(40)  NOT NULL,
   TRANSPORT_MODE_ID  VARCHAR2(40)  NOT NULL,
   NSI_SID  NUMBER  NOT NULL,
   QUANTITY  NUMBER  NOT NULL,
   SCHEDULED_DELIVERY_DATE  DATE  NOT NULL,
   ACTION_CODE  VARCHAR2(1)  NOT NULL,
   LAST_UPDATE_DT  DATE  NOT NULL,
   CONSTRAINT AMD_IN_TRANSITS_FK01
      FOREIGN KEY (
         FROM_LOC_SID,
         TO_LOC_SID,
         TRANSPORT_AGENT_ID,
         TRANSPORT_MODE_ID)
      REFERENCES AMD_SPARE_PIPELINES (
         FROM_LOC_SID,
         TO_LOC_SID,
         TRANSPORT_AGENT_ID,
         TRANSPORT_MODE_ID),
   CONSTRAINT AMD_IN_TRANSITS_FK02
      FOREIGN KEY (NSI_SID)
      REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID),
   CONSTRAINT AMD_IN_TRANSITS_PK
      PRIMARY KEY (ORDER_SID)
      USING INDEX TABLESPACE AMD_INDEX,
) TABLESPACE AMD_DATA ;

/* Creation of AMD_IN_TRANSITS complete */
