CREATE TABLE TMP_A2A_ORG_DEPLOYMENT
(
  BUNO		      	 VARCHAR2(20) DEFAULT 'C17Full',
  CODE					 VARCHAR2(20) DEFAULT 'AF',
  BASE_NAME				 VARCHAR2 (20),
  CUSTOMER				 VARCHAR2 (10) DEFAULT 'AF',
  MDL		         	 VARCHAR2(18) DEFAULT 'C17',
  BEGIN_DATE	   	 DATE DEFAULT TO_DATE('06/14/1993','MM/DD/RRRR'),
  END_DATE		   	 DATE DEFAULT TO_DATE('12/31/4100','MM/DD/RRRR'),
  QTY		         	 NUMBER,
  ACTION_CODE     	 VARCHAR2(1) NOT NULL,
  LAST_UPDATE_DT      DATE DEFAULT SYSDATE NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          72K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

GRANT SELECT ON TMP_A2A_ORG_DEPLOYMENT TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON TMP_A2A_ORG_DEPLOYMENT TO AMD_WRITER_ROLE,BSRM_LOADER;

CREATE PUBLIC SYNONYM tmp_a2a_org_deployment FOR amd_owner.tmp_a2a_org_deployment;