CREATE TABLE TMP_A2A_DEMANDS
(
  PART_NO             VARCHAR2(50) NOT NULL,
  SITE		      	 VARCHAR2(13),
  DOCNO           	 VARCHAR2(20),
  DEMAND_DATE	   	 DATE,
  QTY		         	 NUMBER,
  STATUS	         	 VARCHAR2(10) DEFAULT 'O',
  DEMAND_LEVEL			 VARCHAR2(10),
  DEMAND_TYPE	   	 VARCHAR2(20) DEFAULT 'General',
  BUNO		      	 VARCHAR2(20) DEFAULT 'C17Full',
  ACTION_CODE     	 VARCHAR2(1),
  LAST_UPDATE_DT      DATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          72K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

GRANT SELECT ON TMP_A2A_DEMANDS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON TMP_A2A_DEMANDS TO AMD_WRITER_ROLE,BSRM_LOADER;

CREATE PUBLIC SYNONYM tmp_a2a_demands FOR amd_owner.tmp_a2a_demands;
