    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:54:00  $
     $Workfile:   tmp_lccost.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\tmp_lccost.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:54:00   c970183
/*   Initial revision.
*/

CREATE TABLE TMP_LCCOST
(
  FRACPR     VARCHAR2(10 BYTE),
  JCN_DATE   DATE,
  WUC        VARCHAR2(9 BYTE),
  JCN        VARCHAR2(8 BYTE),
  AJCN       VARCHAR2(8 BYTE),
  PART_NO    VARCHAR2(20 BYTE),
  MASTER_ID  VARCHAR2(4 BYTE),
  MANHOUR    NUMBER,
  BASE_ID    VARCHAR2(4 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE INDEX LCCOST_MID ON TMP_LCCOST
(MASTER_ID)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX LCCOST_PN ON TMP_LCCOST
(PART_NO)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX LCCOST_WUC ON TMP_LCCOST
(WUC)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM TMP_LCCOST FOR TMP_LCCOST;


GRANT DELETE, INSERT, SELECT, UPDATE ON  TMP_LCCOST TO AMD_DATALOAD;

GRANT SELECT ON  TMP_LCCOST TO AMD_USER;

GRANT SELECT ON  TMP_LCCOST TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  TMP_LCCOST TO AMD_WRITER_ROLE;


