
CREATE TABLE TMP_A2A_IN_TRANSITS
(
  SITE_LOCATION  NUMBER,
  QTY            NUMBER,
  TYPE           VARCHAR2(10 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON  TMP_A2A_IN_TRANSITS TO BSRM_LOADER;

