DROP TABLE AMD_OWNER.VENDOR_MASTER CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.VENDOR_MASTER
(
  DUPS             VARCHAR2(255 BYTE),
  PO_DATE          DATE,
  PURCHASE_ORDERS  VARCHAR2(255 BYTE),
  PO_SUFX          VARCHAR2(255 BYTE),
  ITEM_NO          NUMBER,
  PART_NUMBER      VARCHAR2(56 BYTE),
  PART_NAME        VARCHAR2(512 BYTE),
  SUPPLIER_NO      VARCHAR2(255 BYTE),
  SUPPLIER_NAME    VARCHAR2(255 BYTE),
  LAST_UPDATE_DT   DATE                         DEFAULT sysdate
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP PUBLIC SYNONYM VENDOR_MASTER;

CREATE OR REPLACE PUBLIC SYNONYM VENDOR_MASTER FOR AMD_OWNER.VENDOR_MASTER;


GRANT SELECT ON AMD_OWNER.VENDOR_MASTER TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.VENDOR_MASTER TO AMD_WRITER_ROLE;


