
ALTER TABLE C17DEVLPR.SPO_BATCH_JOBS
 DROP PRIMARY KEY CASCADE;
DROP TABLE C17DEVLPR.SPO_BATCH_JOBS CASCADE CONSTRAINTS;


CREATE TABLE C17DEVLPR.SPO_BATCH_JOBS
(
  BATCH_JOB_NUMBER  NUMBER                      NOT NULL,
  SYSTEM_ID         VARCHAR2(30 BYTE)           NOT NULL,
  DESCRIPTION       VARCHAR2(200 BYTE),
  START_TIME        DATE                        NOT NULL,
  END_TIME          DATE,
  JOB_ABORTED       VARCHAR2(1 BYTE)
)

TABLESPACE  USERS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE UNIQUE INDEX C17DEVLPR.SPO_BATCH_JOBS_PK ON C17DEVLPR.SPO_BATCH_JOBS
(BATCH_JOB_NUMBER, SYSTEM_ID)
LOGGING
TABLESPACE  USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



ALTER TABLE C17DEVLPR.SPO_BATCH_JOBS ADD (
  CONSTRAINT SPO_BATCH_JOBS_PK
 PRIMARY KEY
 (BATCH_JOB_NUMBER, SYSTEM_ID)
    USING INDEX 
    TABLESPACE  USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

DROP PUBLIC SYNONYM SPO_BATCH_JOBS;

CREATE PUBLIC SYNONYM SPO_BATCH_JOBS FOR C17DEVLPR.SPO_BATCH_JOBS;

/
               
GRANT DELETE, INSERT, SELECT, UPDATE ON C17DEVLPR.SPO_BATCH_JOBS TO C17V2_DEVELOPER;

GRANT DELETE, INSERT, SELECT, UPDATE ON C17DEVLPR.SPO_BATCH_JOBS TO SPOC17V2_DEVELOPER;               

/
