ALTER TABLE AMD_OWNER.AMD_ORDER_PREFIXES
 DROP PRIMARY KEY CASCADE;

DROP TABLE AMD_OWNER.AMD_ORDER_PREFIXES CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.AMD_ORDER_PREFIXES
(
  PREFIX  VARCHAR2(2 BYTE)
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX AMD_OWNER.AMD_ORDER_PREFIXES_PK ON AMD_OWNER.AMD_ORDER_PREFIXES
(PREFIX)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE AMD_OWNER.AMD_ORDER_PREFIXES ADD (
  CONSTRAINT AMD_ORDER_PREFIXES_PK
  PRIMARY KEY
  (PREFIX)
  USING INDEX AMD_OWNER.AMD_ORDER_PREFIXES_PK);
