DROP VIEW AMD_OWNER.PGOLD_PRC1_V;

/* Formatted on 7/9/2012 4:25:04 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.PGOLD_PRC1_V
(
   SC,
   PART,
   CAP_PRICE,
   GFP_PRICE
)
AS
   SELECT TRIM (sc),
          TRIM (part),
          cap_price,
          gfp_price
     FROM prc1@amd_pgoldlb_link
    WHERE sc = 'DEF' AND part NOT LIKE '% ' AND part NOT LIKE ' %';


DROP PUBLIC SYNONYM PGOLD_PRC1_V;

CREATE OR REPLACE PUBLIC SYNONYM PGOLD_PRC1_V FOR AMD_OWNER.PGOLD_PRC1_V;


GRANT SELECT ON AMD_OWNER.PGOLD_PRC1_V TO AMD_READER_ROLE;
