    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:46  $
     $Workfile:   temp_amd_base_part_ses.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\temp_amd_base_part_ses.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:46   c970183
/*   Initial revision.
*/

CREATE TABLE TEMP_AMD_BASE_PART_SES
(
  NSN                     VARCHAR2(13 BYTE),
  LOC_SID                 NUMBER,
  STOCKAGE_EFFECTIVENESS  VARCHAR2(240 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX TEMP_AMD_BASE_PART_SES_UK01 ON TEMP_AMD_BASE_PART_SES
(NSN, LOC_SID)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TEMP_AMD_BASE_PART_SES_UK02 ON TEMP_AMD_BASE_PART_SES
(LOC_SID)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM TEMP_AMD_BASE_PART_SES FOR TEMP_AMD_BASE_PART_SES;


ALTER TABLE TEMP_AMD_BASE_PART_SES ADD (
  CHECK ("NSN" IS NOT NULL) DISABLE);

ALTER TABLE TEMP_AMD_BASE_PART_SES ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);


GRANT DELETE, INSERT, SELECT, UPDATE ON  TEMP_AMD_BASE_PART_SES TO AMD_DATALOAD;

GRANT SELECT ON  TEMP_AMD_BASE_PART_SES TO AMD_USER;

GRANT SELECT ON  TEMP_AMD_BASE_PART_SES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  TEMP_AMD_BASE_PART_SES TO AMD_WRITER_ROLE;


