    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 23 2005 12:04:40  $
     $Workfile:   scenario_id_seq.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\Sequences\scenario_id_seq.sql-arc  $
/*   
/*      Rev 1.0   May 23 2005 12:04:40   c970183
/*   Initial revision.
*/

DROP SEQUENCE AMD_OWNER.SCENARIO_ID_SEQ;

CREATE SEQUENCE AMD_OWNER.SCENARIO_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 100
  ORDER;


DROP PUBLIC SYNONYM SCENARIO_ID_SEQ;

CREATE PUBLIC SYNONYM SCENARIO_ID_SEQ FOR AMD_OWNER.SCENARIO_ID_SEQ;


GRANT SELECT ON  AMD_OWNER.SCENARIO_ID_SEQ TO AMD_COSMIC_SUPERUSER;

GRANT SELECT ON  AMD_OWNER.SCENARIO_ID_SEQ TO AMD_DATALOAD;

GRANT SELECT ON  AMD_OWNER.SCENARIO_ID_SEQ TO AMD_USER;

GRANT SELECT ON  AMD_OWNER.SCENARIO_ID_SEQ TO AMD_READER_ROLE;

GRANT SELECT ON  AMD_OWNER.SCENARIO_ID_SEQ TO AMD_WRITER_ROLE;


