    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:52:52  $
     $Workfile:   amd_actual_ac_usages.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_actual_ac_usages.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:52:52   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_ACTUAL_AC_USAGES
(
  EFFECTIVE_DATE  DATE                          NOT NULL,
  USAGE           NUMBER,
  TAIL_NO         VARCHAR2(7 BYTE)              NOT NULL,
  UOM_CODE        VARCHAR2(2 BYTE)              NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    5
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_ACTUAL_AC_USAGES_PK ON AMD_ACTUAL_AC_USAGES
(EFFECTIVE_DATE, TAIL_NO, UOM_CODE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_ACTUAL_AC_USAGES FOR AMD_ACTUAL_AC_USAGES;


ALTER TABLE AMD_ACTUAL_AC_USAGES ADD (
  CHECK ("USAGE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_ACTUAL_AC_USAGES ADD (
  CONSTRAINT AMD_ACTUAL_AC_USAGES_PK PRIMARY KEY (EFFECTIVE_DATE, TAIL_NO, UOM_CODE)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_ACTUAL_AC_USAGES ADD (
  CONSTRAINT AMD_ACTUAL_AC_USAGES_FK01 FOREIGN KEY (TAIL_NO) 
    REFERENCES AMD_AIRCRAFTS (TAIL_NO));

ALTER TABLE AMD_ACTUAL_AC_USAGES ADD (
  CONSTRAINT AMD_ACTUAL_AC_USAGES_FK02 FOREIGN KEY (UOM_CODE) 
    REFERENCES AMD_UOMS (UOM_CODE));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_ACTUAL_AC_USAGES TO AMD_DATALOAD;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_ACTUAL_AC_USAGES TO AMD_MAINT;

GRANT SELECT ON  AMD_ACTUAL_AC_USAGES TO AMD_USER;

GRANT SELECT ON  AMD_ACTUAL_AC_USAGES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_ACTUAL_AC_USAGES TO AMD_WRITER_ROLE;


