SET DEFINE OFF;
DROP TABLE AMD_OWNER.TRHI CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.TRHI
(
  TRAN_ID                 VARCHAR2(20 BYTE)     NOT NULL,
  CREATED_DATETIME        DATE                  NOT NULL,
  DOCUMENT_DATETIME       DATE                  NOT NULL,
  CREATED_USERID          VARCHAR2(20 BYTE)     NOT NULL,
  SC                      VARCHAR2(20 BYTE)     NOT NULL,
  PART                    VARCHAR2(50 BYTE)     NOT NULL,
  SERIAL                  VARCHAR2(20 BYTE),
  ASSET_ID                VARCHAR2(50 BYTE),
  ITEM_ID                 VARCHAR2(20 BYTE)     NOT NULL,
  RECEIVED_ITEM_ID        VARCHAR2(20 BYTE)     NOT NULL,
  SPLIT_TO_ITEM_ID        VARCHAR2(20 BYTE),
  CUSTODIAN               VARCHAR2(20 BYTE),
  CUSTODIAN_ALT1          VARCHAR2(20 BYTE),
  CUSTODIAN_ALT2          VARCHAR2(20 BYTE),
  FT_FROM_SC              VARCHAR2(20 BYTE),
  FT_FROM_PART            VARCHAR2(50 BYTE),
  FT_FROM_CONDITION       VARCHAR2(20 BYTE),
  FT_FROM_KEY_REF         VARCHAR2(50 BYTE),
  FT_FROM_LOCATION        VARCHAR2(20 BYTE),
  FT_FROM_LOT             VARCHAR2(20 BYTE),
  FT_FROM_VENDOR_CODE     VARCHAR2(20 BYTE),
  FT_FROM_SERIAL          VARCHAR2(20 BYTE),
  FT_FROM_PRICE           NUMBER(15,5),
  FT_FROM_AWO             VARCHAR2(50 BYTE),
  FT_FROM_U_ID            VARCHAR2(100 BYTE),
  FT_TO_SC                VARCHAR2(20 BYTE),
  FT_TO_PART              VARCHAR2(50 BYTE),
  FT_TO_CONDITION         VARCHAR2(20 BYTE),
  FT_TO_KEY_REF           VARCHAR2(50 BYTE),
  FT_TO_LOCATION          VARCHAR2(20 BYTE),
  FT_TO_LOT               VARCHAR2(20 BYTE),
  FT_TO_SERIAL            VARCHAR2(20 BYTE),
  FT_TO_VENDOR_CODE       VARCHAR2(20 BYTE),
  FT_TO_PRICE             NUMBER(15,5),
  FT_TO_AWO               VARCHAR2(50 BYTE),
  FT_TO_U_ID              VARCHAR2(100 BYTE),
  MISC_FT_FIELD_NAME      VARCHAR2(20 BYTE),
  MISC_FT_FROM_VALUE      VARCHAR2(50 BYTE),
  MISC_FT_TO_VALUE        VARCHAR2(50 BYTE),
  FT_FROM_COST_SOURCE     VARCHAR2(1 BYTE),
  FT_TO_COST_SOURCE       VARCHAR2(1 BYTE),
  FT_FROM_COST_ORD_NO     VARCHAR2(20 BYTE),
  FT_TO_COST_ORD_NO       VARCHAR2(20 BYTE),
  TCN                     VARCHAR2(3 BYTE)      NOT NULL,
  CHANGE_TYPE             VARCHAR2(1 BYTE)      NOT NULL,
  VOUCHER                 VARCHAR2(30 BYTE)     NOT NULL,
  DISPO_SCHED             VARCHAR2(20 BYTE),
  DISPO_SCHED_LINE        NUMBER(8),
  PICK_LIST_ID            VARCHAR2(20 BYTE),
  RESERVE_VOUCHER         VARCHAR2(20 BYTE),
  RESERVE_ID              VARCHAR2(20 BYTE),
  RESERVE_VOUCHER_ALT     VARCHAR2(20 BYTE),
  REQUEST_ID              VARCHAR2(20 BYTE),
  TRAN_SCREEN             VARCHAR2(8 BYTE),
  QTY                     NUMBER(15,5),
  UM                      VARCHAR2(3 BYTE),
  FORM_PRINTED_DATETIME   DATE,
  GOV_REPORT_DUE_YN       VARCHAR2(1 BYTE),
  GOV_REP_MINUS_DATETIME  DATE,
  GOV_REP_PLUS_DATETIME   DATE,
  GOV_REPORT_CONTRACT     VARCHAR2(20 BYTE),
  UNIT_PRICE              NUMBER(15,5),
  PI_GROUP                VARCHAR2(20 BYTE),
  PI_TAG                  NUMBER(8),
  PI_BARCODE_BATCH        VARCHAR2(20 BYTE),
  REQUESTED_PART          VARCHAR2(50 BYTE),
  REQUESTED_USERID        VARCHAR2(20 BYTE),
  ORDER_NO                VARCHAR2(20 BYTE),
  VENDOR_PART             VARCHAR2(50 BYTE),
  REASON_CODE             VARCHAR2(1 BYTE),
  SHIP_TO_ALC             VARCHAR2(6 BYTE),
  MINUS_USERID            VARCHAR2(20 BYTE),
  MINUS_DATETIME          DATE,
  MOVEIT_REMARKS          VARCHAR2(60 BYTE),
  REMARKS                 VARCHAR2(250 BYTE),
  ISSUE_TO_ITEM_ID        VARCHAR2(32 BYTE),
  ISSUE_TO_ASSET_ID       VARCHAR2(50 BYTE),
  USER_REF1               VARCHAR2(20 BYTE),
  USER_REF2               VARCHAR2(20 BYTE),
  USER_REF3               VARCHAR2(20 BYTE),
  USER_REF4               VARCHAR2(20 BYTE),
  USER_REF5               VARCHAR2(20 BYTE),
  USER_REF6               VARCHAR2(20 BYTE),
  USER_REF7               VARCHAR2(20 BYTE),
  USER_REF8               VARCHAR2(20 BYTE),
  USER_REF9               VARCHAR2(20 BYTE),
  USER_REF10              VARCHAR2(20 BYTE),
  USER_REF11              VARCHAR2(20 BYTE),
  USER_REF12              VARCHAR2(20 BYTE),
  USER_REF13              VARCHAR2(20 BYTE),
  USER_REF14              VARCHAR2(20 BYTE),
  USER_REF15              VARCHAR2(20 BYTE),
  USER_REF16              VARCHAR2(20 BYTE),
  REF_INFO                VARCHAR2(20 BYTE),
  VREF                    VARCHAR2(20 BYTE),
  FT_FROM_FURNISHED_BY    VARCHAR2(3 BYTE),
  FT_TO_FURNISHED_BY      VARCHAR2(3 BYTE),
  TEMP_OUT_ID             VARCHAR2(20 BYTE),
  LAST_CHANGED_USERID     VARCHAR2(20 BYTE),
  LAST_CHANGED_DATETIME   DATE,
  TRAN_GROUP_ID           VARCHAR2(20 BYTE),
  BOM_ID                  VARCHAR2(20 BYTE),
  FT_FROM_EGRESS          VARCHAR2(1 BYTE),
  FROM_MODEX              VARCHAR2(10 BYTE),
  TO_MODEX                VARCHAR2(10 BYTE),
  EMBODIMENT_LIST_PRICE   NUMBER(15,5),
  TEC                     VARCHAR2(10 BYTE),
  JOB_ORDER_CAT           VARCHAR2(20 BYTE),
  PREV_ACTIVE_QTY         NUMBER(15,5),
  PREV_CMAV               NUMBER(15,5),
  ADJ_TCN                 VARCHAR2(3 BYTE),
  INV_CLASS_CODE          VARCHAR2(10 BYTE),
  TOP_TEC                 VARCHAR2(10 BYTE),
  PO                      VARCHAR2(20 BYTE),
  PO_LINE                 VARCHAR2(6 BYTE),
  PO_SEQ                  NUMBER(8),
  MODEX                   VARCHAR2(10 BYTE),
  FORM_NUMBER             VARCHAR2(20 BYTE),
  ACQUISITION_AUTHORITY   VARCHAR2(20 BYTE),
  ACQUISITION_DOCUMENT    VARCHAR2(20 BYTE),
  ACQUISITION_DOC_DT      DATE,
  TRANSACTION_DOCUMENT    VARCHAR2(20 BYTE),
  TRANSACTION_DOC_DT      DATE,
  CONTRACT_AUTHORITY      VARCHAR2(20 BYTE),
  FT_FROM_DEPARTMENT      VARCHAR2(20 BYTE),
  FT_TO_DEPARTMENT        VARCHAR2(20 BYTE),
  LOAN_NUMBER             VARCHAR2(20 BYTE),
  FROM_TOP_ASSET          VARCHAR2(50 BYTE),
  TO_TOP_ASSET            VARCHAR2(50 BYTE),
  G009_PROCESSED_DT       DATE,
  G009_MINUSED_DT         DATE,
  ASSET_ID_ALT            VARCHAR2(50 BYTE),
  FT_TO_REVISION_LEVEL    VARCHAR2(20 BYTE),
  FT_FROM_REVISION_LEVEL  VARCHAR2(20 BYTE),
  MINUS_REMARKS           VARCHAR2(60 BYTE),
  INTERFACE_DATETIME      DATE,
  CATEGORY                VARCHAR2(6 BYTE),
  COST_SOURCE_CODE        VARCHAR2(1 BYTE),
  COST_ORDER_NO           VARCHAR2(20 BYTE),
  MCC                     VARCHAR2(20 BYTE),
  SPLIT_TO_ORDER          VARCHAR2(20 BYTE),
  CARRIER                 VARCHAR2(20 BYTE),
  SHIPMENT_CONTROL_NO     VARCHAR2(50 BYTE),
  RCV_DATETIME            DATE,
  TOTAL_VALUE             NUMBER(15,5),
  UM_OVR                  VARCHAR2(3 BYTE),
  UM_OVR_QTY              NUMBER(15,5),
  UM_OVR_FACTOR           NUMBER(10),
  TRF_PREV_TRHI_ID        VARCHAR2(20 BYTE),
  PARENT_TCN              VARCHAR2(3 BYTE)
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX AMD_OWNER.TRHII1 ON AMD_OWNER.TRHI
(PART, CREATED_DATETIME)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII2 ON AMD_OWNER.TRHI
(SC, PART, TCN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII3 ON AMD_OWNER.TRHI
(TCN, VOUCHER, MINUS_USERID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII4 ON AMD_OWNER.TRHI
(PART, DOCUMENT_DATETIME)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII5 ON AMD_OWNER.TRHI
(SC, TCN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII6 ON AMD_OWNER.TRHI
(TCN, MINUS_USERID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII9 ON AMD_OWNER.TRHI
(VENDOR_PART)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII10 ON AMD_OWNER.TRHI
(MINUS_USERID, TCN, CREATED_DATETIME, SC)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII11 ON AMD_OWNER.TRHI
(PART, MINUS_USERID, CREATED_DATETIME, TRAN_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII12 ON AMD_OWNER.TRHI
(SC, TCN, CREATED_DATETIME, MINUS_USERID, TRAN_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII13 ON AMD_OWNER.TRHI
(RESERVE_VOUCHER, MINUS_USERID, CREATED_DATETIME, TRAN_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII14 ON AMD_OWNER.TRHI
(FT_FROM_PART)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII15 ON AMD_OWNER.TRHI
(REQUESTED_PART)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII16 ON AMD_OWNER.TRHI
(FT_TO_PART)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII17 ON AMD_OWNER.TRHI
(TRAN_GROUP_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII18 ON AMD_OWNER.TRHI
(SERIAL)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII19 ON AMD_OWNER.TRHI
(SC)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AMD_OWNER.TRHIP1 ON AMD_OWNER.TRHI
(TRAN_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII20 ON AMD_OWNER.TRHI
(BOM_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII21 ON AMD_OWNER.TRHI
(CREATED_DATETIME)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII22 ON AMD_OWNER.TRHI
(REQUEST_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII23 ON AMD_OWNER.TRHI
(ITEM_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII24 ON AMD_OWNER.TRHI
(ASSET_ID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII25 ON AMD_OWNER.TRHI
(DOCUMENT_DATETIME)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII26 ON AMD_OWNER.TRHI
(ORDER_NO)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.TRHII27 ON AMD_OWNER.TRHI
(VOUCHER)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM TRHI;

CREATE PUBLIC SYNONYM TRHI FOR AMD_OWNER.TRHI;


GRANT SELECT ON AMD_OWNER.TRHI TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.TRHI TO AMD_WRITER_ROLE;

