    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:48  $
     $Workfile:   temp_amd_part_usages.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\temp_amd_part_usages.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:48   c970183
/*   Initial revision.
*/

CREATE TABLE TEMP_AMD_PART_USAGES
(
  COMPONENT_PART_NO        VARCHAR2(20 BYTE),
  COMPONENT_MFGR           VARCHAR2(13 BYTE),
  NEXT_ASSEMBLY_PART_NO    VARCHAR2(20 BYTE),
  NEXT_ASSEMBLY_CAGE_CODE  VARCHAR2(5 BYTE),
  MEL_FLAG                 VARCHAR2(1 BYTE),
  WUC                      VARCHAR2(9 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    5
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE PUBLIC SYNONYM TEMP_AMD_PART_USAGES FOR TEMP_AMD_PART_USAGES;


ALTER TABLE TEMP_AMD_PART_USAGES ADD (
  CHECK ("COMPONENT_PART_NO" IS NOT NULL) DISABLE);

ALTER TABLE TEMP_AMD_PART_USAGES ADD (
  CHECK ("COMPONENT_MFGR" IS NOT NULL) DISABLE);

ALTER TABLE TEMP_AMD_PART_USAGES ADD (
  CHECK ("NEXT_ASSEMBLY_PART_NO" IS NOT NULL) DISABLE);

ALTER TABLE TEMP_AMD_PART_USAGES ADD (
  CHECK ("NEXT_ASSEMBLY_CAGE_CODE" IS NOT NULL) DISABLE);

ALTER TABLE TEMP_AMD_PART_USAGES ADD (
  CHECK ("WUC" IS NOT NULL) DISABLE);


GRANT DELETE, INSERT, SELECT, UPDATE ON  TEMP_AMD_PART_USAGES TO AMD_DATALOAD;

GRANT SELECT ON  TEMP_AMD_PART_USAGES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  TEMP_AMD_PART_USAGES TO AMD_WRITER_ROLE;


