    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:04  $
     $Workfile:   amd_flight_stats.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_flight_stats.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:04   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_FLIGHT_STATS
(
  BASE         NUMBER                           NOT NULL,
  FSL          NUMBER                           NOT NULL,
  TAIL_NO      VARCHAR2(7 BYTE)                 NOT NULL,
  TIME_PERIOD  NUMBER                           NOT NULL,
  UOM          VARCHAR2(2 BYTE)                 NOT NULL,
  UOM_VALUE    NUMBER
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    0
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_FLIGHT_STATS_PK ON AMD_FLIGHT_STATS
(UOM, BASE, FSL, TAIL_NO, TIME_PERIOD)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_FLIGHT_STATS FOR AMD_FLIGHT_STATS;


ALTER TABLE AMD_FLIGHT_STATS ADD (
  CHECK ("UOM_VALUE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_FLIGHT_STATS ADD (
  CONSTRAINT AMD_FLIGHT_STATS_PK PRIMARY KEY (UOM, BASE, FSL, TAIL_NO, TIME_PERIOD)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_FLIGHT_STATS ADD (
  CONSTRAINT AMD_FLIGHT_STATS_FK01 FOREIGN KEY (TAIL_NO) 
    REFERENCES AMD_AIRCRAFTS (TAIL_NO));

ALTER TABLE AMD_FLIGHT_STATS ADD (
  CONSTRAINT AMD_FLIGHT_STATS_FK02 FOREIGN KEY (BASE) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_FLIGHT_STATS ADD (
  CONSTRAINT AMD_FLIGHT_STATS_FK03 FOREIGN KEY (FSL) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_FLIGHT_STATS TO AMD_DATALOAD;

GRANT SELECT ON  AMD_FLIGHT_STATS TO AMD_USER;

GRANT SELECT ON  AMD_FLIGHT_STATS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_FLIGHT_STATS TO AMD_WRITER_ROLE;


