    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:12  $
     $Workfile:   amd_mission_flights.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_mission_flights.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:12   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_MISSION_FLIGHTS
(
  MISSION_LEG         NUMBER                    NOT NULL,
  SCHED_DEPART_TIME   DATE,
  ACTUAL_DEPART_TIME  DATE,
  ACTUAL_ARRIVE_TIME  DATE,
  TAIL_NO             VARCHAR2(7 BYTE),
  DEPARTURE_ICAO      VARCHAR2(4 BYTE),
  ARRIVAL_ICAO        VARCHAR2(4 BYTE),
  MISSION_TYPE_CODE   VARCHAR2(8 BYTE),
  MISSION_ID          VARCHAR2(12 BYTE)         NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_MISSION_FLIGHTS_PK ON AMD_MISSION_FLIGHTS
(MISSION_LEG, MISSION_ID)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_MISSION_FLIGHTS FOR AMD_MISSION_FLIGHTS;


ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("SCHED_DEPART_TIME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("ACTUAL_DEPART_TIME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("ACTUAL_ARRIVE_TIME" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("TAIL_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("DEPARTURE_ICAO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("ARRIVAL_ICAO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CHECK ("MISSION_TYPE_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CONSTRAINT AMD_MISSION_FLIGHTS_PK PRIMARY KEY (MISSION_LEG, MISSION_ID)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CONSTRAINT AMD_MISSION_FLIGHTS_FK1 FOREIGN KEY (MISSION_TYPE_CODE) 
    REFERENCES AMD_MISSION_TYPES (MISSION_TYPE_CODE));

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CONSTRAINT AMD_MISSION_FLIGHTS_FK2 FOREIGN KEY (TAIL_NO) 
    REFERENCES AMD_AIRCRAFTS (TAIL_NO) DISABLE);

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CONSTRAINT AMD_MISSION_FLIGHTS_FK3 FOREIGN KEY (DEPARTURE_ICAO) 
    REFERENCES AMD_AIRPORTS (ICAO));

ALTER TABLE AMD_MISSION_FLIGHTS ADD (
  CONSTRAINT AMD_MISSION_FLIGHTS_FK4 FOREIGN KEY (ARRIVAL_ICAO) 
    REFERENCES AMD_AIRPORTS (ICAO));


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_MISSION_FLIGHTS TO AMD_COSMIC_SUPERUSER;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_MISSION_FLIGHTS TO AMD_DATALOAD;

GRANT SELECT ON  AMD_MISSION_FLIGHTS TO AMD_USER;

GRANT SELECT ON  AMD_MISSION_FLIGHTS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_MISSION_FLIGHTS TO AMD_WRITER_ROLE;


