DROP VIEW AMD_OWNER.PGOLD_VENC_V;

/* Formatted on 7/9/2012 4:25:35 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.PGOLD_VENC_V
(
   PART,
   SEQ,
   VENDOR_CODE,
   USER_REF1
)
AS
   SELECT TRIM (part),
          seq,
          TRIM (vendor_code),
          TRIM (user_ref1)
     FROM venc@amd_pgoldlb_link
    WHERE seq = 1;


DROP PUBLIC SYNONYM PGOLD_VENC_V;

CREATE OR REPLACE PUBLIC SYNONYM PGOLD_VENC_V FOR AMD_OWNER.PGOLD_VENC_V;


GRANT SELECT ON AMD_OWNER.PGOLD_VENC_V TO AMD_READER_ROLE;
