ALTER TABLE AMD_OWNER.TMP_AMD_ON_ORDER
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_OWNER.TMP_AMD_ON_ORDER CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.TMP_AMD_ON_ORDER
(
  PART_NO             VARCHAR2(50 BYTE)         NOT NULL,
  LOC_SID             NUMBER                    NOT NULL,
  ORDER_DATE          DATE,
  ORDER_QTY           NUMBER                    NOT NULL,
  GOLD_ORDER_NUMBER   VARCHAR2(20 BYTE),
  SCHED_RECEIPT_DATE  DATE,
  ACTION_CODE         VARCHAR2(1 BYTE)          NOT NULL,
  LAST_UPDATE_DT      DATE                      NOT NULL
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX AMD_OWNER.TMP_AMD_ON_ORDER_PK ON AMD_OWNER.TMP_AMD_ON_ORDER
(GOLD_ORDER_NUMBER, ORDER_DATE, LOC_SID)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM TMP_AMD_ON_ORDER;

CREATE PUBLIC SYNONYM TMP_AMD_ON_ORDER FOR AMD_OWNER.TMP_AMD_ON_ORDER;


ALTER TABLE AMD_OWNER.TMP_AMD_ON_ORDER ADD (
  CONSTRAINT TMP_AMD_ON_ORDER_PK
 PRIMARY KEY
 (GOLD_ORDER_NUMBER, ORDER_DATE, LOC_SID)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT SELECT ON AMD_OWNER.TMP_AMD_ON_ORDER TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.TMP_AMD_ON_ORDER TO AMD_WRITER_ROLE;


