    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:00  $
     $Workfile:   amd_calendars.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_calendars.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:00   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_CALENDARS
(
  CALENDAR_NAME      VARCHAR2(40 BYTE)          NOT NULL,
  WORKING_SUNDAY     NUMBER,
  WORKING_MONDAY     NUMBER,
  WORKING_TUESDAY    NUMBER,
  WORKING_WEDNESDAY  NUMBER,
  WORKING_THURSDAY   NUMBER,
  WORKING_FRIDAY     NUMBER,
  WORKING_SATURDAY   NUMBER,
  ACTION_CODE        VARCHAR2(1 BYTE),
  LAST_UPDATE_DT     DATE
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_CALENDARS_PK ON AMD_CALENDARS
(CALENDAR_NAME)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_CALENDARS FOR AMD_CALENDARS;


ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_SUNDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_MONDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_TUESDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_WEDNESDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_THURSDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_FRIDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("WORKING_SATURDAY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("ACTION_CODE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CHECK ("LAST_UPDATE_DT" IS NOT NULL) DISABLE);

ALTER TABLE AMD_CALENDARS ADD (
  CONSTRAINT AMD_CALENDARS_PK PRIMARY KEY (CALENDAR_NAME)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


GRANT SELECT ON  AMD_CALENDARS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_CALENDARS TO AMD_WRITER_ROLE;


