DROP VIEW AMD_OWNER.FLIP_DASH2_V;

/* Formatted on 6/10/2011 12:13:25 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.FLIP_DASH2_V
(
   PARTNUM,
   IPB,
   SSSN,
   IPBFIGURE,
   IPBINDEX
)
AS
   SELECT PARTNUM,
          IPB,
          SSSN,
          IPBFIGURE,
          IPBINDEX
     FROM flip_dash2@amd_flip_link;


DROP PUBLIC SYNONYM FLIP_DASH2_V;

CREATE OR REPLACE PUBLIC SYNONYM FLIP_DASH2_V FOR AMD_OWNER.FLIP_DASH2_V;


GRANT SELECT ON AMD_OWNER.FLIP_DASH2_V TO AMD_READER_ROLE;
