DROP VIEW AMD_OWNER.FLIP_IPB_SUP_V;

/* Formatted on 6/10/2011 12:15:00 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.FLIP_IPB_SUP_V
(
   AUTO_ID,
   IPB,
   SSSN,
   IPBFIGURE,
   IPBINDEX,
   INCORPORATION,
   FILE_LOC,
   SUBMIT_DATE,
   SUBMITTED_BY
)
AS
   SELECT AUTO_ID,
          IPB,
          SSSN,
          IPBFIGURE,
          IPBINDEX,
          INCORPORATION,
          FILE_LOC,
          SUBMIT_DATE,
          SUBMITTED_BY
     FROM flip_owner.FLIP_IPB_SUP@amd_flip_link;


DROP PUBLIC SYNONYM FLIP_IPB_SUP_V;

CREATE OR REPLACE PUBLIC SYNONYM FLIP_IPB_SUP_V FOR AMD_OWNER.FLIP_IPB_SUP_V;


GRANT SELECT ON AMD_OWNER.FLIP_IPB_SUP_V TO AMD_READER_ROLE;
