DROP VIEW AMD_OWNER.FLIP_DASH2AND3_V;

/* Formatted on 6/10/2011 12:13:48 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.FLIP_DASH2AND3_V
(
   PARTNUM,
   REFDES,
   IPB,
   SSSN,
   IPBFIGURE,
   IPBINDEX,
   CAGECODE,
   SMRCODE
)
AS
   SELECT PARTNUM,
          REFDES,
          IPB,
          SSSN,
          IPBFIGURE,
          IPBINDEX,
          CAGECODE,
          SMRCODE
     FROM flip_owner.FLIP_dash2and3@amd_flip_link;


DROP PUBLIC SYNONYM FLIP_DASH2AND3_V;

CREATE OR REPLACE PUBLIC SYNONYM FLIP_DASH2AND3_V FOR AMD_OWNER.FLIP_DASH2AND3_V;


GRANT SELECT ON AMD_OWNER.FLIP_DASH2AND3_V TO AMD_READER_ROLE;
