DROP VIEW AMD_OWNER.FLIP_DASH3_V;

/* Formatted on 6/10/2011 12:14:10 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.FLIP_DASH3_V
(
   REFDES,
   PARTNUM,
   IPB,
   SSSN,
   IPBFIGURE,
   IPBINDEX
)
AS
   SELECT REFDES,
          PARTNUM,
          IPB,
          SSSN,
          IPBFIGURE,
          IPBINDEX
     FROM flip_dash3@amd_flip_link;


DROP PUBLIC SYNONYM FLIP_DASH3_V;

CREATE OR REPLACE PUBLIC SYNONYM FLIP_DASH3_V FOR AMD_OWNER.FLIP_DASH3_V;


GRANT SELECT ON AMD_OWNER.FLIP_DASH3_V TO AMD_READER_ROLE;
