DROP TABLE AMD_OWNER.REQ1SA CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.REQ1SA
(
  REQUEST_ID               VARCHAR2(20 BYTE),
  REQUEST_ID_ALT           VARCHAR2(20 BYTE),
  STATUS                   VARCHAR2(1 BYTE),
  SELECT_FROM_SC           VARCHAR2(20 BYTE),
  SELECT_FROM_LOC_ID       VARCHAR2(13 BYTE),
  SELECT_FROM_PART         VARCHAR2(50 BYTE),
  SELECT_FROM_SERIAL       VARCHAR2(20 BYTE),
  SELECT_FROM_LOCATION     VARCHAR2(20 BYTE),
  SELECT_FROM_CONDITION    VARCHAR2(20 BYTE),
  CREATED_ORDER_NO         VARCHAR2(20 BYTE),
  LOCKED_INTO_ORDER_NO     VARCHAR2(20 BYTE),
  ORDER_PRIORITY           NUMBER(2),
  REQUEST_PRIORITY         NUMBER(2),
  PRIME                    VARCHAR2(50 BYTE),
  BOM_ID                   VARCHAR2(20 BYTE),
  ORDERED_DATETIME         DATE,
  ALLOW_ALTS_YN            CHAR(1 BYTE),
  FORM1_PRINTED_DATETIME   DATE,
  FORM2_PRINTED_DATETIME   DATE,
  ADVICE_CODE              VARCHAR2(2 BYTE),
  OVERRIDE_PRIORITY        NUMBER(2),
  FAD_URGENCY              NUMBER(2),
  PROJ_CODE                VARCHAR2(3 BYTE),
  WORK_AREA                VARCHAR2(3 BYTE),
  MODEX                    VARCHAR2(10 BYTE),
  NO_ACTIVITY_CODE         VARCHAR2(1 BYTE),
  DEMAND_CODE              CHAR(1 BYTE),
  PUB_REFA                 VARCHAR2(25 BYTE),
  PUB_REFB                 VARCHAR2(25 BYTE),
  COMPANY_CURR_STATUS      VARCHAR2(20 BYTE),
  REMARKS                  VARCHAR2(60 BYTE),
  QTY_REQUESTED            NUMBER(15,5),
  QTY_RESERVED             NUMBER(15,5),
  QTY_ISSUED               NUMBER(15,5),
  QTY_CANC                 NUMBER(15,5),
  QTY_DUE                  NUMBER(15,5),
  QTY_INIT_ORDERED         NUMBER(15,5),
  QTY_TO_ORDER             NUMBER(15,5),
  NEED_DATE                DATE,
  HELD_UNTIL_DATE          DATE,
  CREATED_DATETIME         DATE,
  CREATED_DOC_DATE         DATE,
  CREATED_USERID           VARCHAR2(20 BYTE),
  LAST_CHANGED_DATETIME    DATE,
  LAST_CHANGED_USERID      VARCHAR2(20 BYTE),
  REVIEWED_DATETIME        DATE,
  REVIEWED_USERID          VARCHAR2(20 BYTE),
  REVIEWED_REMARKS         VARCHAR2(60 BYTE),
  SATISFIED_DATETIME       DATE,
  SATISFIED_DOC_DATE       DATE,
  SATISFIED_USERID         VARCHAR2(20 BYTE),
  EXP_DATE                 DATE,
  STATUS_DATE              DATE,
  STATUS_USERID            VARCHAR2(20 BYTE),
  ISSUE_TO_ORDER_NO        VARCHAR2(20 BYTE),
  REASON_CODE              VARCHAR2(1 BYTE),
  CHARGE_TO_AWO            VARCHAR2(50 BYTE),
  WORK_STOP_YN             CHAR(1 BYTE),
  USER_REF1                VARCHAR2(20 BYTE),
  USER_REF2                VARCHAR2(20 BYTE),
  USER_REF3                VARCHAR2(20 BYTE),
  USER_REF4                VARCHAR2(20 BYTE),
  USER_REF5                VARCHAR2(20 BYTE),
  USER_REF6                VARCHAR2(20 BYTE),
  SELECT_FROM_AWO          VARCHAR2(50 BYTE),
  DELIV_ADDR               VARCHAR2(250 BYTE),
  PA_PROC_B                CHAR(1 BYTE),
  SELECT_FROM_KEY_REF      VARCHAR2(50 BYTE),
  SELECT_FROM_LOT          VARCHAR2(20 BYTE),
  TRN_B                    CHAR(1 BYTE),
  SUPPLY_UI                VARCHAR2(3 BYTE),
  ORG_SHOP_CODE            VARCHAR2(5 BYTE),
  NSN                      VARCHAR2(16 BYTE),
  MARK_FOR                 VARCHAR2(20 BYTE),
  UNIT_OF_ISSUE            VARCHAR2(3 BYTE),
  PURPOSE_CODE             VARCHAR2(20 BYTE),
  INTO_TOP_BOM_ID          VARCHAR2(20 BYTE),
  INTO_STRUCTURE_CODE      VARCHAR2(50 BYTE),
  INTO_SUB_STRUCTURE_CODE  VARCHAR2(50 BYTE),
  INTO_POS                 VARCHAR2(20 BYTE),
  INTO_ALT_POS             VARCHAR2(20 BYTE),
  TURN_ITEM_ID             VARCHAR2(20 BYTE),
  CANI_ID                  VARCHAR2(20 BYTE),
  ON_BASE_ONLY_B           CHAR(1 BYTE),
  MICAP_B                  CHAR(1 BYTE),
  RECURRING_B              CHAR(1 BYTE),
  INITIAL_B                CHAR(1 BYTE),
  FILL_OR_KILL_B           CHAR(1 BYTE),
  MASTER_FORM_TYPE         VARCHAR2(8 BYTE),
  DELIV_TO_REMARKS         VARCHAR2(150 BYTE),
  TEC                      VARCHAR2(20 BYTE),
  UJC                      VARCHAR2(2 BYTE),
  MILS_SOURCE_DIC          VARCHAR2(20 BYTE),
  VENDOR_CODE              VARCHAR2(20 BYTE),
  NHA_PART                 VARCHAR2(50 BYTE),
  SELECT_FROM_ASSET_ID     VARCHAR2(50 BYTE),
  DELIVER_TO_DODAAC        VARCHAR2(20 BYTE),
  SPECIAL_RDD              VARCHAR2(3 BYTE),
  DATE_RECEIPT_PROCESSED   DATE,
  ECD                      DATE,
  ECD_LAST_UPDATE          DATE,
  SOURCE_OF_ECD            VARCHAR2(20 BYTE),
  DIRECT_SHIP_B            CHAR(1 BYTE),
  PROC_CODE                VARCHAR2(20 BYTE),
  DRA_COUNT_B              CHAR(1 BYTE),
  DRB_COUNT_B              CHAR(1 BYTE),
  DRA_QTY_MISMATCH_B       CHAR(1 BYTE),
  DRA_OTHER_MISMATCH_B     CHAR(1 BYTE),
  LAST_UPDATE_DT           DATE                 DEFAULT sysdate
)
TABLESPACE AMD_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX AMD_OWNER.REQ1SA_NK01 ON AMD_OWNER.REQ1SA
(SUBSTR("REQUEST_ID",1,6))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE BITMAP INDEX AMD_OWNER.REQ1SA_NK02 ON AMD_OWNER.REQ1SA
(STATUS)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX AMD_OWNER.REQ1SA_NK03 ON AMD_OWNER.REQ1SA
(PRIME)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE BITMAP INDEX AMD_OWNER.REQ1SA_NK04 ON AMD_OWNER.REQ1SA
(SUBSTR("SELECT_FROM_SC",1,3))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE BITMAP INDEX AMD_OWNER.REQ1SA_NK05 ON AMD_OWNER.REQ1SA
(SUBSTR("REQUEST_ID",11,1))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX AMD_OWNER.REQ1SA_NK06 ON AMD_OWNER.REQ1SA
(NVL("NSN",'null'))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE BITMAP INDEX AMD_OWNER.REQ1SA_NK07 ON AMD_OWNER.REQ1SA
(REQUEST_PRIORITY)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX AMD_OWNER.REQ1SA_NK08 ON AMD_OWNER.REQ1SA
(NVL("MILS_SOURCE_DIC",'null'))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX AMD_OWNER.REQ1SA_NK09 ON AMD_OWNER.REQ1SA
(NVL("QTY_DUE",0)+NVL("QTY_RESERVED",0))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX AMD_OWNER.REQ1SA_NK10 ON AMD_OWNER.REQ1SA
(NVL("QTY_ISSUED",0)+NVL("QTY_DUE",0)+NVL("QTY_RESERVED",0))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE BITMAP INDEX AMD_OWNER.REQ1SA_NK11 ON AMD_OWNER.REQ1SA
(SUBSTR("SELECT_FROM_SC",8,6))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE BITMAP INDEX AMD_OWNER.REQ1SA_NK12 ON AMD_OWNER.REQ1SA
(SUBSTR("SELECT_FROM_LOC_ID",1,3))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE BITMAP INDEX AMD_OWNER.REQ1SA_NK13 ON AMD_OWNER.REQ1SA
(SUBSTR("REQUEST_ID",1,3))
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX AMD_OWNER.REQ1SA_NK14 ON AMD_OWNER.REQ1SA
(SELECT_FROM_PART)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE BITMAP INDEX AMD_OWNER.REQ1SA_NK15 ON AMD_OWNER.REQ1SA
(PURPOSE_CODE)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

DROP PUBLIC SYNONYM REQ1SA;

CREATE PUBLIC SYNONYM REQ1SA FOR AMD_OWNER.REQ1SA;


ALTER TABLE AMD_OWNER.REQ1SA ADD (
  CHECK ("ALLOW_ALTS_YN" IS NOT NULL)
  ENABLE VALIDATE,
  CHECK ("STATUS" IS NOT NULL)
  ENABLE VALIDATE,
  CHECK ("REQUEST_ID" IS NOT NULL)
  ENABLE VALIDATE);

GRANT SELECT ON AMD_OWNER.REQ1SA TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.REQ1SA TO AMD_WRITER_ROLE;
