create table TMP_AMD_DEMANDS
(
 DOC_NO VARCHAR2 (20),
 DOC_DATE DATE ,
 DOC_DATE_DEFAULTED DATE ,
 NSI_SID NUMBER ,
 LOC_SID NUMBER ,
 QUANTITY NUMBER ,
 ACTION_CODE VARCHAR2 (1),
 LAST_UPDATE_DT DATE
 )
 TABLESPACE AMD_DATA
 STORAGE (initial 65K
 	  minextents 1
 	  pctincrease 0);

GRANT SELECT ON TMP_AMD_DEMANDS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON TMP_AMD_DEMANDS TO AMD_WRITER_ROLE, BSRM_LOADER; 	 
