CREATE TABLE TMP_A2A_ORG_FLIGHT_ACTY_FRECST
(
  BUNO		      	 VARCHAR2(20) DEFAULT 'C17Full',
  MDL		         	 VARCHAR2(18) DEFAULT 'C17',
  CUSTOMER				 VARCHAR2 (10) DEFAULT 'AF',
  CAUSAL_TYPE			 VARCHAR2(20) DEFAULT 'Flight Hours',
  PERIOD			   	 DATE,
  CAUSAL_VALUE			 NUMBER,
  BASE_NAME				 VARCHAR2 (20),
  ACTION_CODE     	 VARCHAR2(1) DEFAULT 'A' NOT NULL ,
  LAST_UPDATE_DT      DATE DEFAULT SYSDATE NOT NULL
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          72K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

GRANT SELECT ON TMP_A2A_ORG_FLIGHT_ACTY_FRECST TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON TMP_A2A_ORG_FLIGHT_ACTY_FRECST TO AMD_WRITER_ROLE,BSRM_LOADER;

CREATE PUBLIC SYNONYM tmp_a2a_org_flight_acty_frecst FOR amd_owner.tmp_a2a_org_flight_acty_frecst;

