    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:16  $
     $Workfile:   amd_param_changes.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_param_changes.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:16   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_PARAM_CHANGES
(
  PARAM_KEY       VARCHAR2(50 BYTE)             NOT NULL,
  EFFECTIVE_DATE  DATE                          NOT NULL,
  PARAM_VALUE     VARCHAR2(2000 BYTE),
  USER_ID         VARCHAR2(20 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_PARAM_CHANGES_PK ON AMD_PARAM_CHANGES
(PARAM_KEY, EFFECTIVE_DATE)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_PARAM_CHANGES FOR AMD_PARAM_CHANGES;


ALTER TABLE AMD_PARAM_CHANGES ADD (
  CHECK ("USER_ID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_PARAM_CHANGES ADD (
  CONSTRAINT AMD_PARAM_CHANGES_PK PRIMARY KEY (PARAM_KEY, EFFECTIVE_DATE)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_PARAM_CHANGES ADD (
  CONSTRAINT AMD_PARAM_CHANGES_FK01 FOREIGN KEY (PARAM_KEY) 
    REFERENCES AMD_PARAMS (PARAM_KEY));


GRANT SELECT ON  AMD_PARAM_CHANGES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_PARAM_CHANGES TO AMD_WRITER_ROLE;


