DROP SEQUENCE AMD_OWNER.AMD_INTERFACE_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_INTERFACE_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP PUBLIC SYNONYM AMD_INTERFACE_SEQ;

CREATE PUBLIC SYNONYM AMD_INTERFACE_SEQ FOR AMD_OWNER.AMD_INTERFACE_SEQ;


GRANT SELECT ON AMD_OWNER.AMD_INTERFACE_SEQ TO AMD_WRITER_ROLE;


