    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:00  $
     $Workfile:   amd_ccn_prefix.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_ccn_prefix.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:00   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_CCN_PREFIX
(
  CCN_PREFIX  VARCHAR2(10 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_CCN_PREFIX FOR AMD_CCN_PREFIX;


ALTER TABLE AMD_CCN_PREFIX ADD (
  CHECK ("CCN_PREFIX" IS NOT NULL) DISABLE);


GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_CCN_PREFIX TO AMD_DATALOAD;

GRANT SELECT ON  AMD_CCN_PREFIX TO AMD_USER;

GRANT SELECT ON  AMD_CCN_PREFIX TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_CCN_PREFIX TO AMD_WRITER_ROLE;


