    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:53:14  $
     $Workfile:   amd_nsi_loc_distribs.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_nsi_loc_distribs.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:53:14   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_NSI_LOC_DISTRIBS
(
  NSI_SID             NUMBER                    NOT NULL,
  LOC_SID             NUMBER                    NOT NULL,
  TIME_PERIOD_START   DATE                      NOT NULL,
  TIME_PERIOD_END     DATE                      NOT NULL,
  AS_FLYING_COUNT     NUMBER,
  AS_FLYING_PERCENT   NUMBER,
  AS_CAPABLE_COUNT    NUMBER,
  AS_CAPABLE_PERCENT  NUMBER
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX AMD_NSI_LOC_DISTRIBS_PK ON AMD_NSI_LOC_DISTRIBS
(NSI_SID, LOC_SID, TIME_PERIOD_START, TIME_PERIOD_END)
LOGGING
TABLESPACE AMD_NDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_NSI_LOC_DISTRIBS FOR AMD_NSI_LOC_DISTRIBS;


ALTER TABLE AMD_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_NSI_LOC_DISTRIBS_PK PRIMARY KEY (NSI_SID, LOC_SID, TIME_PERIOD_START, TIME_PERIOD_END)
    USING INDEX 
    TABLESPACE AMD_NDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));


ALTER TABLE AMD_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_NSI_LOC_DISTRIBS_FK01 FOREIGN KEY (NSI_SID) 
    REFERENCES AMD_NATIONAL_STOCK_ITEMS (NSI_SID));

ALTER TABLE AMD_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_NSI_LOC_DISTRIBS_FK02 FOREIGN KEY (LOC_SID) 
    REFERENCES AMD_SPARE_NETWORKS (LOC_SID));

ALTER TABLE AMD_NSI_LOC_DISTRIBS ADD (
  CONSTRAINT AMD_NSI_LOC_DISTRIBS_FK03 FOREIGN KEY (TIME_PERIOD_START, TIME_PERIOD_END) 
    REFERENCES AMD_TIME_PERIODS (TIME_PERIOD_START,TIME_PERIOD_END));


GRANT SELECT ON  AMD_NSI_LOC_DISTRIBS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_NSI_LOC_DISTRIBS TO AMD_WRITER_ROLE;


