SET DEFINE OFF;
DROP SEQUENCE AMD_OWNER.AMD_LOAD_WARNINGS_SEQ;

CREATE SEQUENCE AMD_OWNER.AMD_LOAD_WARNINGS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


GRANT SELECT ON AMD_OWNER.AMD_LOAD_WARNINGS_SEQ TO AMD_ADMIN;

GRANT SELECT ON AMD_OWNER.AMD_LOAD_WARNINGS_SEQ TO AMD_DATALOAD;

GRANT SELECT ON AMD_OWNER.AMD_LOAD_WARNINGS_SEQ TO AMD_WRITER_ROLE;


