DROP VIEW AMD_OWNER.AMD_PSLMS_HA;

/* Formatted on 6/10/2011 12:21:10 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.AMD_PSLMS_HA
(
   DBKEY,
   UPDTCNT,
   BCKP,
   CAN_INT,
   UPDTCD,
   CAGECDXH,
   REFNUMHA,
   ITNAMEHA,
   INAMECHA,
   REFNCCHA,
   REFNVCHA,
   DLSCRCHA,
   DOCIDCHA,
   ITMMGCHA,
   COGNSNHA,
   SMMNSNHA,
   MATNSNHA,
   FSCNSNHA,
   NIINSNHA,
   ACTNSNHA,
   UICONVHA,
   SHLIFEHA,
   SLACTNHA,
   PPSLSTHA,
   DOCAVCHA,
   PRDLDTHA,
   SPMACCHA,
   SMAINCHA,
   CRITCDHA,
   PMICODHA,
   SAIPCDHA,
   AAPLCCHA,
   BBPLCCHA,
   CCPLCCHA,
   DDPLCCHA,
   EEPLCCHA,
   FFPLCCHA,
   GGPLCCHA,
   HHPLCCHA,
   JJPLCCHA,
   KKPLCCHA,
   LLPLCCHA,
   MMPLCCHA,
   PHYSECHA,
   ADPEQPHA,
   DEMILIHA,
   ACQMETHA,
   AMSUFCHA,
   HMSCOSHA,
   HWDCOSHA,
   HWSCOSHA,
   CTICODHA,
   UWEIGHHA,
   ULENGTHA,
   UWIDTHHA,
   UHEIGHHA,
   HAZCODHA,
   UNITMSHA,
   UNITISHA,
   LINNUMHA,
   CRITITHA,
   INDMATHA,
   MTLEADHA,
   MTLWGTHA,
   MATERLHA,
   SCHEDULE_B_EXPORT_CODE_TYPE,
   EXT_PART_ID
)
AS
   SELECT "DBKEY",
          "UPDTCNT",
          "BCKP",
          "CAN_INT",
          "UPDTCD",
          "CAGECDXH",
          "REFNUMHA",
          "ITNAMEHA",
          "INAMECHA",
          "REFNCCHA",
          "REFNVCHA",
          "DLSCRCHA",
          "DOCIDCHA",
          "ITMMGCHA",
          "COGNSNHA",
          "SMMNSNHA",
          "MATNSNHA",
          "FSCNSNHA",
          "NIINSNHA",
          "ACTNSNHA",
          "UICONVHA",
          "SHLIFEHA",
          "SLACTNHA",
          "PPSLSTHA",
          "DOCAVCHA",
          "PRDLDTHA",
          "SPMACCHA",
          "SMAINCHA",
          "CRITCDHA",
          "PMICODHA",
          "SAIPCDHA",
          "AAPLCCHA",
          "BBPLCCHA",
          "CCPLCCHA",
          "DDPLCCHA",
          "EEPLCCHA",
          "FFPLCCHA",
          "GGPLCCHA",
          "HHPLCCHA",
          "JJPLCCHA",
          "KKPLCCHA",
          "LLPLCCHA",
          "MMPLCCHA",
          "PHYSECHA",
          "ADPEQPHA",
          "DEMILIHA",
          "ACQMETHA",
          "AMSUFCHA",
          "HMSCOSHA",
          "HWDCOSHA",
          "HWSCOSHA",
          "CTICODHA",
          "UWEIGHHA",
          "ULENGTHA",
          "UWIDTHHA",
          "UHEIGHHA",
          "HAZCODHA",
          "UNITMSHA",
          "UNITISHA",
          "LINNUMHA",
          "CRITITHA",
          "INDMATHA",
          "MTLEADHA",
          "MTLWGTHA",
          "MATERLHA",
          "SCHEDULE_B_EXPORT_CODE_TYPE",
          "EXT_PART_ID"
     FROM PSLMS_HA@AMD_PSLMS_LINK.BOEINGDB;


DROP PUBLIC SYNONYM AMD_PSLMS_HA;

CREATE OR REPLACE PUBLIC SYNONYM AMD_PSLMS_HA FOR AMD_OWNER.AMD_PSLMS_HA;


GRANT SELECT ON AMD_OWNER.AMD_PSLMS_HA TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.AMD_PSLMS_HA TO BSRM_LOADER;
