DROP DATABASE LINK "LGB_AMD_LINK.WORLD";


CREATE DATABASE LINK "LGB_AMD_LINK.WORLD"
 CONNECT TO AMD_OWNER
 IDENTIFIED BY sdsproject11
 USING 'AMDD.BOEINGDB';

 /*
CREATE DATABASE LINK "LGB_AMD_LINK.WORLD"
 CONNECT TO bsrm_loader
 IDENTIFIED BY fromnewyork
 USING 'AMDI.BOEINGDB';
 */