#!/bin/ksh
# vim:ts=2:sw=2:sts=2:expandtab:autoindent:
# compare.ksh
# Author: Douglas S. Elder
# Date: 4/24/17
# Rev: 1.0
# Desc: compare the files generated by amd_bssmFlatFiles.ksh
# to the files generated by genBssmFiles.ksh
# Rev 1.0 4/24/17 initial version
# Rev 1.1 5/18/17 used new genBssmFiles.ksh with the -o data_dir option
#                 eliminates the need to copy the files.  Just create
#                 the onese without views in the data directory
#                 and the genBssmFiles.ksh to the data/bssmFilesViaViews
#

debug=N
MENU=N
DATA_SUBDIR=bssm
COMPARE_ONLY=Y
BSSM_VIEW_SQL=bssm_sql.txt
function usage {
  echo "compare.ksh [ -c -d -m -o data_subdir ]"
  echo "  where -c does a complete execution (default is compare only)"
  echo "    -d turns on debug"
  echo "    -m displays a menu of steps to execute"
  echo "    -o data_subdir overrides the default of bssm
}
. /apps/CRON/AMD/lib/amdenv.ksh
. /apps/CRON/AMD/lib/amdconfig.ksh
while getopts :cdm arguments
do
   case $arguments in
     c) COMPARE_ONLY=N;;
     d) set -x
        debug=Y;;
     m) MENU=Y;;
     *) usage
        exit 1;;
   esac
done
shift $((OPTIND - 1))

function loadFileList {
  [[ "$debug" == "Y" ]] && set -x
  fileList=
  numFiles=0
  YYMM=$(date +%Y%m)
  if [[ -e $DATA_HOME/$BSSM_VIEW_SQL ]] ; then
    while IFS= read -r line
    do
      fileList="${fileList} ${line%.*}_${YYMM}[0-9][0-9].TXT "
      let numFiles=$numFiles+1
    done < $DATA_HOME/$BSSM_VIEW_SQL 
    echo processing $numFiles files
  else
    echo $DATA_HOME/$BSSM_VIEW_SQL was not found
    exit 2
  fi
}

function copy {
  [[ "$debug" == "Y" ]] && set -x
  dir=$1
  cnt=0
  for f in $fileList
  do
    if [[ ! -e $DATA_HOME/$dir ]] ; then
      mkdir $DATA_HOME/$dir
    fi
    if [[ -e $DATA_HOME/$f ]] ; then
      echo copying $f to $DATA_HOME/$dir
      cp $DATA_HOME/$f $DATA_HOME/$dir/.
      if (($?==0)) ; then
        let cnt=$cnt+1
      else
        echo unable to copy $f to $DATA_HOME/$dir
        exit 4
      fi
    else
      echo $DATA_HOME/$f does not exist
    fi
  done
  echo copied $cnt files to $DATA_HOME/$dir
  return $cnt
}

function compare {
  [[ "$debug" == "Y" ]] && set -x
  cnt=0
  filesCompared=0
  for f in $filelist
  do
    tmp=$$
    filename=${f##*/}
    fo=${filename%.TXT}
    echo processing $f
    echo removing header line from 
    echo   $f 
    echo and saving to /tmp/$tmp
    tail -n +2 $f | sed 's/ *$//' > /tmp/$tmp
    echo sorting /tmp/$tmp 
    echo to      /tmp/${fo}_bssmFilesViaOldScript_sorted
    sort /tmp/$tmp > /tmp/${fo}_bssmFilesViaOldScript_sorted
    if [[ -e $DATA_HOME/$DATA_SUBDIR/${fo}.TXT ]] ; then
      
      echo processing $DATA_HOME/$DATA_SUBDIR/${fo}.TXT
      echo removing header line from 
      echo  $DATA_HOME/$DATA_SUBDIR/${fo}.TXT 
      echo and saving to /tmp/$tmp
      tail -n +2 $DATA_HOME/$DATA_SUBDIR/${fo}.TXT > /tmp/$tmp
      echo sorting /tmp/$tmp 
      echo to      /tmp/${fo}_bssmFilesViaViews_sorted
      sort /tmp/$tmp > /tmp/${fo}_bssmFilesViaViews_sorted
      rm -f /tmp/$tmp
      echo comparing /tmp/${fo}_bssmFilesViaOldScript_sorted 
      echo to        /tmp/${fo}_gen_bssn_sorted
      diff -q /tmp/${fo}_bssmFilesViaOldScript_sorted /tmp/${fo}_bssmFilesViaViews_sorted 2>&1 > /dev/null
      if (($?!=0)) ; then
        echo $fo.TXT differ
        let cnt=$cnt+1
      fi
    else
      echo $DATA_HOME/$DATA_SUBDIR/${fo}.TXT does not exist
      echo run createViaViews
      break
    fi
    let filesCompared=$filesCompared+1
  done
  if ((filesCompared>0)) ; then
    echo compared $filesCompared files
    echo $cnt files differ
  else
    echo no files found in $DATA_HOME/bssmFilesViaOldScript
    echo run createViaOldQueries
    exit 8
  fi
}

function removeFiles {
  [[ "$debug" == "Y" ]] && set -x

  CWD=$(pwd)
  dir=$1

  cd $DATA_HOME
  for f in $fileList
  do
    if [[ -e $f ]] ; then
      rm $f
    fi
  done

  cd $dir
  for f in $fileList
  do
    if [[ -e $f ]] ; then
      rm $f
    fi
  done

  cd $CWD
}

function fileCnt {
  [[ "$debug" == "Y" ]] && set -x
  cnt=0
  for f in $fileList
  do
    if [[ -e $DATA_HOME/$f ]] ; then
      let cnt=$cnt+1
    fi
  done
  return $cnt
}

function createViaOldScripts {
  [[ "$debug" == "Y" ]] && set -x
  removeFiles bssmFilesViaOldScript
  echo "Creating files using scripts without views, amd_lists, and amd_substitutions"
  perl $DATA_HOME/getBssmSql.pl
  $LIB_HOME/amd_bssmFlatFiles.ksh
  fileCnt
  cnt=$?
  if ((cnt!=numFiles)) ; then
    echo only $cnt files created. expected $fileCnt
    exit 16
  fi
}

function displaySqlUsingViews {
  [[ "$debug" == "Y" ]] && set -x
  if [[ -e $DATA_HOME/$BSSM_VIEW_SQL ]] ; then
    echo "SQL*Plus scripts using views, amd_lists, and amd_substitutions"
    while IFS= read -r line
    do
      echo $line
    done < $DATA_HOME/$BSSM_VIEW_SQL 
    echo processing $numFiles files
  else
    echo $DATA_HOME/$BSSM_VIEW_SQL was not found
    exit 2
  fi
}

function createViaViews {
  [[ "$debug" == "Y" ]] && set -x
  removeFiles bssmFilesViaViews
  displaySqlUsingViews
  echo executing $LIB_HOME/genBssmFiles.ksh
  cat $DATA_HOME/$BSSM_VIEW_SQL
  $LIB_HOME/genBssmFiles.ksh -o data/bssmFilesViaViews
  fileCnt
  cnt=$?
  if ((cnt!=numFiles)) ; then
    echo only $cnt files created by genBssmFiles.ksh expected $fileCnt
    exit 64 
  fi
}

function displayMenu {
  echo 1. createViaOldScripts
  echo 2. createViaViews
  echo 3. compare
  return 3
}
function menu {
  [[ "$debug" == "Y" ]] && set -x
    displayMenu
    num_steps=$?
    stepnum=0
    while read stepnum?"Enter stepnum or 0 to exit? "
    do
      case $stepnum in
        0) break ;;
        1) createViaOldScripts;;
        2) createViaViews;;
        3) compare;;
        *) echo $stepnum is not a valid step;;
      esac
   done
}

function main {
  [[ "$debug" == "Y" ]] && set -x

  loadFileList
  if [[ "$COMPARE_ONLY" == "N" ]] ; then
    createViaOldScripts
    createViaViews
  fi

  compare
}

TimeStamp=$(date +%Y%m%d_%H_%M_%S)

LOG_FILE=$LOG_HOME/${TimeStamp}_compare.log
(
  if [[ "$MENU" == "Y" ]]; then
    menu
  else
    main 
  fi
) 2>&1 | tee -a $LOG_FILE

echo $LOG_FILE created
