 /*
      $Author:   zf297a  $
    $Revision:   1.0  $
        $Date:   23 Aug 2007 10:41:24  $
    $Workfile:   lvls.sql  $
         $Log:   I:\Program Files\Merant\vm\win32\bin\pds\archives\SDS-AMD\Database\Scripts\AMD 2.0 Implementation\lvls.sql.-arc  $
/*   
/*      Rev 1.0   23 Aug 2007 10:41:24   zf297a
/*   Initial revision.
*/

set define off

ALTER TABLE AMD_OWNER.LVLS
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_OWNER.LVLS CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.LVLS
(
  NIIN                    VARCHAR2(16 BYTE),
  SRAN                    VARCHAR2(6 BYTE),
  NSN                     VARCHAR2(15 BYTE)     NOT NULL,
  LVL_DOCUMENT_NUMBER     VARCHAR2(8 BYTE)      NOT NULL,
  ROUTING_IDENTIFIER      VARCHAR2(3 BYTE),
  AFMC_FLAG               VARCHAR2(1 BYTE),
  TEX_CODE                VARCHAR2(1 BYTE),
  LVL_JUSTIFICATION_CODE  VARCHAR2(1 BYTE),
  UNIT_OF_ISSUE           VARCHAR2(2 BYTE),
  APPROVED_LVL_QTY        NUMBER(6),
  STOCK_LVL_TRAN_CODE     VARCHAR2(1 BYTE),
  JUSTIFICATION_INFO      VARCHAR2(20 BYTE),
  ICP_ROUTING_IDENTIFIER  VARCHAR2(3 BYTE),
  ISG_SUBGROUP_CODE       VARCHAR2(2 BYTE),
  PARTS_REFERENCE_CODE    VARCHAR2(1 BYTE),
  RECONCILE_UPDATE_CODE   VARCHAR2(1 BYTE),
  TYPE_LVL_CODE           VARCHAR2(1 BYTE),
  LVL_DIRECTED_BY_CODE    VARCHAR2(1 BYTE),
  DEMAND_LVL_QTY          NUMBER(6),
  ADJUSTED_LVL_QTY        NUMBER(6),
  COMPATIBILITY_CODE      VARCHAR2(1 BYTE),
  D043B_ISG_MASTER_NSN    VARCHAR2(26 BYTE),
  NET_ADJUSTMENT_QTY      NUMBER(6),
  XE4_ORIGINATOR          VARCHAR2(1 BYTE),
  XE4_REJECT_CODE         VARCHAR2(1 BYTE),
  CMSK_FLAG               VARCHAR2(1 BYTE),
  DATE_LVL_COMPUTED       VARCHAR2(5 BYTE),
  DATE_LVL_LOADED         DATE,
  DOCUMENT_DATETIME       DATE,
  CURRENT_STOCK_NUMBER    VARCHAR2(50 BYTE),
  REORDER_POINT           NUMBER(10),
  ECONOMIC_ORDER_QTY      NUMBER(10),
  APPLICATION_DATA        VARCHAR2(6 BYTE),
  REMARKS                 VARCHAR2(100 BYTE),
  LAST_UPDATE_DT          DATE
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX AMD_OWNER.LVLS_PK ON AMD_OWNER.LVLS
(NIIN, SRAN, DOCUMENT_DATETIME)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AMD_OWNER.LVLS_NK01 ON AMD_OWNER.LVLS
(NSN)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM LVLS;

CREATE PUBLIC SYNONYM LVLS FOR AMD_OWNER.LVLS;


ALTER TABLE AMD_OWNER.LVLS ADD (
  CONSTRAINT LVLS_PK
 PRIMARY KEY
 (NIIN, SRAN, DOCUMENT_DATETIME)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT SELECT ON AMD_OWNER.LVLS TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.LVLS TO AMD_WRITER_ROLE;


