 /*
      $Author:   zf297a  $
    $Revision:   1.0  $
        $Date:   23 Aug 2007 10:41:26  $
    $Workfile:   tmp_amd_dmnd_frcst_consumables.sql  $
         $Log:   I:\Program Files\Merant\vm\win32\bin\pds\archives\SDS-AMD\Database\Scripts\AMD 2.0 Implementation\tmp_amd_dmnd_frcst_consumables.sql.-arc  $
/*   
/*      Rev 1.0   23 Aug 2007 10:41:26   zf297a
/*   Initial revision.
*/

set define off

ALTER TABLE AMD_OWNER.TMP_AMD_DMND_FRCST_CONSUMABLES
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_OWNER.TMP_AMD_DMND_FRCST_CONSUMABLES CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.TMP_AMD_DMND_FRCST_CONSUMABLES
(
  NSN              VARCHAR2(13 BYTE)            NOT NULL,
  SRAN             VARCHAR2(6 BYTE)             NOT NULL,
  PERIOD           NUMBER,
  DDR              NUMBER(12,9),
  DEMAND_FORECAST  NUMBER(12,9),
  LAST_UPDATE_DT   DATE                         DEFAULT sysdate,
  DUPLICATE        NUMBER
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX AMD_OWNER.TMP_AMD_DMND_FRCST_CONSUMBL_PK ON AMD_OWNER.TMP_AMD_DMND_FRCST_CONSUMABLES
(NSN, SRAN, PERIOD)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM TMP_AMD_DMND_FRCST_CONSUMABLES;

CREATE PUBLIC SYNONYM TMP_AMD_DMND_FRCST_CONSUMABLES FOR AMD_OWNER.TMP_AMD_DMND_FRCST_CONSUMABLES;


ALTER TABLE AMD_OWNER.TMP_AMD_DMND_FRCST_CONSUMABLES ADD (
  CONSTRAINT TMP_AMD_DMND_FRCST_CONSUMBL_PK
 PRIMARY KEY
 (NSN, SRAN, PERIOD)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT SELECT ON AMD_OWNER.TMP_AMD_DMND_FRCST_CONSUMABLES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.TMP_AMD_DMND_FRCST_CONSUMABLES TO AMD_WRITER_ROLE;


