    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 23 2005 12:33:00  $
     $Workfile:   links.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\Scripts\links.sql-arc  $
/*   
/*      Rev 1.0   May 23 2005 12:33:00   c970183
/*   Initial revision.
*/
--ICWO_ADMIN_PC17I.LGB.AMS.BOEING.COM 
--ICWO_USER_PC17I.LGB.AMS.BOEING.COM 
--PGA.LGB.AMS.BOEING.COM 
--PGA8P.LGB.AMS.BOEING.COM 
--PSMS.LGB.AMS.BOEING.COM 
--RPMS_CMS_LINK.LGB.AMS.BOEING.COM 
--RPMS_PSMS_IF.LGB.AMS.BOEING.COM 
--RPMS_TOMS_LINK.LGB.AMS.BOEING.COM 


CREATE PUBLIC DATABASE LINK "PGA8P.LGB.AMS.BOEING.COM"
 USING 'PGA9I';


CREATE PUBLIC DATABASE LINK "ICWO_ADMIN_PC17I.LGB.AMS.BOEING.COM"
 CONNECT TO ICWO_31_ADMIN
 IDENTIFIED BY <PWD>
 USING 'PC17I';


CREATE PUBLIC DATABASE LINK "ICWO_USER_PC17I.LGB.AMS.BOEING.COM"
 CONNECT TO ICWO_31_USER
 IDENTIFIED BY <PWD>
 USING 'PC17I';


CREATE PUBLIC DATABASE LINK "RPMS_PSMS_IF.LGB.AMS.BOEING.COM"
 CONNECT TO PSMS_RPMS_IF
 IDENTIFIED BY <PWD>
 USING 'PSMSP';


CREATE PUBLIC DATABASE LINK "RPMS_CMS_LINK.LGB.AMS.BOEING.COM"
 CONNECT TO CMS_RPMS_IF_USER
 IDENTIFIED BY <PWD>
 USING 'U50PAMC';


CREATE PUBLIC DATABASE LINK "RPMS_TOMS_LINK.LGB.AMS.BOEING.COM"
 CONNECT TO TOMS_RPMS_IF_USER
 IDENTIFIED BY <PWD>
 USING 'psmsp';


CREATE PUBLIC DATABASE LINK "PGA.LGB.AMS.BOEING.COM"
 USING 'PGA9I';


CREATE PUBLIC DATABASE LINK "PSMS.LGB.AMS.BOEING.COM"
 USING 'PSMSP';



