set define off

ALTER TABLE AMD_OWNER.AMD_DMND_FRCST_CONSUMABLES
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_OWNER.AMD_DMND_FRCST_CONSUMABLES CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.AMD_DMND_FRCST_CONSUMABLES
(
  NSN              VARCHAR2(13 BYTE)            NOT NULL,
  SRAN             VARCHAR2(6 BYTE)             NOT NULL,
  PERIOD           NUMBER,
  DEMAND_FORECAST  NUMBER(12,9),
  ACTION_CODE      VARCHAR2(1 BYTE)             DEFAULT 'A',
  LAST_UPDATE_DT   DATE                         DEFAULT sysdate,
  DUPLICATE        NUMBER
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX AMD_OWNER.AMD_DMND_FRCST_CONSUMABL_PK ON AMD_OWNER.AMD_DMND_FRCST_CONSUMABLES
(NSN, SRAN, PERIOD)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM AMD_DMND_FRCST_CONSUMABLES;

CREATE PUBLIC SYNONYM AMD_DMND_FRCST_CONSUMABLES FOR AMD_OWNER.AMD_DMND_FRCST_CONSUMABLES;


ALTER TABLE AMD_OWNER.AMD_DMND_FRCST_CONSUMABLES ADD (
  CONSTRAINT AMD_DMND_FRCST_CONSUMABL_PK
 PRIMARY KEY
 (NSN, SRAN, PERIOD)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT SELECT ON AMD_OWNER.AMD_DMND_FRCST_CONSUMABLES TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_DMND_FRCST_CONSUMABLES TO AMD_WRITER_ROLE;


