DROP VIEW AMD_OWNER.AMD_PSLMS_XI;

/* Formatted on 6/10/2011 12:21:23 PM (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.AMD_PSLMS_XI
(
   DBKEY,
   UPDTCNT,
   BCKP,
   CAN_INT,
   UPDTCD,
   TMCODEXI,
   TMNUMBXI
)
AS
   SELECT DBKEY,
          UPDTCNT,
          BCKP,
          CAN_INT,
          UPDTCD,
          TMCODEXI,
          TMNUMBXI
     FROM pslms_xi@amd_pslms_link.boeingdb;


DROP PUBLIC SYNONYM AMD_PSLMS_HG;

CREATE OR REPLACE PUBLIC SYNONYM AMD_PSLMS_HG FOR AMD_OWNER.AMD_PSLMS_XI;


GRANT SELECT ON AMD_OWNER.AMD_PSLMS_XI TO AMD_READER_ROLE;
