    /*   				
       $Author:   c970183  $
     $Revision:   1.0  $
         $Date:   May 20 2005 08:52:58  $
     $Workfile:   amd_bssm_source.sql  $
	  $Log:   \\www-amssc-01\pds\archives\SDS-AMD\Database\ddl\amd_bssm_source.sql-arc  $
/*   
/*      Rev 1.0   May 20 2005 08:52:58   c970183
/*   Initial revision.
*/

CREATE TABLE AMD_BSSM_SOURCE
(
  REQUISITION_NO    VARCHAR2(20 BYTE),
  REQUISITION_DATE  DATE,
  QUANTITY          NUMBER,
  LOC_SID           NUMBER,
  NSN               VARCHAR2(16 BYTE)
)
TABLESPACE AMD_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE PUBLIC SYNONYM AMD_BSSM_SOURCE FOR AMD_BSSM_SOURCE;


ALTER TABLE AMD_BSSM_SOURCE ADD (
  CHECK ("REQUISITION_NO" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BSSM_SOURCE ADD (
  CHECK ("REQUISITION_DATE" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BSSM_SOURCE ADD (
  CHECK ("QUANTITY" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BSSM_SOURCE ADD (
  CHECK ("LOC_SID" IS NOT NULL) DISABLE);

ALTER TABLE AMD_BSSM_SOURCE ADD (
  CHECK ("NSN" IS NOT NULL) DISABLE);


GRANT SELECT ON  AMD_BSSM_SOURCE TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON  AMD_BSSM_SOURCE TO AMD_WRITER_ROLE;


