SET DEFINE OFF;
ALTER TABLE AMD_OWNER.AMD_SITE_ASSET_MGR
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMD_OWNER.AMD_SITE_ASSET_MGR CASCADE CONSTRAINTS;

CREATE TABLE AMD_OWNER.AMD_SITE_ASSET_MGR
(
  BEMS_ID         VARCHAR2(8 BYTE)              NOT NULL,
  PLANNER_CODE    VARCHAR2(8 BYTE)              NOT NULL,
  ACTION_CODE     VARCHAR2(1 BYTE)              DEFAULT 'A',
  LAST_UPDATE_DT  DATE                          DEFAULT sysdate
)
TABLESPACE AMD_INDEX
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX AMD_OWNER.AMD_SITE_ASSET_MGR_PK01 ON AMD_OWNER.AMD_SITE_ASSET_MGR
(BEMS_ID, PLANNER_CODE)
LOGGING
TABLESPACE AMD_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM AMD_SITE_ASSET_MGR;

CREATE PUBLIC SYNONYM AMD_SITE_ASSET_MGR FOR AMD_OWNER.AMD_SITE_ASSET_MGR;


ALTER TABLE AMD_OWNER.AMD_SITE_ASSET_MGR ADD (
  CONSTRAINT AMD_SITE_ASSET_MGR_PK01
 PRIMARY KEY
 (BEMS_ID, PLANNER_CODE)
    USING INDEX 
    TABLESPACE AMD_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE AMD_OWNER.AMD_SITE_ASSET_MGR ADD (
  CONSTRAINT AMD_SITE_ASSET_MGR_FK01 
 FOREIGN KEY (PLANNER_CODE) 
 REFERENCES AMD_OWNER.AMD_PLANNERS (PLANNER_CODE));

GRANT SELECT ON AMD_OWNER.AMD_SITE_ASSET_MGR TO AMD_READER_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON AMD_OWNER.AMD_SITE_ASSET_MGR TO AMD_WRITER_ROLE;


