DROP VIEW AMD_OWNER.DATASYS_LP_OVERRIDE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.DATASYS_LP_OVERRIDE_V
(
   PART,
   CAGE,
   SITE_LOCATION,
   TYPE,
   QUANTITY,
   BEGIN_DATE,
   END_DATE,
   OVERRIDE_USER,
   OVERRIDE_REASON
)
AS
   SELECT /*+ driving_site (p) */
         p.part,
          p.cage,
          l.site_location,
          t.VALUE,
          lpo.quantity,
          lpo.begin_date,
          lpo.end_date,
          su.spo_user,
          r.VALUE
     FROM escmc17v2.lp_override@stl_escm_link lpo,
          escmc17v2.part@stl_escm_link p,
          escmc17v2.LOCATION@stl_escm_link l,
          escmc17v2.TYPE@stl_escm_link t,
          escmc17v2.spo_user@stl_escm_link su,
          escmc17v2.TYPE@stl_escm_link r
    WHERE     lpo.part_id = p.part_id
          AND lpo.override_type_id = t.type_id
          AND lpo.location_id = l.location_id
          AND lpo.override_user_id = su.spo_user_id
          AND lpo.override_reason_id = r.type_id;


DROP VIEW AMD_OWNER.DATASYS_PART_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.DATASYS_PART_V
(
   PART_ID,
   EQUIPMENT_TYPE_ID,
   INDENTURE_ID,
   PART,
   CAGE,
   UNIT_ISSUE,
   END_DATE,
   BEGIN_DATE,
   PLANNED,
   NOUN,
   HAZMAT,
   SHELF_LIFE,
   SHELF_LIFE_ACTION_CODE,
   NSN_COG,
   NSN_FSC,
   NSN_NIIN,
   NSN_SMIC_MMAC,
   NSN_ACTY,
   NSN_MCC,
   ESSENTIALITY,
   UNIT_PACK_CUBE,
   UNIT_PACK_QTY,
   UNIT_PACK_WEIGHT,
   UNIT_PACK_MEASURE,
   ESD,
   PBL,
   MTBF,
   THIRD_PARTY,
   ROQ_BASED,
   SMRCODE,
   DECAY_RATE,
   SOURCE_SYSTEM,
   MATERIAL_CLASS,
   EXEMPT,
   IGNORE_WEIGHT_VOLUME,
   PRICE,
   REPAIR_COST,
   HOLDING_COST_RATE,
   MTBF_TYPE_ID,
   RCM_TYPE_ID,
   FIXED_ORDER_COST,
   PLANNER_CODE_ID,
   GENERATE_NEW_BUY,
   GENERATE_REPAIR,
   GENERATE_ALLOCATION,
   GENERATE_TRANSSHIPMENT,
   TIMESTAMP,
   ATTRIBUTE_28,
   ATTRIBUTE_29,
   ATTRIBUTE_30,
   ATTRIBUTE_31,
   ATTRIBUTE_32,
   IS_SEASONAL,
   MAX_TOTAL_TSL,
   ATTRIBUTE_18,
   ATTRIBUTE_19
)
AS
   SELECT "PART_ID",
          "EQUIPMENT_TYPE_ID",
          "INDENTURE_ID",
          "PART",
          "CAGE",
          "UNIT_ISSUE",
          "END_DATE",
          "BEGIN_DATE",
          "PLANNED",
          "NOUN",
          "HAZMAT",
          "SHELF_LIFE",
          "SHELF_LIFE_ACTION_CODE",
          "NSN_COG",
          "NSN_FSC",
          "NSN_NIIN",
          "NSN_SMIC_MMAC",
          "NSN_ACTY",
          "NSN_MCC",
          "ESSENTIALITY",
          "UNIT_PACK_CUBE",
          "UNIT_PACK_QTY",
          "UNIT_PACK_WEIGHT",
          "UNIT_PACK_MEASURE",
          "ESD",
          "PBL",
          "MTBF",
          "THIRD_PARTY",
          "ROQ_BASED",
          "SMRCODE",
          "DECAY_RATE",
          "SOURCE_SYSTEM",
          "MATERIAL_CLASS",
          "EXEMPT",
          "IGNORE_WEIGHT_VOLUME",
          "PRICE",
          "REPAIR_COST",
          "HOLDING_COST_RATE",
          "MTBF_TYPE_ID",
          "RCM_TYPE_ID",
          "FIXED_ORDER_COST",
          "PLANNER_CODE_ID",
          "GENERATE_NEW_BUY",
          "GENERATE_REPAIR",
          "GENERATE_ALLOCATION",
          "GENERATE_TRANSSHIPMENT",
          "TIMESTAMP",
          "ATTRIBUTE_28",
          "ATTRIBUTE_29",
          "ATTRIBUTE_30",
          "ATTRIBUTE_31",
          "ATTRIBUTE_32",
          "IS_SEASONAL",
          "MAX_TOTAL_TSL",
          "ATTRIBUTE_18",
          "ATTRIBUTE_19"
     FROM escmc17v2.part@stl_escm_link;


DROP VIEW AMD_OWNER.DATASYS_PLANNER_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.DATASYS_PLANNER_V
(
   PLANNER_ID,
   PLANNER_CODE_ID,
   PLANNER_TIMESTAMP,
   PLANNER_CODE,
   SPO_USER,
   NAME,
   USER_TIMESTAMP
)
AS
   SELECT p.planner_id "planner_id",
          p.planner_code_id "planner_code_id",
          p.TIMESTAMP "planner_timestamp",
          c.planner_code "planner_code",
          u.spo_user "spo_user",
          u.NAME "name",
          u.TIMESTAMP "user_timestamp"
     FROM escmc17v2.planner@stl_escm_link p,
          escmc17v2.planner_code@stl_escm_link c,
          escmc17v2.spo_user@stl_escm_link u
    WHERE     p.planner_code_id = c.planner_code_id
          AND p.spo_user_id = u.spo_user_id;


DROP VIEW AMD_OWNER.DATASYS_TRANS_PROCESSED_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.DATASYS_TRANS_PROCESSED_V
(
   DAY,
   BACKORDER_INFO,
   BOM_DETAIL,
   ORG_DEPLOYMENT,
   DEMAND_INFO,
   EXT_FORECAST,
   INV_INFO,
   IN_TRANSIT,
   LOCATION_CAUSAL,
   PART_FACTORS,
   LOCATION_PART_LEAD_TIME,
   LOCATION_PART_OVERRIDE,
   LOCATION_PART_REPLACEMENT_RATE,
   NETWORK_PART,
   ORDER_INFO_LINE,
   ORG_FLIGHT_ACTY,
   ORG_FLIGHT_ACTY_FORECAST,
   PART_INFO,
   PART_ALT_REL_DEL,
   PART_CAUSAL_TYPE,
   PART_LEAD_TIME,
   PART_SUPERSEDURE,
   PART_UPGRADED_PART,
   REPAIR_INFO,
   SITE_RESP_ASSET_MGR,
   SPO_USER,
   TAILNO_INFO,
   UNKNOWN,
   TRANSIT_TIME,
   TRANSIT_COST,
   TIMESTAMP,
   PART_ALT
)
AS
   SELECT "DAY",
          "BACKORDER_INFO",
          "BOM_DETAIL",
          "ORG_DEPLOYMENT",
          "DEMAND_INFO",
          "EXT_FORECAST",
          "INV_INFO",
          "IN_TRANSIT",
          "LOCATION_CAUSAL",
          "PART_FACTORS",
          "LOCATION_PART_LEAD_TIME",
          "LOCATION_PART_OVERRIDE",
          "LOCATION_PART_REPLACEMENT_RATE",
          "NETWORK_PART",
          "ORDER_INFO_LINE",
          "ORG_FLIGHT_ACTY",
          "ORG_FLIGHT_ACTY_FORECAST",
          "PART_INFO",
          "PART_ALT_REL_DEL",
          "PART_CAUSAL_TYPE",
          "PART_LEAD_TIME",
          "PART_SUPERSEDURE",
          "PART_UPGRADED_PART",
          "REPAIR_INFO",
          "SITE_RESP_ASSET_MGR",
          "SPO_USER",
          "TAILNO_INFO",
          "UNKNOWN",
          "TRANSIT_TIME",
          "TRANSIT_COST",
          "TIMESTAMP",
          "PART_ALT"
     FROM escmc17v2.transactions_processed@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_BACKORDER_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_BACKORDER_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "NAME",
          "DESCRIPTION",
          "LAST_MODIFIED"
     FROM spoc17v2.v_backorder_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_BOM_DETAIL_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_BOM_DETAIL_V
(
   PART,
   INCLUDED_PART,
   BOM,
   QUANTITY,
   BEGIN_DATE,
   END_DATE,
   PARENT_INCLUDED_PART,
   LAST_MODIFIED
)
AS
   SELECT part,
          included_part,
          bom,
          quantity,
          begin_date,
          end_date,
          parent_included_part,
          last_modified
     FROM spoc17v2.v_bom_detail@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_BOM_LOCATION_CONTRACT_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_BOM_LOCATION_CONTRACT_V
(
   LOCATION,
   BOM,
   CONTRACT_TYPE,
   CUSTOMER_LOCATION,
   BEGIN_DATE,
   END_DATE,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT location,
          bom,
          contract_type,
          customer_location,
          begin_date,
          end_date,
          quantity,
          last_modified
     FROM spoc17v2.v_bom_location_contract@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_CAUSAL_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_CAUSAL_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "NAME",
          "DESCRIPTION",
          last_modified
     FROM spoc17v2.v_causal_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_CONFIRMED_REQUEST_LINE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_CONFIRMED_REQUEST_LINE_V
(
   CONFIRMED_REQUEST,
   LINE,
   LOCATION,
   PART,
   PROPOSED_REQUEST,
   REQUEST_DATE,
   DUE_DATE,
   QUANTITY_ORDERED,
   QUANTITY_RECEIVED,
   REQUEST_STATUS,
   SUPPLIER_LOCATION,
   LAST_MODIFIED,
   ATTRIBUTE_1,
   ATTRIBUTE_2,
   ATTRIBUTE_3,
   ATTRIBUTE_4,
   ATTRIBUTE_5,
   ATTRIBUTE_6,
   ATTRIBUTE_7,
   ATTRIBUTE_8
)
AS
   SELECT confirmed_request,
          line,
          location,
          part,
          proposed_request,
          request_date,
          due_date,
          quantity_ordered,
          quantity_received,
          request_status,
          supplier_location,
          last_modified,
          attribute_1,
          attribute_2,
          attribute_3,
          attribute_4,
          attribute_5,
          attribute_6,
          attribute_7,
          attribute_8
     FROM spoc17v2.v_confirmed_request_line@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_CONFIRMED_REQUEST_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_CONFIRMED_REQUEST_V
(
   ID,
   NAME,
   REQUEST_TYPE,
   LAST_MODIFIED
)
AS
   SELECT id,
          name,
          request_type,
          last_modified
     FROM spoc17v2.v_confirmed_request@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_CONTRACT_CAUSAL_FORECAST_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_CONTRACT_CAUSAL_FORECAST_V
(
   LOCATION,
   CONTRACT,
   CONTRACT_TYPE,
   CAUSAL_TYPE,
   PERIOD,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT "LOCATION",
          "CONTRACT",
          "CONTRACT_TYPE",
          "CAUSAL_TYPE",
          "PERIOD",
          "QUANTITY",
          last_modified
     FROM spoc17v2.v_contract_causal_forecast@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_CONTRACT_CAUSAL_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_CONTRACT_CAUSAL_V
(
   LOCATION,
   CONTRACT,
   CONTRACT_TYPE,
   CAUSAL_TYPE,
   PERIOD,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT "LOCATION",
          "CONTRACT",
          "CONTRACT_TYPE",
          "CAUSAL_TYPE",
          "PERIOD",
          "QUANTITY",
          last_modified
     FROM spoc17v2.v_contract_causal@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_CURRENT_PERIOD_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_CURRENT_PERIOD_V
(
   ID,
   BEGIN_DATE,
   END_DATE,
   YEAR_NUMBER,
   MONTH_NUMBER,
   WEEK_NUMBER,
   CALENDAR_YEAR_NUMBER,
   CALENDAR_MONTH_NUMBER
)
AS
   SELECT "ID",
          "BEGIN_DATE",
          "END_DATE",
          "YEAR_NUMBER",
          "MONTH_NUMBER",
          "WEEK_NUMBER",
          "CALENDAR_YEAR_NUMBER",
          "CALENDAR_MONTH_NUMBER"
     FROM spoc17v2.v_current_period@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_DEMAND_FORECAST_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_DEMAND_FORECAST_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "NAME",
          "DESCRIPTION",
          "LAST_MODIFIED"
     FROM spoc17v2.v_demand_forecast_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_DEMAND_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_DEMAND_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "NAME",
          "DESCRIPTION",
          last_modified
     FROM spoc17v2.v_demand_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_EXCEPTION_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_EXCEPTION_V
(
   ID,
   EXCEPTION_TYPE,
   CLASS,
   MESSAGE
)
AS
   SELECT "ID",
          "EXCEPTION_TYPE",
          "CLASS",
          "MESSAGE"
     FROM spoc17v2.v_exception@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_FIXED_CURRENT_PERIOD_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_FIXED_CURRENT_PERIOD_V
(
   PERIOD,
   LAST_MODIFIED
)
AS
   SELECT "PERIOD", last_modified FROM spoc17v2.current_period@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_FLAG_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_FLAG_V
(
   NAME,
   DESCRIPTION,
   FLAG_TYPE,
   VALUE,
   LAST_MODIFIED
)
AS
   SELECT "NAME",
          "DESCRIPTION",
          "FLAG_TYPE",
          "VALUE",
          last_modified
     FROM spoc17v2.v_flag@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_FX_LP_DEMAND_FORECAST_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_FX_LP_DEMAND_FORECAST_V
(
   LOCATION,
   PART,
   DEMAND_FORECAST_TYPE,
   PERIOD,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT "LOCATION",
          "PART",
          "DEMAND_FORECAST_TYPE",
          "PERIOD",
          "QUANTITY",
          last_modified
     FROM spoc17v2.v_fx_lp_demand_forecast@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_INTERFACE_BATCH_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_INTERFACE_BATCH_V
(
   INTERFACE,
   BATCH,
   BATCH_MODE,
   BEGIN_DATE,
   LAST_DATE,
   END_DATE,
   PROCESSED_RECORDS,
   LAST_MODIFIED
)
AS
   SELECT "INTERFACE",
          "BATCH",
          "BATCH_MODE",
          "BEGIN_DATE",
          "LAST_DATE",
          "END_DATE",
          "PROCESSED_RECORDS",
          last_modified
     FROM spoc17v2.v_interface_batch@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_IN_TRANSIT_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_IN_TRANSIT_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "NAME",
          "DESCRIPTION",
          last_modified
     FROM spoc17v2.v_in_transit_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_LOCATION_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_LOCATION_V
(
   ID,
   NAME,
   LOCATION_TYPE,
   DESCRIPTION,
   IS_DGI_LOCATION,
   MAX_PART_UNIT_WEIGHT,
   MAX_PART_UNIT_VOLUME,
   LAST_MODIFIED,
   ATTRIBUTE_1,
   ATTRIBUTE_2,
   ATTRIBUTE_3,
   ATTRIBUTE_4,
   ATTRIBUTE_5,
   ATTRIBUTE_6,
   ATTRIBUTE_7,
   ATTRIBUTE_8
)
AS
   SELECT "ID",
          "NAME",
          "LOCATION_TYPE",
          "DESCRIPTION",
          "IS_DGI_LOCATION",
          "MAX_PART_UNIT_WEIGHT",
          "MAX_PART_UNIT_VOLUME",
          last_modified,
          "ATTRIBUTE_1",
          "ATTRIBUTE_2",
          "ATTRIBUTE_3",
          "ATTRIBUTE_4",
          "ATTRIBUTE_5",
          "ATTRIBUTE_6",
          "ATTRIBUTE_7",
          "ATTRIBUTE_8"
     FROM spoc17v2.v_location@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_LP_ATTRIBUTE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_LP_ATTRIBUTE_V
(
   LOCATION,
   PART,
   CONDEMNATION_RATE,
   PASSUP_RATE,
   CRITICALITY,
   VARIANCE_TO_MEAN_RATIO,
   DEMAND_FORECAST_TYPE,
   ATTRIBUTE_1,
   ATTRIBUTE_2,
   ATTRIBUTE_3,
   ATTRIBUTE_4,
   ATTRIBUTE_5,
   ATTRIBUTE_6,
   ATTRIBUTE_7,
   ATTRIBUTE_8,
   ATTRIBUTE_9,
   ATTRIBUTE_10,
   ATTRIBUTE_11,
   ATTRIBUTE_12,
   ATTRIBUTE_13,
   ATTRIBUTE_14,
   ATTRIBUTE_15,
   ATTRIBUTE_16,
   ATTRIBUTE_17,
   ATTRIBUTE_18,
   ATTRIBUTE_19,
   ATTRIBUTE_20,
   ATTRIBUTE_21,
   ATTRIBUTE_22,
   ATTRIBUTE_23,
   ATTRIBUTE_24,
   ATTRIBUTE_25,
   ATTRIBUTE_26,
   ATTRIBUTE_27,
   ATTRIBUTE_28,
   ATTRIBUTE_29,
   ATTRIBUTE_30,
   ATTRIBUTE_31,
   ATTRIBUTE_32,
   LAST_MODIFIED
)
AS
   SELECT "LOCATION",
          "PART",
          "CONDEMNATION_RATE",
          "PASSUP_RATE",
          "CRITICALITY",
          "VARIANCE_TO_MEAN_RATIO",
          "DEMAND_FORECAST_TYPE",
          "ATTRIBUTE_1",
          "ATTRIBUTE_2",
          "ATTRIBUTE_3",
          "ATTRIBUTE_4",
          "ATTRIBUTE_5",
          "ATTRIBUTE_6",
          "ATTRIBUTE_7",
          "ATTRIBUTE_8",
          "ATTRIBUTE_9",
          "ATTRIBUTE_10",
          "ATTRIBUTE_11",
          "ATTRIBUTE_12",
          "ATTRIBUTE_13",
          "ATTRIBUTE_14",
          "ATTRIBUTE_15",
          "ATTRIBUTE_16",
          "ATTRIBUTE_17",
          "ATTRIBUTE_18",
          "ATTRIBUTE_19",
          "ATTRIBUTE_20",
          "ATTRIBUTE_21",
          "ATTRIBUTE_22",
          "ATTRIBUTE_23",
          "ATTRIBUTE_24",
          "ATTRIBUTE_25",
          "ATTRIBUTE_26",
          "ATTRIBUTE_27",
          "ATTRIBUTE_28",
          "ATTRIBUTE_29",
          "ATTRIBUTE_30",
          "ATTRIBUTE_31",
          "ATTRIBUTE_32",
          last_modified
     FROM spoc17v2.v_lp_attribute@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_LP_BACKORDER_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_LP_BACKORDER_V
(
   LOCATION,
   PART,
   BACKORDER_TYPE,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT location,
          part,
          backorder_type,
          quantity,
          last_modified
     FROM spoc17v2.v_lp_backorder@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_LP_DEMAND_FORECAST_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_LP_DEMAND_FORECAST_V
(
   LOCATION,
   PART,
   DEMAND_FORECAST_TYPE,
   PERIOD,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT "LOCATION",
          "PART",
          "DEMAND_FORECAST_TYPE",
          "PERIOD",
          "QUANTITY",
          last_modified
     FROM spoc17v2.v_lp_demand_forecast@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_LP_DEMAND_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_LP_DEMAND_V
(
   TRANSACTION_ID,
   LOCATION,
   PART,
   CONTRACT,
   DEMAND_TYPE,
   DEMAND_DATE,
   CUSTOMER_LOCATION,
   PRODUCT_SERIAL_NUMBER,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT "TRANSACTION_ID",
          "LOCATION",
          "PART",
          "CONTRACT",
          "DEMAND_TYPE",
          "DEMAND_DATE",
          "CUSTOMER_LOCATION",
          "PRODUCT_SERIAL_NUMBER",
          "QUANTITY",
          last_modified
     FROM spoc17v2.v_lp_demand@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_LP_IN_TRANSIT_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_LP_IN_TRANSIT_V
(
   LOCATION,
   PART,
   IN_TRANSIT_TYPE,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT "LOCATION",
          "PART",
          "IN_TRANSIT_TYPE",
          "QUANTITY",
          last_modified
     FROM spoc17v2.v_lp_in_transit@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_LP_ON_HAND_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_LP_ON_HAND_V
(
   LOCATION,
   PART,
   ON_HAND_TYPE,
   LAST_MODIFIED,
   QUANTITY
)
AS
   SELECT "LOCATION",
          "PART",
          "ON_HAND_TYPE",
          last_modified,
          "QUANTITY"
     FROM spoc17v2.v_lp_on_hand@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_LP_OVERRIDE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_LP_OVERRIDE_V
(
   PART,
   LOCATION,
   OVERRIDE_TYPE,
   QUANTITY,
   OVERRIDE_REASON,
   OVERRIDE_USER,
   BEGIN_DATE,
   END_DATE,
   LAST_MODIFIED
)
AS
     SELECT "PART",
            "LOCATION",
            "OVERRIDE_TYPE",
            "QUANTITY",
            "OVERRIDE_REASON",
            "OVERRIDE_USER",
            "BEGIN_DATE",
            "END_DATE",
            last_modified
       FROM spoc17v2.v_lp_override@stl_escm_link
   ORDER BY location, part, override_type;


DROP VIEW AMD_OWNER.SPO_MTBF_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_MTBF_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "NAME",
          "DESCRIPTION",
          last_modified
     FROM spoc17v2.v_mtbf_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_ON_HAND_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_ON_HAND_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "NAME",
          "DESCRIPTION",
          last_modified
     FROM spoc17v2.v_on_hand_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_OVERRIDE_REASON_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_OVERRIDE_REASON_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION
)
AS
   SELECT "ID", "NAME", "DESCRIPTION"
     FROM spoc17v2.v_override_reason_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_OVERRIDE_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_OVERRIDE_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "NAME",
          "DESCRIPTION",
          last_modified
     FROM spoc17v2.v_override_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_PARAMETER_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_PARAMETER_V
(
   NAME,
   DESCRIPTION,
   PARAMETER_TYPE,
   VALUE,
   LAST_MODIFIED
)
AS
   SELECT "NAME",
          "DESCRIPTION",
          "PARAMETER_TYPE",
          "VALUE",
          last_modified
     FROM spoc17v2.v_parameter@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_PART_CAUSAL_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_PART_CAUSAL_TYPE_V
(
   PART,
   CAUSAL_TYPE,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT part,
          causal_type,
          quantity,
          last_modified
     FROM spoc17v2.v_part_causal_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_PART_MTBF_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_PART_MTBF_V
(
   PART,
   MTBF_TYPE,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT part,
          mtbf_type,
          quantity,
          last_modified
     FROM spoc17v2.v_part_mtbf@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_PART_PLANNED_PART_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_PART_PLANNED_PART_V
(
   PART,
   PLANNED_PART,
   SUPERSESSION_TYPE,
   BEGIN_DATE,
   END_DATE,
   LAST_MODIFIED,
   SPO_USER
)
AS
   SELECT part,
          planned_part,
          supersession_type,
          begin_date,
          end_date,
          last_modified,
          spo_user
     FROM spoc17v2.v_part_planned_part@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_PART_UPGRADED_PART_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_PART_UPGRADED_PART_V
(
   PART,
   UPGRADED_PART,
   LAST_MODIFIED
)
AS
   SELECT part, upgraded_part, last_modified
     FROM spoc17v2.v_part_upgraded_part@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_PART_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_PART_V
(
   ID,
   NAME,
   PART_TYPE,
   DESCRIPTION,
   COST,
   BEGIN_DATE,
   END_DATE,
   HOLDING_COST_RATE,
   FIXED_ORDER_COST,
   IS_ORDER_POLICY_ROQ_BASED,
   IS_REPARABLE,
   REPAIR_COST,
   DECAY_RATE,
   GENERATE_NEW_BUY,
   GENERATE_REPAIR,
   GENERATE_ALLOCATION,
   GENERATE_TRANSSHIPMENT,
   MAX_QTY_ALLOWANCE,
   MAX_TOTAL_TSL,
   LAST_MODIFIED,
   IS_PLANNED,
   ATTRIBUTE_1,
   ATTRIBUTE_2,
   ATTRIBUTE_3,
   ATTRIBUTE_4,
   ATTRIBUTE_5,
   ATTRIBUTE_6,
   ATTRIBUTE_7,
   ATTRIBUTE_8,
   ATTRIBUTE_9,
   ATTRIBUTE_10,
   ATTRIBUTE_11,
   ATTRIBUTE_12,
   ATTRIBUTE_13,
   ATTRIBUTE_14,
   ATTRIBUTE_15,
   ATTRIBUTE_16,
   ATTRIBUTE_17,
   ATTRIBUTE_18,
   ATTRIBUTE_19,
   ATTRIBUTE_20,
   ATTRIBUTE_21,
   ATTRIBUTE_22,
   ATTRIBUTE_23,
   ATTRIBUTE_24,
   ATTRIBUTE_25,
   ATTRIBUTE_26,
   ATTRIBUTE_27,
   ATTRIBUTE_28,
   ATTRIBUTE_29,
   ATTRIBUTE_30,
   ATTRIBUTE_31,
   ATTRIBUTE_32,
   MATERIAL_CLASS,
   WEIGHT,
   VOLUME,
   IS_EXEMPT,
   IGNORE_WEIGHT_AND_VOLUME,
   IS_SEASONAL,
   IS_CANNIBALIZABLE,
   PARTIAL_ONE_WAY_SUPERSESSION,
   IS_NEW,
   LIKE_PART,
   NEW_BUY_LEAD_TIME,
   REPAIR_LEAD_TIME,
   NEW_BUY_LEAD_TIME_VARIANCE,
   REPAIR_LEAD_TIME_VARIANCE,
   FORECAST_RISK_MULTIPLIER
)
AS
   SELECT "ID",
          "NAME",
          "PART_TYPE",
          "DESCRIPTION",
          "COST",
          "BEGIN_DATE",
          "END_DATE",
          "HOLDING_COST_RATE",
          "FIXED_ORDER_COST",
          "IS_ORDER_POLICY_ROQ_BASED",
          "IS_REPARABLE",
          "REPAIR_COST",
          "DECAY_RATE",
          "GENERATE_NEW_BUY",
          "GENERATE_REPAIR",
          "GENERATE_ALLOCATION",
          "GENERATE_TRANSSHIPMENT",
          "MAX_QTY_ALLOWANCE",
          "MAX_TOTAL_TSL",
          "LAST_MODIFIED",
          "IS_PLANNED",
          "ATTRIBUTE_1",
          "ATTRIBUTE_2",
          "ATTRIBUTE_3",
          "ATTRIBUTE_4",
          "ATTRIBUTE_5",
          "ATTRIBUTE_6",
          "ATTRIBUTE_7",
          "ATTRIBUTE_8",
          "ATTRIBUTE_9",
          "ATTRIBUTE_10",
          "ATTRIBUTE_11",
          "ATTRIBUTE_12",
          "ATTRIBUTE_13",
          "ATTRIBUTE_14",
          "ATTRIBUTE_15",
          "ATTRIBUTE_16",
          "ATTRIBUTE_17",
          "ATTRIBUTE_18",
          "ATTRIBUTE_19",
          "ATTRIBUTE_20",
          "ATTRIBUTE_21",
          "ATTRIBUTE_22",
          "ATTRIBUTE_23",
          "ATTRIBUTE_24",
          "ATTRIBUTE_25",
          "ATTRIBUTE_26",
          "ATTRIBUTE_27",
          "ATTRIBUTE_28",
          "ATTRIBUTE_29",
          "ATTRIBUTE_30",
          "ATTRIBUTE_31",
          "ATTRIBUTE_32",
          "MATERIAL_CLASS",
          "WEIGHT",
          "VOLUME",
          "IS_EXEMPT",
          "IGNORE_WEIGHT_AND_VOLUME",
          "IS_SEASONAL",
          "IS_CANNIBALIZABLE",
          "PARTIAL_ONE_WAY_SUPERSESSION",
          "IS_NEW",
          "LIKE_PART",
          "NEW_BUY_LEAD_TIME",
          "REPAIR_LEAD_TIME",
          "NEW_BUY_LEAD_TIME_VARIANCE",
          "REPAIR_LEAD_TIME_VARIANCE",
          "FORECAST_RISK_MULTIPLIER"
     FROM spoc17v2.v_part@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_PERIOD_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_PERIOD_V
(
   ID,
   BEGIN_DATE,
   END_DATE,
   YEAR_NUMBER,
   MONTH_NUMBER,
   WEEK_NUMBER,
   CALENDAR_YEAR_NUMBER,
   CALENDAR_MONTH_NUMBER,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "BEGIN_DATE",
          "END_DATE",
          "YEAR_NUMBER",
          "MONTH_NUMBER",
          "WEEK_NUMBER",
          "CALENDAR_YEAR_NUMBER",
          "CALENDAR_MONTH_NUMBER",
          last_modified
     FROM spoc17v2.v_period@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_REQUEST_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_REQUEST_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "NAME",
          "DESCRIPTION",
          last_modified
     FROM spoc17v2.v_request_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_SUPERSESSION_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_SUPERSESSION_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "NAME",
          "DESCRIPTION",
          last_modified
     FROM spoc17v2.v_supersession_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_USER_PART_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_USER_PART_V
(
   SPO_USER,
   PART,
   LAST_MODIFIED
)
AS
   SELECT "SPO_USER", "PART", uparts.last_modified last_modified
     FROM spoc17v2.v_user_part@stl_escm_link uparts,
          spoc17v2.v_part@stl_escm_link parts
    WHERE uparts.part = parts.name AND parts.end_date IS NULL;


DROP VIEW AMD_OWNER.SPO_USER_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_USER_TYPE_V
(
   ID,
   NAME,
   DESCRIPTION,
   LAST_MODIFIED
)
AS
   SELECT "ID",
          "NAME",
          "DESCRIPTION",
          last_modified
     FROM spoc17v2.v_user_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_USER_USER_TYPE_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_USER_USER_TYPE_V
(
   SPO_USER,
   USER_TYPE,
   LAST_MODIFIED
)
AS
   SELECT "SPO_USER", "USER_TYPE", last_modified
     FROM spoc17v2.v_user_user_type@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_USER_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_USER_V
(
   ID,
   NAME,
   EMAIL_ADDRESS,
   ATTRIBUTE_1,
   ATTRIBUTE_2,
   ATTRIBUTE_3,
   ATTRIBUTE_4,
   ATTRIBUTE_5,
   ATTRIBUTE_6,
   ATTRIBUTE_7,
   ATTRIBUTE_8,
   LAST_MODIFIED
)
AS
   SELECT id,
          name,
          email_address,
          attribute_1,
          attribute_2,
          attribute_3,
          attribute_4,
          attribute_5,
          attribute_6,
          attribute_7,
          attribute_8,
          last_modified
     FROM spoc17v2.v_spo_user@stl_escm_link;


DROP VIEW AMD_OWNER.SPO_X_IMP_INTERFACE_BATCH_V;

/* Formatted on 2/13/2015 1:06:00 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.SPO_X_IMP_INTERFACE_BATCH_V
(
   INTERFACE,
   BATCH,
   BATCH_MODE,
   ACTION,
   EXCEPTION,
   LAST_MODIFIED,
   INTERFACE_SEQUENCE
)
AS
   SELECT "INTERFACE",
          "BATCH",
          "BATCH_MODE",
          "ACTION",
          "EXCEPTION",
          last_modified,
          "INTERFACE_SEQUENCE"
     FROM spoc17v2.x_imp_interface_batch@stl_escm_link;


CREATE OR REPLACE PUBLIC SYNONYM DATASYS_LP_OVERRIDE_V FOR AMD_OWNER.DATASYS_LP_OVERRIDE_V;


CREATE OR REPLACE PUBLIC SYNONYM DATASYS_PART_V FOR AMD_OWNER.DATASYS_PART_V;


CREATE OR REPLACE PUBLIC SYNONYM DATASYS_PLANNER_V FOR AMD_OWNER.DATASYS_PLANNER_V;


CREATE OR REPLACE PUBLIC SYNONYM DATASYS_TRANS_PROCESSED_V FOR AMD_OWNER.DATASYS_TRANS_PROCESSED_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_BACKORDER_TYPE_V FOR AMD_OWNER.SPO_BACKORDER_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_BOM_DETAIL_V FOR AMD_OWNER.SPO_BOM_DETAIL_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_BOM_LOCATION_CONTRACT_V FOR AMD_OWNER.SPO_BOM_LOCATION_CONTRACT_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_CAUSAL_TYPE_V FOR AMD_OWNER.SPO_CAUSAL_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_CONFIRMED_REQUEST_LINE_V FOR AMD_OWNER.SPO_CONFIRMED_REQUEST_LINE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_CONFIRMED_REQUEST_V FOR AMD_OWNER.SPO_CONFIRMED_REQUEST_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_CONTRACT_CAUSAL_FORECAST_V FOR AMD_OWNER.SPO_CONTRACT_CAUSAL_FORECAST_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_CONTRACT_CAUSAL_V FOR AMD_OWNER.SPO_CONTRACT_CAUSAL_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_CURRENT_PERIOD_V FOR AMD_OWNER.SPO_CURRENT_PERIOD_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_DEMAND_FORECAST_TYPE_V FOR AMD_OWNER.SPO_DEMAND_FORECAST_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_DEMAND_TYPE_V FOR AMD_OWNER.SPO_DEMAND_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_EXCEPTION_V FOR AMD_OWNER.SPO_EXCEPTION_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_FIXED_CURRENT_PERIOD_V FOR AMD_OWNER.SPO_FIXED_CURRENT_PERIOD_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_FLAG_V FOR AMD_OWNER.SPO_FLAG_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_FX_LP_DEMAND_FORECAST_V FOR AMD_OWNER.SPO_FX_LP_DEMAND_FORECAST_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_INTERFACE_BATCH_V FOR AMD_OWNER.SPO_INTERFACE_BATCH_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_IN_TRANSIT_TYPE_V FOR AMD_OWNER.SPO_IN_TRANSIT_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_LOCATION_V FOR AMD_OWNER.SPO_LOCATION_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_LP_ATTRIBUTE_V FOR AMD_OWNER.SPO_LP_ATTRIBUTE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_LP_BACKORDER_V FOR AMD_OWNER.SPO_LP_BACKORDER_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_LP_DEMAND_FORECAST_V FOR AMD_OWNER.SPO_LP_DEMAND_FORECAST_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_LP_DEMAND_V FOR AMD_OWNER.SPO_LP_DEMAND_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_LP_IN_TRANSIT_V FOR AMD_OWNER.SPO_LP_IN_TRANSIT_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_LP_ON_HAND_V FOR AMD_OWNER.SPO_LP_ON_HAND_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_LP_OVERRIDE_V FOR AMD_OWNER.SPO_LP_OVERRIDE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_MTBF_TYPE_V FOR AMD_OWNER.SPO_MTBF_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_ON_HAND_TYPE_V FOR AMD_OWNER.SPO_ON_HAND_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_OVERRIDE_REASON_TYPE_V FOR AMD_OWNER.SPO_OVERRIDE_REASON_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_OVERRIDE_TYPE_V FOR AMD_OWNER.SPO_OVERRIDE_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_PARAMETER_V FOR AMD_OWNER.SPO_PARAMETER_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_PART_CAUSAL_TYPE_V FOR AMD_OWNER.SPO_PART_CAUSAL_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_PART_MTBF_V FOR AMD_OWNER.SPO_PART_MTBF_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_PART_PLANNED_PART_V FOR AMD_OWNER.SPO_PART_PLANNED_PART_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_PART_UPGRADED_PART_V FOR AMD_OWNER.SPO_PART_UPGRADED_PART_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_PART_V FOR AMD_OWNER.SPO_PART_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_PERIOD_V FOR AMD_OWNER.SPO_PERIOD_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_REQUEST_TYPE_V FOR AMD_OWNER.SPO_REQUEST_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_SUPERSESSION_TYPE_V FOR AMD_OWNER.SPO_SUPERSESSION_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_USER_PART_V FOR AMD_OWNER.SPO_USER_PART_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_USER_TYPE_V FOR AMD_OWNER.SPO_USER_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_USER_USER_TYPE_V FOR AMD_OWNER.SPO_USER_USER_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_USER_V FOR AMD_OWNER.SPO_USER_V;


CREATE OR REPLACE PUBLIC SYNONYM SPO_X_IMP_INTERFACE_BATCH_V FOR AMD_OWNER.SPO_X_IMP_INTERFACE_BATCH_V;


GRANT SELECT ON AMD_OWNER.DATASYS_LP_OVERRIDE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.DATASYS_PART_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.DATASYS_PLANNER_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.DATASYS_TRANS_PROCESSED_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_BACKORDER_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_BOM_DETAIL_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_BOM_LOCATION_CONTRACT_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_CAUSAL_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_CONFIRMED_REQUEST_LINE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_CONFIRMED_REQUEST_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_CONTRACT_CAUSAL_FORECAST_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_CONTRACT_CAUSAL_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_CURRENT_PERIOD_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_DEMAND_FORECAST_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_DEMAND_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_EXCEPTION_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_FIXED_CURRENT_PERIOD_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_FLAG_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_FX_LP_DEMAND_FORECAST_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_INTERFACE_BATCH_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_IN_TRANSIT_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_LOCATION_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_LP_ATTRIBUTE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_LP_BACKORDER_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_LP_DEMAND_FORECAST_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_LP_DEMAND_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_LP_IN_TRANSIT_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_LP_ON_HAND_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_LP_OVERRIDE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_MTBF_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_ON_HAND_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_OVERRIDE_REASON_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_OVERRIDE_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_PARAMETER_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_PART_CAUSAL_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_PART_MTBF_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_PART_PLANNED_PART_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_PART_UPGRADED_PART_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_PART_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_PERIOD_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_REQUEST_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_SUPERSESSION_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_USER_PART_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_USER_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_USER_USER_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_USER_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.SPO_X_IMP_INTERFACE_BATCH_V TO AMD_READER_ROLE;

DROP VIEW AMD_OWNER.AMD_RSP_SUM_REPAIRABLES_V;

/* Formatted on 2/13/2015 1:41:23 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.AMD_RSP_SUM_REPAIRABLES_V
(
   PART_NO,
   RSP_LOCATION,
   QTY_ON_HAND,
   RSP_LEVEL,
   ACTION_CODE,
   LAST_UPDATE_DT,
   OVERRIDE_TYPE
)
AS
     SELECT part_no,
            rsp_location,
            qty_on_hand,
            rsp_level,
            action_code,
            last_update_dt,
            override_type
       FROM amd_rsp_sum
      WHERE override_type = (SELECT tsl_fixed_override FROM amd_spo_types_v)
   ORDER BY 1, 2;


DROP VIEW AMD_OWNER.AMD_SPO_TYPES_V;

/* Formatted on 2/13/2015 1:41:23 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.AMD_SPO_TYPES_V
(
   GENERAL_BACKORDER,
   EXTERNAL_DEMAND_FORECAST,
   GENERAL_DEMAND,
   GENERAL_IN_TRANSIT,
   DEFECTIVE_IN_TRANSIT,
   GENERAL_ON_HAND,
   DEFECTIVE_ON_HAND,
   TSL_FIXED_OVERRIDE,
   ROP_FIXED_OVERRIDE,
   ROQ_FIXED_OVERRIDE,
   FIXED_TSL_LOAD_OVERRIDE_REASON,
   FLIGHT_HOURS_CAUSAL,
   ENGINEERING_FLIGHT_HOURS_MTBF,
   NEW_BUY_REQUEST,
   REPAIR_REQUEST,
   NEW_BUY_LEAD_TIME,
   REPAIR_LEAD_TIME,
   TWO_WAY_SUPERSESSION
)
AS
   SELECT (SELECT name
             FROM spo_backorder_type_v
            WHERE id = 1001)
             general_backorder,
          (SELECT name
             FROM spo_demand_forecast_type_v
            WHERE id = 1003)
             external_demand_forecast,
          (SELECT name
             FROM spo_demand_type_v
            WHERE id = 1001)
             general_demand,
          (SELECT name
             FROM spo_in_transit_type_v
            WHERE id = 1001)
             general_in_transit,
          (SELECT name
             FROM spo_in_transit_type_v
            WHERE id = 1004)
             defective_in_transit,
          (SELECT name
             FROM spo_on_hand_type_v
            WHERE id = 1001)
             general_on_hand,
          (SELECT name
             FROM spo_on_hand_type_v
            WHERE id = 1004)
             defective_on_hand,
          (SELECT name
             FROM spo_override_type_v
            WHERE id = 1004)
             tsl_fixed_override,
          (SELECT name
             FROM spo_override_type_v
            WHERE id = 1008)
             rop_fixed_override,
          (SELECT name
             FROM spo_override_type_v
            WHERE id = 1010)
             roq_fixed_override,
          (SELECT name
             FROM spo_override_reason_type_v
            WHERE id = 10001)
             fixed_load_override_reason,
          (SELECT name
             FROM spo_causal_type_v
            WHERE id = 1002)
             flight_hours_causal,
          (SELECT name
             FROM spo_mtbf_type_v
            WHERE id = 1004)
             engineering_flight_hours_mtbf,
          (SELECT name
             FROM spo_request_type_v
            WHERE id = 1001)
             new_buy_request,
          (SELECT name
             FROM spo_request_type_v
            WHERE id = 1002)
             repair_request,
          (SELECT name
             FROM spo_request_type_v
            WHERE id = 1001)
             new_buy_lead_time,
          (SELECT name
             FROM spo_request_type_v
            WHERE id = 1002)
             repair_lead_time,
          (SELECT name
             FROM spo_supersession_type_v
            WHERE id = 1002)
             two_way_supersession
     FROM DUAL;


CREATE OR REPLACE PUBLIC SYNONYM AMD_RSP_SUM_REPAIRABLES_V FOR AMD_OWNER.AMD_RSP_SUM_REPAIRABLES_V;


CREATE OR REPLACE PUBLIC SYNONYM AMD_SPO_TYPES_V FOR AMD_OWNER.AMD_SPO_TYPES_V;


GRANT SELECT ON AMD_OWNER.AMD_RSP_SUM_REPAIRABLES_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.AMD_SPO_TYPES_V TO AMD_READER_ROLE;

DROP VIEW AMD_OWNER.X_CONFIRMED_REQUEST_LINE_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_CONFIRMED_REQUEST_LINE_V
(
   CONFIRMED_REQUEST,
   LINE,
   LOCATION,
   PART,
   PROPOSED_REQUEST,
   REQUEST_DATE,
   DUE_DATE,
   QUANTITY_ORDERED,
   QUANTITY_RECEIVED,
   REQUEST_STATUS,
   SUPPLIER_LOCATION,
   LAST_MODIFIED,
   ATTRIBUTE_1,
   ATTRIBUTE_2,
   ATTRIBUTE_3,
   ATTRIBUTE_4,
   ATTRIBUTE_5,
   ATTRIBUTE_6,
   ATTRIBUTE_7,
   ATTRIBUTE_8,
   DATA_SOURCE
)
AS
   SELECT gold_order_number confirmed_request,
          line,
          amd_utils.getspolocation (loc_sid) location,
          on_order.part_no part,
          NULL proposed_request,
          order_date request_date,
          CASE
             WHEN sched_receipt_date IS NOT NULL THEN sched_receipt_date
             ELSE amd_owner.getduedate (on_order.part_no, order_date)
          END
             due_date,
          order_qty quantity,
          0 quantity_received,
          'O' request_status,
          NULL supplier_location,
          on_order.last_update_dt last_modified,
          NULL attribute_1,
          NULL attribute_2,
          NULL attribute_3,
          NULL attribute_4,
          NULL attribute_5,
          NULL attribute_6,
          NULL attribute_7,
          NULL attribute_8,
          'AMD_ON_ORDER' data_source
     FROM amd_on_order on_order, amd_spare_parts parts, x_confirmed_request_v
    WHERE     gold_order_number = name
          AND amd_utils.getspolocation (loc_sid) IS NOT NULL
          AND on_order.action_code <> 'D'
          AND on_order.part_no = parts.part_no
          AND parts.is_spo_part = 'Y'
   UNION
   SELECT order_no confirmed_request,
          ROWNUM line,
          amd_utils.getspolocation (loc_sid) location,
          in_repair.part_no part,
          NULL proposed_request,
          repair_date request_date,
          CASE
             WHEN repair_need_date IS NOT NULL THEN repair_need_date
             ELSE amd_owner.getduedate (in_repair.part_no, repair_date)
          END
             due_date,
          repair_qty quantity,
          0 quantity_received,
          'O' request_status,
          NULL supplier_location,
          in_repair.last_update_dt last_modified,
          NULL attribute_1,
          NULL attribute_2,
          NULL attribute_3,
          NULL attribute_4,
          NULL attribute_5,
          NULL attribute_6,
          NULL attribute_7,
          NULL attribute_8,
          'AMD_IN_REPAIR' data_source
     FROM amd_in_repair in_repair,
          amd_spare_parts parts,
          x_confirmed_request_v
    WHERE     order_no = name
          AND amd_utils.getspolocation (loc_sid) IS NOT NULL
          AND in_repair.action_code <> 'D'
          AND in_repair.part_no = parts.part_no
          AND parts.is_spo_part = 'Y'
          AND parts.is_repairable = 'Y';


DROP VIEW AMD_OWNER.X_CONFIRMED_REQUEST_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_CONFIRMED_REQUEST_V
(
   NAME,
   REQUEST_TYPE,
   LAST_MODIFIED
)
AS
   SELECT order_no name,
          repair_request request_type,
          in_repair.last_update_dt last_modified
     FROM amd_in_repair in_repair, amd_spare_parts parts, amd_spo_types_v
    WHERE     in_repair.action_code <> 'D'
          AND in_repair.part_no = parts.part_no
          AND parts.is_spo_part = 'Y'
          AND parts.is_repairable = 'Y'
          AND amd_utils.getspolocation (loc_sid) IS NOT NULL
          AND in_repair.last_update_dt =
                 (SELECT MAX (last_update_dt)
                    FROM amd_in_repair r
                   WHERE     r.order_no = in_repair.order_no
                         AND r.action_code <> 'D')
   UNION
   SELECT gold_order_number name,
          new_buy_request request_type,
          on_order.last_update_dt last_modified
     FROM amd_on_order on_order, amd_spare_parts parts, amd_spo_types_v
    WHERE     on_order.action_code <> 'D'
          AND on_order.part_no = parts.part_no
          AND parts.is_spo_part = 'Y'
          AND amd_utils.getspolocation (loc_sid) IS NOT NULL
          AND on_order.last_update_dt =
                 (SELECT MAX (last_update_dt)
                    FROM amd_on_order o
                   WHERE     o.gold_order_number = on_order.gold_order_number
                         AND o.action_code <> 'D');


DROP VIEW AMD_OWNER.X_LP_BACKORDER_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_LP_BACKORDER_V
(
   LOCATION,
   PART,
   BACKORDER_TYPE,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT spo_location location,
          backorder.spo_prime_part_no part,
          general_backorder backorder_type,
          qty,
          backorder.last_update_dt last_modified
     FROM amd_backorder_sum backorder, amd_spare_parts parts, amd_spo_types_v
    WHERE     backorder.action_code <> 'D'
          AND backorder.spo_prime_part_no = parts.part_no
          AND parts.is_spo_part = 'Y';


DROP VIEW AMD_OWNER.X_LP_DEMAND_FORECAST_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_LP_DEMAND_FORECAST_V
(
   LOCATION,
   PART,
   DEMAND_FORECAST_TYPE,
   PERIOD,
   PERIOD_YEAR,
   QUANTITY,
   PART_TYPE,
   SOURCE,
   LAST_MODIFIED
)
AS
   SELECT spo_location location,
          parts.spo_prime_part_no part,
          external_demand_forecast demand_forecast_type,
          begin_date period,
          calendar_year_number period_year,
          dmnd.demand_forecast quantity,
          'Consumable' part_type,
          'Consumable1' source,
          dmnd.last_update_dt last_modified
     FROM amd_dmnd_frcst_consumables dmnd,
          amd_owner.amd_national_stock_items items,
          amd_spare_parts parts,
          amd_spare_networks ntwks,
          amd_current_period_v,
          amd_spo_types_v
    WHERE     dmnd.action_code <> 'D'
          AND dmnd.nsn = items.nsn
          AND items.prime_part_no = parts.part_no
          AND parts.is_spo_part = 'Y'
          AND parts.part_no = parts.spo_prime_part_no
          AND parts.is_consumable = 'Y'
          AND parts.spo_prime_part_no IS NOT NULL
          AND dmnd.sran = ntwks.loc_id
          AND dmnd.period = calendar_year_number
   UNION
   SELECT spo_location location,
          parts.spo_prime_part_no part,
          external_demand_forecast demand_forecast_type,
          amd_current_period_v.begin_date period,
          amd_current_period_v.calendar_year_number period_year,
          dmnd.demand_forecast quantity,
          'Consumable' part_type,
          'Consumable2' source,
          dmnd.last_update_dt last_modified
     FROM amd_dmnd_frcst_consumables dmnd,
          amd_owner.amd_national_stock_items items,
          amd_spare_parts parts,
          amd_spare_networks ntwks,
          amd_current_period_v,
          amd_spo_types_v
    WHERE     dmnd.action_code <> 'D'
          AND dmnd.nsn = items.nsn
          AND items.prime_part_no = parts.part_no
          AND parts.is_spo_part = 'Y'
          AND parts.part_no = parts.spo_prime_part_no
          AND parts.is_consumable = 'Y'
          AND parts.spo_prime_part_no IS NOT NULL
          AND dmnd.sran = ntwks.loc_id
          AND dmnd.period = (SELECT calendar_year_number
                               FROM spo_period_v
                              WHERE id = amd_current_period_v.id + 1)
   UNION
   SELECT amd_utils.getspolocation (frcst.loc_sid) location,
          frcst.part_no part,
          external_demand_forecast demand_forecast_type,
          begin_date period,
          calendar_year_number period_year,
          frcst.forecast_qty quantity,
          'Repairable' part_type,
          'Repairable1' source,
          frcst.last_update_dt last_modified
     FROM amd_part_loc_forecasts frcst,
          amd_spare_parts parts,
          amd_current_period_v,
          amd_spo_types_v
    WHERE     frcst.action_code <> 'D'
          AND frcst.part_no = parts.part_no
          AND parts.is_spo_part = 'Y'
          AND parts.part_no = parts.spo_prime_part_no
          AND parts.is_repairable = 'Y'
          AND parts.spo_prime_part_no IS NOT NULL
   UNION
   SELECT amd_utils.getspolocation (frcst.loc_sid) location,
          frcst.part_no part,
          external_demand_forecast demand_forecast_type,
          spo_period_v.begin_date period,
          spo_period_v.calendar_year_number current_period_year,
          frcst.forecast_qty quantity,
          'Repairable' part_type,
          'Repairable2' source,
          frcst.last_update_dt last_modified
     FROM amd_part_loc_forecasts frcst,
          amd_spare_parts parts,
          spo_period_v,
          amd_current_period_v,
          amd_spo_types_v
    WHERE     frcst.action_code <> 'D'
          AND frcst.part_no = parts.part_no
          AND parts.is_spo_part = 'Y'
          AND parts.part_no = parts.spo_prime_part_no
          AND parts.is_repairable = 'Y'
          AND parts.spo_prime_part_no IS NOT NULL
          AND spo_period_v.id = amd_current_period_v.id + 1;


DROP VIEW AMD_OWNER.X_LP_IN_TRANSIT_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_LP_IN_TRANSIT_V
(
   LOCATION,
   PART,
   IN_TRANSIT_TYPE,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT site_location location,
          transits.part_no part,
          DECODE (serviceable_flag,
                  'Y', general_in_transit,
                  'N', defective_in_transit,
                  serviceable_flag)
             in_transit_type,
          quantity,
          transits.last_update_dt last_modified
     FROM amd_in_transits_sum transits,
          amd_spare_parts parts,
          amd_spo_types_v
    WHERE     transits.action_code <> 'D'
          AND transits.part_no = parts.part_no
          AND parts.is_spo_part = 'Y';


DROP VIEW AMD_OWNER.X_LP_LEAD_TIME_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_LP_LEAD_TIME_V
(
   LOCATION,
   PART,
   LEAD_TIME_TYPE,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT ntwks.spo_location location,
          lt.part_no part,
          repair_lead_time lead_time_type,
          time_to_repair quantity,
          lt.last_update_dt last_modified
     FROM amd_location_part_leadtime lt,
          amd_spare_networks ntwks,
          amd_spare_parts parts,
          amd_spo_types_v
    WHERE     lt.action_code <> 'D'
          AND lt.part_no = parts.part_no
          AND parts.is_spo_part = 'Y'
          AND parts.is_repairable = 'Y'
          AND lt.loc_sid = ntwks.loc_sid
          AND ntwks.spo_location = ntwks.loc_id;


DROP VIEW AMD_OWNER.X_LP_ON_HAND_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_LP_ON_HAND_V
(
   LOCATION,
   PART,
   ON_HAND_TYPE,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT spo_location location,
          invs.part_no part,
          general_on_hand on_hand_type,
          qty_on_hand quantity,
          invs.last_update_dt last_modified
     FROM amd_on_hand_invs_sum invs, amd_spare_parts parts, amd_spo_types_v
    WHERE     invs.action_code <> 'D'
          AND invs.part_no = parts.part_no
          AND parts.is_spo_part = 'Y'
   UNION
   SELECT site_location location,
          invs.part_no part,
          defective_on_hand on_hand_type,
          qty_on_hand quantity,
          invs.last_update_dt last_modified
     FROM amd_repair_invs_sum invs, amd_spare_parts parts, amd_spo_types_v
    WHERE     invs.action_code <> 'D'
          AND invs.part_no = parts.part_no
          AND parts.is_spo_part = 'Y';


DROP VIEW AMD_OWNER.X_LP_OVERRIDE_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_LP_OVERRIDE_V
(
   LOCATION,
   PART,
   OVERRIDE_TYPE,
   QUANTITY,
   OVERRIDE_REASON,
   OVERRIDE_USER,
   BEGIN_DATE,
   END_DATE,
   SOURCE,
   LAST_MODIFIED
)
AS
   SELECT "LOCATION",
          "PART",
          "OVERRIDE_TYPE",
          "QUANTITY",
          "OVERRIDE_REASON",
          "OVERRIDE_USER",
          "BEGIN_DATE",
          "END_DATE",
          "SOURCE",
          "LAST_MODIFIED"
     FROM amd_lp_override_wk_v LPO
    WHERE EXISTS
             (  SELECT NULL
                  FROM amd_LP_OVERRIDE_wk_V, amd_spo_types_v
                 WHERE     LOCATION = LPO.LOCATION
                       AND PART = LPO.PART
                       AND OVERRIDE_TYPE IN (rop_fixed_override,
                                             roq_fixed_override,
                                             tsl_fixed_override)
              GROUP BY LOCATION, PART
                HAVING SUM (QUANTITY) <> 0);


DROP VIEW AMD_OWNER.X_PART_CAUSAL_TYPE_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_PART_CAUSAL_TYPE_V
(
   PART,
   CAUSAL_TYPE,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT parts.part_no part,
          flight_hours_causal causal_type,
          1 quantity,
          parts.last_update_dt last_modified
     FROM amd_spare_parts parts, amd_spo_types_v
    WHERE parts.is_spo_part = 'Y';


DROP VIEW AMD_OWNER.X_PART_LEAD_TIME_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_PART_LEAD_TIME_V
(
   PART,
   LEAD_TIME_TYPE,
   QUANTITY,
   VARIANCE,
   LAST_MODIFIED
)
AS
   SELECT pref.part_no part,
          new_buy_lead_time lead_time_type,
          pref.order_lead_time quantity,
          0 VARIANCE,
          part_last_update_dt last_modified
     FROM amd_preferred_v pref, amd_spare_parts parts, amd_spo_types_v
    WHERE     pref.part_no = parts.part_no
          AND parts.action_code <> 'D'
          AND parts.is_spo_part = 'Y'
   UNION
   SELECT pref.part_no part,
          repair_lead_time lead_time_type,
          pref.time_to_repair_off_base quantity,
          0 VARIANCE,
          part_last_update_dt last_modified
     FROM amd_preferred_v pref, amd_spare_parts parts, amd_spo_types_v
    WHERE     pref.part_no = parts.part_no
          AND parts.action_code <> 'D'
          AND parts.is_repairable = 'Y'
          AND parts.is_consumable = 'N'
          AND parts.is_spo_part = 'Y';


DROP VIEW AMD_OWNER.X_PART_MTBF_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_PART_MTBF_V
(
   PART,
   MTBF_TYPE,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT pref.part_no part,
          engineering_flight_hours_mtbf mtbf_type,
          pref.mtbdr quantity,
          part_last_update_dt last_modified
     FROM amd_preferred_v pref, amd_spare_parts parts, amd_spo_types_v
    WHERE     pref.mtbdr IS NOT NULL
          AND parts.part_no = pref.part_no
          AND parts.is_spo_part = 'Y';


DROP VIEW AMD_OWNER.X_PART_PLANNED_PART_V;

/* Formatted on 2/13/2015 1:38:20 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_PART_PLANNED_PART_V
(
   PART,
   PLANNED_PART,
   SUPERSESSION_TYPE,
   BEGIN_DATE,
   END_DATE,
   LAST_MODIFIED,
   SPO_USER,
   SOURCE
)
AS
   SELECT part,
          parts2.spo_prime_part_no planned_part,
          supersession_type,
          assignment_date begin_date,
          TO_DATE ('12/31/4100', 'MM/DD/YYYY') end_date,
          SYSDATE last_modified,
          'SPO' spo_user,
          'RBL_PAIRS' source
     FROM (SELECT old_prime_part_no part,
                  amd_utils.getprimepartno (planned_nsn) planned_part,
                  supersession_type
             FROM amd_twoway_rbl_pairs_v twoway,
                  (SELECT old_nsn planned_nsn, new_nsn
                     FROM amd_rbl_pairs a
                    WHERE     subgroup_code = (SELECT subgroup_code
                                                 FROM amd_rbl_pairs
                                                WHERE old_nsn = a.new_nsn)
                          AND part_pref_code =
                                 (SELECT MAX (part_pref_code)
                                    FROM amd_rbl_pairs
                                   WHERE     new_nsn = a.new_nsn
                                         AND subgroup_code =
                                                (SELECT subgroup_code
                                                   FROM amd_rbl_pairs
                                                  WHERE old_nsn = a.new_nsn)))
                  planned
            WHERE twoway.new_nsn = planned.new_nsn) twoway_planned,
          amd_nsi_parts nsi,
          amd_spare_parts parts1,
          amd_spare_parts parts2,
          amd_spare_parts parts3
    WHERE     twoway_planned.part = parts1.part_no
          AND parts1.is_spo_part = 'Y'
          AND twoway_planned.planned_part = parts2.part_no
          AND parts2.is_spo_part = 'Y'
          AND part <> parts2.spo_prime_part_no
          AND nsi.part_no = twoway_planned.part
          AND nsi.unassignment_date IS NULL
          AND parts2.spo_prime_part_no = parts3.part_no
          AND parts3.is_spo_part = 'Y'
   UNION
   SELECT parts.part_no,
          parts.spo_prime_part_no planned_part,
          two_way_supersession supersession_type,
          alts.assignment_date begin_date,
          CASE
             WHEN parts.action_code = 'D' THEN parts.last_update_dt
             ELSE TO_DATE ('12/31/4100', 'MM/DD/YYYY')
          END
             end_date,
          SYSDATE last_modified,
          'SPO' spo_user,
          'ALTERNATE_PARTS' source
     FROM amd_spare_parts parts,
          amd_national_stock_items items,
          amd_nsi_parts alts,
          amd_spo_types_v,
          amd_spare_parts parts2
    WHERE     parts.is_spo_part = 'Y'
          AND parts.part_no <> parts.spo_prime_part_no
          AND parts.nsn = items.nsn
          AND items.action_code <> 'D'
          AND parts.part_no <> items.prime_part_no
          AND parts.part_no = alts.part_no
          AND alts.unassignment_date IS NULL
          AND alts.prime_ind = 'N'
          AND parts.spo_prime_part_no = parts2.part_no
          AND parts2.is_spo_part = 'Y';


CREATE OR REPLACE PUBLIC SYNONYM X_CONFIRMED_REQUEST_LINE_V FOR AMD_OWNER.X_CONFIRMED_REQUEST_LINE_V;


CREATE OR REPLACE PUBLIC SYNONYM X_CONFIRMED_REQUEST_V FOR AMD_OWNER.X_CONFIRMED_REQUEST_V;


CREATE OR REPLACE PUBLIC SYNONYM X_LP_BACKORDER_V FOR AMD_OWNER.X_LP_BACKORDER_V;


CREATE OR REPLACE PUBLIC SYNONYM X_LP_DEMAND_FORECAST_V FOR AMD_OWNER.X_LP_DEMAND_FORECAST_V;


CREATE OR REPLACE PUBLIC SYNONYM X_LP_IN_TRANSIT_V FOR AMD_OWNER.X_LP_IN_TRANSIT_V;


CREATE OR REPLACE PUBLIC SYNONYM X_LP_LEAD_TIME_V FOR AMD_OWNER.X_LP_LEAD_TIME_V;


CREATE OR REPLACE PUBLIC SYNONYM X_LP_ON_HAND_V FOR AMD_OWNER.X_LP_ON_HAND_V;


CREATE OR REPLACE PUBLIC SYNONYM X_LP_OVERRIDE_V FOR AMD_OWNER.X_LP_OVERRIDE_V;


CREATE OR REPLACE PUBLIC SYNONYM X_PART_CAUSAL_TYPE_V FOR AMD_OWNER.X_PART_CAUSAL_TYPE_V;


CREATE OR REPLACE PUBLIC SYNONYM X_PART_LEAD_TIME_V FOR AMD_OWNER.X_PART_LEAD_TIME_V;


CREATE OR REPLACE PUBLIC SYNONYM X_PART_MTBF_V FOR AMD_OWNER.X_PART_MTBF_V;


CREATE OR REPLACE PUBLIC SYNONYM X_PART_PLANNED_PART_V FOR AMD_OWNER.X_PART_PLANNED_PART_V;


GRANT SELECT ON AMD_OWNER.X_CONFIRMED_REQUEST_LINE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.X_CONFIRMED_REQUEST_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.X_LP_BACKORDER_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.X_LP_DEMAND_FORECAST_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.X_LP_IN_TRANSIT_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.X_LP_LEAD_TIME_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.X_LP_ON_HAND_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.X_LP_OVERRIDE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.X_PART_CAUSAL_TYPE_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.X_PART_LEAD_TIME_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.X_PART_MTBF_V TO AMD_READER_ROLE;

GRANT SELECT ON AMD_OWNER.X_PART_PLANNED_PART_V TO AMD_READER_ROLE;

DROP VIEW AMD_OWNER.AMD_CURRENT_PERIOD_V;

/* Formatted on 2/13/2015 1:35:53 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.AMD_CURRENT_PERIOD_V
(
   ID,
   BEGIN_DATE,
   END_DATE,
   YEAR_NUMBER,
   MONTH_NUMBER,
   WEEK_NUMBER,
   CALENDAR_YEAR_NUMBER,
   CALENDAR_MONTH_NUMBER,
   SOURCE
)
AS
   SELECT id,
          begin_date,
          end_date,
          year_number,
          month_number,
          week_number,
          calendar_year_number,
          calendar_month_number,
          'FIXED_CURRENT_PERIOD' source
     FROM spo_period_v, spo_fixed_current_period_v
    WHERE     EXISTS
                 (SELECT 1
                    FROM spo_flag_v
                   WHERE     name = 'IS_TACTICS_CURRENT_DATE_FIXED'
                         AND UPPER (VALUE) = 'T')
          AND period = id
   UNION
   SELECT id,
          begin_date,
          end_date,
          year_number,
          month_number,
          week_number,
          calendar_year_number,
          calendar_month_number,
          'SYSDATE' source
     FROM spo_period_v
    WHERE     (   NOT EXISTS
                         (SELECT 1
                            FROM spo_flag_v
                           WHERE     name = 'IS_TACTICS_CURRENT_DATE_FIXED'
                                 AND UPPER (VALUE) = 'T')
               OR NOT EXISTS
                     (SELECT 1
                        FROM spo_fixed_current_period_v, spo_period_v
                       WHERE period = id))
          AND TRUNC (begin_date, 'mon') = TRUNC (SYSDATE, 'mon');


CREATE OR REPLACE PUBLIC SYNONYM AMD_CURRENT_PERIOD_V FOR AMD_OWNER.AMD_CURRENT_PERIOD_V;


GRANT SELECT ON AMD_OWNER.AMD_CURRENT_PERIOD_V TO AMD_READER_ROLE;
DROP VIEW AMD_OWNER.X_LP_DEMAND_V;

/* Formatted on 2/13/2015 1:00:08 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.X_LP_DEMAND_V
(
   TRANSACTION_ID,
   LOCATION,
   PART,
   CONTRACT,
   DEMAND_TYPE,
   DEMAND_DATE,
   CUSTOMER_LOCATION,
   PRODUCT_SERIAL_NUMBER,
   QUANTITY,
   LAST_MODIFIED
)
AS
   SELECT doc_no || '-' || LPAD (TO_CHAR (loc_sid), 4, '0') transaction_id,
          amd_utils.getspolocation (loc_sid) location,
          parts.spo_prime_part_no part,
          'C17' contract,
          general_demand demand_type,
          doc_date demand_date,
          NULL customoer_location,
          NULL product_serial_number,
          quantity,
          dmnd.last_update_dt last_modified
     FROM amd_demands dmnd,
          amd_national_stock_items items,
          amd_spare_parts parts,
          amd_spo_types_v
    WHERE     dmnd.action_code <> 'D'
          AND amd_utils.getSpoLocation (loc_sid) IS NOT NULL
          AND dmnd.nsi_sid = items.nsi_sid
          AND items.prime_part_no = parts.part_no
          AND parts.is_spo_part = 'Y';


CREATE OR REPLACE PUBLIC SYNONYM X_LP_DEMAND_V FOR AMD_OWNER.X_LP_DEMAND_V;


GRANT SELECT ON AMD_OWNER.X_LP_DEMAND_V TO AMD_READER_ROLE;

DROP VIEW AMD_OWNER.AMD_LP_OVERRIDE_WK_V;

/* Formatted on 2/13/2015 12:54:38 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE VIEW AMD_OWNER.AMD_LP_OVERRIDE_WK_V
(
   LOCATION,
   PART,
   OVERRIDE_TYPE,
   QUANTITY,
   OVERRIDE_REASON,
   OVERRIDE_USER,
   BEGIN_DATE,
   END_DATE,
   SOURCE,
   LAST_MODIFIED
)
AS
   SELECT spo_location location,
          locov.part_no,
          tsl_fixed_override override_type,
          CASE
             WHEN     spo_location =
                         amd_location_part_override_pkg.getthe_warehouse
                  AND parts.is_repairable = 'Y'
             THEN
                0
             ELSE
                tsl_override_qty
          END
             quantity,
          fixed_tsl_load_override_reason override_reason,
          TO_CHAR (TO_NUMBER (tsl_override_user)) override_user,
          locov.last_update_dt begin_date,
          NULL end_date,
          'AMD_LOCATION_PART_OVERRIDE' source,
          locov.last_update_dt last_modified
     FROM amd_location_part_override locov,
          amd_spare_parts parts,
          amd_spo_types_v,
          amd_spare_networks ntwks
    WHERE     locov.LOC_SID = ntwks.LOC_SID
          AND locov.action_code <> 'D'
          AND tsl_override_qty IS NOT NULL
          AND locov.part_no = parts.part_no
          AND parts.is_spo_part = 'Y'
   UNION
   SELECT rsp_location location,
          part_no,
          override_type,
          rop_or_roq quantity,
          fixed_tsl_load_override_reason override_reason,
          TO_CHAR (
             TO_NUMBER (
                amd_location_part_override_pkg.getfirstlogonidforpart (
                   amd_utils.getnsisidfrompartno (part_no))))
             override_user,
          last_update_dt begin_date,
          NULL end_date,
          'AMD_RSP_SUM_CONSUMABLES_V' source,
          last_update_dt last_modified
     FROM amd_owner.amd_rsp_sum_consumables_v, amd_spo_types_v
    WHERE action_code <> 'D' AND rop_or_roq IS NOT NULL
   UNION
   SELECT rsp_location location,
          part_no,
          override_type,
          rsp_level quantity,
          fixed_tsl_load_override_reason override_reason,
          TO_CHAR (
             TO_NUMBER (
                amd_location_part_override_pkg.getfirstlogonidforpart (
                   amd_utils.getnsisidfrompartno (part_no))))
             override_user,
          last_update_dt begin_date,
          NULL end_date,
          'AMD_RSP_SUM_REPAIRABLES_V' source,
          last_update_dt last_modified
     FROM amd_owner.amd_rsp_sum_repairables_v, amd_spo_types_v
    WHERE action_code <> 'D' AND rsp_level IS NOT NULL
   UNION
   SELECT spo_location,
          part_no,
          tsl_override_type,
          tsl_override_qty,
          fixed_tsl_load_override_reason override_reason,
          TO_CHAR (TO_NUMBER (tsl_override_user)),
          last_update_dt begin_date,
          NULL end_date,
          'AMD_LOCPART_OVERID_CONSUMABLES' source,
          last_update_dt last_modified
     FROM amd_locpart_overid_consumables, amd_spo_types_v
    WHERE action_code <> 'D' AND tsl_override_qty IS NOT NULL
   ORDER BY 1, 2, 3;


CREATE OR REPLACE PUBLIC SYNONYM AMD_LP_OVERRIDE_WK_V FOR AMD_OWNER.AMD_LP_OVERRIDE_WK_V;


GRANT SELECT ON AMD_OWNER.AMD_LP_OVERRIDE_WK_V TO AMD_READER_ROLE;

